### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#1]
The first one to create an issue:)
Kudos for your work!
However I have a few suggestions that I want to share:

I personally think that your approach with selecting the theme one wants to use is the right thing to do. But I don't think that your approach with an `extra` folder is the simplest solution. You really should consider to do something like

`from gi.repository import Gtk`
`theme = Gtk.IconTheme.set_custom_theme(your_chosen_theme)`
`theme.has_icon(icon_name)`

and if `True` symlink the icon either from `22x22` or `24x24` to the hardcoded folder. This is actually not slower than your current approach, because list-manipulations are really fast in Python. This would ensure that the icon themes do not need to adapt their structure in order to support your script.

If the icon is present it will be copied if not, fine as well. This means that you'll have initially a little bit more work, because you can't symlink whole folders, but in the long run I think this is a better idea

**Comment by bil-elmoussaoui** [comment]
Thank you very much for taking the time to read my code! 
Well , if i did understand very well what you are saying : the database file will change from only the folder location to the folder location + icons? If so, i think it's will take some time , but it's really a good idea. I will try to do that asap.

**Comment by bil-elmoussaoui** [comment]
I was getting the list of supported themes by checking if the extra folder exists, but using your way will make it a little bit different. I think of showing all the installed icons?

**Comment by wa4557** [comment]
well why not just ignore supported themes and do something like 

```theme = Gtk.IconTheme.get_default() 
   theme.has_icon```

if the icon you want to symlink is in the current theme symlink it, if not don't.

**Comment by wa4557** [comment]
So let's say you want to fix pushbullet-indicator

1. Check if the icon `pushbullet-indicator` exists in the current theme `theme.has_icon()`
2. If `True` symlink it to the folder that is specified in the `.csv`
3. If `False` or the folder you want to symlink to doesn't exist, continue with the next hardcoded `icon`

**Comment by bil-elmoussaoui** [comment]
I wanted to keep the supported theme so you can use the indicator/tray icon from an other theme. For example, i'm using elementary base theme with Numix circle. if i just get the default theme, the script won't find any icon as the Numix-Circle get his base icons from Elementary base. But i can just show all the themes, so the user can choose on of theme. And i'm open for any better ideas.

**Comment by wa4557** [comment]
Well that's not entirely true:

`theme.lookup_icon('pushbullet-indicator`, 22, 0).get_filename()`

will find icons also in the inherited theme. So it will(!) find icons from elementary if you use Numix-Circle

**Comment by wa4557** [comment]
So if you use Numix-Circle and inherit Numix and elementary this approach would look for icons in Numix-Circle afterwards in Numix and finally in elementary. If no icons are found or the target folder doesn't exist (i.e. the program is not installed) nothing happens. If an icon is found and the target folder exists a symlink is created and the original "wrong" icon overwritten

**Comment by wa4557** [comment]
Last point: I think your default sizes are wrong. Ubuntu etc. should use 22x22 icons not 24x24 icons and elementary OS and XFCE distributions are using 24x24 sized panel icons

**Comment by bil-elmoussaoui** [comment]
Well, i did fix all that. But i didn't test it; i had a little problem. I put the tray icons of each app in a list and i really don't know how to use JSON or something like that to serialize this so i can use it back in my code?

**Comment by wa4557** [comment]
You have your list in a csv file? Why not use https://docs.python.org/2/library/csv.html ?

**Comment by bil-elmoussaoui** [comment]
Well, this has been fixed! I did tried the script now.. And everything rocks! The database supports less apps than before. But i'will update it later ;) 
![capture du 2015-04-09 18 18 48](https://cloud.githubusercontent.com/assets/7660997/7071351/f4721ae8-dee4-11e4-8cb5-d01b8b3966f0.png)
Thank you

**Comment by wa4557** [comment]
Happy to help :) I think this a somehow more elegant approach

**Comment by wa4557** [comment]
A few more minor things that needs to be changed. I'll create a pull request if you allow :)

**Comment by bil-elmoussaoui** [comment]
Of course! 
Feel free to add/change whatever you want ;)

**Comment by wa4557** [comment]
Closing because issue solved :)
