### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#10]
One minor thing: You should consider to use 4 spaces instead of tabs for indenting code blocks (this can be automatically done with almost every editor). It makes coding a lot easier and its recommended by the google python styleguide.

https://google-styleguide.googlecode.com/svn/trunk/pyguide.html#Indentation

Nevertheless this is up to you if you don't want to do this, that's fine as well :)

**Comment by bil-elmoussaoui** [comment]
This is should be fixed now, can you confirm that?

**Comment by wa4557** [comment]
Yeah cool, thanks!
