### ISSUE TITLE
second column must not be the same in db.csv

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#102]
A rather serious bug, I wasn't able to fix yet. The second column in `db.csv` must not be the same (like for all the chrome variants) because the dictionary will  be overwritten by the last one. 

If you have for example installed chrome and chrome-beta the function `get_apps_information` only returns the information for `chrome-beta` because the corresponding key from `google-chrome` is overwritten by the key `google-chrome` from chrome-beta

**Comment by bil-elmoussaoui** [comment]
Thanks for the quick fix :+1:
