### ISSUE TITLE
Clementine Idle icon not visible

### ISSUE THREAD

**Issue by TeoSakel** [bil-elmoussaoui/Hardcode-Tray#105]
Clementine icon is not visible when it's idle (it is there however).
Using: Numix-circle-theme, 22 font size

The script outputs:
```
Clementine -- fixed using clementine-panel
```

![screenshot from 2015-10-03 20 32 34](https://cloud.githubusercontent.com/assets/5864415/10264239/a74f6c1a-6a0e-11e5-91ea-b0f059664511.png)

**Comment by bil-elmoussaoui** [comment]
Can you open clementine and  paste the output of `ls /tmp` ?

**Comment by TeoSakel** [comment]
Sure! Here you are:

```
config-err-6AsZRb
qtsingleapp-clemen-d211-3e8
qtsingleapp-clemen-d211-3e8-lockfile
sni-qt_clementine_3930-6T3WIC
unity_support_test.0
```

**Comment by bil-elmoussaoui** [comment]
and the output of  `ls /tmp/sni-qt_clementine_3930-6T3WIC`?

**Comment by TeoSakel** [comment]
```
tine_3930-6T3WIC
icons/
```

and in the icons folder there is:
' /tmp/sni-qt_clementine_3930-6T3WIC/icons/hicolor/48x48/apps/
clementine_3930_e1c70cd6785ac768670030ea5df41c35.png'

**Comment by bil-elmoussaoui** [comment]
Thanks, and clementine have only one tray icon or more?

**Comment by TeoSakel** [comment]
One at time.
It changes depending on its state. 
When playing or paused it's visible though.
Only when it's stopped or idle it's invisible

**Comment by bil-elmoussaoui** [comment]
First remove `.local/share/sni-qt/icons/clementine/*`, reopen Clementine and try getting all the tray icons even if it's invisible. Don't close Clementine and paste the output of `ls /tmp/sni-qt_clementine` the clementine folder in /tmp will not have the same name once you reopen Clementine

**Comment by TeoSakel** [comment]
The tray icon is now visible, though not monochrome.
` ls /tmp/sni-qt_clementine_5783-BhAM5v/ ` outputs: ` icons/ ` and from there it goes:
` icons/hicolor/48x48/apps/clementine_5783_*.png ` (4 png files)

**Comment by bil-elmoussaoui** [comment]
Can you get the 4 png icons names ? And a screenshot of the folder too :)

**Comment by TeoSakel** [comment]
Sure! Now there are more because I played a song!
The names are:
```
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_10a04e23b84e9983c45c711ba0ed64cc.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_209c8d6f9b60d2e2ebc5a0fe387ca48f.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_2c73462acd0f550bd40b4eb69c92c9ff.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_2d4aaad14ea972aab69fb008299762a7.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_3acbcd91d769df957b0e8e47159e72d9.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_42cef68137f7db86c78f511db7a39d65.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_4f79d0cf1ce058a79572708bba62db34.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_56d57e1c8dae66b0a9e02dfde8364c0a.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_59cc4572186ec4d80d6117ddb6ca05fe.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_60be45c633978239990190b7148de8fc.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_702d17b9e830ed7f3a9a3d44ed6f062c.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_77f87b3f44ff898e46833b2d8e08a32e.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_94fd15a06fb5343f3aed1c0790df117f.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_9e25e457f43d36b9717b028be10cd64e.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_a6c84d822084f3b540ca1915aaf76fc6.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_bc2bf417e092cfd9485f9e263aebc609.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_cc3bc778663612e29d742386c227e89d.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_d918cc6f4ba4bbec172cb6932dca6083.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_e1c70cd6785ac768670030ea5df41c35.png
/tmp/sni-qt_clementine_5783-BhAM5v/icons/hicolor/48x48/apps/clementine_5783_fd857104813caf9b67ee95dbb8385ec0.png
```
And the screenshot:
![image](https://cloud.githubusercontent.com/assets/5864415/10267123/9073dd1a-6a8f-11e5-8896-1f68abadb115.png)

**Comment by wa4557** [comment]
Ok, it seems that we need a few additional icons :)

**Comment by bil-elmoussaoui** [comment]
@TeoSakel I will add them to Hardcode-Tray database:) I will report the missing icons to Numix

**Comment by TeoSakel** [comment]
Cool! Then we can consider it closed I guess...

**Comment by bil-elmoussaoui** [comment]
Yes, thanks for the report ! :+1:

**Comment by bil-elmoussaoui** [comment]
[https://github.com/numixproject/numix-icon-theme/issues/766](Clementine indicator icons) Once this got closed you can try Hardcode-Tray again :)

**Comment by sagarpanchal** [comment]
@bil-elmoussaoui https://github.com/clementine-player/Clementine/blob/f482612127ca72ea92cd04b95f33c6ae3a1ddab7/dist/CMakeLists.txt
