### ISSUE TITLE
Weird Hexchat Thing

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#109]
No idea how or why, but the script did this.
![screenshot_2015-10-09_13-51-44](https://cloud.githubusercontent.com/assets/5920259/10394131/edbe28bc-6e8c-11e5-8b4f-75baf335f08c.png)

**Comment by bil-elmoussaoui** [comment]
Can i have the icon size? :)

**Comment by Foggalong** [comment]
It's 48px - for some reason it's taken the icon from Circle rather than base.

**Comment by bil-elmoussaoui** [comment]
@Foggalong The 48px is the Numix circle icon? What about the rest of the icons? And i think i know what causes circle icons being token instead of base icons! I can fix it today if i have some free time

**Comment by Foggalong** [comment]
Yeah, all the other ones just came out fine it's just that one

**Comment by Foggalong** [comment]
As a note on hexchat generally - the icons don't actually have to be PNGs, they just have to use the `.png` extension.

**Comment by bil-elmoussaoui** [comment]
Really don't know what makes the icons really small..I don't think that i can do anything about creating svg icons and then renaming them to ".png" I will have to rewrite the code for only one application.The best solution is that Hexchat does not hardcode the extension name too..

**Comment by Foggalong** [comment]
It's the fact that the symbol from a 48px app icon (which is 24px) is then being scaled down to a 24px panel icon (making it look 12px).

**Comment by bil-elmoussaoui** [comment]
I was thinking about this one, it's due to the fact that `hexchat.png` do exists in Numix-Circle and it's being used instead of the `hexchat-indicator` as the script looks for the original icon first. 
@wa4557 I was thinking about adding a way to force using the symlink icon, do you have any idea?

**Comment by wa4557** [comment]
The thing is: this is one of those toxic icons and isn't in numix-base at all (there's just a `renamed-hexchat`) which means that a symlink in base is necessary to sth called `hexchat-indicator` and a change in the database file here...

**Comment by bil-elmoussaoui** [comment]
Well, in the database file we have this `hexchat.png, hexchat-indicator` but the script looks for the original icon first :/ and i really don't want to recode the install function just to fix this... and i think @Foggalong has done the modifications in Numix base!

**Comment by wa4557** [comment]
True. Well the script shouldn't look for the original icon first if there's a symlinked icon entry, imo

**Comment by bil-elmoussaoui** [comment]
A possible bug :P I will try to figure out what's going wrong

**Comment by wa4557** [comment]
Argh, the code has become actually a little bit too complicated to figure out what's going on without digging really deep :)

**Comment by bil-elmoussaoui** [comment]
Yeah :/ I will try renaming some variables to make things clearer for future contributors

**Comment by wa4557** [comment]
Well I guess it's just up to us to fix issues codewise...

**Comment by bil-elmoussaoui** [comment]
Yes, but the source code is open if anyone wants to contribute

**Comment by bil-elmoussaoui** [comment]
Should be fixed in my latest commit! Please revert & try again

**Comment by Foggalong** [comment]
Yeah, seem to be working now :)

**Comment by bil-elmoussaoui** [comment]
This can be closed now ? :D

**Comment by Foggalong** [comment]
Yeah!
