### ISSUE TITLE
Dependency Mess

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#113]
The problem described [here](https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/104#issuecomment-145690157) combined with the fact that the `python3-cairocffi` doesn't exist in LTS basically means that users have to edit the script to get it work on that platform. I'm not sure what the solution is though :/

**Comment by bil-elmoussaoui** [comment]
Well, i don' t think that `python3-cairocffi`is really a dependency! as `python3-cairosvg` works great without it in older versions of Ubuntu! it's might be a bug with Cairosvg itself or something else that has been fixed in your case by updating your system

**Comment by Foggalong** [comment]
It was literally just installing cairocffi that fixed the problem - didn't work before, worked after, and nothing else happened inbetween :(

**Comment by bil-elmoussaoui** [comment]
The solution didn't work in my case :( and i have the same error message..using inkscape instead of cairosvg  will make things complicated!  @wa4557 what do you think?

**Comment by Foggalong** [comment]
Do all these programs require actual PNG files or just the `.png` extension? (like hexchat)

**Comment by bil-elmoussaoui** [comment]
Almost every icon requires png files.Especially Qt applications like Skype..

**Comment by Foggalong** [comment]
Shoot :(

**Comment by bil-elmoussaoui** [comment]
I'm going to close this i will start working on a way to use inkscape if the user does not have Cairosvg! I will remove the other library from the dependency, and hope this will get fixed in Ubuntu 15.10

**Comment by wa4557** [comment]
@bil-elmoussaoui I guess this is the only way to really handle this bug. Anyways: 15.10 is not officially out yet so maybe this will be fixed after the official release

**Comment by bil-elmoussaoui** [comment]
@wa4557 Yes! and hope it's will be fixed soon
