### ISSUE TITLE
Use sys path 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#115]
I think using `sys.path.insert` in `svg2png.py` and `qt-tray`  and call the `svgtopng` function will help us improving the script and make the code clearer! 
What do you think? 
@wa4557 @Foggalong

**Comment by wa4557** [comment]
You mean importing script.py and use the convert function from there? I like that. We need a `if __name__ == "__main__":` then.

**Comment by bil-elmoussaoui** [comment]
Yes! As the same code is repeated in the three files.. In the script.py file?

**Comment by wa4557** [comment]
Ah yeah not `script.py` of course... Instead of `sys.path` (too much) we should instead use `imp.load_source`

**Comment by bil-elmoussaoui** [comment]
I ever heard of `imp.load_source`! I'm going to add that if i have some free time ;)

**Comment by wa4557** [comment]
I can do it, if you want. Right now I have some free time :)

**Comment by bil-elmoussaoui** [comment]
Sure you can! I will do this one #71

**Comment by wa4557** [comment]
@bil-elmoussaoui Can you try (beta branch) for me the script somehow stopped working (not because of the changes I made, but because of something else)

**Comment by Foggalong** [comment]
@wa4557 @bil-elmoussaoui [Possibly this?](https://github.com/bil-elmoussaoui/Hardcode-Tray/pull/114#discussion-diff-42319393)

**Comment by wa4557** [comment]
Yeah no I changed that already :)

**Comment by bil-elmoussaoui** [comment]
Works fine here! Do you have any error message?

**Comment by wa4557** [comment]
`The svg file `/usr/share/icons/Numix/22/status/dropboxstatus-busy.svg` is invalid.`

**Comment by bil-elmoussaoui** [comment]
@wa4557 The only one? or you have an other error message?

**Comment by wa4557** [comment]
This error message but infinitely often which means that the script does not continue. 
You have to try again, I forgot to push the changes before...

**Comment by bil-elmoussaoui** [comment]
Found it! i will push a fix right now

**Comment by bil-elmoussaoui** [comment]
Can you try again?

**Comment by wa4557** [comment]
Did you push to beta branch?

**Comment by wa4557** [comment]
Yeah it works almost, spotify and chrome still have a problem on my machine though

**Comment by bil-elmoussaoui** [comment]
They're not working at all or you have an error message

**Comment by wa4557** [comment]
I fixed it :) I'll push right now
