### ISSUE TITLE
Google chrome icons are not partially fixed

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#117]
I don't know why this is happening but sometimes the script does not detect all the 4 Google chrome icons.. and the script does not fixed the ones that are found! 
We will need to think of a better way to handle this

**Comment by wa4557** [comment]
Hmm so the problem is the `get_correct_chrome_icon` function?

**Comment by bil-elmoussaoui** [comment]
Yes! and we have two pak files in the `chrome` database file, we should modify the way we fixed this a little bit #84; as in this case the other pak file isn't extracted...

**Comment by wa4557** [comment]
What do you mean? Extracting one file replacing icons remove extracted files and then do the same thing with the other one?

**Comment by bil-elmoussaoui** [comment]
Yes! i guess that we should add an if statement and have a counter for each `pak` file

**Comment by wa4557** [comment]
I see, I'll try to come up with something :) Not sure what to do about the chrome icons that are not recognized though...

**Comment by bil-elmoussaoui** [comment]
i will see what i can do about this one

**Comment by bil-elmoussaoui** [comment]
Fixed the first part of the issue! @wa4557 still wanna do the rest? i have some free time today i can do it if you want :)

**Comment by wa4557** [comment]
Go ahead. I'm fairly occuied with work these days...

**Comment by bil-elmoussaoui** [comment]
It's just so hard to implement :/ i think i will just make the icon in an other file or something like that.. what do you think?

**Comment by bil-elmoussaoui** [comment]
Or maybe just removing the support of the third icon as Google chrome will remove the notification center  in the newest versions!
