### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#119]
![screenshot_2015-10-29_13-24-20](https://cloud.githubusercontent.com/assets/5920259/10819520/6edf59c6-7e40-11e5-8676-4be61663c6f8.png)
VLC isn't showing as themed for me under Numix Circle, and there isn't an icon in hicolor so I'm guessing this means it's hardcoded. Any information you need let me know :)

**Comment by bil-elmoussaoui** [comment]
I'm not sure if the icon is the one in `/usr/share/vlc/`, can you try changing the icon with the Numix icon manually and see if that works?

**Comment by Foggalong** [comment]
I can't seem to get it to change by changing that no

**Comment by bil-elmoussaoui** [comment]
Can you paste the output of `cd /usr/share/icons/hicolor && sudo find -name vlc*` ?

**Comment by Foggalong** [comment]
Just these

```
./256x256/apps/vlc.png
./32x32/apps/vlc-xmas.xpm
./32x32/apps/vlc.png
./32x32/apps/vlc.xpm
./128x128/apps/vlc.png
./128x128/apps/vlc-xmas.png
./16x16/apps/vlc.png
./16x16/apps/vlc.xpm
./48x48/apps/vlc.png
./48x48/apps/vlc-xmas.png
```

They'd be picked up by Circle though so I figure it can't be one of them

**Comment by bil-elmoussaoui** [comment]
VLC is not a Qt application? Can you open VLC and see if you will find any icon in `/tmp`

**Comment by bil-elmoussaoui** [comment]
Seem that VLC use `vlc-panel`, see [here](https://bugs.launchpad.net/ubuntu/+source/vlc/+bug/530797)

**Comment by wa4557** [comment]
You have to rename ``renamed-vlc`` in numix to ``vlc``. THat's because it's one of the toxic icons...

**Comment by Foggalong** [comment]
Does renaming `renamed-vlc` to `vlc-panel`

**Comment by bil-elmoussaoui** [comment]
@Foggalong You forgot a part of the sentence i guess? :P

**Comment by Foggalong** [comment]
Oops :P what I get for typing between lectures!

> Does renaming `renamed-vlc` to `vlc-panel` allow it to appear in the panel then?

**Comment by bil-elmoussaoui** [comment]
I guess you should rename `renamed-vlc` to `vlc` but not sure!

**Comment by Foggalong** [comment]
We can't rename it to VLC because of the clash with the app icon name, I was just going on the information in the issue you linked

**Comment by bil-elmoussaoui** [comment]
I tried to rename the icon name to `vlc-panel` but it's not working..maybe commenting on the issue or opening a new one and see if the devs will fix that?

**Comment by bil-elmoussaoui** [comment]
Sorry, but we can do anything to fix this :(

**Comment by wa4557** [comment]
Well one has to decide wheter he wants the correct app icon (then just keep it the way it is) or the correct tray icon (then one has to rename `renamed-vlc` to `vlc` in `status`)
