### ISSUE TITLE
Inkscape interface opens in Fedora

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#120]
Hello
I tried to use the script after adding the support of inkscape too! 
And inkscape opens every image that was converted to png..
Is there a way to avoid that? :)
CC: @wa4557

**Comment by wa4557** [comment]
Weird on my (ubuntu) machine inkscape is not opened. I have to think about it, maybe there is a command preventing the gui to be opened...
