### ISSUE TITLE
Icons too small on Gnome 3.18

### ISSUE THREAD

**Issue by MrTimscampi** [bil-elmoussaoui/Hardcode-Tray#122]
A detection for Gnome should probably be added in the detect_de(), because the icons look slightly too small at 22px, compared to the regular icons on the bar.

![screenshot from 2015-11-16 16-39-35](https://cloud.githubusercontent.com/assets/1087450/11186172/bbeeecba-8c80-11e5-95f0-45a4e026bf47.png)

**Comment by bil-elmoussaoui** [comment]
What extension you're using to have top bar icons? 
Do you have the same size issue if you revert to the default icons?

**Comment by MrTimscampi** [comment]
I'm using [this](https://github.com/rgcjonas/gnome-shell-extension-appindicator) along with a patched GTK and sni-qt.

Here's how it looks like with the script reverted:
![screenshot from 2015-11-16 17-43-00](https://cloud.githubusercontent.com/assets/1087450/11188096/8decdb98-8c89-11e5-8c58-7862594e1bf4.png)

Skype looks alright, Steam is still too small.

**Comment by bil-elmoussaoui** [comment]
Well, default skype icons are so big! that's why they look fine :) Steam does not have a hardcoded icon, This is not a Hardcode-Tray issue and we can do nothing about it :/ If they user does not use the Top bar icons extensions the icons will look so big.

**Comment by Foggalong** [comment]
I'd wager that's an error with the extension rather than the script
