### ISSUE TITLE
Hardcoded icons for museeq

### ISSUE THREAD

**Issue by pavethem** [bil-elmoussaoui/Hardcode-Tray#123]
Numix just added new icons for museeq soulseek client.
The tray icons are hardcoded however.

the item names in /tmp/sni-qt_museeq_18307-wcZLd1/icons/hicolor/64x64/apps/ are:

when you first start the application:
![museeq_30211_2f0bfbefd5f436ee06255de74ae04b74](https://cloud.githubusercontent.com/assets/847563/11315550/fcaf5e44-8ff3-11e5-8f84-136728241d7d.png)
museeq_18307_2f0bfbefd5f436ee06255de74ae04b74.png
connected:
![museeq_30256_0008df6b8abb9fb96af23f526732e605](https://cloud.githubusercontent.com/assets/847563/11315553/fcb275ac-8ff3-11e5-9d37-3e983a6015d6.png)
museeq_18307_0008df6b8abb9fb96af23f526732e605.png
the other two are in /tmp/sni-qt_museeq_18307-wcZLd1/icons/hicolor/16x16/apps/
when you first connect, then it changes to the above:
![museeq_30256_bdf9b53b9cd16f3c032bf1eca0892643](https://cloud.githubusercontent.com/assets/847563/11315552/fcb1fb18-8ff3-11e5-8334-d17877180387.png)
museeq_18307_bdf9b53b9cd16f3c032bf1eca0892643.png
disconnected:
![museeq_30256_21dff8ad54c6c56ada4c3e69610fcaf4](https://cloud.githubusercontent.com/assets/847563/11315551/fcb1d75a-8ff3-11e5-9da8-49b5cbf3b4cf.png)
museeq_18307_21dff8ad54c6c56ada4c3e69610fcaf4.png

**Comment by bil-elmoussaoui** [comment]
One more information; can you give me a folder/file location (full path) that's created when installing the application? The best thing is an executable file?

**Comment by bil-elmoussaoui** [comment]
Fixed in my latest commit!

**Comment by pavethem** [comment]
you mean /usr/bin/museeq?

**Comment by bil-elmoussaoui** [comment]
Thanks! i've added that to museeq to the latest version , just re download the script and follow the instructions in the readme file
