### ISSUE TITLE
Fix only svg icons 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#124]
We can fix only svg icons if inkscape & cairosvg are not installed instead of not fixing any icon at all?
@wa4557 what do you think?

**Comment by wa4557** [comment]
So an additional variable, if inkscape/cairosvg is not installed only fix svg and not execute conversion and scripts (like spotify). Seems like a good idea.

**Comment by bil-elmoussaoui** [comment]
I will see what i can do about it :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed in 5a8e3ad61f88918a0200dffa444cea465957e6d1
