### ISSUE TITLE
Tray-Icon for Trimage

### ISSUE THREAD

**Issue by Stunkymonkey** [bil-elmoussaoui/Hardcode-Tray#128]
**Original icon:**
![Image of Trimage](http://trimage.org/trimage-icon.png)

**Icon name:** trimage (of desktop-file)

**Notes:** It's a software for compressing images for the web without losing quality.

**Comment by bil-elmoussaoui** [comment]
I took a look at the source code of Tirmage and it seems that the icon name is `trimage-icon` as you can see here : [#L548](https://github.com/Kilian/Trimage/blob/master/src/trimage/trimage.py#L548); 
Can you use your default file browser and see if you can find that file ?

**Comment by Stunkymonkey** [comment]
found in `/usr/lib/python2.7/site-packages/trimage/pixmaps`

**Comment by bil-elmoussaoui** [comment]
Can you try changing this icon with an other one and see if the tray icon changes? And check if this file `/usr/bin/trimage` do exists?

**Comment by Stunkymonkey** [comment]
yes it is the icon (is colored it with gimp):
![screenshot from 2015-12-23 00-08-36](https://cloud.githubusercontent.com/assets/1315818/11968140/53db0d48-a909-11e5-9ccb-c29cbbec64af.png)
and yes the `/usr/bin/trimage` exists

**Comment by bil-elmoussaoui** [comment]
Nice! :+1: Fixed here. Open a new issue on Numix Base with this icon name `trimage-indicator`, once the icon added, execute the script again
