### ISSUE TITLE
Monochrome-Tray-Icon for Telegram

### ISSUE THREAD

**Issue by Stunkymonkey** [bil-elmoussaoui/Hardcode-Tray#129]
**Original tray-icon:**
![Tray-Image of Telegram](https://desktop.telegram.org/img/td_logo.png)

**Icon name:** telegram (of desktop-file)

**Notes:** It's a popular chat-software.

**Comment by bil-elmoussaoui** [comment]
Already supported, just use the script and the icon should be fixed. If not please check this one #99 #89.
