### ISSUE TITLE
sni-qt png?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#130]
Is it necessary that the sni-qt icons are there in png? Or would svg be ok as well?

**Comment by bil-elmoussaoui** [comment]
The guys from elementaryPlus tried to use SVG icons instead of PNG ones. But i don't remember that they've succeed; I will download the source code of sni-qt and see if there's anyway to patch that...

**Comment by bil-elmoussaoui** [comment]
If you clone the bzr repo, take a look at `src/iconcache.cpp` you will see that in the code there's a lot of `.png` I don't think that just changing that will make it works with SVG icons instead of png ones..

**Comment by wa4557** [comment]
Not worth the worries :)

**Comment by bil-elmoussaoui** [comment]
I will keep an eye on this, having will add HDpi support too ;)
