### ISSUE TITLE
teamviewer not working

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#131]
Although the icons are added in `~/.local/share/sni-qt` the new icon is not shown in the tray...

**Comment by bil-elmoussaoui** [comment]
Try changing the folder where Teamviewer tray icons are stored to `TVGuiDelegate`?

**Comment by bil-elmoussaoui** [comment]
And in `/tmp` , the icons are stored in a folder? if so, can you get the name of that folder

**Comment by wa4557** [comment]
the name is `sni-qt_TVGuiDelegate_3689-3btu2I` but this changes everytime teamviewer is opened

**Comment by bil-elmoussaoui** [comment]
This is how Qt icons works, can you screenshot the folder in `~/.local/share/sni-qt`and in `/tmp`too?

**Comment by wa4557** [comment]
in `/tmp/sni-qt_TVGuiDelegate_4314-ihUvdE`
```
icons/
└── hicolor
    ├── 128x128
    │   └── apps
    │       ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
    │       ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
    │       ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
    │       ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
    │       └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png
    ├── 16x16
    │   └── apps
    │       ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
    │       ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
    │       ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
    │       ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
    │       └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png
    ├── 24x24
    │   └── apps
    │       ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
    │       ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
    │       ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
    │       ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
    │       └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png
    ├── 32x32
    │   └── apps
    │       ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
    │       ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
    │       ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
    │       ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
    │       └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png
    ├── 48x48
    │   └── apps
    │       ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
    │       ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
    │       ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
    │       ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
    │       └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png
    └── 64x64
        └── apps
            ├── TVGuiDelegate_4314_0b040b0d9ec00ce0d8189ece93cd2b7f.png
            ├── TVGuiDelegate_4314_4327113cab136a09fac832e66878159a.png
            ├── TVGuiDelegate_4314_4cd9545d0021db224685d863ac738f91.png
            ├── TVGuiDelegate_4314_86e4f5bf63a6fa1725afd2e08e0ce105.png
            └── TVGuiDelegate_4314_c28d37df9872311f7c6b295b70b8a39d.png

13 directories, 30 files
```

and in `~/.local/share/sni-qt/TVGuiDelegate`

```
├── 0b040b0d9ec00ce0d8189ece93cd2b7f.png
├── 4327113cab136a09fac832e66878159a.png
├── 4cd9545d0021db224685d863ac738f91.png
├── 54b99333baa6a26fda3eb8ce6d664bd5.png
├── 86e4f5bf63a6fa1725afd2e08e0ce105.png
└── c28d37df9872311f7c6b295b70b8a39d.png
```

**Comment by bil-elmoussaoui** [comment]
Something is wrong in the `/tmp/sni-qt_*/` folder, in all the other Qt icons; the icons were only in `/tmp/sni-qt_*/icons/hicolor/24x24/apps`

**Comment by wa4557** [comment]
If I manually change the icons in /tmp it works though

Bilal Elmoussaoui <notifications@github.com> schrieb am Do., 24. Dez. 2015
14:10:

**Comment by bil-elmoussaoui** [comment]
Try installing the 32 bits version of sni-qt too?

**Comment by wa4557** [comment]
Already installed (skype is working). If I manually change the icons in `24x24/apps` it works

**Comment by bil-elmoussaoui** [comment]
try creating a `24x24/apps` folder for Teamviewer in `.local/share/sni-qt` and see if the new icons will work?

**Comment by bil-elmoussaoui** [comment]
I still need to build sni-qt:i386 version and i'm so busy those days. if you find a way to fix this feel free to modify the code :+1:

**Comment by wa4557** [comment]
I think I found out why teamviewer is not working. Teamviewer is shipping its own version of libsni-qt.so `/opt/teamviewer/tv_bin/RTlib/plugins/systemtrayicon/` which means that the patched version of `sni-qt` is probably not used

**Comment by wa4557** [comment]
This fixes it: `sudo ln -sf /usr/lib/i386-linux-gnu/qt4/plugins/systemtrayicon/libsni-qt.so /opt/teamviewer/tv_bin/RTlib/plugins/systemtrayicon/` I'm not sure though if this is a fix to implement in the code, or something that should be mentioned in the README

**Comment by bil-elmoussaoui** [comment]
Its depends if we can easily implement the create/remove symlink :+1:

**Comment by wa4557** [comment]
That's probably not to hard (i.e. I could do that) but it's a big change in the system...

**Comment by wa4557** [comment]
Ah what the heck I'm going to implement this!

**Comment by bil-elmoussaoui** [comment]
Well, adding to the readme is fine too. Maybe showing a message to the user to confirm that he wants to create that symlink :+1:

**Comment by wa4557** [comment]
Thinking about it, it's actually not a bigger change then changing `pngs`. I guess it's ok to do it

**Comment by bil-elmoussaoui** [comment]
Maybe adding a new section on the readme to explain why we do have to create that symlink?

**Comment by wa4557** [comment]
Sure I'll do that as well :+1: Finally my tray looks good again :)

**Comment by wa4557** [comment]
Done. I've added two short sentence in the Readme :+1:
It is really great that we have been able to fix every problem so far :)

**Comment by bil-elmoussaoui** [comment]
Thanks. Nice idea btw! I wouldn't think of that :+1: We did a great work on this
