### ISSUE TITLE
Icon size in Mint

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#132]
Reported by @ikuria 
The icon size used in Linux Mint 17.3 Rosa is 22x22. I'm not sure if the icon is small or it's normal? 
See the skype indicator
![psynkv1](https://cloud.githubusercontent.com/assets/7660997/11995051/24aca5ee-aa4a-11e5-86d7-557eb20dc107.png)
@Foggalong @wa4557 Anyone of you guys is using Cinnamon and can try that? :+1:

**Comment by ikuria** [comment]
https://i.imgur.com/Q4gsTnk.png

mint classic theme, the systray icon (only skype) the other ones are 
applets have diffrent css styles in the numix cinnamon.css, so i must 
change that to resize the icon i think,...

you prefere bigger icons? i like it that small *g* maybe i changed it 
that way, maybe its my resolution 1920x1080 on 13"FHD (xps13 Dell 
notebook)  but i want all the icons in a good proportion to each other 
in size
hope you understand, sry my english is not good xD

Anja



Am 24.12.2015 um 14:28 schrieb Bilal Elmoussaoui:

**Comment by wa4557** [comment]
Looks crisp, so I guess 22px is ok

**Comment by bil-elmoussaoui** [comment]
As it depends on the theme you're using; i'm going to close this. Maybe one day we won't need to patch any ugly icons
