### ISSUE TITLE
Building sni-qt 32bits version

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#133]
Skype and some other applications tray icons needs sni-qt:i386.
We need to add the new dependencies and how to build sni-qt as i386 package too

**Comment by bil-elmoussaoui** [comment]
@cybre do you know which flags should i add to `cmake ./ ` in order to build a 32bits version? I tried a lot of solutions from internet but i didn't succeed?

**Comment by cybre** [comment]
I have no idea @bil-elmoussaoui

**Comment by bil-elmoussaoui** [comment]
I added a way to build 32 bits version but not sure... @wa4557 can you try it ? :+1:

**Comment by bil-elmoussaoui** [comment]
Added and works fine here. @wa4557 It would be cool if you can check if it good explained :P

**Comment by cybre** [comment]
@bil-elmoussaoui This just came to my mind. Building sni-qt manually doesn't get you the patched version. The patch is loaded from a diff in `debian/patches` and that's handled in the packaging process.
You should add info about patching to your wiki (`patch -p1 < debian/patches/custom-icons-injection` from the parent directory of the repo before compiling)

**Comment by wa4557** [comment]
I was able to build the patched version of sni-qt exactly as it is presented in the wiki (the 64bit version)

**Comment by bil-elmoussaoui** [comment]
@cybre Thanks, added that :+1:

**Comment by cybre** [comment]
@wa4557 Well, I've just compiled it and it built the vanilla libraries.
Also, there is no rule in the build system to patch available patches.

**Comment by bil-elmoussaoui** [comment]
@cybre i don't understand pretty well what do you mean by "patch available patches"

**Comment by cybre** [comment]
Ah, I had a brain fart
"Also, there is no rule in the build system to patch the sources with the available patches/diff's"
There, fixed
