### ISSUE TITLE
Telegram Indicator

### ISSUE THREAD

**Issue by cpriego** [bil-elmoussaoui/Hardcode-Tray#135]
The script used to work with previous versions of Telegram but in the latest versions it stopped working.

**Comment by bil-elmoussaoui** [comment]
Which version of Telegram you're using?

**Comment by cpriego** [comment]
I'm using the latest versions of both Telegram (0.9.18) and Hardcode-Tray

**Comment by bil-elmoussaoui** [comment]
@cpriego Try opening Telegram and see if there's any new folder/icons created in `/tmp`
we had an issue with Telegram before in Ubuntu, i'm not sure if it's the same issue #99 #129

**Comment by cpriego** [comment]
I'm pretty sure is the same issue.

Yes, there's an icon in /tmp named qt-trayicon-XXXXXX.png

**Comment by bil-elmoussaoui** [comment]
Well, we can't do anything about it :/ Telegram ships a modified version of sni-qt (qt library used to create/show tray icons) and as every file is hardcoded in the binary file `Telegram` I can't fix it without rebuilding an other version of Telegram... Sorry about that!

**Comment by wa4557** [comment]
@bil-elmoussaoui Is it the same as with teamviewer? Can we overwrite the telegram `sni-qt` version?

**Comment by bil-elmoussaoui** [comment]
@wa4557 I don't think so , Telegram has only a binary file(executable one) :(

**Comment by bil-elmoussaoui** [comment]
@cpriego Can you open Telegram from terminal and paste the output ?
The binary file is in `/opt/telegram/` or in `~/.TelegramDesktop`

**Comment by cpriego** [comment]
I feared that (telegram hardcoding everything), should I close the issue?

**Comment by bil-elmoussaoui** [comment]
We will try to figure out a way to fix this

**Comment by cpriego** [comment]
Here's the output of the Telegram binary
```
./Telegram
libs init..
loading gtk-3 with version 0..
loaded gtk-3 with version 0!
loaded gtk funcs!
loading unity with version 9..
loaded unity with version 9!
unity count api loaded
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
```

**Comment by bil-elmoussaoui** [comment]
Can you try install libappindicator ? I don't know the exact package name

**Comment by cpriego** [comment]
Ok, done, do you want me to install the -dev version?

**Comment by bil-elmoussaoui** [comment]
Nop just the normal version, close Telegram and try again (using Terminal)
Telegram tries to use libappindicator first, before using the patched version of sni-qt 
```bash
loading appindicator3 with version 1..
could not load appindicator3 without version.
loading appindicator with version 1..
loaded appindicator with version 1!
```

**Comment by cpriego** [comment]
hmmm weird, I do have the libraries installed but the Telegram output didn't change. After my first attempt I tried all of the next:

1. Install telegram in new folder /opt/telegram and /opt/Telegram
2. Delete the .TelegramDesktop folder

but the output was always the same
```
libs init..
loading gtk-3 with version 0..
loaded gtk-3 with version 0!
loaded gtk funcs!
loading unity with version 9..
loaded unity with version 9!
unity count api loaded
```

**Comment by bil-elmoussaoui** [comment]
Maybe reporting that to Telegram as the libraries are not detected even if they're installed?

**Comment by cpriego** [comment]
Ok, let me do that.

**Comment by wa4557** [comment]
Relevant: https://github.com/telegramdesktop/tdesktop/issues/1908#issuecomment-211073097

I started coding, shouldn't be too hard

**Comment by wa4557** [comment]
Hmm, the code telegram is written right now it is NOT possible to change that, so that theme icons are used. This is because they are using an Qt version which is not the system one, which means that theme icons cannot be found...

I was, however, able to do a somewhat dirty hack, so that the old method (i.e. the one hardcode-tray uses) works, they won't merge that unfortunately because it really is a dirty hack -> I have now the NUmix icons back in the tray.

If you want I can send you the binary of that...

**Comment by cpriego** [comment]
@wa4557 Of course, if could please send me the binaries I'd be happy to try them. :smiley:

**Comment by wa4557** [comment]
Here you go. Just replace the executable with this one, then run `hardcode-tray` and it should work. I'm afraid that this won't work after an update
https://mega.nz/#!F4IWxSpY

**Comment by bil-elmoussaoui** [comment]
@wa4557 You have changed a lot of lines of code? I think the best way to close this issue, is adding the informations about it on the wiki with the temporary solution. if it's only few lines of code to change adding them instead of the executable file is better i guess

**Comment by wa4557** [comment]
I haven't, it's actually only one line. The thing is it is EXTREMELY hard to build `telegram` (it took me almost 1 week to figure that out, maybe that's my fault). To be fair I don't think my binary is a proper fix for this issue, I guess we have to keep that open

**Comment by wa4557** [comment]
I pushed a PR in telegram, that at least allows to replace the icons as it was possible before. System icon theming is still not possible though :(

We'll see if it gets merged

**Comment by bil-elmoussaoui** [comment]
@wa4557 The guys from telegramdesktop have added your fix to the dev branch.
@cpriego Can you try using the dev version of telegramdesktop or just check the latest stable version and see if your issue was fixed?

**Comment by cpriego** [comment]
It's been fixed since the latest couple of versions. I've been able to copy the icons to the tdata/ticons folder and telegram picks ups any existing icons. If the icon "number" does not exist is automatically generated (with the default telegram style).

Here are some pics of the ticons folder
![](https://s31.postimg.org/eli2di0jf/muestra_003.png)

and the Panel
![](https://s32.postimg.org/mddhjl40l/muestra_004.png)
![](https://s31.postimg.org/e0aytgsq3/muestra_005.png)

**Comment by bil-elmoussaoui** [comment]
That's great :D glad it's fixed now

**Comment by incorwild** [comment]
@cpriego where can I get icons for telegrams to be replaced? can you share them?

**Comment by bil-elmoussaoui** [comment]
Just install Numix thème, make it as your default theme and run the script as mentionned on the readme

**Comment by cpriego** [comment]
@incorwild Well, I just batch copied the png files in the folder but I'll share them here anyway https://db.tt/iLeSQw9d

**Comment by wa4557** [comment]
@incorwild Why don't you run the script? That's what it is for :)

**Comment by incorwild** [comment]
@cpriego thanks
@bil-elmoussaoui @wa4557 I do not want to install all the dependencies for one icon, which can be copied manually

**Comment by bil-elmoussaoui** [comment]
You don't need to install all of them.. just inkscape or cairosvg!
