### ISSUE TITLE
Possibility to fix one application

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#136]
I think it's a great idea to be able to fix/revert only one application.
Won't have to change a lot of things, just if the user adds a new arg to the command list and choose apply or revert the script will only fix/revert this application.
Something like `--only=telegram,skype`
@wa4557 What do you think?

**Comment by wa4557** [comment]
:+1: Should be nothing more than a `if not (sys.argv[1]=="only" and sys.argv[2]=="skype"): continue`

**Comment by bil-elmoussaoui** [comment]
Yeah! we just pass the argument to the `get_app_informations` https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/script.py#L260 And only get the infos for applications in the argument?

**Comment by wa4557** [comment]
Even better!

**Comment by bil-elmoussaoui** [comment]
Done! :+1: 
![screenshot from 2016-01-15 15-29-36](https://cloud.githubusercontent.com/assets/7660997/12355423/ce8cb9ba-bb9c-11e5-8966-f6b8c81cedad.png)

**Comment by wa4557** [comment]
Like that :)

**Comment by bil-elmoussaoui** [comment]
Yeah :) Just need some help, i don't know how to explain that the user can get the applications name from the second column in the db.csv file :/ Can you  do that? :+1:

**Comment by wa4557** [comment]
Sure
