### ISSUE TITLE
Gitter and Stremio support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#138]
Gitter and Stremio are using Electron (i guess)
The icons are hardcoded on `nw.pak`
I think that we need a better way to handle those applications(not like the chrome way)

Update: all the applications created using Nodejs/Electron and uses a tray icon has the icon hardcoded on `nw.pak` file

**Comment by wa4557** [comment]
What do you suggest? I guess there is no way to not use the unpack script and afterwards pack it again...

**Comment by Foggalong** [comment]
Might also be worth filing an upstream support to the Electron team.

**Comment by bil-elmoussaoui** [comment]
@wa4557 Yeah, just for chrome the icons didn't have the same name, and we had to copy them and have a "special" code just for chrome...
@Foggalong Yeah, i will diffidently do; to the Chromuim Team

**Comment by bil-elmoussaoui** [comment]
I couldn't find the icons anywhere :( @wa4557 Can you confirm that if you're using one of those applications please? :)

**Comment by bil-elmoussaoui** [comment]
Sadly i just found out that the icons are hardcoded in the js source files of those applications :/
