### ISSUE TITLE
 skype icon did not change

### ISSUE THREAD

**Issue by eldarik** [bil-elmoussaoui/Hardcode-Tray#139]
After running script icon did not change. Here is screenshot http://puu.sh/mGlD7/6560419507.png. DE-xfce 4.12

**Comment by wa4557** [comment]
Have you installed the patched version of sni-qt?

**Comment by Foggalong** [comment]
The icon Skype icon is massive so I'm guessing so

**Comment by eldarik** [comment]
@wa4557 yes, I've installed the latest version of sni-qt

**Comment by bil-elmoussaoui** [comment]
@eldarik have you installed the 32 bits version of sni-qt too?

**Comment by bil-elmoussaoui** [comment]
@eldarik can you give us more information please?
