### ISSUE TITLE
apps with a lot of icons

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#14]
Ok and last but not least the probably biggest issue:

As far as I understand the code right now you need all the telegram icons in order to replace them with icons from the theme (we discussed this also in the numix-base issue tracker). Wouldn't it be a good idea to add a second row in the `.txt` files with the icon name that is in the icon theme and is going to replace the original icon? This could be also optional (say if the name is the same, just put `, ,` there and the same name is used) and would allow to fix apps like `viber` and it wouldn't be necessary to add those funny named symlinks in numix-base

Plus it would be probably a good idea to turn the `.txt` files (this is soo Windows :P) to `.csv` or at least ommit the extension altogether :)

**Comment by bil-elmoussaoui** [comment]
I already did this for telegram,  you only need the first and the second icon for telegram; the rest of icons have a row with the icon the must be symlinked too
like this 
``` 
ico_22_3.png,ico_22_1.png
```
the ```ico_22_3.png``` will be automaticlly symlinked to ```ico_22_1.png``` instead of the original icon.

And i did changed from ```.csv``` to ```.txt``` to fix an issue with github as it's keeps asking me to fix it because i'm not using any comma in any database file

**Comment by wa4557** [comment]
Ok that's cool but for viber you'd need a different approach (just like I said above). I think it is better to deal with funny icon names here than at the icon-themes (I mean your script should basically work with every icon theme)

**Comment by bil-elmoussaoui** [comment]
The script will now check if the original icon exists if so, it will use it, if not it will use the icon you want to symlink it too

**Comment by wa4557** [comment]
Yeah this won't work, because line 97-99 have to come first...

**Comment by bil-elmoussaoui** [comment]
are you sure? because i check i modify the value of ```icon``` and ```symlink_icon```

**Comment by wa4557** [comment]
But you're checking if the icon `blabla.png` exists and this one definitely doesn't exist in for example `numix` because they are using `svgs` instead of `pngs` so the extension has to be removed before checking if the icon exists

**Comment by bil-elmoussaoui** [comment]
Never do algebra in the same time with python haha finals)! Thank you i forgot a line ,this is working now

**Comment by wa4557** [comment]
Ah algebra I see :), you shouldn't check github too often, algebra needs all of your attention :P Good luck! I'll try it out this evening and change the `.txt` files if it works

**Comment by bil-elmoussaoui** [comment]
I suppose this is fixed now?
