### ISSUE TITLE
Update chrome script

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#141]
In order to fix this issue #138 I updated the code we have been using to fix Google chrome/Chromuim icons. 
Everything works fine. The only issue is now it's possible to fix icons from different pak files. 
Those lines [#L504-L509](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/script.py#L504-L509) need to be updated in order to change counter `do` if the pak file of the next icon is different from the current one(remove the extracted file and the move the pak file) or if the pak file of the current icon is different from the previous one(copy the new pak file and unpack it to the extract  folder).
We will need to modify the [chrome](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/scripts/chrome) script file too i guess.

**Comment by bil-elmoussaoui** [comment]
@wa4557 Would you like to take care of this if you have some free time? :)

**Comment by wa4557** [comment]
I see what I can do. As you may have noticed I'm not so much arund these days because I have a shitload of work to do, but I'll have a look at it :)

**Comment by wa4557** [comment]
I had a look into it, but I'm not sure what you want to have sorry. For all the apps with thos `pak` icons we have special scripts anyways...

**Comment by bil-elmoussaoui** [comment]
If you took a look at Chrome script, there's an icon that i haven't fixed because it's not in the same pak file as the others..

**Comment by wa4557** [comment]
Ah so you mean see first if the currently extracted pak file is the one needed for the current script, and if no remove it and extract the new one. I think I get it now :)

**Comment by bil-elmoussaoui** [comment]
Yes, i was not that clear sorry :p

**Comment by bil-elmoussaoui** [comment]
There's the reason why i did all of that :P 
![capture du 2016-01-24 19-35-49](https://cloud.githubusercontent.com/assets/7660997/12538136/b305bfde-c2d1-11e5-8f52-44287a7daa08.png)

**Comment by wa4557** [comment]
Looks good :) Except for the skype icon...

**Comment by wa4557** [comment]
There are several problems when trying to do this, need your thoughts on this: 

1) The chrome pak is extracted already in `get_correct_chrome_icons` and not deleted afterwards. This makes sense because there is no sense in doing this multiple times.

2) The thing is: In order to find out the correct icons it is necessary to unpack all the other `pak` files for this app as well, so this means that we have to remove the previously unpacked folders...

3) What we can do (not a big fan of that though): Unpack the first `pak` file - find the correct icons - remove it. Unpack second `pak` file - find icons - remove it. And afterwards doing the same thing when fixing the icons...

Any ideas? (Anyways I'll have to work on it tomorrow, have other work to do now)...

**Comment by bil-elmoussaoui** [comment]
1)  I've just added the code to remove the extracted folder at the end of `get_correct_chrome_icons` , because the latest extracted pak file may not be the same as the first one.
2) Yes, the pak folder should be removed just after finding the right icon;
3) it's what i thought too; may not be the best way but it's fast enough (extracting the pak files does not take really to much time);

**Comment by wa4557** [comment]
:+1: Cool then it shouldn't be too hard, already have some ideas :) we might find an even better solution in the future :)

**Comment by bil-elmoussaoui** [comment]
I've made few modifications to the way we detect the right icons, i think this will fix every pak file in the future (i hope)  :+1:

**Comment by Foggalong** [comment]
A little off topic, but are those insync emblems themeable?

**Comment by bil-elmoussaoui** [comment]
@Foggalong They're and the icons do exists in Numix theme; but i really don't know why there's not being used.. :(

**Comment by Foggalong** [comment]
@bil-elmoussaoui damn :(

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you explain to me what was your idea so i can write the code ? :+1: i would like to release a stable version as soon as possible

**Comment by wa4557** [comment]
Sorry for not coming back to this for such a long time, had a shitload of work to do the last months. (But I'm back now - though not so often as I used to be probably). Anyways: my original idea was something like this: 

1) when looping through all the apps (get_app_information), unpack the corresponding pak files to folders that correspond to their names (so chrome_100 for chrome_100.pak) and don't delete them 
2) store the names of the folders in a list
3) When changing the icons go into those folders and change the icons repack them and then delete the folder...

**Comment by bil-elmoussaoui** [comment]
@wa4557 Not a problem. Do you think you still have the time to do this? otherwise i can implement it when i have some free time :)

**Comment by wa4557** [comment]
I can do it end of next week if that's early enough...

**Comment by wa4557** [comment]
I have a really hard time, figuring out how to do this best... The code has become too complicated to just simply change things...

**Comment by bil-elmoussaoui** [comment]
Yeah i know.. i want to do this too, but so busy with studies those days.. :/

**Comment by wa4557** [comment]
I'm slowly understanding what needs to be done. A lot of code needs to be rewritten though :(

**Comment by bil-elmoussaoui** [comment]
Well, maybe just updating the chrome script? What needs to be done is removing the old pak file, extract the new one, and remove it when the old pak file name isn't the same as the one before, that shouldn't be hard to do by sending the pak file name to the bash script and change the `do` variable value to other values that means to remove/extract/copy the pak file..?

**Comment by wa4557** [comment]
the problem is the function `get_correct_chrome_icons` -> very twisted

**Comment by bil-elmoussaoui** [comment]
Can you explain more which things should be modified/not working correctly in `get_correct_chorme_icons`? I will try to fix it this evening

**Comment by wa4557** [comment]
What I tried so far (I've uploaded my changes to this branch: https://github.com/wa4557/Hardcode-Tray/tree/script)

every program that needs to be extracted, extract to a foldername that corresponds to its `pak` file. This way unpacking only once would be sufficient for all programs (just check if the folder already exists etc...). I changed `get_correct_chrome_icons` already in a way that should work (there's still a smaller error somewhere I wasn't able to find yet)...

Now we just need to change the chrome script file (and spotify and all the other programs that needs unpacking)

**Comment by bil-elmoussaoui** [comment]
Spotify does not use get_correct_icons function?

**Comment by wa4557** [comment]
True, this is why we need to change the spotify script as well, to extract to its own folder. But the thing is: spotify does not need to clean up after itself (deleting the folder) but the script can do that after everything is finished.

**Comment by bil-elmoussaoui** [comment]
Great! Seems to be the best solution :+1:

**Comment by wa4557** [comment]
is it only chrome and spotify that do unpacking?

**Comment by bil-elmoussaoui** [comment]
Yes, the only other script is Teamviewer but it's only copy a file

**Comment by wa4557** [comment]
Ok I've fixed the errors that were still occuring, I'm not sure ,however, if the script works as intented. Can you try?

**Comment by bil-elmoussaoui** [comment]
Everything works fine; the pak files are extracted on `extracted/pakfilename`. The folder is removed at the end. But the icons are not being fixed. I don't understand why you've removed the (0/1) in the chrome database file. Some icons have a file name that changes in each chrome version; but the icon in the resources.pak is always the same, the 1 means that the icon name provided is not the correct one and need to be changed by the `get_correct_chrome_icon`. I don't know if it's clear enough

**Comment by wa4557** [comment]
Ah I see. Ok I thought this is for something else that is not needed anymore. I still have not figured out how to reliably do it with those "do" variables though

**Comment by bil-elmoussaoui** [comment]
I might help fixing the "do" part this weekend, maybe moving your code to a beta branch here so i can push my commits too?

**Comment by wa4557** [comment]
How can I merge to a new branch?

**Comment by bil-elmoussaoui** [comment]
The easiest way is to create a new branch and move your code to the branch and push it!

**Comment by wa4557** [comment]
Done :+1:

**Comment by bil-elmoussaoui** [comment]
Thanks! i will finish the code tomorrow (i hope)

**Comment by bil-elmoussaoui** [comment]
Everything works fine now! One last issue is the pak file is not copied back :+1:

**Comment by wa4557** [comment]
If the "do" variable is working now, everything should be ok!

**Comment by wa4557** [comment]
I'm actually wondering if we can do the same as with the electron files here. Unpacking into memory replacing the png bits on the fly and repacking from memory. I suppose it can be done, albeit it may be a bit harder because we have to compare the pngs also

**Comment by wa4557** [comment]
I updated the spotify to do the same, no more extracting is now necessary, which means that it is a lot faster, and doesn't have to write so much on the harddisk either -> next up chrome

**Comment by wa4557** [comment]
@bil-elmoussaoui I've updated the script in the beta branch to get correct chrome icons without extracting everything, can you try and test it?

**Comment by bil-elmoussaoui** [comment]
Thanks for your hard work, im going to try it in few hours

**Comment by wa4557** [comment]
No worries, is good to come away from work sometimes :)

**Comment by bil-elmoussaoui** [comment]
It does not detect the icons at all, i tried it with Chrome & Chromium

**Comment by wa4557** [comment]
Hmm the question is why. Any obvious mistakes in my code?

**Comment by bil-elmoussaoui** [comment]
I hadn't the time to read the whole code yet, but i think that the icons are not the same anymore? and for the icons that have the 0 as the latest parameter passed should not be checked if they exists or not

**Comment by wa4557** [comment]
Yeah this also what I think, the icon changed I will try to get the new ones...

Why exactly shouldn't they be changed?

**Comment by bil-elmoussaoui** [comment]
Because the icon name is always the same (for chrome and chromium) it's the ugly icon always shown, not the notification one

**Comment by wa4557** [comment]
Ah ok, yeah makes sense

**Comment by bil-elmoussaoui** [comment]
Wanna add this condition or you want me to do it?

**Comment by wa4557** [comment]
Sure go ahead

**Comment by bil-elmoussaoui** [comment]
There was some missing stuff on the chrome script, this is the new version, but i still have an issue 
```python
#!/usr/bin/python3

import struct
import json
import sys
import data_pack
import os
from imp import load_source

filename = sys.argv[3]+sys.argv[5]
icon_to_repl = sys.argv[2]
icon_for_repl = sys.argv[1]

svgtopng = load_source('svgtopng', './database/scripts/svgtopng.py')

filename_svg, file_extension = os.path.splitext(icon_for_repl)
if file_extension == '.svg':
    pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
else:
    with open(icon_for_repl, 'rb') as pngfile:
        pngbytes = pngfile.read()

dataPack = data_pack.ReadDataPack(filename)
dataPack.resources[int(icon_to_repl)] = pngbytes

data_pack.WriteDataPack(dataPack.resources, filename, BINARY)

```

the error message is 
```
fixing failed with error:
	Traceback (most recent call last):
	  File "./database/scripts/chrome", line 26, in <module>
	    data_pack.WriteDataPack(dataPack.resources, filename, BINARY)
	NameError: name 'BINARY' is not defined
	

```

**Comment by wa4557** [comment]
Ah you can replace binary with 0

**Comment by bil-elmoussaoui** [comment]
Wow! it works :D tested with Chrome & Chromium
![capture du 2016-05-08 00-02-35](https://cloud.githubusercontent.com/assets/7660997/15094801/2f0403c2-14b0-11e6-856e-271761a2b294.png)

**Comment by wa4557** [comment]
How cool 😎 now nothing is extracted and everything is done on the fly

Bilal Elmoussaoui <notifications@github.com> schrieb am So., 8. Mai 2016,
00:02:

**Comment by bil-elmoussaoui** [comment]
Yay! finally fixed
