### ISSUE TITLE
Boinc Tray Icon

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#145]
The only icon I'm missing. I forget how this work so let me know what information I need to add and I'll find it :)
![screenshot_2016-02-21_14-08-43](https://cloud.githubusercontent.com/assets/5920259/13203015/a54c0914-d8a4-11e5-8f5a-3238ce78839a.png)

**Comment by bil-elmoussaoui** [comment]
I will add it as soon as possible :+1:

**Comment by bil-elmoussaoui** [comment]
I couldn't find the icon location :/

**Comment by Foggalong** [comment]
No, me neither. Really hidded away :(

**Comment by bil-elmoussaoui** [comment]
I will take a look at the source code this evening and see if i can find out a way to fix it :+1:

**Comment by bil-elmoussaoui** [comment]
Sorry couldn't find anything on this.. if you have any more information like icons directory reopen this issue :+1:

**Comment by Foggalong** [comment]
I don't sorry :( I couldn't find anything in my search

**Comment by bil-elmoussaoui** [comment]
Maybe opening a new issue on BOINC github repository and we will see if
they will provide more information

**Comment by Foggalong** [comment]
I tried to do this, but couldn't even find which BOINC repo corresponded to the GTK app. The link on their website shows up dead, though I don't think they've taken it closed source :/

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you give a look at this one? It was by far the only application that we haven't successed to fix until now...

**Comment by wa4557** [comment]
I'm not even able to install this app oO Some serious library issues with Ubuntu 16.04. Anyways there seems to be a png shipped with this program? Isn't it the one that needs to be replaced?

**Comment by bil-elmoussaoui** [comment]
I downloaded the source code of the application, those are the tray icons used by the applications 
https://github.com/BOINC/boinc/tree/master/clientgui/res
For example `boincdisconnect.xpm`
The problem, is once you install a pre-compiled application, you won't find any trace of those icons :P
