### ISSUE TITLE
Whatsie support

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#147]
There is a beautiful whatsapp wrapper on linux that creates a tray icon called whatsie. Unfortunately they use hardcoded tray icons :( 

https://github.com/Aluxian/Whatsie

I already opened a issue there asking for themable tray icons, but as far as I understand its currently not possible with the framework they are using (javascript / electron :o)

I guess the images are stored in a biinary file `/opt/whatsie/resources/app.asar` which is probably possible to unpack, I was, however, so far unable to do that...

@bil-elmoussaoui Any ideas?

**Comment by bil-elmoussaoui** [comment]
I will take a look at the PR

**Comment by bil-elmoussaoui** [comment]
Can you open an other PR and change the script name from whatsie to electron?
