### ISSUE TITLE
Support more electron apps

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#150]
Here's a small list of most used electron apps (i think) : 

- [x] Gitter -won't fix- the application does not have a `app.asar` file
- [x] Slack desktop - already fixed, nothing to do here :)
- [x] Stremio

**Comment by bil-elmoussaoui** [comment]
@wa4557 Seems that Stremio use the same path for images as Whatsie, i renamed the script to electron instead of Whatsie. But i couldn't unpack the slack `app.asar` file, can you give it a try?

**Comment by wa4557** [comment]
Yeah I can try that out. For Gitter: there's probably a asap file somewhere else?

**Comment by bil-elmoussaoui** [comment]
I couldn't find it.. and btw after trying fixing Stremio with the script i had this issue
```
fixing failed with error:
	Traceback (most recent call last):
	  File "./database/scripts/electron", line 44, in <module>
	    files = json.loads(header)
	  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
	    return _default_decoder.decode(s)
	  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
	    raise JSONDecodeError("Extra data", s, end)
	json.decoder.JSONDecodeError: Extra data: line 1 column 212343 (char 212342)
```
when i tried to print the json file content(the header variable) it seems to be a unicode issue. Using `asar extract app.asar ./stremio` extracts the file correctly without any issue

**Comment by wa4557** [comment]
Ok it seems there's something wrong with the headersize (also for stremio). I really think we have to add custom scripts for all of those electron icons

**Comment by bil-elmoussaoui** [comment]
Alright, just wanted to have a script for all electron apps, but let's keep it simple for now

**Comment by wa4557** [comment]
Sure that would be ideal, but on the other hand the scripts are relatively simple...

**Comment by wa4557** [comment]
I've added a stremio script that fixes the above error, I'm not 100% sure why but the header is 3 bytes too short :( can you try it out?

**Comment by bil-elmoussaoui** [comment]
Still getting this 
```
fixing failed with error:
	Traceback (most recent call last):
	  File "./database/scripts/stremio", line 45, in <module>
	    files = json.loads(header)
	  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
	    return _default_decoder.decode(s)
	  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
	    obj, end = self.scan_once(s, idx)
	json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 212342 (char 212341)
```

**Comment by wa4557** [comment]
Yeah I know, I will try to rewrite the script to make it suitable for any electron app

**Comment by wa4557** [comment]
For slack: do you have this file? `usr/lib/slack/resources/app.asar.unpacked/src/static/slack-taskbar-rest.png` and what happens if you change it?

Btw: I think I have figured out a way to use one `electron` script to fix all electron scripts, I have to test it a bit more though

**Comment by bil-elmoussaoui** [comment]
I will try that for Slack.
Btw, i just figured out that i've already added the database file for Slack with this icon line without testing it :p

**Comment by wa4557** [comment]
I guess it won't work right away, but slack has a slightly different `asar` file where the png is not stored in the file

**Comment by bil-elmoussaoui** [comment]
I can confirm that the new script fixes Stremio icon without any issues! :+1: I just need to reinstall the application and see if everything will work fine

**Comment by bil-elmoussaoui** [comment]
I've got this issue when i run the application, maybe it's due to a verification from Stremio's side to be sure that the files were not changed? 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/usr/share/stremio/resources/atom.asar/browser/lib/init.js:92:11)
    at Object.<anonymous> (/usr/share/stremio/resources/atom.asar/browser/lib/init.js:125:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
```

**Comment by wa4557** [comment]
Oh damnit it, thiis means that I'm doing something wrong in decoding the file... I will try to look into that.

**Comment by wa4557** [comment]
I think I found the problem, but it is a bit hard to figure out how to fix the error, I'll try and do this tomorrow :)

**Comment by wa4557** [comment]
Fixed last issue with stremio the, script works now with stremio and whatsie, and every other electron app :)

**Comment by bil-elmoussaoui** [comment]
Perfect ! :D

**Comment by wa4557** [comment]
Oh come on, now whatsie stopped working :(

**Comment by bil-elmoussaoui** [comment]
Maybe it's impossible to fix all electron apps using only one script ?

**Comment by wa4557** [comment]
This is what I'm trying but it's hard

**Comment by wa4557** [comment]
Now it is working :)

**Comment by bil-elmoussaoui** [comment]
Thanks for fixing this! :+1:
