### ISSUE TITLE
Correct chrome icons to compare to

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#151]
The icons that we use right now to compare the chrome icons to are incorrect, since they seem to have changed over the last releases. We might need to implement something that allows to loop over multiple `png` icons in the `get_correct_chrome_icons` function

**Comment by bil-elmoussaoui** [comment]
We just need to create a folder for each release and loop over the icons in each folder, once an icon is found in the folder we don't look on the next one?

**Comment by wa4557** [comment]
I think we can throw them all into one folder and just append sth like `-1.png` to it and then compare it. I'm working on that... I just can't get the notifications to work, so I don't know which icons are the correct ones.

**Comment by wa4557** [comment]
I fixed the code. All we need now is to put the new icons into the same folder alongside the old ones with `1.png` `2.png` etc. suffixes

**Comment by bil-elmoussaoui** [comment]
I will add the new icons (if i can find them) in a few minutes

**Comment by bil-elmoussaoui** [comment]
The only icons that looks like notification tray icon are
In the `chrome_100_percent.pak`
![5622](https://cloud.githubusercontent.com/assets/7660997/15274545/d36de7de-1ab4-11e6-98d5-e29915bd3d83.png) ![5623](https://cloud.githubusercontent.com/assets/7660997/15274543/d36d82c6-1ab4-11e6-9311-a85f08ec84f4.png) ![5624](https://cloud.githubusercontent.com/assets/7660997/15274544/d36dbd7c-1ab4-11e6-9c8d-9cad64591a92.png)
But i couldn't find the normal status icon, i used the latest version of Chromium :/

**Comment by wa4557** [comment]
can you get them to show up? I can't...

**Comment by bil-elmoussaoui** [comment]
I can't neither.. and that's why http://www.omgchrome.com/chrome-drops-notification-center-from-windows-mac-and-linux/

**Comment by wa4557** [comment]
Oh nice, was completely useless anyways :)

**Comment by bil-elmoussaoui** [comment]
Yeah
