### ISSUE TITLE
Force icon theme

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#154]
I think that the user should have the possibilty to use an other icon theme instead of using the default one.
For example, if you use an other icon theme and it's does not support all the hardcoded icons, it would be perfect combination with `--only` option.

@wa4557 What do you think?

**Comment by wa4557** [comment]
Sure. A `--theme` flag should be a good idea

**Comment by bil-elmoussaoui** [comment]
Just started working on this, but i can't see how i can use the other theme without changing the theme for a moment
I found a function on the documentation `Gtk.IconTheme.set_custom_theme(IconTheme theme_name)` it takes an object of type IconTheme, but how i can create a new one using the theme name entered by the user! Do you have any idea?

**Comment by bil-elmoussaoui** [comment]
Nevermind ,fixed that :p
