### ISSUE TITLE
Add the script to pip

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#155]
The script is growing up more and more and in order to make it easier to fix ugly tray icons. I thought that we can add the script to pip packages (if it's possible) so the user can upgrade to a newer version and can use it by something like `sudo -E Hardcode-Tray` which is better than having to clone the package each time you want to use it.

@wa4557 What do you think about that? :)

**Comment by wa4557** [comment]
I don't know. Isn't pip supposed to be for python modules, rather than scripts doing something which happens to be written in python?

**Comment by bil-elmoussaoui** [comment]
Not really, you can even add examples for your module as a pip package or scripts (you can find them easily in the search section). It's just package manager for everything related to Python

**Comment by wa4557** [comment]
Probably a ppa would still be better? (I have no experience with this kind of things...)

**Comment by bil-elmoussaoui** [comment]
Well, i would love to have a PPA but it will only works with Ubuntu, and those stuffs changes a lot. Adding the script to pip will make it available for all linux users

**Comment by bil-elmoussaoui** [comment]
I thought about this, and i was looking on aur packages and i find out that someone created an aur package for Hardcode-Tray but it's really cool to see that :) I think we should create a simple bash script that will be called instead of calling the python file, the bash script will call `sudo -E python3 script.py $1...`
The installation will be a simple script that will copy the cloned folder to `/opt/Hardcode-Tray` for example, creates a symlink from the bash script to `/usr/bin/Hardcode-Tray`, we can add an option to upgrade the script and print it's version, we do all of that on the bash script to keep the python files clean.
What do you think? :P

**Comment by wa4557** [comment]
Nice!

I like the idea of a script that acts as a wrapper, but it is actually not necessary. Just rename `script.py` to `hardcode-tray`(or sth else is probably better, but without ending, since we have the shebang there). 

And we have to think about a way to not use the `-E` flag for `sudo`

**Comment by bil-elmoussaoui** [comment]
I think having an other bash script that will have those optional options : 
- `update`
- `version`
And if none of them is used the bash script calls the python file with the `-E` flag. And we can't really remove the `-E` flag as it's used to detect the default theme too. Try runing the script with `sudo python3 script.py --size 24` the theme name won't be Numix but the default theme on your distro..

**Comment by bil-elmoussaoui** [comment]
I've added a new branch `install`, the branch contains `hardcode-tray`, `install.sh` and `uninstall.sh`
The `install.sh` and `uninstall.sh` are scripts that will be called by the user from the documentation.
