### ISSUE TITLE
Spotify script dangerous

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#156]
In the spotify script, the script generates a folder in `/` repacks the `zip` folder and removes this folder afterwards. This is because it is only possible to update a file in a zip archive if it has exactly the same absolute path as in the zip file, I don't know why... 

Is the last `rm -rf /_linux/` potentially dangerous, we don't want a `rm -rf /` to happen, when running the script. Is there any other way to update a file in a zip file without creating and deleting folders in the root directory? (Maybe using python instead of bash?)

**Comment by bil-elmoussaoui** [comment]
Totally agree with you! We can use `zipfile` i did some searches and i think we can update a zip file without having to extract it. There's an example of the code here [StackOverflow](http://stackoverflow.com/questions/25738523/how-to-update-one-file-inside-zip-file-using-python)

**Comment by wa4557** [comment]
Well as far as I understand this still does not allow changing files in place

**Comment by wa4557** [comment]
I did some research, and it seems that there is no easy way to do that :(  so we either keep it as it is now, or we go back to extracting etc. (I vote for keeping it as it is now)

**Comment by bil-elmoussaoui** [comment]
I vote for keeping the script as it's now, maybe using the absolute path of the directory instead of  ` rm -rf /_linux/` to avoid removing an other folder? this will reduce the probability of removing everything

**Comment by wa4557** [comment]
Well that is the absolute path. But yeah thinking about it, it is actually not dangerous since this path is hardcoded anyways...

**Comment by bil-elmoussaoui** [comment]
Closing this then, we might find a better solution using only python in the futur :)
