### ISSUE TITLE
Add Electron apps to how to contribute

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#158]
We should add a small paragraph on how to get the icons from the `asar.file`

**Comment by wa4557** [comment]
Hmm. I don't know. It is actually pretty hard to figure out the right icons, isn't it?

**Comment by bil-elmoussaoui** [comment]
Yes, the hardest part is finding the key of the icons :( but we can just explain briefly how that works and how to extract an `asar` file using `asar` npm package, what do you think?

**Comment by bil-elmoussaoui** [comment]
Added few texts, can you see if everything is cristal clear?

**Comment by wa4557** [comment]
Looks fine :+1:
