### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#160]
No time to fix it, but just a quick reminder that the last changes broke the script:

```
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 587, in <module>
    install(fix_only)
  File "/opt/Hardcode-Tray/script.py", line 445, in install
    apps = get_apps_informations(fix_only)
  File "/opt/Hardcode-Tray/script.py", line 311, in get_apps_informations
    db = open(db_file)

FileNotFoundError: [Errno 2] File or directory not found: 'db.csv'
```

**Comment by bil-elmoussaoui** [comment]
Works perfectly here.. can you try with the modification i just pushed?

**Comment by wa4557** [comment]
No that didn't help. Reproducible when running the script outside of the `Hardcode-tray` folder. Just go to your `home` folder and try running `hardcode-tray`

**Comment by bil-elmoussaoui** [comment]
Forgot to test the script somewhere else than the installation folder :P Should be fixed now
