### ISSUE TITLE
Spotify support is broken in latest version

### ISSUE THREAD

**Issue by kerozoli** [bil-elmoussaoui/Hardcode-Tray#161]
Spotify support is broken for me in the latest version (earlier version worked for me)
Error in console :

Spotify -- fixed using spotify-indicator
fixing failed with error:
	/opt/Hardcode-Tray/database/scripts/spotify: 3. sor: cd: ./database/scripts: Nincs ilyen fájl vagy könyvtár
	python3: can't open file 'svgtopng.py': [Errno 2] No such file or directory

**Comment by bil-elmoussaoui** [comment]
Can you try changing the `spotify` script file to this 
```bash
#!/bin/bash

cd ./database/scripts
mkdir -p /_linux/

f="/_linux/$2"
if [[ $1 == *.svg ]]; then
    python3 ./svgtopng.py "$1" "$f"
else
    cp $1 $f
fi

zip -u "$3""$4" "$f"
rm -rf "/_linux/"
```
The spotify file is in `/opt/Hardcode-Tray/database/scripts/`
In the latest version of Spotify, the indicator is not working anymore that's why i can't test if the solution works! 
Thanks for reporting

**Comment by kerozoli** [comment]
Hi,

The fix isn't working for me.
Yeah,I still using spotify 0.97... because of the indicator :)
I will try to fix the script and make a pull request if it works. 
Is this good for you ?

Thanks,
Zoltán Keresztes

**Comment by bil-elmoussaoui** [comment]
PR are welcome :) You can just change `    python3 ./svgtopng.py "$1" "$f"` to `    python3 /opt/Hardcode-Tray/database/scripts/svgtopng.py "$1" "$f"` but it's not the cleanest solution

**Comment by kerozoli** [comment]
The "cd" in the 3. line isn't working :

cd ./database/scripts

because the actual directory is where i run "hardcoded-tray"

if I change this line to :

cd /opt/Hardcode-Tray/database/scripts

everything works fine

But this isn't clean too :)

**Comment by bil-elmoussaoui** [comment]
Fixed! Run `hardcode-tray --update` to update your script.
Thanks for reporting again :)

**Comment by kerozoli** [comment]
It works :) Thanks for the fix

**Comment by wa4557** [comment]
This is actually a bad fix. If I don't have the script installed and just try to run the script it fails now :(

**Comment by bil-elmoussaoui** [comment]
I will see what i can do

**Comment by bil-elmoussaoui** [comment]
I've pushed a better fix, can you guys test it ? :+1:

**Comment by kerozoli** [comment]
I tested the fix and it's working
Thanks
