### ISSUE TITLE
Franz

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#162]
another (great) electron app. http://www.omgubuntu.co.uk/2016/04/franz-messaging-app-linux-slack-whatsapp-telegram. This one can be themed wthout altering the `app.asar` file but just by replacing a few icons. The thing is: There is no official way to install it but just downloading a source package and run it from there, which means that there is no "official" location for the icons. 

How do we deal with that?

**Comment by bil-elmoussaoui** [comment]
Maybe having a hardcoded path for application directory? 
During the fix, if the icons do exists, we ask the user to enter the application path, which is not perfect if the user updates the script. We will need an other csv file stored, on `~/.config/` with the hardcoded paths of each application(this one, and maybe others on the future)
But the hardest part, is how to detect if the application is installed...

**Comment by wa4557** [comment]
But how can the script detect if the app exists?

**Comment by bil-elmoussaoui** [comment]
I've got a better idea!
We add `franz` support with `/opt/franz` as the default path (Aur package https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=franz)
We modifiy `--only` so the user can write a `--path` to the application directory. And ofc, we do that only if the user wants to fix only one application!

**Comment by wa4557** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
Do you want to do that? i will look into fixing nwjs apps tomorrow

**Comment by wa4557** [comment]
I'll do my best. So just to be clear: `--path` should only work if there's also the `--only` flag, right?

**Comment by bil-elmoussaoui** [comment]
It should work only if the https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/script.py#L320 has only one application, as you can fix more than one application using `--only`
`hardcode-tray --only dropbox --path /opt/dropbox/` should work, but `hardcode-tray --only dropbox,skype --path /opt/skype`  should ignore the path argument

**Comment by wa4557** [comment]
Ok that's easy :)

**Comment by bil-elmoussaoui** [comment]
Yep :p just a simple condition to add

**Comment by wa4557** [comment]
This should be fixed now, I guess :)

**Comment by bil-elmoussaoui** [comment]
Great! :+1:
