### ISSUE TITLE
sudo -E hardcode-tray not working

### ISSUE THREAD

**Issue by IronJaeger** [bil-elmoussaoui/Hardcode-Tray#165]
runing "sudo -E hardcode-tray" after installation returns error message: 
" You need to run the script using 'sudo -E'.
Please try again"

Thanks :)

**Comment by bil-elmoussaoui** [comment]
Script was not able to desktop session, you can fix that by forcing icon size
`sudo -E hardcode-tray --size 24` or 22 if it's fits better with Solus

**Comment by IronJaeger** [comment]
tried both, killed budgie-panel for refresh, didn't show anything :/

**Comment by bil-elmoussaoui** [comment]
What was the output after using `sudo -E hardcode-tray --size 24`?

**Comment by bil-elmoussaoui** [comment]
* Sorry, you should not call the script using sudo -E, just call `hardcode-tray --size 24 --theme Numix-Circle` (the theme is detected automatically, but just in case.)

**Comment by IronJaeger** [comment]
My icon theme is recognized as Faba , this is the icons folder by Jeorge Sanchez from soluscentral: https://drive.google.com/file/d/0B3A0PYw7fIlJOWZ1VUR1YS1oM00/view?usp=drive_web  we use this because the numix icons do not have "symbolic" which contains the menu button and it replaces it with the ugly stinky gnome foot. with this pack you got Numix circle with mnu button that you can change it with what you want.

**Comment by bil-elmoussaoui** [comment]
Ah i thought you were using Numix Circle with Numix base icons! The theme you're using does not provide a `google-chrome-tray` icon. You will need to add this icon to your icon theme, update the cache and run the script again. Closing as this has nothing to do with script!

**Comment by IronJaeger** [comment]
All right, thanks for everything,  "lah yhfdeeeek"  :D
