### ISSUE TITLE
Not working Dropbox theme icons

### ISSUE THREAD

**Issue by suprovsky** [bil-elmoussaoui/Hardcode-Tray#166]
```
hardcode-tray --theme Numix-Circle --only dropbox
hardcode-tray --theme Numix --only dropbox
hardcode-tray --apply
```
did nothing.
I'm using Gentoo x64 with latest stable packages + unstable Dropbox 5.3.23. I've installed dependencies by manual compiling. The same thing was on every version of dropbox. Only version 2.10.2 had nice icons.

When I was emerging new version of dropbox in verbose mode, I found out where dropbox keep its tray icons:
```
>>> Safely unmerging already-installed instance...
No package files given... Grabbing a set.
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-x.png
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-logo.png
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-idle.png
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-busy2.png
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-busy.png
--- replaced obj /usr/share/icons/hicolor/16x16/status/dropboxstatus-blank.png
```
I've converted icons from Numix-Circle theme to png, replaced and it works.
I'm also attaching converted icons if somebody could need it.
[aa.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/316355/aa.zip)

**Comment by bil-elmoussaoui** [comment]
Where did you replace the icons ? in `/usr/share/icons/hicolor/16x16/status`?

**Comment by suprovsky** [comment]
Yeah.

**Comment by bil-elmoussaoui** [comment]
Well, which means that Dropbox get the icons from the fallback theme instead of Numix. I can't do anything about it. It must be the distro you're using :/

**Comment by suprovsky** [comment]
I will test it tommorow on Xubuntu 16.04 and I'll give you more info about that.

**Comment by bil-elmoussaoui** [comment]
Thanks! And i can't add this path `/usr/share/icons/hicolor` to the dropbox path as this will change the fallback theme

**Comment by bil-elmoussaoui** [comment]
@suprovsky any news?

**Comment by bil-elmoussaoui** [comment]
Reopen this if you have any more info!
