### ISSUE TITLE
Not working with skype

### ISSUE THREAD

**Issue by Winterwolf** [bil-elmoussaoui/Hardcode-Tray#168]
I just installed [latest](https://www.skype.com/en/download-skype/skype-for-computer/) skype for ubuntu 64 (12.04 multiarch), run your script and nothings changes.

**Comment by wa4557** [comment]
Have you installed the modified `sni-qt` package?

```
sudo add-apt-repository ppa:cybre/sni-qt-eplus
sudo apt-get update && sudo apt-get dist-upgrade
sudo apt-get install sni-qt sni-qt:i386
```

**Comment by Winterwolf** [comment]
Yes, just installed. Run script again and nothing. With other apps (dropbox for example) script works fine. I'm using lubuntu 16.04.

**Comment by bil-elmoussaoui** [comment]
Can you paste the output of the script when you run it?

**Comment by Winterwolf** [comment]
```
sudo -E hardcode-tray
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Faenza
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Dropbox -- fixed using dropboxstatus-busy
Dropbox -- fixed using dropboxstatus-busy2
Dropbox -- fixed using dropboxstatus-idle
Dropbox -- fixed using dropboxstatus-logo
Dropbox -- fixed using dropboxstatus-x
Google Chrome -- fixed using google-chrome-tray
Skype -- fixed using skype-status-away
Skype -- fixed using skype-status-away-notification
Skype -- fixed using skype-status-connected
Skype -- fixed using skype-status-connected-notification
Skype -- fixed using skype-status-connecting-0
Skype -- fixed using skype-status-connecting-1
Skype -- fixed using skype-status-connecting-2
Skype -- fixed using skype-status-connecting-3
Skype -- fixed using skype-status-disturb
Skype -- fixed using skype-status-disturb-notification
Skype -- fixed using skype-status-invisible
Skype -- fixed using skype-status-invisible-notification
Skype -- fixed using skype-status-offline
Skype -- fixed using skype-status-offline-notification

Done , Thank you for using the Hardcode-Tray fixer!

```

**Comment by bil-elmoussaoui** [comment]
Can you try to restart your machine? btw, you can just run `hardcode-tray` instead of `sudo -E hardcode-tray`

**Comment by Winterwolf** [comment]
Same output and skype icon is still green.

**Comment by wa4557** [comment]
Are you using the new `skypeforlinux` client?

**Comment by Winterwolf** [comment]
No

**Comment by Winterwolf** [comment]
![skype](https://cloud.githubusercontent.com/assets/405685/16895589/8cde8e80-4b84-11e6-89d8-9d90f372ac17.png)

**Comment by wa4557** [comment]
@bil-elmoussaoui Maybe the same problem as with teamviewer?

**Comment by Winterwolf** [comment]
I don't know. I'm not using teamviewer.

**Comment by bil-elmoussaoui** [comment]
@wa4557 TeamViewer uses sni-qt:32 version too?

**Comment by wa4557** [comment]
Yeah

**Comment by bil-elmoussaoui** [comment]
@cybre Can you please take a look if the 32bits patched version is outdated? Thanks! :+1:

**Comment by wa4557** [comment]
Cannot confirm that. For me skype works (teamviewer doesn't). @Winterwolf Can you post the output of 
`ls /tmp/sni-qt_skype_13278-aGlMoJ/icons/hicolor/24x24/apps`?

**Comment by Winterwolf** [comment]
@wa4557 there is no such file or directory

**Comment by wa4557** [comment]
With running skype? Something similar in `\tmp` (like `\tmp\sni-qt_skype_*`)?

**Comment by Winterwolf** [comment]
`/tmp/sni-qt_skype_20454-AacStX/icons/hicolor/24x24/apps$ ls
skype_20454_0972e5fde53a4a87346ebb91c4c2b159.png  skype_20454_37e170fc54e7355d9d298917e74f9ea9.png  skype_20454_dad77418071bead905e2dbe605715dcd.png
skype_20454_2d1ee5482260fd9cd180b32787792683.png  skype_20454_6cbeda8e2c9f56d3ac75ccdf8d282a69.png  skype_20454_f2fc4a539a7b9553f5b35241d1154e84.png
`

**Comment by bil-elmoussaoui** [comment]
Can you share a screenshot of this folder too? Also check if you have any icons here `~/.local/share/sni-qt/icons/`

**Comment by cybre** [comment]
I no longer maintain the patched sni-qt, you are free to fork it and publish it in your own PPA.

**Comment by bil-elmoussaoui** [comment]
@cybre thanks for the answer!
@wa4557 @Winterwolf can you guys try to build the patched version from source code?

**Comment by Winterwolf** [comment]
I'm sorry, something strange happens with my system! At first I lost access rights ~/.local/share (they changes to root), then skype is crashes! Now I change rights to all files in my home directory and then restart PC. After this Skype icon is gray. Sorry guys and thank you very much!

**Comment by bil-elmoussaoui** [comment]
You're welcome! Don't hesitate to report any other issues in the futur :)
