### ISSUE TITLE
Caprine and Anatine support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#169]
More electron apps out there
Caprine is yet an other Facebook Messenger application built using Electron, the `app.asar` file is installed on `/usr/share/caprine/resources/`
The tray icons are 
![selection_002](https://cloud.githubusercontent.com/assets/7660997/16900973/8092f1da-4c2d-11e6-8085-1a82e5a137a2.png)
They're stored in `files/media/files/`
The icon names are : 
- `IconTray.png`
- `IconTray@2x.png`
- `IconTray@4x.png` 
- `IconTrayUnread.png`
- `IconTrayUnread@2x.png`
- `IconTrayUnread@4x.png`

I don't know how we should handle this case? I thought of using the same icon for all the sizes. But what if the user switch from a normal screen to a 4K one? or a FHD one?

Anatine is a Twitter Client, built using Electron too. The application does not have a `app.asar` file. The content of it is extracted into `/usr/share/anatine/resources/app`
The tray icons are in `media` folder (`/usr/share/anatine/resources/app/media`
![selection_003](https://cloud.githubusercontent.com/assets/7660997/16900999/48ff73e6-4c2e-11e6-919f-5ede53b5352c.png)

The icon names are: 
- `IconTray.png`
- `IconTray@2x.png`
- `IconTrayUnread.png`
- `IconTrayUnread@2x.png`

Again this is the same case as Caprine, how we should handle hidpi cases? how we can implement something like this ?

@wa4557 What do you think about this?

**Comment by wa4557** [comment]
why not double th sizes if the filename contains @2x?

**Comment by bil-elmoussaoui** [comment]
I will see what can i do :) shouldn't be that hard to implement!

**Comment by bil-elmoussaoui** [comment]
@wa4557 Fixed the issue! Everything is working perfectly right now:)
