### ISSUE TITLE
Show a progressbar

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#170]

**Comment by leoheck** [comment]
Very simple one... 

```python
#!/usr/bin/python

import sys
import time

def progress(count, total, status=''):
    bar_len = 60
    filled_len = int(round(bar_len * count / float(total)))

    percents = round(100.0 * count / float(total), 1)
    bar = '=' * filled_len + '-' * (bar_len - filled_len)

    sys.stdout.write('[%s] %s%s ...%s\r' % (bar, percents, '%', status))
    sys.stdout.flush()


def do_something():
    time.sleep(0.8)

trayname = [ "Whatsapp", "Hangouts", "Teamviwer", "Dropbox", "Electron" ]

TOTAL_ITENS=len(trayname)

print "My progress bar..."

for i in range(0, TOTAL_ITENS):
        progress(i, TOTAL_ITENS, status=" Fixing " + trayname[i%TOTAL_ITENS] + "    ")
        do_something()
```

**Comment by bil-elmoussaoui** [comment]
@leoheck If you want you can open a PR to fix this ;) i'm very busy those days to work on Hardcode-Tray..

**Comment by bil-elmoussaoui** [comment]
@leoheck Fixed, i used a part of your code, but modified somethings, i tottaly forgot to mention that on the commit history! i will do add a comment about that soon!

**Comment by leoheck** [comment]
@bil-elmoussaoui, you don't have to do that. I was only trying to help you to fix your issue. :)

**Comment by bil-elmoussaoui** [comment]
The issue wasn't really how to show a progress bar :P but i had to refactor the code in order to get the number of icons that are going to be fixed so i can get the total number of that ! that's why it took some time ! thanks anyway :+1:

**Comment by leoheck** [comment]
Sure @bil-elmoussaoui, that was what I was trying to say :) 
I am not very good in English.
