### ISSUE TITLE
Fixing failed for electron icons

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#171]
```
fixing failed with error:
	Traceback (most recent call last):
	  File "/home/andreas/Diverses/Hardcode-Tray/database/scripts/electron", line 56, in <module>
	    fileinfo = getFromDict(files, keys)
	  File "/home/andreas/Diverses/Hardcode-Tray/database/scripts/electron", line 14, in getFromDict
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	  File "/home/andreas/Diverses/Hardcode-Tray/database/scripts/electron", line 14, in <lambda>
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	KeyError: 'tray-skypeTemplate@2x.png'
```
this happened when trying to fix skypeforlinux

**Comment by bil-elmoussaoui** [comment]
Maybe the keys changed on the latest version of skype? We need to check if d[k] exists first to avoid this error

**Comment by bil-elmoussaoui** [comment]
Can you try after removing the skypeTemplate icon line? I think this icon is no more needed

**Comment by wa4557** [comment]
All good after removing the line :)

**Comment by bil-elmoussaoui** [comment]
I guess we can remove the line. But it might be used for older versions of
skypeforlinux. Maybe adding a verification to check if the key exists
before? This way we keep supporting for old versions of electron
applications

Le 5 sept. 2016 13:15, "Andreas Angerer" <notifications@github.com> a
écrit :

**Comment by wa4557** [comment]
I can do that

**Comment by wa4557** [comment]
Fixd

**Comment by bil-elmoussaoui** [comment]
That would be great, i don't have my laptop anymore so i cant contribute to
any project at the moment :/

Le 5 sept. 2016 13:21, "Andreas Angerer" <notifications@github.com> a
écrit :
