### ISSUE TITLE
Changing parent directories owner

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#172]
Seems like the current version is changing the parent directories (/, /home) owner to the current user applying the fix. Check this out: https://asciinema.org/a/82689

EDIT: Ubuntu GNOME Xenial

**Comment by bil-elmoussaoui** [comment]
I will take a lot asap! Thanks for reporting the issue

**Comment by szekeres2016** [comment]
I had login issues on my ubuntu installation after using this (there were some permission issues I could not figure out how to fix), could this have been a reason? I did not made any attempt since I reinstalled with this just to be safe.

**Comment by bil-elmoussaoui** [comment]
@edgard I've added a ignore list to avoid that. The fix was pushed to master. You can't not upgrade to the latest version (4.0) as it's still on beta! Please clone the repo,  revert the permission issues caused by the script before, try again and report back if you have any issues!

**Comment by bil-elmoussaoui** [comment]
@szekeres2016 Your issue has nothing to do with this as far as i can tell. The script only changes the permissions of /home in order to be able to create .sni-qt folder and change it permission to the current user applying the fix so the icons can be used by Qt apps...

**Comment by edgard** [comment]
Hey Bilal!

Just tried and it doesn't seem to work. There's also a small error on the script. Here's a test:
https://asciinema.org/a/19ftlqijauui811dowta5lwwb

Thanks a lot for the great work!

**Comment by szekeres2016** [comment]
Even after a reboot there seems to be no difference...

![tray](https://cloud.githubusercontent.com/assets/20751590/17818887/beaae96e-6645-11e6-92f1-865f63d8df04.png)

**Comment by bil-elmoussaoui** [comment]
@edgard I don't see any error message? i will push an other fix soon!
@szekeres2016 Which indicators does not work and should work or (marked as fixed when you use the script?). Have you installed the patched version of sni-qt?

**Comment by edgard** [comment]
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/script.py#L154

Should be "not in" instead of "is not in"? Here it's throwing an error.

**Comment by bil-elmoussaoui** [comment]
Indeed! Thanks, i don't have my laptop and just trying to fix those issues using github without even testing the code :P

**Comment by edgard** [comment]
Last fixes working like a charm, all good in the hood!

Thanks!

**Comment by bil-elmoussaoui** [comment]
Thanks for reporting! :+1: 
@szekeres2016 Please open a new issue if you have any unreleated issue!
