### ISSUE TITLE
KeePassX - Generic application icon instead of the tray icons

### ISSUE THREAD

**Issue by aviskase** [bil-elmoussaoui/Hardcode-Tray#173]
Hello! I found an issue #143 that should have fixed tray icons for KeePassX.
When I'm running `hardcode-tray` it seems to successfully fix them:

```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Numix-Circle
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

...
Keepassx -- fixed using keepassx-indicator
Keepassx -- fixed using keepassx-locked
```
But nothing happens: tray icon is still generic application icon, not the ones committed in the https://github.com/numixproject/numix-icon-theme/issues/1000
![0821_997](https://cloud.githubusercontent.com/assets/3819473/17833881/2aeba0b2-674c-11e6-97c0-e67abb5591b0.png)

**Comment by bil-elmoussaoui** [comment]
Can you take a screenshot of the content of /usr/share/keepassx/icons? Also which version of Keepassx/Numix circle are you using?

**Comment by aviskase** [comment]
Versions:

- keepassx: 2.0.2-1.02~eugenesan~wily1
- numix-icon-theme: 0.3+824~201608071940~ubuntu16.04.1
- numix-icon-theme-circle: 2.0.3+5~201608132046~ubuntu16.04.1

And a screenshot:
![0821_965](https://cloud.githubusercontent.com/assets/3819473/17837812/04a8ade4-67df-11e6-9969-e9f6a8ca8574.png)

**Comment by bil-elmoussaoui** [comment]
What happens if you change your theme from Numix-circle to Numix?

**Comment by wa4557** [comment]
Looks like the icon is taken from circle instead of base. Might be another case for moving them to `panel`

**Comment by aviskase** [comment]
> What happens if you change your theme from Numix-circle to Numix?

Now it's plane keepassx icon.
![0821_763](https://cloud.githubusercontent.com/assets/3819473/17838905/78413d50-67fa-11e6-9a66-f3a35ec20e4a.png)

I'm beginning to think that there is something wrong with keepassx itself. Because it was mentioned in the #143 that there is standard `keepassx-locked` icon for tray --- but it never shows up regardless of theme / applying-reverting with harcode-tray.

**Comment by wa4557** [comment]
Oh yeah, the poblem is that the app uses the same name for the app icon and for the icon in the tray. Thus the theme cannot provide both :( Nothing that can be done but changing this upstream I'm afraid

**Comment by aviskase** [comment]
Thanks! I used your explanation and reported an issue to keepassx bug tracker. For those, who might be interested, link is https://dev.keepassx.org/issues/527 
So this one could be closed.

**Comment by bil-elmoussaoui** [comment]
Thanks for reporting it upstream! We had the same issue with other application on Numix theme. Can you please keep us updated if there's any modification in the future? :)

**Comment by aviskase** [comment]
Yep, of course =)
