### ISSUE TITLE
Telegram icons getting corrupted GNOME 3.20

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#174]
Hey Bilal!

I'm getting some corruption on Telegram icons on Gnome 3.20. It's rather random when it happens so I wasn't really able to figure out a way to reproduce it. The only icon that this is happening is on Telegram (indicator icon).

![](http://oi64.tinypic.com/15mh3ro.jpg)

EDIT: icon was created with cairosvg, not inkscape.

**Comment by bil-elmoussaoui** [comment]
Can you paste a screenshot of  `~/.TelegramDesktop/tdata/ticons/`?

**Comment by edgard** [comment]
There you go!

![](http://oi65.tinypic.com/5m051z.jpg)

**Comment by bil-elmoussaoui** [comment]
Well i guess it has something to do with the topbar extension you're using..Do you still can reproduce this bug without it?
Anyway, the icons are replaced correctly. For me, it's either a gnome-shell bug or topbar extension one. Closing this, thanks for the report anyway!

**Comment by edgard** [comment]
Nice! I disabled the topbar extension to test, let's see how it goes.

Think it might be a GNOME issue, since on 3.16 had no problem with the same extension.

**Comment by bil-elmoussaoui** [comment]
I guess it's a gnome 3.20 extension issue see this issue for more info https://github.com/jonls/redshift/issues/330

**Comment by edgard** [comment]
I think I found the culprit. Seems like libappindicator-gtk3 is the problem. Removed it and installed libappindicator-gtk2 and so far so good. Will keep you posted.

**Comment by edgard** [comment]
Confirmed to be the case, if you have libappindicator-gtk3 installed Telegram is using it and it seems to be slightly broken. It's shifting the icon 1px to left and up, thats why it's getting corrupted at the bottom/right.
