### ISSUE TITLE
Telegram "attention" muted chat icons unchanged

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#175]
Hey Bilal!

Another bug on the Telegram icons, the muted chat icons when in "attention" status and with an active count of messages is showing the original icons. Same thing you do for regular chats should be done for muted ones.

```icomute_22_{1-100}.png, telegram-attention-panel```

**Comment by bil-elmoussaoui** [comment]
Do you have any information about the max number that you can have on the counter so i can update the normal notification icons too?

**Comment by edgard** [comment]
That would be 1000 (!!) according to [source](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L88).

**Comment by bil-elmoussaoui** [comment]
I will push a fix this evening!

**Comment by edgard** [comment]
Awesome!! Thanks a lot!

**Comment by bil-elmoussaoui** [comment]
Fixed upsteam,  will try to release 0.4 soon, otherwise you can always pull the latest code version or just update telegram database file
