### ISSUE TITLE
Applying sets owner/group of user home folder to "root"

### ISSUE THREAD

**Issue by Floofies** [bil-elmoussaoui/Hardcode-Tray#176]
On a fresh, but fully updated installation of Xubuntu 16.04 with Telegram installed, applying causes the following:
Here is my user folder **before** applying:
```
dani@Traxus-GD65:/home$ ls -l
total 4
drwxrwxr-x 30 dani dani 4096 Sep 21 20:26 dani
```

Here is the same folder right **after** applying:
```
dani@Traxus-GD65:/home$ ls -l
total 4
drwxrwxr-x 30 root root 4096 Sep 21 20:26 dani

```
In addition to this, the `.TelegramDesktop` and `.TelegramDesktop/tdata` folders receive the same treatment:
```
drwxrw-r-x 5 root root  4096 Sep 21 21:03 tdata
```
```
drwxrw-r-x  3 root root 4096 Sep 21 20:50 .TelegramDesktop
```
The owner + group are both being set to `root`. Any program that needs access to any of these folders will fail. (Since it is the user's home folder, this breaks lots of critical system components and application socket functionality) I do not have any non-default users or accounts set up. I suspect the issue lies in one of the calls to `chown`. 

Inserting `print("path: " + dir_path + ", UID: " + str(getenv("SUDO_UID")) + ", GID: " + str(getenv("SUDO_GID")))` above the `chown` call located on line 153 yields these results:
```
Applying now..

Google Chrome -- fixed using google-chrome-tray
Nylas N1 -- fixed using nylas-tray-full-newitems
Nylas N1 -- fixed using nylas-tray-full
Nylas N1 -- fixed using nylas-tray-empty
path: //, UID: 0, GID: 0
path: //home/, UID: 0, GID: 0
path: //home/dani/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/ticons/, UID: 0, GID: 0
Telegram -- fixed using telegram-panel
path: //, UID: 0, GID: 0
path: //home/, UID: 0, GID: 0
path: //home/dani/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/ticons/, UID: 0, GID: 0
Telegram -- fixed using telegram-attention-panel
```
Followed by this is well over 50 identical blocks:
```
path: //, UID: 0, GID: 0
path: //home/, UID: 0, GID: 0
path: //home/dani/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/, UID: 0, GID: 0
path: //home/dani/.TelegramDesktop/tdata/ticons/, UID: 0, GID: 0
```
As you can see, the GID, and UID are 0, causing the script to set the owner to root.
Because I am only seeing `chown` being executed on Telegram-related directories, this indicates to me it could be a unique issue related to Telegram.

Executing the `os.getenv()` calls right in the terminal yields the correct UID and GID:
```
dani@Traxus-GD65:~$ sudo python3 -c "import os; print(os.getenv('SUDO_UID'))"
1000
dani@Traxus-GD65:~$ sudo python3 -c "import os; print(os.getenv('SUDO_GID'))"
1000
```

**While I have not yet found the source of the bug, I have found a workaround for the user.**
Running `sudo -E -H hardcode-tray` (that's with the `-H` flag) prevents the problem from occurring.

**Comment by Floofies** [comment]
While I have not found the bug yet, I have found a solution. Running `sudo -E -H hardcode-tray` (that's with the `-H` flag) prevents the problem from occurring.

**Comment by Floofies** [comment]
Inserting `print(dir_path + str(getenv("SUDO_UID")) + str(getenv("SUDO_GID")))` above the `chown` call located on line 153 yields these results:
```
Applying now..

Google Chrome -- fixed using google-chrome-tray
Nylas N1 -- fixed using nylas-tray-full-newitems
Nylas N1 -- fixed using nylas-tray-full
Nylas N1 -- fixed using nylas-tray-empty
//00
//home/00
//home/dani/00
//home/dani/.TelegramDesktop/00
//home/dani/.TelegramDesktop/tdata/00
//home/dani/.TelegramDesktop/tdata/ticons/00
Telegram -- fixed using telegram-panel
//00
//home/00
//home/dani/00
//home/dani/.TelegramDesktop/00
//home/dani/.TelegramDesktop/tdata/00
//home/dani/.TelegramDesktop/tdata/ticons/00
Telegram -- fixed using telegram-attention-panel
```
Followed by this is well over 50 identical blocks:
```
//00
//home/00
//home/dani/00
//home/dani/.TelegramDesktop/00
//home/dani/.TelegramDesktop/tdata/00
//home/dani/.TelegramDesktop/tdata/ticons/00
```
This indicates to me it could be a unique issue related to Telegram.

**Comment by bil-elmoussaoui** [comment]
Hey! Thanks for the report 
Are you using the latest stable version or the git one? I will investigate this and push a fix by the evening

**Comment by Floofies** [comment]
Running `hardcode-tray --version` reveals I am using the latest stable version, **3.1**

**Comment by bil-elmoussaoui** [comment]
The home directory issue was fixed on git version that will be released soon (i hope!) check this issue for more information #172 
Can you try the latest git version ? just clone the repo/download the zip file and run `sudo -E python3 script.py --apply --only telegram` and see if you still have this issue with Telegram

**Comment by Floofies** [comment]
I tested the latest git version and did not see the problem occur. Sorry, I did not know this had been fixed and probably should have searched the issues better!

**Comment by bil-elmoussaoui** [comment]
Not a problem :) i will push a new release soon!

**Comment by leoheck** [comment]
@bil-elmoussaoui, this is a bug, should be updated right now, not only for version 4.0. This makes the login break.

**Comment by bil-elmoussaoui** [comment]
I will do by this evening! i will just add few fixes and push a new update! :+1:
