### ISSUE TITLE
Spotify indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#18]
For the spotify indicator icon and others i suppose that i will add a new row in the db file; the row will have the script link in the scripts folder (that i will add) 
and this python script will call the bash script to fix the icon issue; 

for spotify the icons are in 
```
/opt/spotify/spotify-client/Data/locales/resources.zip/_linux/
 ``` 

- [x] Spotify bash script that will receive an argument with the icons that exists in the current theme.
- [x] a way to convert the ```svg``` icons to ```ico```? yeah spotify uses this.. :/ 
- [x]  a new function in ```script.py``` to handle script files

**Comment by wa4557** [comment]
If you want I can do this. I already finished my finals :)

**Comment by bil-elmoussaoui** [comment]
I will be very thankful

**Comment by bil-elmoussaoui** [comment]
I did tried the script today and i've some questions :P 
the first the icon is token from scalable folder in Numix as the icon name for spotify is the same used for indicator :/ is it possible to force not using scalable icons? 
```
spotify -- fixed using /usr/share/icons/Numix-Circle/scalable/apps/spotify-client.svg
```
Also, the icon has not been changed in my case at all ,when i open the ```recources.zip``` file the last modified time is still the same even after using the script

**Comment by bil-elmoussaoui** [comment]
For the second question, changing this 
```
subprocess.Popen([script_name, filename], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
to this 
```
subprocess.call([script_name, filename], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
fixes the issue

**Comment by bil-elmoussaoui** [comment]
I found out that you've to change the 512 icon too :s so i updated the spotify.txt for that, as i'm not that good in bash, can you check if the icon extension is png then convert it to png instead of ico? and also as the filename is used as a parameter in the script file 
```
if [[ $1 == *.svg ]]; then
    inkscape $1 --export-png=resources_old/_linux/spotify_icon.ico
fi
    convert $1 --background none resources_old/_linux/spotify_icon.ico
```
if you can use the filename +extension instead of spotify_icon.ico this will solve the issue (i hope)

**Comment by wa4557** [comment]
Sure. Will do this evening

**Comment by bil-elmoussaoui** [comment]
this is fixed :D
