### ISSUE TITLE
Icon request - No Machine

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#181]
Hi, it is possible to add support to no-machine?
https://www.nomachine.com/

It its the red icon here:
![tray-icons](https://cloud.githubusercontent.com/assets/1277920/19628334/1d5da10a-993a-11e6-8cec-b678e4b9b4b8.png)

**Comment by leoheck** [comment]
F.lux (1), hangouts (2), TeamViewer (4), are default icons too. I think it is because the script breaks before it finishes.

**Comment by bil-elmoussaoui** [comment]
Hangouts is not supported take a look at the documentation for more informations. For TeamViewer see this #163  . F.lux icon is not hardcoded so i can't do anything about it.. open an issue for that on Numix theme.

**Comment by bil-elmoussaoui** [comment]
I will open a new issue on Numix to request the icons

**Comment by KottV** [comment]
Anyone tested nomachine?
doesn't work for me (KDE 5.8.3)
and i've found lot of original themed tray icons in /usr/NX/share/images/

**Comment by bil-elmoussaoui** [comment]
Which theme are you using? I personally don't use No Machine, so i couldn't test it correctly. Which are the icons that are missing so i can see if i can fix them too.

**Comment by bil-elmoussaoui** [comment]
NoMachine have only one tray icon? the red one?

**Comment by varlesh** [comment]
@KottV Papirus have NoMachine icons
Numix not available:
https://github.com/numixproject/numix-icon-theme/issues/1158

**Comment by bil-elmoussaoui** [comment]
Fixed this issue, the icons should be replaced... There's only two tray icons 
![tray-archlinux](https://cloud.githubusercontent.com/assets/7660997/20322090/0cb4a7b8-ab78-11e6-9719-3ad7e8aa713d.png)
![tray-archlinux-faded](https://cloud.githubusercontent.com/assets/7660997/20322091/0cb5807a-ab78-11e6-8239-121a4424456d.png)
the second one is transparent by default (nothing shown) but you can use the same indicator with a different transperency..

**Comment by varlesh** [comment]
good solution :+1:  Because i'm don't want draw 28 icons

**Comment by varlesh** [comment]
@bil-elmoussaoui  This icons not used anymore?:

- nomachine-desktop
- nomachine-recording
- nomachine-service

**Comment by bil-elmoussaoui** [comment]
Yeah, but you can keep them just in case..

**Comment by varlesh** [comment]
ok

**Comment by KottV** [comment]
yep, now evrthng ok

**Comment by KottV** [comment]
I use papirus, it's just perfect.

**Comment by bil-elmoussaoui** [comment]
Happy to hear that !
