### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by iwex** [bil-elmoussaoui/Hardcode-Tray#182]
Hello! Can't guess why it's not working for me.. I have clean Ubuntu 16.04.
![screenshot from 2016-10-26 17-50-58](https://cloud.githubusercontent.com/assets/4510068/19731078/e5e758ac-9ba4-11e6-8306-9f378e361a37.png)
I've installed script, then python3-cairosvg sni-qt sni-qt:i386, launched hardcode-tray and Apply. But with no success

**Comment by bil-elmoussaoui** [comment]
Hardcode-Tray does not contain any icon on it. It only uses the icons provided by your current theme(the one you use). You can try Numix icon theme. Almost all icons are supported by Hardcode-tray are supported by Numix so it shouldn't be an issue. 
Btw, what's the application indicator on top left?

**Comment by iwex** [comment]
@bil-elmoussaoui hmm.. Okey, numix

![screenshot from 2016-10-26 18-07-34](https://cloud.githubusercontent.com/assets/4510068/19731734/18ea39e8-9ba7-11e6-932b-01c5dc6f820b.png)


It's https://github.com/Guake/guake

**Comment by bil-elmoussaoui** [comment]
You need to run the script again once you've choosen Numix

**Comment by iwex** [comment]
`iwex@iwex-pc:~$ hardcode-tray --apply
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Numix
Svg to png functions are : Enabled
Applications will be fixed : All
Applying now..

Google Chrome -- fixed using google-chrome-tray

Done , Thank you for using the Hardcode-Tray fixer!`

Nothing has changed.

**Comment by bil-elmoussaoui** [comment]
You need to force close Chrome before the icon changes. For Telegram the application is not detected. Can you tell me if this folder exists in your case `.TelegramDesktop/tdata/ticons/`? For Hangouts, it's sadly impossible to change the icons of Chrome extensions, take a look at Hardcode-Tray documentation to understand why. And Guake is not supported yet, i will take a look a bit later if it's possbile.

**Comment by iwex** [comment]
No, I don't have .TelegramDesktop folder

**Comment by bil-elmoussaoui** [comment]
Can you try to find out if you have any folder that we can use to check if telegram is installed on your system? and which version of telegram are you using? you might need to check if you have libappindicator installed on y our system too

**Comment by iwex** [comment]
I used zip archive from Telegram site https://desktop.telegram.org/ 0.10.19
I have libappindicator1 and libappindicator3-1

**Comment by iwex** [comment]
I've found icon in /tmp folder :)

**Comment by bil-elmoussaoui** [comment]
There's no .ticons folder in your system? You might find some Telegram icons on /tmp/ folder

**Comment by iwex** [comment]
/home/iwex/.local/share/TelegramDesktop/tdata/ticons and here

**Comment by varlesh** [comment]
Why use 2 icons only **telegram-panel** and **telegram-attention-panel**?
Script not apply icon **telegram-mute-panel** https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/182#issuecomment-256377642
Numix available icon  **telegram-mute-panel**:
https://raw.githubusercontent.com/numixproject/numix-icon-theme/432bcb1908be75727a2d6a4548dc742c6d57d8b8/Numix/22/status/telegram-mute-panel.svg

**Comment by bil-elmoussaoui** [comment]
Telegram-panel is the standard tray icon, and telegram-attention-panel is the notification icon. I will fix those issues this evening!

**Comment by bil-elmoussaoui** [comment]
@iwex The icons should be fixed in your case now

**Comment by bil-elmoussaoui** [comment]
Fixed !
