### ISSUE TITLE
Chrome/Chromium icon size

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#183]
Google Chrome not use 22px icon size on panel.
Chrome 54
OS: KDE Neon (Kubuntu 16.04)
DE: KDE Plasma 5.8.2
Icon theme: Papirus Arc Dark
Please compare.
Original icon 22px
![screenshot_20161026_212055](https://cloud.githubusercontent.com/assets/8083855/19739057/4100aa82-9bc2-11e6-8a7d-2ea9cb5860c0.png)
On tray (icon blurred):
![screenshot_20161026_212308](https://cloud.githubusercontent.com/assets/8083855/19739117/6cfba132-9bc2-11e6-9a2c-08c71939212f.png)

**Comment by varlesh** [comment]
It's Chrome/Chromium bug only, because another icons show fine. For example, telegram, megasync :
![image](https://cloud.githubusercontent.com/assets/8083855/19739267/fa384fbe-9bc2-11e6-95e2-7e9ceb0d2088.png)

**Comment by bil-elmoussaoui** [comment]
Can you try something like this `hardcode-tray --apply --size 24 --only chrome` ?

**Comment by varlesh** [comment]
run:
`hardcode-tray --apply --size 24 --only google-chrome`
Icon not changed

**Comment by bil-elmoussaoui** [comment]
You need to force close chrome first, the icon won't change automatically

**Comment by varlesh** [comment]
yes, i doing this - Icon not changed

**Comment by bil-elmoussaoui** [comment]
Do you have 24px icons on your theme? it seems to be an icon size problem. I have never used KDE but they use 22px icons for tray/indicator icons (correct me if i'm wrong)! if you can share the chrome tray icons you're using so i can check if it's the correct size :)

**Comment by varlesh** [comment]
Yes on Theme available only 22px icon, but script this icon crop to other size (i don't know this size, because icon packed).
Original icon:
https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/master/papirus-dark/22x22/status/google-chrome-no-notification.svg

**Comment by varlesh** [comment]
google-chrome-tray.svg it's symlink to google-chrome-no-notification.svg

**Comment by bil-elmoussaoui** [comment]
Can you try adding a 24px icons before trying the commad i proposed before? The script does not crop any size of the icon, it's only uses gtk framework to look for the icon with the correct size. Which gtk version is installed on your kde system?

**Comment by varlesh** [comment]
On Plasa use 22px for tra only/ And my theme available only 22px for tray

**Comment by varlesh** [comment]
24px not available on icon theme. I try --size 24 and --size 22 -  this not change icon (icon blurred)

**Comment by varlesh** [comment]
gtk 3.18.9

**Comment by varlesh** [comment]
Appositely Unity use too 22px on panel. Maybe anybody test on Unity

**Comment by varlesh** [comment]
LOG:
`alex@dell:~$ hardcode-tray --apply --size 22 --only google-chrome
[sudo] пароль для alex: 
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Adwaita
Svg to png functions are : Enabled
Applications will be fixed : google-chrome
Applying now..

Google Chrome -- fixed using google-chrome-tray

Done , Thank you for using the Hardcode-Tray fixer!
alex@dell:~$ 
`

**Comment by bil-elmoussaoui** [comment]
The icon must be scaled by gtk from 22px to 24px which Will make the icons look blurry. Sadly i çan do anything about it! Can you try with Numix theme and see if the icon will look nicer ?

**Comment by varlesh** [comment]
Hm it's interested.... because on Plasma 5 used only 22px tray icons.
You can compare with Numix
![image](https://cloud.githubusercontent.com/assets/8083855/19828990/7f80ad16-9dde-11e6-9c24-baad85d9e83e.png)

**Comment by bil-elmoussaoui** [comment]
The icons looks the same.. Try with Numix by forcing the size to 24px (Numix have 24px icons too!)

**Comment by varlesh** [comment]
Numix 22px
`hardcode-tray --apply --size 22 --only google-chrome`
restart chrome
![image](https://cloud.githubusercontent.com/assets/8083855/19829041/7e31a1da-9ddf-11e6-91a1-8739d1fb12e4.png)
Numix 24px
`hardcode-tray --apply --size 24 --only google-chrome`
restart chrome
![image](https://cloud.githubusercontent.com/assets/8083855/19829053/a5fba274-9ddf-11e6-9cfc-75d77d7c5e17.png)
Original icon:
![image](https://cloud.githubusercontent.com/assets/8083855/19829057/cb6bd9de-9ddf-11e6-8aa5-a0d4e6b7decb.png)

**Comment by varlesh** [comment]
You see - icon blurred with Numix too!

**Comment by varlesh** [comment]
It's possible unpack chrome resource pack and check really size?

**Comment by varlesh** [comment]
Plasma not change icon size, because now used only 22px for  tray icons.
![image](https://cloud.githubusercontent.com/assets/8083855/19829090/c3dc0a80-9de0-11e6-891b-c42c73eeb085.png)

**Comment by bil-elmoussaoui** [comment]
Yes it's not that complicated ! Take a look at the documentation here on GitHub. If you couldn't do so, I will provide a script for you this evening

**Comment by bil-elmoussaoui** [comment]
I didn't say that Plasma change the icons. Never used it before... But it has nothing to do with Hardcode-Tray.. It's either a bug with Gtk on plasma or with the tray indicator on Plasma.. But what I don't understand is that the icon look nice for telegram and megasync! Maybe you can try an other theme and see if you get the same result?

**Comment by varlesh** [comment]
Numix original icon theme (chrome & megasync)
![image](https://cloud.githubusercontent.com/assets/8083855/19829135/e457dae0-9de1-11e6-9ea0-7cae9db937d7.png)
Papirus Arc Dark  (chrome & megasync)
![image](https://cloud.githubusercontent.com/assets/8083855/19829146/27e41864-9de2-11e6-816e-e9ac47b273a9.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh Can you try an other env like xfce or gnome and see if you will have the same issue as with plasma?

**Comment by wa4557** [comment]
I thought chrome/chromium removed the tray icon completely?

**Comment by bil-elmoussaoui** [comment]
They only removed the notifications tray, but chrome indicator is still being used on the latest version.

**Comment by varlesh** [comment]
it's Plasma bug only. On Unity icon looks good
![screenshot from 2016-10-31 11-06-04](https://cloud.githubusercontent.com/assets/8083855/19852296/8d0dc072-9f73-11e6-8528-c2b62c495a3b.png)

**Comment by bil-elmoussaoui** [comment]
I can't do anything about Plasma special bug :( you can try asking on some kde forums out there!

**Comment by varlesh** [comment]
Ok.

**Comment by wa4557** [comment]
@varlesh How does the original icon look like. Btw. Unpacking the `.pak` file and replacing the icon is exatly what we are doing (with the same size). This means that the original icon probably is also blurry...

**Comment by varlesh** [comment]
@wa4557 No, original icon not blurred. I'm author Papirus icon theme and draw this icon (and more others too). 
Original icon here:
https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk/master/Papirus-GTK/22x22/panel/google-chrome-no-notification.svg
https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk/master/Papirus-GTK/24x24/panel/google-chrome-no-notification.svg

**Comment by wa4557** [comment]
Hmm, this is strange. @bil-elmoussaoui Are we probably replacing a wrong size? Maybe chrome always(!) uses 24px icons?

**Comment by varlesh** [comment]
@wa4557 No, it's Plasma bug. Because Unity use 22px icons for panel too.

**Comment by bil-elmoussaoui** [comment]
@wa4557 Whatever the image sizes you replace with it should be shown correctly. As Chrome/Chromium does not handle the size of the tray icon but it's the libappindicator or something smillar in Plasma.

**Comment by varlesh** [comment]
@wa4557 You right! I found this icon:
/tmp/.com.google.Chrome.SVIQ1P/icons/hicolor/24x24/apps/chrome_app_indicator2_375b2c77f413e2c2dcb95a7b1196b20c.png
![image](https://cloud.githubusercontent.com/assets/8083855/19888860/68d74f0a-a042-11e6-928b-f525941db8cc.png)
![chrome_app_indicator2_375b2c77f413e2c2dcb95a7b1196b20c](https://cloud.githubusercontent.com/assets/8083855/19888892/996c0430-a042-11e6-9ed4-86164a40889b.png)

After runing script:
```
sudo -E python3 script.py -o google-chrome -s 22
```
Icon changed, BUT size 24px:
/tmp/.com.google.Chrome.bd099L/icons/hicolor/24x24/apps/chrome_app_indicator2_7cc1675d0780c4c41cc111531efd7b28.png
![image](https://cloud.githubusercontent.com/assets/8083855/19888947/0c35b97a-a043-11e6-9bd9-173e31d8fb2f.png)
![chrome_app_indicator2_7cc1675d0780c4c41cc111531efd7b28](https://cloud.githubusercontent.com/assets/8083855/19888961/1f681466-a043-11e6-9ad8-4d272567b819.png)

I don't know why use 24px anywhere. And on icon theme 24px status icons not available!!!
It's possible fix it?

**Comment by varlesh** [comment]
22px not created with script:
![image](https://cloud.githubusercontent.com/assets/8083855/19889048/d0cb6aaa-a043-11e6-9f20-e53fbe4816f5.png)
Also with Wire this bug reproduced too.

**Comment by bil-elmoussaoui** [comment]
For me this can't be fixed from our side. The folders are created by the API used by KDE to draw tray icons. This is why the icons are stored on `/tmp` (like Qt icons). And as i've never used KDE, i don't know if it's a missing package, or there's any way to patch the current library used to draw tray icons on KDE. If you have any solution for this later, feel free to add it to Wiki! Thanks
I might investigate later, i will have to install KDE...

**Comment by varlesh** [comment]
Ok, thx for info. I'm already reported bug on KDE:
https://bugs.kde.org/show_bug.cgi?id=366062
I hope this fixed on new KDE vesion...
