### ISSUE TITLE
@2x icons

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#184]
We should somehow implement, that if a icon name contains `@2x` it should be doubled in size (if it is a png at least). This should enable us to have HiDPi support

**Comment by bil-elmoussaoui** [comment]
This was already implemented in order to fix Caprine icons #169

**Comment by wa4557** [comment]
Ah I see, but this is not a good fix, isn't it?
 Instead of looking for a 22px icon and double it in size, the script is now looking for a 44px sized icon which arguably  does not exist. The theme_lookup funtion should still looking for a 22px icon, and after converting it to png (no further action needed for svg icons) it should double its size

**Comment by bil-elmoussaoui** [comment]
Ah i didn't think of that! Do you have any idea how to double an svg icon on size? I thnik we can only use Inksape for an easy solution..

**Comment by wa4557** [comment]
How did you do it for numix-core? There I guess you have to do multiple sizes, right?

**Comment by bil-elmoussaoui** [comment]
Ah completly forgot that i have already did that :P I will implement the same code here :+1:

**Comment by wa4557** [comment]
We have to think about how to handle all the script (electron) things though, where there are also potentially @2x icons.

**Comment by bil-elmoussaoui** [comment]
I will save the icons on /tmp folder and i can give the icon path to electron script which only have to handle the case where the icon is a path, what do you think?

**Comment by wa4557** [comment]
Hmm, I really like the current situation where everthing is written into ram instead of saving it to hard disc. We can keep the binary blob of the png in working memory, just like we do right now for electron scripts...

**Comment by wa4557** [comment]
```
png_io = BytesIO()
        img.write_to_png(png_io)
        with open(outfile, 'wb') as fout:
            fout.write(png_io.getvalue())
        svg.close()
        png_io.close()
        img.finish()
```

png_io should be the correct icon right? No need to write a temporary icon anywhere imo

**Comment by bil-elmoussaoui** [comment]
Ah yeah! i will implement it that way :+1:

**Comment by wa4557** [comment]
maybe we can rewrite the `svgtopng` script to accept a size argument?

**Comment by bil-elmoussaoui** [comment]
Yeah :) it's the easiest solution we can implement !

**Comment by wa4557** [comment]
Top :+1:

**Comment by bil-elmoussaoui** [comment]
Done! Will push the new code in few minutes 
![capture du 2016-11-02 16-55-25](https://cloud.githubusercontent.com/assets/7660997/19936264/374387f2-a11d-11e6-8823-52ebaf50b11c.png)
![icontrayunread](https://cloud.githubusercontent.com/assets/7660997/19936271/40840530-a11d-11e6-9ce2-ab1388cb2397.png)
![icontrayunread 2x](https://cloud.githubusercontent.com/assets/7660997/19936272/40852802-a11d-11e6-97c8-7539d56c5763.png)
![icontrayunread 4x](https://cloud.githubusercontent.com/assets/7660997/19936273/408a6344-a11d-11e6-94e1-d6f64484aa78.png)
The quality is quite nice :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed upstream
