### ISSUE TITLE
Discord/Discord Canary

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#186]
Electron app https://discordapp.com 
Officialy Linux will be available soon:
https://discordapp.com/apps
On AUR
https://aur.archlinux.org/packages/discord-canary
DEB-package:
https://discordapp.com/api/download/canary?platform=linux
APP.ASAR (rename **zip** to **asar**):
[app.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/564076/app.zip)

**Comment by bil-elmoussaoui** [comment]
The app.asar file is stored on `/opt/discord-canary/resources/`?

**Comment by varlesh** [comment]
No, here:
/usr/share/discord-canary/resources/app.asar

**Comment by bil-elmoussaoui** [comment]
The icons are 
- `discord-tray`
- `discord-tray-notification`

**Comment by varlesh** [comment]
ok, thx

**Comment by abouvier** [comment]
@bil-elmoussaoui On Arch the path is indeed `/opt/discord-canary/resources/app.asar`, so it doesn't works at the moment.

**Comment by bil-elmoussaoui** [comment]
@abouvier I've added the new path, try `hardcode-tray --update-git` and run the script again. Should work fine now
