### ISSUE TITLE
Guake icon

### ISSUE THREAD

**Issue by iwex** [bil-elmoussaoui/Hardcode-Tray#187]
Hello! Could you please add guake support? https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk/issues/111

**Comment by bil-elmoussaoui** [comment]
I will see what can i do about this ;)

**Comment by bil-elmoussaoui** [comment]
Fixed! Please clone the git version and run `sudo -E ./python3 script.py --only guake`

**Comment by varlesh** [comment]
@bil-elmoussaoui maybe better create script **install-git.sh** and **uninstall-git.sh**? It's will be comfortable for more users...

**Comment by iwex** [comment]
@bil-elmoussaoui Also, please add `/usr/local/share/pixmaps/guake`. Thank you :)

**Comment by varlesh** [comment]
@iwex No ;) it's script for only tray

**Comment by varlesh** [comment]
@iwex https://github.com/Foggalong/hardcode-fixer

**Comment by varlesh** [comment]
It's not needed. On desktop file use icon name **guake**:
```
[Desktop Entry]
Encoding=UTF-8
Name=Guake Terminal
Name[fr]=Guake Terminal
Name[pl]=Terminal Guake
Name[pt]=Guake Terminal
Name[pt_BR]=Guake Terminal
Comment=Use the command line in a Quake-like terminal
Comment[fr]=Utilisez la ligne de commande comme dans un terminal quake
Comment[pl]=Wiersz poleceń w terminalu w stylu gry Quake
Comment[pt]=Utilizar a linha de comando em um terminal estilo Quake
Comment[pt_BR]=Utilizar a linha de comando em um terminal estilo Quake
TryExec=guake
Exec=guake
Icon=guake
Type=Application
Categories=GNOME;GTK;System;Utility;TerminalEmulator;
StartupNotify=true
X-Desktop-File-Install-Version=0.22
```
https://github.com/Guake/guake/blob/master/data/guake.desktop.in

**Comment by bil-elmoussaoui** [comment]
@varlesh I'm planning to improve the install script to make it possible to update the script to the latest git version. But i need to fix the rest of the issues first. For now, i've added few lines to Wiki to explain how to use Git version 
https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/FAQ#how-to-use-git-version

**Comment by iwex** [comment]
@varlesh, yes, but I have Guake icons only in `/usr/local/share/pixmaps/guake`

**Comment by varlesh** [comment]
@bil-elmoussaoui Ok, fine!

**Comment by varlesh** [comment]
@iwex show input:
`cat /usr/share/applications/guake.desktop`

**Comment by iwex** [comment]
@varlesh 
`cat /usr/share/applications/guake.desktop`:
```
cat: /usr/share/applications/guake.desktop: No such file or directory
```

`cat /usr/local/share/applications/guake.desktop`:
```
[Desktop Entry]
Encoding=UTF-8
Name=Guake Terminal
Name[fr]=Guake Terminal
Name[pl]=Terminal Guake
Name[pt]=Guake Terminal
Name[pt_BR]=Guake Terminal
Comment=Use the command line in a Quake-like terminal
Comment[fr]=Utilisez la ligne de commande comme dans un terminal quake
Comment[pl]=Wiersz poleceń w terminalu w stylu gry Quake
Comment[pt]=Utilizar a linha de comando em um terminal estilo Quake
Comment[pt_BR]=Utilizar a linha de comando em um terminal estilo Quake
TryExec=guake
Exec=guake
Icon=guake
Type=Application
Categories=GNOME;GTK;System;Utility;TerminalEmulator;
StartupNotify=true
X-Desktop-File-Install-Version=0.22
```

**Comment by varlesh** [comment]
@iwex Icon=guake

**Comment by iwex** [comment]
@varlesh aaaand?

**Comment by varlesh** [comment]
icon use from icon theme

**Comment by iwex** [comment]
@varlesh but we are talking about tray-icon, not desktop

**Comment by varlesh** [comment]
tray icon name **guake-tray**
