### ISSUE TITLE
sni-qt-eplus not available anymore on arch, readme update

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#189]
Hey!

Just a small update, the package sni-qt-eplus is not available on arch anymore, only the bzr version 'sni-qt-eplus-bzr'. On your readme you're refering to it so people might get confused.

Also, on unrelated note, I'm maintaining the AUR package called 'hardcode-tray-fixer-git' to make it easier to install. :)

**Comment by bil-elmoussaoui** [comment]
Can you push an update with all the those informations? you can also mention how to install hardcode-tray-fixer-git from AUR if you want to :+1:

**Comment by varlesh** [comment]
Also need update README and add new depends - librsvg2-bin and etc

**Comment by edgard** [comment]
Sure thing, #194 

Haven't added anything about librsvg2-bin because I'm running Arch and this is not a dependency here, so I can't properly check.

**Comment by bil-elmoussaoui** [comment]
It should be a dependency on Arch too! I will take care of the rest :) thanks!

**Comment by edgard** [comment]
Oh I meant it was already installed because librsvg is a dependency of gtk2/3 on Arch.
