### ISSUE TITLE
Viber indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#19]
The viber indicator icons are in 

``` 
/opt/viber/icons
``` 
i don't know which one is used for the viber indicator. But this not working in ubuntu/unity/gnome-shell/pantheon desktop. Should we add this? or it's a won't fix!

if i add this, i will have to symlink ```viber.svg``` and not the others

**Comment by wa4557** [comment]
I suppose this is a wontfix. Tray indicator seems to work if you install the package viberwrapper-indicator
see:

http://www.webupd8.org/2014/11/viber-wrapper-indicator-hides-floating.html


but this icons are not hardcoded:

https://github.com/karas84/viberwrapper-indicator/tree/master/icons/ubuntu-mono-dark/apps

 Would you like to add those icons to your missing tray indicator list in Numix-base? I think I'm going to add those icons this evening

**Comment by bil-elmoussaoui** [comment]
Yeah i did reported this to the dev of viber-wrapper! i will do that right now 
i will add viber-wrapper link in the readme then ;)
