### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#191]
fixing failed with error:
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 56
	    print 'xxx'
	              ^
	SyntaxError: Missing parentheses in call to 'print'
	

Done , Thank you for using the Hardcode-Tray fixer!

**Comment by bil-elmoussaoui** [comment]
This line does not even exists in the script :P https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/scripts/electron

**Comment by leoheck** [comment]
Sorry I think this problem was caused by me. I installed again but the script was not override.

**Comment by leoheck** [comment]
Wow, you are fast! :)
Actually, the problem is this. 

```
Whatsie -- fixed using whatsie-tray-attention
fixing failed with error:
	Traceback (most recent call last):
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 57, in <module>
	    fileinfo = getFromDict(files, keys)
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 14, in getFromDict
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 14, in <lambda>
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	KeyError: 'tray-skypeTemplate@2x.png'
Done , Thank you for using the Hardcode-Tray fixer!
```

**Comment by leoheck** [comment]
I am trying to reinstall to see why facebook icon has a bad resolution.
![screenshot from 2016-11-04 13-09-40](https://cloud.githubusercontent.com/assets/1277920/20010632/ffc0237a-a28f-11e6-9d4e-729470b305c0.png)

**Comment by bil-elmoussaoui** [comment]
Fixed !

**Comment by bil-elmoussaoui** [comment]
Btw, which version of Facebook are you using?

**Comment by leoheck** [comment]
messenger 2.0.1-beta

**Comment by bil-elmoussaoui** [comment]
Can you please try again ? the icon shown in your screenshot does not seem to be from Numix theme..

**Comment by leoheck** [comment]
This line (mine is 57) isn't working with electra:

 ```python
fileinfo = getFromDict(files, keys)
```

**Comment by leoheck** [comment]
I am trying. Do I need reboot or restart something?

**Comment by bil-elmoussaoui** [comment]
I fixed the issue on git, please update !

**Comment by bil-elmoussaoui** [comment]
You need to close the application and restart it again

**Comment by leoheck** [comment]
Hmm, t was fixed now?
Oh, ok. I will do that.

**Comment by leoheck** [comment]
The icon is still bad.

**Comment by bil-elmoussaoui** [comment]
When you run the script what's the result you have?

**Comment by leoheck** [comment]
Now it is ok (I forgot to restart afert install the git version). I am dumb today, sorry to bother you @bil-elmoussaoui

**Comment by leoheck** [comment]
Suggestion: Add a -d flag in install script to install git version =)

**Comment by bil-elmoussaoui** [comment]
There's already a flag for installing from git version :p Not a problem :) happy to hear that everything works nice for you!
