### ISSUE TITLE
Wrong convert INKSCAPE-SVG to PNG

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#193]
It's very strange. I don't know it's bug inkscape or ...
Script convert icon with background, but background - it's not layer!
For example, **clementine-panel** from Papirus Arc Dark (for KDE).

On left original icon - on right converted with script.
![image](https://cloud.githubusercontent.com/assets/8083855/20010814/971d4192-a2ba-11e6-84f7-e17f5ebcffe9.png)
Converted icon have background **#f7f7f7** but really background from source transparent! 
Script convert **pagecolor** to **layer**. But why?!
source:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/blob/master/papirus-arc-dark/22x22/status/clementine-panel.svg
```
 id="namedview88"
     inkscape:object-nodes="true"
     inkscape:object-paths="true"
     objecttolerance="10"
     pagecolor="#f7f7f7"
     inkscape:pageopacity="1"
     inkscape:pageshadow="2"
     showborder="true"
     showgrid="false"
     showguides="true"
```
i know, **pagecolor** option not available on **PLAIN-SVG**... but maybe available method for fixing **INKSCAPE-SVG**?

**Comment by varlesh** [comment]
I'm delete icon cache, update script from git and run twice. Bug reproduced with INKSCAPE-SVG icons...
I know need save icons as PLAIN-SVG, but i must remake all tray icons - it's very long work and have more icons... because Developers like hardcoded :(

**Comment by bil-elmoussaoui** [comment]
Tried with Numix theme, and the issue is only reproducible with your theme :(

**Comment by wa4557** [comment]
@varlesh You could try some svg-cleaning scripts (https://github.com/RazrFalcon/svgcleaner) that removes all of the unneeded parameters

**Comment by varlesh** [comment]
@wa4557 I previously used this util and after some SVG's will bee broken. For example, cleaning icon not change color anymore.

**Comment by varlesh** [comment]
Maybe it's possible add option for ignore pagecolor?

**Comment by bil-elmoussaoui** [comment]
If you can figure out how to do that with Inkscape command line, i would be more than happy to implement that :+1:

**Comment by varlesh** [comment]
it's **pagecolor**. I confirm this.
Icon saved as PLAIN-SVG and converted with script:
![image](https://cloud.githubusercontent.com/assets/8083855/20012679/4212c99a-a2c1-11e6-9a2a-a2dc58fb2a64.png)

**Comment by varlesh** [comment]
@bil-elmoussaoui 
**-l, --export-plain-svg=FILENAME**
> Export document(s) to plain SVG format, without sodipodi: or inkscape: namespaces and without RDF metadata.

https://inkscape.org/en/doc/inkscape-man.html#options

**Comment by bil-elmoussaoui** [comment]
Well in that case just run a bash script that will export all your svg icons as plain ones? I can provide one if you want to :)

**Comment by varlesh** [comment]
But if another (future) icon theme have this INKSCAPE-SVG or NUMIX too?
Maybe better add this option on script? And i'm will be happy ... and others too!!!

**Comment by varlesh** [comment]
Yes, convert time will. But all icon theme will be converted right.

**Comment by bil-elmoussaoui** [comment]
Well, Numix does not have this issue :) if any future icon theme has this issue i will link this issue with the script i'm going to provide. The reason why i'm not willing to implement this directly on Hardcode-Tray because we will have the same result if the user uses Cairosvg we will face the same issue again. So better fix it from the source! 
The script will walk in the directory you provide and fix all the icons in there, so it's up to you to decide which directory of your theme should be fixed :)

**Comment by varlesh** [comment]
I hate inkscape!!! :( Ok, i'm go clean SVG's...

**Comment by bil-elmoussaoui** [comment]
I do hate it too! Good luck with that :+1:

**Comment by varlesh** [comment]
Thx :)
