### ISSUE TITLE
Use json instead of csv

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#197]
As discussed here #196 
I think it's time to move to a more readable database by us and a way to make adding new icons more easier. 
I started moving some database files in the json branch, if you have some free time a help will be much appreciated. Once all the files are using the new format, i will modify the script to read the json files instead of the csv files. Shouldn't be hard, but i will try to make all the stuff use the json file and we won't have to treat each application differently on the python script (reduce the number of the scripts).

CC: @wa4557

**Comment by bil-elmoussaoui** [comment]
Quick update : finished converting all csv files to json, was the hardest task till now :p i will have to check every file if the json syntax is correct. once everything is okay, i will update the script which shouldn't be complicated

**Comment by wa4557** [comment]
Great, I might have some freetime this weekend, if there's still something left to do then :P

**Comment by bil-elmoussaoui** [comment]
I have some free time today, i will see if i can fix everything and release a new version ! :P

**Comment by bil-elmoussaoui** [comment]
@wa4557 it's working pretty well now, i just need to modify the revert code. I've removed the google chrome notification center support as it's removed in the latest versions of chrome, and it was causing too many issues, and a lot of lines codes...People will just have to upgrade their browser ;) 
I couldn't manage to integrate the dropbox path into the json file, i modified the code a little bit to have fewer lines of code, it works well but it's not the best solution i guess. 
Will release a new version tomorrow if everything works fine. It would be really nice if you can try the json branch and report back

**Comment by wa4557** [comment]
Looking good to me. Wasn't able to find any breakage so far. Will have a look into the code a bit later...

**Comment by bil-elmoussaoui** [comment]
I will see how to fix the issue. We still need chrome script, as i've only removed the icons that were used by the notification center; But chrome still have a tray icon, the get_correct_chrome_icons were used by the notification center, also the chrome images we had in the database folder. I don't know how we can really fix the dropbox issue :( if you have any idea feel free to tell me about it :+1:

**Comment by bil-elmoussaoui** [comment]
Moved the dropbox code to a new script "dropbox", and added a new key to the json files, that have a script that will be executed on the application path.

**Comment by rpbaptist** [comment]
I was wondering where the CSV database file was. The documentation on how to contribute still refers to that, but this clears it up.

**Comment by bil-elmoussaoui** [comment]
@rpbaptist i need to modify the documentation as too many things changed since the latest version... but the new code is more easy to understand than before ;)
