### ISSUE TITLE
Dropbox icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#20]
Hello
I did push a new update for dropbox fixes
but there's still something to do: 
the dropbox folder name is something like this  ``` dropbox-lnx.x86_64-3.6.4```
so i did this in the ```db.csv``` file 
```
dropbox,{userhome}/.dropbox-dist/dropbox-lnx{*}/images/hicolor/16x16/status
```
so i have to remplace the ``` {*}``` with the dropbox folder that starts with ```dropbox-lnx``` :P 
and i don't have any idea how to do this 
Any ideas?

**Comment by wa4557** [comment]
In the script? Or in `db.csv`

**Comment by bil-elmoussaoui** [comment]
In the script

**Comment by wa4557** [comment]
Ah so it depends on the dropbox version and if one uses 32bit or 64 bit...

**Comment by bil-elmoussaoui** [comment]
Yeah i was thinking about getting the only folder that is in ```.dropbox-dist```

**Comment by wa4557** [comment]
Ah that's a hard one. Something with `os.walk('dropbox-lnx.')` should work but that needs some rewriting

**Comment by bil-elmoussaoui** [comment]
This will be fixed in the next commit

**Comment by bil-elmoussaoui** [comment]
@wa4557 can you check this please? :)
in the ```dropbox_folder``` fonction there's something that is not working 
the result of ```sub_dirs``` is ```None``` and i really don't have any idea
and the result of dirs is 
```
['/home/bilal/.dropbox-dist/', '/images/hicolor/16x16/status']
```

**Comment by wa4557** [comment]
Yeah you made a standard python error :) 
replace line 71&72 with

```
sub_dirs = os.listdir(""+dirs[0])
sub_dirs.sort()
```

sub_dirs.sort() has no return value, but it changes the list in place

**Comment by bil-elmoussaoui** [comment]
Ah yeah! i forgot about this ,thanks i will push an update

**Comment by bil-elmoussaoui** [comment]
I can close this now ;) Thank you very much @wa4557

**Comment by wa4557** [comment]
You missed a print(row[1])

**Comment by bil-elmoussaoui** [comment]
Done
