### ISSUE TITLE
Solaar support?

### ISSUE THREAD

**Issue by francoism90** [bil-elmoussaoui/Hardcode-Tray#200]
Is it possible? Battery icons of the current icon theme could be used.

Thanks. :)

**Comment by bil-elmoussaoui** [comment]
I will push a fix once i've done with moving from csv to json database, see #197

**Comment by bil-elmoussaoui** [comment]
As i don't have a Logitech pref, which icons are used from the ones you have in /usr/share/solaar?

**Comment by bil-elmoussaoui** [comment]
Fixed
