### ISSUE TITLE
Wrong path install on PKGBUILD

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#203]
@edgard 
PKGBUILD now have wrong path install:
```
_pkgbase=hardcode-tray-fixer
....
package() {
  install -Dm755 "$srcdir/hardcode-tray-fixer.sh" "$pkgdir/usr/bin/hardcode-tray"
  install -Dm755 "$srcdir/$pkgname/script.py" "$pkgdir/opt/$_pkgbase/script.py"
  install -d "$pkgdir/opt/$_pkgbase"
  cp -r "$srcdir/$pkgname/database" "$pkgdir/opt/$_pkgbase"
}
```
Right path install will be **/opt/Hardcode-Tray**:
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/hardcode-tray

**Comment by bil-elmoussaoui** [comment]
@edgard Can you also add me as a co-maintainer ? my username is `bil-elmoussaoui`. This way i can keep the AUR package updated if you're busy :+1:

**Comment by edgard** [comment]
sure thing! just did!

**Comment by bil-elmoussaoui** [comment]
I'm going to create a new aur repo, once i've done with that i will request a merge with your repo. As the name of the repo is not the name of the script... 
There's also few things to change.

**Comment by bil-elmoussaoui** [comment]
@varlesh I've added two new packages to AUR. `hardcode-tray` for the latest stable version and `hardcode-tray-git` for the latest development version on git.

**Comment by varlesh** [comment]
Fine, i'm already update PPA. 
We are the best! :laughing:

**Comment by edgard** [comment]
@bil-elmoussaoui I haven't seen anywhere how to delete the package, I suppose they will sent something to me to confirm, as soon as they do, I will confirm it.

**Comment by bil-elmoussaoui** [comment]
I have sent a request to remove the package. I will keep maintaining both, i can add you as co-maintainer in case I'm not available if you would like so :)

**Comment by edgard** [comment]
Sure, feel free to add me, I can definitely help if needed.

**Comment by bil-elmoussaoui** [comment]
Done! You can update the PKGBUILD and your contact information in case ;)
