### ISSUE TITLE
WMail

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#205]
Electron app:
https://github.com/Thomas101/wmail
Header.json (rename zip to json):
[header.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/587048/header.zip)
Binary archive:
https://github.com/Thomas101/wmail/releases/download/v2.0.0/WMail_2_0_0_linux_x86_64.tar.gz
app.asar very big (i can't attach here) and not extract, have error 'dist'

**Comment by varlesh** [comment]
Oops, not needed. Program have option for customize tray color:
![image](https://cloud.githubusercontent.com/assets/8083855/20235859/67d16548-a8b0-11e6-9ad2-04defc1b4f08.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh  You can change the icons or just background/border?

**Comment by varlesh** [comment]
Only colors changed.

**Comment by bil-elmoussaoui** [comment]
Well, i will add it to Hardcode-Tray then, as the icon will remain the same whatever the theme you're using. Which is the main reason of creating this script

**Comment by bil-elmoussaoui** [comment]
Hardcoded on the code source see https://github.com/Thomas101/wmail/blob/master/src/scenes/mailboxes/src/Components/TrayRenderer.js

**Comment by varlesh** [comment]
Program have color change - it's good.

**Comment by bil-elmoussaoui** [comment]
Yeah but drawing the icons is not the best solution, it can be fixed easily by using the icon from the theme instead of hardcoding things even more.

**Comment by varlesh** [comment]
It's better than nothing ))

**Comment by varlesh** [comment]
I found site with electron apps. OMG, it's crazy - very more apps use Electron.
http://electron.atom.io/apps/

**Comment by varlesh** [comment]
Oh, no... Please stop :)! I must will be draw new icons...

**Comment by bil-elmoussaoui** [comment]
Well, not all of them have tray icons :P
