### ISSUE TITLE
Wire not working

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#206]
New script again  not working with electron apps
Fresh git-version:
![image](https://cloud.githubusercontent.com/assets/8083855/20238500/27e4bc2a-a8fe-11e6-9f64-05d5bcbfc572.png)

Old version worked (https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/9aad49a67c004b314dbdb4cddbc512e8d552e6f7):
![image](https://cloud.githubusercontent.com/assets/8083855/20238517/81966a20-a8fe-11e6-8c03-7e95153a6e60.png)

**Comment by varlesh** [comment]
I don't know why it's happened. Qt-apps (for example) clementine and megasync working, chrome too.
Wire not. No errors.

**Comment by varlesh** [comment]
json-version bugged :(

**Comment by varlesh** [comment]
Also i' seen Hexchat on status progress, but hexchat not installed. Why script use this app?

**Comment by bil-elmoussaoui** [comment]
The Hexchat is a known bug after the latest upgrade to json structure, i'm working on it ;) I will check the electron apps right now!

**Comment by bil-elmoussaoui** [comment]
Can't confirm your issue! Have you received any Wire update recently ?

**Comment by varlesh** [comment]
wire-2.11.2670-amd64.deb

**Comment by varlesh** [comment]
> Can't confirm your issue! Have you received any Wire update recently ?

You revert icons before run script?

**Comment by bil-elmoussaoui** [comment]
Yeah, i reinstalled Whatsie and skypeforlinux and tried again, the icons work perfectly! It must be the new update of Wire, i will take a look

**Comment by varlesh** [comment]
It's strange, because old version (not JSON) working fine with wire

**Comment by varlesh** [comment]
Whatsie working, Wire not
![image](https://cloud.githubusercontent.com/assets/8083855/20238685/1f7413f2-a902-11e6-8e12-df8b9abe9192.png)

**Comment by bil-elmoussaoui** [comment]
Wire, change the installation location to `/usr/lib/wire/resources`. I added this path to the json file, clone and try again :)

**Comment by varlesh** [comment]
```
alex@dell:~$ hardcode-tray
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : papirus-arc-dark
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Traceback (most recent call last):
  File "script.py", line 512, in <module>
    install(fix_only, icon_path)
  File "script.py", line 402, in install
    apps = get_supported_apps(fix_only, custom_path)
  File "script.py", line 219, in get_supported_apps
    data = json.load(data_file)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 34 (char 101)
alex@dell:~$ 
```

**Comment by bil-elmoussaoui** [comment]
Fixed, it was a typo :p

**Comment by varlesh** [comment]
Icon not changed

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/20238755/664b00dc-a903-11e6-87f1-b84c3a4fb514.png)

**Comment by bil-elmoussaoui** [comment]
What if you try with `--only wire`? What's the result?

**Comment by varlesh** [comment]
```
alex@dell:~$ hardcode-tray -o wire
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : papirus-arc-dark
Svg to png functions are : Enabled
Applications will be fixed : wire
1 - Apply
2 - Revert
Please choose: 1
Applying now..


Done , Thank you for using the Hardcode-Tray fixer!
alex@dell:~$ 

```
But icon not changed!

**Comment by bil-elmoussaoui** [comment]
Well, copy the app.asar to your home directory and run 
`asar extract app.asar ./wire`
Move to `/wire/img` and see if the icon changed?

**Comment by varlesh** [comment]
Not JSON version worked! https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/9aad49a67c004b314dbdb4cddbc512e8d552e6f7

**Comment by varlesh** [comment]
it's problem with new json database only

**Comment by varlesh** [comment]
On PPA available old version https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/9aad49a67c004b314dbdb4cddbc512e8d552e6f7 and this version works with Wire.
New git-version with json-database not fix Wire

**Comment by bil-elmoussaoui** [comment]
Fixed! I modified the path of the icons on the new version, don't know or remember why :P

**Comment by varlesh** [comment]
Now worked :)

**Comment by bil-elmoussaoui** [comment]
Fixed the Hexchat issue on master!

**Comment by varlesh** [comment]
Fine, working!
