### ISSUE TITLE
cannot start hardcode-tray

### ISSUE THREAD

**Issue by lbngoc** [bil-elmoussaoui/Hardcode-Tray#207]
Hi,

I use Linux Mint 18 and install hardcode-tray from PPA, when I type this command "hardcode-tray" from Terminal, I face this error:
```
> $ hardcode-tray                                                                                                      
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 23, in <module>
    from gi import require_version
ImportError: No module named 'gi'
    
```
Can anyone tell me how to fix this ?
Many thanks !!

**Comment by bil-elmoussaoui** [comment]
You will need to install `python3-gobject` As i don't use Mint, i don't know the name of the package there.

**Comment by varlesh** [comment]
@bil-elmoussaoui  For PPA use depends: git, python3, wget, inkscape, python3-cairosvg, gir1.2-rsvg-2.0, libqt4-svg, sni-qt
Need add `python3-gi`?

**Comment by varlesh** [comment]
http://packages.ubuntu.com/search?keywords=python3-gi&searchon=names&suite=xenial&section=all

**Comment by varlesh** [comment]
Also availabe package `python3-gi-cairo`. I don't know what use on script, because i'm not programmer :)
http://packages.ubuntu.com/xenial/python3-gi-cairo

**Comment by varlesh** [comment]
I think it's python3-gi, because i'm use Ubuntu and script working fine. python3-gi-cairo not installed

**Comment by bil-elmoussaoui** [comment]
Yes its python3-gi

**Comment by varlesh** [comment]
Packages updated with fresh git-version, python3-gi added.
Close.

**Comment by varlesh** [comment]
@bil-elmoussaoui Need add python3-g depends on README

**Comment by bil-elmoussaoui** [comment]
Added

**Comment by varlesh** [comment]
@lbngoc Update APT package database and reinstall `hardcode-tray`, now fixed.

**Comment by lbngoc** [comment]
@bil-elmoussaoui @varlesh  Thanks for your support !
Finally I found that this issue was occurred because of my python3 version (3.4), I update to version 3.5 and this issue is fixed.
I think you need to note this to README.

**Comment by bil-elmoussaoui** [comment]
Well, the script was coded using python 3.3. It must be just a new package that was installed for python3.5 that was needed in order to make everything works in your case.
