### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#212]
The screenshots used right now, shows just a few of the applications (almost 70) that we actually can fix using Hardcode-Tray. 
Would like to have both screenshots of Numix and  Papirus to show the same applications before and after.

**Comment by varlesh** [comment]
OMG, i'm not have all this apps

**Comment by bil-elmoussaoui** [comment]
There's no need to include all the applications icons on the same screenshot. 
Something like this might look great
![ElementaryPlus](https://raw.githubusercontent.com/mank319/elementaryPlus/master/StatusIconPreview.png)

**Comment by varlesh** [comment]
OK i'm add, but only later. I'm busy now

**Comment by bil-elmoussaoui** [comment]
@varlesh Have you took a look at this?

**Comment by varlesh** [comment]
Oh, im forgot. Sorry

**Comment by varlesh** [comment]
Soon add...

**Comment by varlesh** [comment]
![papirus](https://cloud.githubusercontent.com/assets/8083855/20325803/2f54b564-ab97-11e6-953f-2d79ebaaebfd.png)

**Comment by bil-elmoussaoui** [comment]
Amazing! Can you do the same with Numix? :+1:

**Comment by bil-elmoussaoui** [comment]
@varlesh any news? :)

**Comment by varlesh** [comment]
@bil-elmoussaoui Sorry, but i'm now busy :( Fix more thousand icons on Papirus... Will be global update

**Comment by bil-elmoussaoui** [comment]
Not a problem, i've updated the screenshot here https://github.com/bil-elmoussaoui/Hardcode-Tray#themes, the credits are on the commit https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/9c3abf990ea014105021ab6951d7601e1e107e5b

**Comment by polarathene** [comment]
I just found out about hardcode tray when reading the Papirus theme README, they included this before/after screenshot: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/blob/master/hardcode-tray-preview.png

It wasn't clear what hardcode-tray was doing with it's description, it fixes something about tray icons and themes. I'm guessing some tray icons/apps don't respect themes for some reason and that is what hardcode-tray fixes. If you could explain the issue a little better and show off something like the before/after that'd communicate the purpose much better :)

**Comment by bil-elmoussaoui** [comment]
My english skills are not that good, if you have a better description just open a PR and i will merge it ;)

**Comment by varlesh** [comment]
Numix:
![numix](https://cloud.githubusercontent.com/assets/8083855/20661122/1e5a19ea-b55e-11e6-9df4-79621b7a2540.png)
Papirus:
![papirus](https://cloud.githubusercontent.com/assets/8083855/20661128/296d4e38-b55e-11e6-81dc-c20a69695213.png)

**Comment by varlesh** [comment]
@bil-elmoussaoui Also please fix link to https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by varlesh** [comment]
Papirus:
![papirus-new](https://cloud.githubusercontent.com/assets/8083855/20661326/51a097f6-b55f-11e6-949f-f4d018760386.png)

**Comment by bil-elmoussaoui** [comment]
Done
