### ISSUE TITLE
Applications not patched, detected on revert

### ISSUE THREAD

**Issue by xaxousis** [bil-elmoussaoui/Hardcode-Tray#213]
I am trying to run the script on a Linux Mint 18 fresh install, with Papirus icon theme and I can't get it to work.

This is the output I get:
```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-GTK
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..


Done , Thank you for using the Hardcode-Tray fixer!
```

When I select revert, I get the following output:
```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-GTK
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 2
Reverting now..

Chromium -- reverted
Hexchat -- reverted
Skype -- reverted
Teamviewer -- reverted

Done , Thank you for using the Hardcode-Tray fixer!
```

I guess this has something to do with the script not finding the icons or the apps when trying to set them. The icons are located in the standard `~/.icons/Papirus-GTK' folder.

Thanks for yours help.

**Comment by varlesh** [comment]
sni-qt version updated to 0.2.8?

**Comment by xaxousis** [comment]
Got the one from the PPA.
```
Package: sni-qt
Version: 0.2.8-0~81~ubuntu16.04.1
...
APT-Sources: http://ppa.launchpad.net/varlesh-l/hardcode-tray/ubuntu xenial/main amd64 Packages
```

**Comment by varlesh** [comment]
Yes, it's ok.
@bil-elmoussaoui

**Comment by bil-elmoussaoui** [comment]
You shouldn't revert after applying the new icons :P You have to force quit the application and restart it in order to see the new icon. Or just restart the system

**Comment by xaxousis** [comment]
I did restart, to no avail !

**Comment by varlesh** [comment]
@xaxousis If install icon theme on root directory?

**Comment by xaxousis** [comment]
I tried that too...

**Comment by varlesh** [comment]
hm

**Comment by bil-elmoussaoui** [comment]
Which version of hardcode-tray are you using? try this to know `hardcode-tray --version` and how did you install it

**Comment by xaxousis** [comment]
I've been fiddling with `script.py` a bit. It detects:
  - Chromium (which is not installed on the computer by the way);
  - Hexchat, the app_path points directly to the executable but it isn't patched;
  - Skype, the app_path points to "/usr/share/skype" while the binary is at /ussr/bin/skype.

I tried specifying Skype with the `--path /usr/bin/skype` option. It is then found but not patched.

**Comment by xaxousis** [comment]
I'm using the version from the PPA
```
$ hardcode-tray --version
v3.5
```

**Comment by bil-elmoussaoui** [comment]
Well, the script is more complicated than your thought! The app_path is used only to detect if the application is installed, which is the case as they're shown when you hit revert. 
You need to check the icons_path to see if the icons have been created successfully or not.

**Comment by xaxousis** [comment]
`icon_path` is empty for all the programs, but `app_icons` seems to hold the correct values.

**Comment by varlesh** [comment]
On Ubuntu 16.04 script worked with Papirus-GTK icon theme (installed on root directory):
![image](https://cloud.githubusercontent.com/assets/8083855/20280119/38684b7e-aabc-11e6-897d-eabd94d44dbe.png)
Telegram and Chrome icons on tray

**Comment by varlesh** [comment]
Installed from PPA

**Comment by bil-elmoussaoui** [comment]
I don't understand anything, you have been saying that nothing is fixed. And now Chrome and Telegram are? Can you please explain more.

**Comment by xaxousis** [comment]
No, I've been trying to make it work for Skype and HexChat. Which are detected by the script but not patched. I've since been trying to find out how to have them work.

**Comment by bil-elmoussaoui** [comment]
Which version you have of skype? Can you try something like `hardcode-tray --only hexchat`

**Comment by bil-elmoussaoui** [comment]
I know what causing this issue, will push a fix right now

**Comment by xaxousis** [comment]
Great ! :D 
I was about to post the JSON content of the `app` variable for HexChat.

**Comment by bil-elmoussaoui** [comment]
Should be fixed! it's not the best fix yet, but if it's does what it should do, i will refactor this part of code :P

**Comment by xaxousis** [comment]
Thanks ! :smiley: 
I'll check that as soon as possible.

**Comment by bil-elmoussaoui** [comment]
@xaxousis You will have to clone the repo in order to use the latest version, check the wiki on how to do so

**Comment by varlesh** [comment]
@xaxousis Use option `hardcode-tray -ug `
