### ISSUE TITLE
Telegram icons created wrong path

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#214]
hardcode-tray v3.5
icons created on **~/.local/share/TelegramDesktop/tdata**
right path **~/.local/share/TelegramDesktop/tdata/ticons**
![image](https://cloud.githubusercontent.com/assets/8083855/20279422/8f49cc36-aab9-11e6-95b8-0ad451784375.png)

**Comment by bil-elmoussaoui** [comment]
Can't confirm that at all :P as you can see in the icons path https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/telegram.json

**Comment by varlesh** [comment]
But i'm now tested and script create icons and symlinks on **tdata** folder.
Maybe need add slash after ticons?:
`"{userhome}/.local/share/TelegramDesktop/tdata/ticons"`

**Comment by bil-elmoussaoui** [comment]
Completly forgot the /, should be all good right now

**Comment by varlesh** [comment]
Now  worked :+1:
