### ISSUE TITLE
Youtube indicator not full

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#215]
Fixed script:
youtube-indicator-dark-sync{0-9}.svg
youtube-indicator-light-sync{0-9}.svg
youtube-indicator-downloading-dark.svg
youtube-indicator-downloading-light.svg

```
{
    "name": "Youtube Indicator",
    "app_path": [
        "/opt/extras.ubuntu.com/youtube-indicator/"
    ],
    "icons_path": [
        "/opt/extras.ubuntu.com/youtube-indicator/share/youtube-indicator/icons/"
    ],
    "is_qt": false,
    "force_create_folder": false,
    "exec_path_script": false,
    "is_script": false,
    "backup_ignore": false,
    "icons": [
        "youtube-indicator-downloading-dark.svg",
        "youtube-indicator-dark-disabled.svg",
        "youtube-indicator-dark-sync{0-9}.svg",
        "youtube-indicator-dark.svg",
        "youtube-indicator-downloading-light.svg",
        "youtube-indicator-light-disabled.svg",
        "youtube-indicator-light-sync{0-9}.svg",
        "youtube-indicator-light.svg"
    ]
}
```
![image](https://cloud.githubusercontent.com/assets/8083855/20305975/3fd0b062-ab49-11e6-9199-ddfc8f7e4a29.png)

**Comment by bil-elmoussaoui** [comment]
Which ones are missing ?

**Comment by varlesh** [comment]
youtube-indicator-dark-sync{0-9}.svg
youtube-indicator-light-sync{0-9}.svg
youtube-indicator-downloading-dark.svg
youtube-indicator-downloading-light.svg

**Comment by varlesh** [comment]
On database available:
youtube-indicator-dark-sync{0-5}.svg
youtube-indicator-light-sync{0-5}.svg

**Comment by varlesh** [comment]
@bil-elmoussaoui on first message already fixed code, compare

**Comment by bil-elmoussaoui** [comment]
Done
