### ISSUE TITLE
Script not running on Ubuntu 16.10: ImportError

### ISSUE THREAD

**Issue by lordbertus** [bil-elmoussaoui/Hardcode-Tray#216]
When I try to run the script on Ubuntu 16.10 64bit (Hardcode-Tray installed through the PPA):

bert@bertswritingmachine:~$ sudo hardcode-tray 

Traceback (most recent call last):
  File "script.py", line 13, in <module>
    from csv import reader
  File "/usr/local/lib/python3.5/csv.py", line 7, in <module>
    from _csv import Error, __version__, writer, reader, register_dialect, \
ImportError: /usr/local/lib/python3.5/lib-dynload/_csv.cpython-35m-x86_64-linux-gnu.so: file too short

**Comment by bil-elmoussaoui** [comment]
You must use `hardcode-tray` and not `sudo hardcode-tray`. I don't use csv anymore. I will remove the unneeded code right now

**Comment by varlesh** [comment]
@lordbertus 
```
sudo apt purge hardcode-tray
sudo rm -rf /opt/Hardcode-Tray
sudo apt update
sudo apt install hardcode-tray
hardcode-tray -ug
hardcode-tray -s 22
```

**Comment by bil-elmoussaoui** [comment]
Released a new version, 3.5.1 which includes to many small fixes. Should fix your issue too

**Comment by varlesh** [comment]
Soon updated on PPA

**Comment by lordbertus** [comment]
Thanks for the response. Actually the issue is there whether I use sudo or not. Unfortunately, after applying all the steps written by Varlesh and making sure I have the latest version, I still have the same problem:

bert@bertswritingmachine:~$ hardcode-tray --update
Hardcode-Tray is up to date

bert@bertswritingmachine:~$ hardcode-tray 
Traceback (most recent call last):
  File "script.py", line 15, in <module>
    from shutil import copyfile, move, rmtree
  File "/usr/local/lib/python3.5/shutil.py", line 13, in <module>
    import tarfile
  File "/usr/local/lib/python3.5/tarfile.py", line 48, in <module>
    import struct
  File "/usr/local/lib/python3.5/struct.py", line 13, in <module>
    from _struct import *
ImportError: /usr/local/lib/python3.5/lib-dynload/_struct.cpython-35m-x86_64-linux-gnu.so: file too short
bert@bertswritingmachine:~$

**Comment by bil-elmoussaoui** [comment]
It's seems that your python installation is broken :( Please open an issue on a ubuntu forum, as i'm using Arch linux and i can not help you fix this!

**Comment by varlesh** [comment]
@lordbertus **hardcode-tray --update-git**

**Comment by bil-elmoussaoui** [comment]
@varlesh no need to use update-git as i've released a new version!

**Comment by varlesh** [comment]
Oh, yes i'm stupid ^)

**Comment by lordbertus** [comment]
So yeah probably something wrong with my Python installation, will check it elsewhere. Thanks for your willingness to help though!

**Comment by bil-elmoussaoui** [comment]
@lordbertus This might help you https://unix.stackexchange.com/questions/218911/help-me-repair-my-python-i-think-dpkg-has-to-be-reset-very-tricky-issue
