### ISSUE TITLE
[Question] Support not hardcoded apps

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#217]
@bil-elmoussaoui Hi :)
Some apps have one icon name for tray and desktop-file. This not like me and some users, because we like monochrome icons for tray :) 
Maybe we can add hack for this apps?

For example, apps:
```
deluge
vlc
synapse
clipit-trayicon
```

**Comment by bil-elmoussaoui** [comment]
I don't think i can do something about this :( Numix had a long discussion about how to fix this and sadly we got no way to fix those applications. Either the application should rename the tray icon name or the application name. I would like to create a PR for each project to do that but would they merge it ?

**Comment by varlesh** [comment]
I think devs not fixed this, because not interested for them...
Better variant - use another apps

**Comment by bil-elmoussaoui** [comment]
For vlc, i might have a "solution". As it's a Qt application, it must create a folder under `/tmp` with the icon on it. Can you check that?

**Comment by varlesh** [comment]
Ok, some momnets only... i'm now fix nomachine

**Comment by varlesh** [comment]
For tray icon name `vlc-panel`

**Comment by bil-elmoussaoui** [comment]
I know that, just check if there's any vlc icons in `/tmp`?

**Comment by varlesh** [comment]
hm, vlc use **vlc-panel** icon on tray (tested with Unity)
![image](https://cloud.githubusercontent.com/assets/8083855/20322751/43ed45ec-ab8b-11e6-82f9-3f8efe869dd7.png)

**Comment by varlesh** [comment]
Not needed for Unity  DE:
![image](https://cloud.githubusercontent.com/assets/8083855/20322842/8e9eb76a-ab8b-11e6-9519-959ebfb6ca8f.png)
VLC good devs :)

**Comment by bil-elmoussaoui** [comment]
Anyway, i can't fix the rest of the apps :P i'm going to close this.

**Comment by varlesh** [comment]
Ok
