### ISSUE TITLE
[warning] Script change recursive owner system folders with Guake

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#218]
After apply script for **guake** change recursive owner system folders from ROOT to USER.
**/usr/share/pixmaps/guake**
RECURSIVE!!!
![2016-11-16 04-20-23](https://cloud.githubusercontent.com/assets/8083855/20331153/94c2e3e0-abb4-11e6-909f-0db62b74af91.png)

**Comment by bil-elmoussaoui** [comment]
I know what causes this issue. Will fix it tomorrow morning

**Comment by bil-elmoussaoui** [comment]
Fixed on master
