### ISSUE TITLE
Not work on Linux Mint

### ISSUE THREAD

**Issue by lbngoc** [bil-elmoussaoui/Hardcode-Tray#220]
I am using Linux Mint 18, after run `hardcode-tray --apply` it seem did not working, all applications icon was not changed, excluded skype apha
![](https://i.imgur.com/dERgQQ7.png)

**Comment by bil-elmoussaoui** [comment]
It must be the theme you're using. Hardcode-tray does not have any icons, it's uses the icons provided by the theme itself. So just use an other theme, or open a new issue upstream to ask the designers of Super Flat Remix to add Hardcode-Tray support.

**Comment by lbngoc** [comment]
@bil-elmoussaoui  Thank you for explaining ! But something was wrong here because current icon theme on my system was [Papyrus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk).
I tried with this command ` hardcode-tray --theme Papirus-GTK  --apply` but nothing was changed.

**Comment by bil-elmoussaoui** [comment]
The theme name is Paiprus-gtk and not Papirus-GTK

**Comment by lbngoc** [comment]
I attach my settings Theme in Linux Mint and my command here, what was wrong here :(
![](https://i.imgur.com/6D4WX0O.png)
Also tried with `Paiprus-gtk`, `Papirus-gtk`.. :( but not working too

**Comment by bil-elmoussaoui** [comment]
You need to install the patched version of sni-qt in order to make megasync icons works
