### ISSUE TITLE
qbittorrent (monochrome icons)

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#222]
I know, for tray use desktop icon, BUT qbittorrent have light and dark icons (it's enabled on settings).

![image](https://cloud.githubusercontent.com/assets/8083855/20589899/752264ac-b230-11e6-8e1e-83debb3e10fa.png)

Maybe we can fix this icons?
for example icon name` qbittorrent-panel-dark` and `qbittorrent-panel-light`

icon created on tmp :)
![image](https://cloud.githubusercontent.com/assets/8083855/20589930/b1ea5034-b230-11e6-89f0-9da9097d73e9.png)

**Comment by varlesh** [comment]
I think his code will be worked...
```
{
    "name": "qBittorrent",
    "app_path": [
        "/usr/bin/qbitorrent"
    ],
    "icons_path": [
        "{userhome}/.local/share/sni-qt/icons/qbittorrent/"
    ],
    "is_qt": true,
    "force_create_folder": false,
    "exec_path_script": false,
    "is_script": false,
    "backup_ignore": true,
    "icons": {
        "original": "764504178688.png",
        "theme": "qbittorrent-panel"
    }
}
```

**Comment by bil-elmoussaoui** [comment]
Have you tried your code? also you must change `force_create_folder` to `true`

**Comment by varlesh** [comment]
oops, not needed... program apply icon `qbittorrent-panel` from icon theme :)
![image](https://cloud.githubusercontent.com/assets/8083855/20597785/bbd41c80-b256-11e6-9b9d-8342f3db28fb.png)
It's worked how with vlc
