### ISSUE TITLE
Inconsistent Progress Bar Persistence

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#225]
The progress bars which the script displays while fixing don't have consistent persistence. The first few cycle through, each one replacing the position of the last (I assume this is intended functionality?)
![edited_sc](https://cloud.githubusercontent.com/assets/5920259/20629230/5161bd0e-b322-11e6-9286-298a230386d7.png)
But then the last one always remains rather than being replaced by the done string.
![screenshot_2016-11-25_15-13-56](https://cloud.githubusercontent.com/assets/5920259/20629237/5d1d6d32-b322-11e6-9417-a540e6270ea2.png)
In my opinion it'd be more useful if all the progress bars remained (each on a new line) so the user can see what has been fixed after running.

**Comment by bil-elmoussaoui** [comment]
Will push a fix this evening

**Comment by bil-elmoussaoui** [comment]
Better like this?
![capture du 2016-11-25 22-16-06](https://cloud.githubusercontent.com/assets/7660997/20635442/4fdc4478-b35d-11e6-94de-a40ea889e4e3.png)
![capture du 2016-11-25 22-19-22](https://cloud.githubusercontent.com/assets/7660997/20635443/4fdd3b26-b35d-11e6-8d17-af75cc0e413d.png)

**Comment by varlesh** [comment]
Yes, it's fine! :+1:
