### ISSUE TITLE
Pacman status icons

### ISSUE THREAD

**Issue by Jacobtey** [bil-elmoussaoui/Hardcode-Tray#230]
Hi! What about subject?

**Comment by bil-elmoussaoui** [comment]
Are you using Pamac by Monjaro? if so the icons are not hardcoded. 
You can find the icon names here https://github.com/manjaro/pamac/blob/master/src/tray.vala

```vala
const string update_icon_name = "pamac-tray-update";
const string noupdate_icon_name = "pamac-tray-no-update";
```

**Comment by varlesh** [comment]
also octopi:
https://github.com/aarnt/octopi/blob/0cff45f88c4b41decda6a35a8435c10d29c06a6b/src/uihelper.h

**Comment by bil-elmoussaoui** [comment]
@varlesh Do you want me to add octopi support?

**Comment by varlesh** [comment]
if possible.

**Comment by varlesh** [comment]
icons names from source... (on Papirus already available)

**Comment by bil-elmoussaoui** [comment]
Couldn't build octopi correctly on my laoptop, can you get the path where the icons are stored, also the binary file in /usr/bin to check if the app is installed ! thanks

**Comment by varlesh** [comment]
On Manjaro package:
![image](https://cloud.githubusercontent.com/assets/8083855/20671904/5b6769aa-b590-11e6-9c8c-90d7e76a02e7.png)

**Comment by varlesh** [comment]
```
/usr/share/icons/octopi.png
/usr/share/icons/octopi_red.png
/usr/share/icons/octopi_yellow.png
```

**Comment by varlesh** [comment]
it's octopi-notifier. Main cpp here:
https://github.com/aarnt/octopi/blob/master/notifier/octopi-notifier/mainwindow.cpp

**Comment by bil-elmoussaoui** [comment]
@varlesh done, icon names are 
- octopi-indicator
- octopi-error
- octopi-info

**Comment by varlesh** [comment]
ok, thx

**Comment by Jacobtey** [comment]
Hi! Also there is an octopi-transparent icon - https://github.com/aarnt/octopi/tree/master/resources/images

**Comment by Jacobtey** [comment]
Changing /usr/share/icons/octopi.png  octopi_red.png octopi_yellow.png doesn't effect to octopi-notifier tray icons. Only replacement in source above and recompiling.

**Comment by bil-elmoussaoui** [comment]
@Jacobtey Well, the icons must be stored somewhere else than. I will take a look

**Comment by bil-elmoussaoui** [comment]
@Jacobtey The icons are hardcoded on qresource file https://github.com/aarnt/octopi/blob/master/resources.qrc#L10; an equivalent to gresource files.. and those files can not be modified as far as i know. There seem to be an opened issue about that here https://github.com/aarnt/octopi/issues/156
