### ISSUE TITLE
Choose Color

### ISSUE THREAD

**Issue by bhajneet** [bil-elmoussaoui/Hardcode-Tray#231]
Hello,

Sorry I could not figure out how to direct message the developer.

Is there a way to choose the color of the hardcoded icons? For instance since I'm using Papirus Dark, the icons are all white. I would like to use a less bright color which matches the icons of the Papirus Dark plain greyscale icons.

**Comment by bil-elmoussaoui** [comment]
Well, it's not possible as the script does not provide any icons. if you want to do any modifications on icons you can open icons that you want to modify using inkscape and change the color to the one you wish

**Comment by varlesh** [comment]
@bhajneet 
```
sed -i 's|#fff|#YOUR_COLOR|g' ~/.icons/Papirus-Dark/22x22/panel/*.svg
sed -i 's|#fff|#YOUR_COLOR|g' ~/.icons/Papirus Dark/24x24/panel/*.svg
sed -i 's|#ffffff|#YOUR_COLOR|g' ~/.icons/Papirus Dark/22x22/panel/*.svg
sed -i 's|#ffffff|#YOUR_COLOR|g' ~/.icons/Papirus Dark/24x24/panel/*.svg
```

**Comment by varlesh** [comment]
i'm now commited single color.. update and run:
```
sed -i 's|#ffffff|#YOUR_COLOR|g' ~/.icons/Papirus-Dark/22x22/panel/*.svg
sed -i 's|#ffffff|#YOUR_COLOR|g' ~/.icons/Papirus-Dark/24x24/panel/*.svg
```

**Comment by bhajneet** [comment]
Ah very cool! I will have to pick files more manually as some icons are darker than others when disabled, but this was a very good lead on using svg @varlesh  (Also I believe the "fill" is only #fff with 3 instead of 6)

**Comment by varlesh** [comment]
#fff not needed anymore, i'm replace all #fff to #ffffff

**Comment by varlesh** [comment]
Update Papirus from git

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/314960d1f450c145c701006140a2f5e37f12f4fe

**Comment by varlesh** [comment]
All worked fine :)
![image](https://cloud.githubusercontent.com/assets/8083855/20729063/96b6de80-b691-11e6-85b3-ccc5f58858fa.png)

**Comment by bil-elmoussaoui** [comment]
@wa4557 do you think it's a good idea to add such an option to the script? shouldn't be complicated..

**Comment by wa4557** [comment]
Hey, sorry for not being around lately, I'm kinda busy lately. I personally don't think we should add such an option, this is something the icon theme has to provide, not this script
