### ISSUE TITLE
Bug: can't apply  your's script

### ISSUE THREAD

**Issue by stelmak** [bil-elmoussaoui/Hardcode-Tray#233]
Chromium                 [##......................................] 1/23 4.3%
Traceback (most recent call last):
  File "script.py", line 549, in <module>
    install(fix_only, icon_path)
  File "script.py", line 502, in install
    symlink_file(output_icon, symlink_icon)
UnboundLocalError: local variable 'output_icon' referenced before assignment

**Comment by bil-elmoussaoui** [comment]
Should be fixed; just update to git version using `hardcode-tray --update-git`
