### ISSUE TITLE
hunk #1 FAILED at 145

### ISSUE THREAD

**Issue by aditiapratama** [bil-elmoussaoui/Hardcode-Tray#236]
Hi, I tried to patch sni-qt, but I got following err
```
patching file src/iconcache.cpp
Hunk #1 FAILED at 145.
1 out of 1 hunk FAILED -- saving rejects to file src/iconcache.cpp.rej

```

any lead? I'm on fedora 25

**Comment by aditiapratama** [comment]
![image](https://cloud.githubusercontent.com/assets/982553/20841169/5f0e69d4-b8e5-11e6-8de1-94bc3efe8f56.png)

Here you go

**Comment by aditiapratama** [comment]
![image](https://cloud.githubusercontent.com/assets/982553/20841202/7c5d4ad2-b8e5-11e6-9a27-61ce7282e671.png)

this is what inside patches

**Comment by bil-elmoussaoui** [comment]
You can apply the patch manually if you want. if you don't want to do something wrong just email me both of the files and i will send the patched file to you at bil[dot]elmoussaoui[at]gmail[dot]com

**Comment by aditiapratama** [comment]
Ok it seems manually apply the patch works. btw should I uninstall/remove sni-qt from repo packages?

**Comment by bil-elmoussaoui** [comment]
Yep
