### ISSUE TITLE
Some troubles in Ubuntu 16.04.1

### ISSUE THREAD

**Issue by systematicat** [bil-elmoussaoui/Hardcode-Tray#240]
- Ubuntu 16.04.1 
- Latest patched sni-qt from git 
- Latest Arc-Dark theme 
- Latest Papirus-Dark from git 
- Latest Harcdode-tray from git 
- I want to patch Google Chrome, Keepassx and Skype 4.3 

Help me please with these problems: 
1) Hardcode-tray didn`t create app folders in ~/.local/share/sni-qt/icons even if I set option "force_create_folder": true in app .json file. So I create them myself. 
2) No matter which theme I use even if I set "$hardcode-tray --theme Papirus-Dark --apply" icons in ~/.local/share/sni-qt/icons/skype appear only in dark variant and no icons in other apps folders. 
3) No icons for Google Chrome and Keepassx in ~/.local/share/sni-qt/icons/<app_folder>

**Comment by bil-elmoussaoui** [comment]
Please, first change the title to something else. Saying that the script is absolutely useless won't help me improve it. 
In order to explain how things works. 
Google chrome does not use a qt tray icons. It's uses a gtk indicator, but the icons are hardcoded on a binary file. `resources.pak`, which can be extracted using the data_pack file provided with the script. Or others libraries. So no folder will be created in `.local/share/sni-qt/icons` as it's not needed. Please restart Google chrome or your laptop once you applied the script; 
Keepassx, is using the same tray icon as the application icon name. So i can't patch it at all :( see this #239 #173. The issue is reported upstream; we hope it will be fixed soon!
For skype, please move to skypeforlinux, a new version of Skype based on Electron instead of the old ugly version ! (which is supported by hardcode-tray)

**Comment by systematicat** [comment]
Sorry but after your answer I think I was right name script useless... 
What about this - No matter which theme I use even if I set "$hardcode-tray --theme Papirus-Dark --apply" icons in ~/.local/share/sni-qt/icons/skype appear only in dark variant and no icons in other apps folders. ? 
And yes I HATE ELECTRON :-) And all you guys who write desktop apps with web technologies.

**Comment by bil-elmoussaoui** [comment]
Because you're setting the theme using `--theme Papirus-Dark`. We can't have more than one color variant using Qt (sni-qt...) don't know why people still using this.. Try using something like `--theme Papirus` or without it at all. 
And which other folders are you talking about ?

**Comment by systematicat** [comment]
Thx. But it doesn`t work. Icons still setting in dark variant dont`t know why. 
"$hardcode-tray" or "$hardcode-tray --theme Papirus --apply" - no difference

**Comment by bil-elmoussaoui** [comment]
Which icon theme are you using ? Can you screenshot the result on terminal  + the content of the sni-qt folder

**Comment by wa4557** [comment]
@systematicat You know this is a FOSS program, so we are working on this in our free-time? Instead of complaining you could help improving it, or fork it and make it better 

@bil-elmoussaoui Are there any sni-qt programs that still work? I had a look in the path and it is actually a really simple patch with just a few lines of code (written in C, which would be ok for me), I have absolutely no idea how launchpad works though, otherwise we could just make our own patched version (with debugging information ideally, to figure out what's wrong)

**Comment by bil-elmoussaoui** [comment]
Yeah, we can create a new repository for that. Add a log file and we will see how to improve sni-qt support

**Comment by wa4557** [comment]
I have no idea how, but I think I have just created a PPA with the patched version of sni-qt :) We'll see how this works out, and if we can add debug infos into the code...

**Comment by bil-elmoussaoui** [comment]
If this works, we have to put the code somewhere in order to improve it. Maybe adding more features to it

**Comment by wa4557** [comment]
i have the code hosted on launchpad
https://code.launchpad.net/~andreas-angerer89/sni-qt/sni-qt-patched

I can add you as collaborator?

**Comment by bil-elmoussaoui** [comment]
Here's my account on launchpad https://launchpad.net/~bilal-elmoussaoui

**Comment by wa4557** [comment]
ppa is ready asa well

https://code.launchpad.net/~andreas-angerer89/+archive/ubuntu/sni-qt-patched

**Comment by bil-elmoussaoui** [comment]
Perfect! Can you use the same recipe to build the patched version of sni-qt for older versions of Ubuntu too?

**Comment by wa4557** [comment]
14.04?

**Comment by bil-elmoussaoui** [comment]
@wa4557 all the possible ubuntu builds, this way we won't force users to upgrade their system just to fix an ugly icon..

**Comment by wa4557** [comment]
I can only build supported versions, so 14.04 is the only one I can add

**Comment by bil-elmoussaoui** [comment]
Well, we add only 14.04 then ;) and i think that the i386 version is missing too :P

**Comment by wa4557** [comment]
no, i386 should be built. Just installed it on my system

**Comment by varlesh** [comment]
Maybe better update sni-qt on my PPA?

**Comment by varlesh** [comment]
@wa4557 You want maintainer for hardcode-tray packge too?

**Comment by varlesh** [comment]
or i can copy new sni-qt patched version from your PPA

**Comment by wa4557** [comment]
I don't care actually. As far as I can see, you are using the original sni-qt-eplus code. I think we want to change that because we have to change the source code of it. What you can do is use my branch as source for your ppa. I'm going to delete mine then

**Comment by wa4557** [comment]
You have to use this branch https://code.launchpad.net/~andreas-angerer89/sni-qt/sni-qt-patched

I'm keeping my ppa for now because I try different things

**Comment by varlesh** [comment]
Yes, on my PPA e-plus version build for 16.10 release only. For older ubuntu releases only copied

**Comment by varlesh** [comment]
@wa4557 Oh no... i'm don't know how work with recipie bazar and other tools...
Maybe you want new mantainer for hardcode-tray and sni-qt? For example hardcode-tray will be better integrate update with git (daily builds PPA)

**Comment by varlesh** [comment]
sorry my Emglish :)

**Comment by wa4557** [comment]
ok, i will then use git-import to maintain hardcode-tray as well :) No worries

**Comment by varlesh** [comment]
Thx! Because i'm not have time for this... Ok, when all finished and update readme - i'm delete my PPA

**Comment by bil-elmoussaoui** [comment]
We better use the new PPA as i'm going to see if it's possible to use the current theme directly or at least svg icons..

**Comment by wa4557** [comment]
@varlesh How did you make the hardcode-fixer package?

**Comment by varlesh** [comment]
@wa4557 i'm create manual. Sources and DEBIAN available on PPA

**Comment by wa4557** [comment]
Ok, I have no idea how to do that, sorry :/ I'm really not good with launchpad. Can you give me any instructions, or can I copy your branch somehow?

**Comment by varlesh** [comment]
i'm not have branch. Upload only src and changelog.
https://launchpad.net/~varlesh-l/+archive/ubuntu/hardcode-tray/+files/hardcode-tray_3.5.2.1xenial.tar.gz

**Comment by varlesh** [comment]
unpack archive. And see debian directory

**Comment by wa4557** [comment]
ah, ok I get it. So you're not importing with git? I think I can do that automatically :)

**Comment by wa4557** [comment]
@bil-elmoussaoui I figured it out how to automaatically upload the git version to launchpad; now I'm a bzr master \o/. In the ppa is now the patched version of sni-qt and a package for hardcode-tray

@varlesh After we change the readme you can delete your ppa I guess :)

**Comment by systematicat** [comment]
Found all answers...

**Comment by bil-elmoussaoui** [comment]
@wa4557 Perfect! i'm going to change the README.
@systematicat Hope that we were able to provide helpful information.

**Comment by bil-elmoussaoui** [comment]
@systematicat I just updated Chrome on my system and it's seems that they have changed the icon name again :P i will push a fix right now!

**Comment by systematicat** [comment]
Hey @bil-elmoussaoui thank you for updates! 
But I think I`ll get rid of Chrome soon. It drives me crazy - sometimes after Chrome update tray icon is invisible, sometimes visible.

**Comment by bil-elmoussaoui** [comment]
You're welcome! Well, if you have any other issue with Hardcode-tray please report it :)
