### ISSUE TITLE
Blurry skype icon

### ISSUE THREAD

**Issue by Jacobtey** [bil-elmoussaoui/Hardcode-Tray#247]
### Specifications
- Hardcode-Tray version : `v3.5.2.1`
- Distribution : `manjaro fringilla`
- Gtk version : `3.22.5-1`
- Inkscape version : `0.91-20`
- Cairo version : `1.14.8-1`
- Sni-qt-eplus-bzr version: `1:r101-1`
- Application name :  `skypeforlinux`
- Application version : `1.13.0.3-2`

### Expected behavior and actual behavior
Skype status tray icon is blurry. It should look like this one that exported from svg to png whith inkscape by hand. breeze-rsm is recolored numix
![screenshot_20161212_131448](https://cloud.githubusercontent.com/assets/7997512/21096557/e2d59f44-c079-11e6-9ff9-7deb2a517148.png)

### Steps to reproduce the problem
1. run `hardcode-tray --only skypeforlinux --theme breeze-rsm --size 22`
2. run `skypeforlinux`

**Comment by bil-elmoussaoui** [comment]
Can you try this `hardcode-tray --update-git` and then use `--force-inkscape` and see if things will work correctly ?

**Comment by Jacobtey** [comment]
I've tried it. No effect. It looks like a 16px icon is resized to 22px one or more. Icons in the menu looks correctly.
![screenshot_20161212_185348](https://cloud.githubusercontent.com/assets/7997512/21105888/5f6963e4-c0a5-11e6-91cf-0d4207a6b158.png)

**Comment by bil-elmoussaoui** [comment]
You can try forcing icon size using --size 24 for example and see if something changes.
Anyway, for me it must be an electron/skypeforlinux issue...

**Comment by bil-elmoussaoui** [comment]
Closing as, it's not a hardcode-tray issue. Please report it upstream

**Comment by Jacobtey** [comment]
Is it possible to change icons by hand? Native icons look smooth at any resolution.
![screenshot_20161215_201921](https://cloud.githubusercontent.com/assets/7997512/21238450/91370db2-c31c-11e6-8fd8-734c02e95454.png)

**Comment by varlesh** [comment]
it's bug Plasma 5:
https://bugs.kde.org/show_bug.cgi?id=366062
