### ISSUE TITLE
My-weather-indicator symlinks?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#25]
Hmm for my-weather-indicator no additional icons are needed, just a second column in `my-weather-indicator.txt` pointing to `weathter-clear.svg` etc., am I right?

**Comment by bil-elmoussaoui** [comment]
The icons are the same so a symlink is needed

**Comment by wa4557** [comment]
Hmm if you put the generic weather-icon names in the second colum in my-weather-indicator.txt those funny named symlinks are not needed in the icon them, imo

**Comment by bil-elmoussaoui** [comment]
Yeah i will do that next week

**Comment by wa4557** [comment]
No need to hurry :)

**Comment by wa4557** [comment]
If you look [here] (https://github.com/numixproject/numix-icon-theme/issues/580) you'll see that there are actually a lot of weather icons  that aren't covered yet in Numix. I think however that you can use them in your my-weather-indicator script (this is then also an additional reason for numix to make those icons :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 yeah, i already added some symlinks. i will do the rest soon

**Comment by bil-elmoussaoui** [comment]
A lot of icons are missing in Numix too ;) i will report that later;

**Comment by bil-elmoussaoui** [comment]
I added the symlinks, waiting for Numix to fix [this](https://github.com/numixproject/numix-icon-theme/issues/668)
