### ISSUE TITLE
something wrong in last version

### ISSUE THREAD

**Issue by KottV** [bil-elmoussaoui/Hardcode-Tray#250]
### Specifications
- Hardcode-Tray version : v3.5.2.2
- Distribution : openSUSE Tumbleweed
- Gtk version : 
- Inkscape version : 0.91
- Cairo version : 1.15.2
- Sni-qt version: from git (2.8.1 ?)
- Application name :  All (skype,megasync,whatsie) except steam
- Application version : 

### Expected behavior 
Applied fixes
### actual behavior
No apps to fix! Please report on GitHub if this is not the case
### Steps to reproduce the problem

1.  run hardcode-tray

**Comment by varlesh** [comment]
avialable repo for opensuse?

**Comment by KottV** [comment]
>>avialable repo for opensuse?

repo with what? patched sni-qt built by myself: https://software.opensuse.org/search?p=1&baseproject=openSUSE:Tumbleweed&q=sni-qt-patched

hardcode-tray - straight from git

**Comment by varlesh** [comment]
Maybe not full install depends. It's list for Debian:
git, python3, python3-gi, wget, inkscape, python3-cairosvg, gir1.2-rsvg-2.0

**Comment by KottV** [comment]
it worked couple days ago, all dependencies are met

**Comment by bil-elmoussaoui** [comment]
Which theme are you using? And can you take a screenshot of the terminal output.
Also, it would be nice if you can maintain the opensuse repo, what do you think ?

**Comment by KottV** [comment]
Yes i can. But we need change some hardcoded distro-specific paths in database, i can point just one right now:
/usr/lib/i386-linux-gnu/
in teamviewer.json

And deal with my current problem :)
I really don't know what happened. After reverting to old revisions i get same errors. So, i should investigate this for a while.

Now it looks as

> kv@Kot:~> hardcode-tray --theme Papirus
> [sudo] пароль для root: 
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Не удалось подключиться к: Connection refused
> 
> (script.py:16941): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> Welcome to the tray icons hardcoder fixer!
> Your indicator icon size is : 22
> Your current icon theme is : Papirus
> Svg to png functions are : Enabled
> Applications will be fixed : All
> 1 - Apply
> 2 - Revert
> Please choose: 1
> Applying now..
> 
> Steam                    [########################################] 1/1 100.0%
> 
> Done, Thank you for using the Hardcode-Tray fixer!
> 

or

> kv@Kot:~> hardcode-tray
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused                                                   
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Не удалось подключиться к: Connection refused                                           
>                                                                                                                                              
> (script.py:17198): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed                                 
> Welcome to the tray icons hardcoder fixer!                                                                                                   
> Your indicator icon size is : 22                                                                                                             
> Your current icon theme is : Adwaita                                                                                                         
> Svg to png functions are : Enabled                                                                                                           
> Applications will be fixed : All                                                                                                             
> 1 - Apply                                                                                                                                    
> 2 - Revert                                                                                                                                   
> Please choose: 1                                                                                                                             
> Applying now..                                                                                                                               
>                                                                                                                                              
> Traceback (most recent call last):
>   File "script.py", line 553, in <module>
>     install(fix_only, icon_path)
>   File "script.py", line 443, in install
>     apps = get_supported_apps(fix_only, custom_path)
>   File "script.py", line 274, in get_supported_apps
>     data["icons"], dont_install = get_app_icons(data)
>   File "script.py", line 328, in get_app_icons
>     theme_icon = theme.lookup_icon(path.splitext(theme_icon)[
> AttributeError: 'NoneType' object has no attribute 'lookup_icon'

or

> kv@Kot:~> hardcode-tray --theme Breeze -o skype
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Не удалось подключиться к: Connection refused
> 
> (script.py:17392): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> Welcome to the tray icons hardcoder fixer!
> Your indicator icon size is : 22
> Your current icon theme is : Breeze
> Svg to png functions are : Enabled
> Applications will be fixed : skype
> 1 - Apply
> 2 - Revert
> Please choose: 1
> Applying now..
> 
> No apps to fix! Please report on GitHub if this is not the case
> 
> kv@Kot:~> ldd `which skype`
> linux-gate.so.1 (0xf774b000)
> libXv.so.1 => /usr/lib/libXv.so.1 (0xf547f000)
> libXss.so.1 => /usr/lib/libXss.so.1 (0xf5477000)
> librt.so.1 => /lib/librt.so.1 (0xf5467000)
> libdl.so.2 => /lib/libdl.so.2 (0xf545f000)
> libX11.so.6 => /usr/lib/libX11.so.6 (0xf5307000)
> libXext.so.6 => /usr/lib/libXext.so.6 (0xf52ef000)
> libQtDBus.so.4 => /usr/lib/libQtDBus.so.4 (0xf525f000)
> libQtWebKit.so.4 => /usr/lib/libQtWebKit.so.4 (0xf3187000)
> libQtXml.so.4 => /usr/lib/libQtXml.so.4 (0xf313f000)
> libQtGui.so.4 => /usr/lib/libQtGui.so.4 (0xf25b7000)
> libQtNetwork.so.4 => ....

**Comment by bil-elmoussaoui** [comment]
For the second issue, i know how to fix it. I will push a fix soon! It's due to using a theme that does not exists on your machine. Adwaita is detected as your default theme but it's not the case.. For Breeze, there's no icons on that theme (hardcoded icons). 
Can you try updating the icon cache of Papirus?
For the rest of the issues 
```
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Не удалось подключиться к: Connection refused

(script.py:17198): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
```
It's has nothing to do with the script, must be your gtk installation or python-gobejct that are broken :((

**Comment by KottV** [comment]
found it
it fails when icon dirs simlinked:

kv@Kot:~> ls -l ~/.icons
итого 4
drwxr-xr-x 2 kv users 4096 апр 15  2016 default
lrwxrwxrwx 1 kv users   39 дек 12 22:07 Papirus -> /home/kv/src/papirus-icon-theme/Papirus
lrwxrwxrwx 1 kv users   44 дек 12 22:07 Papirus-Dark -> /home/kv/src/papirus-icon-theme/Papirus-Dark

**Comment by bil-elmoussaoui** [comment]
Is it's working for now?

**Comment by KottV** [comment]
Yes. At least - all apps detected.

> hardcode-tray --theme Papirus
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
> Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Не удалось подключиться к: Connection refused
> 
> (script.py:10159): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
> Welcome to the tray icons hardcoder fixer!
> Your indicator icon size is : 22
> Your current icon theme is : Papirus
> Svg to png functions are : Enabled
> Applications will be fixed : All
> 1 - Apply
> 2 - Revert
> Please choose: 1
> Applying now..
> 
> Megasync                 [######..................................] 4/29 13.8%
> No Machine               [########................................] 6/29 20.7%
> Skype                    [############################............] 20/29 69.0%
> Steam                    [#############################...........] 21/29 72.4%
> Teamviewer               [#####################################...] 27/29 93.1%
> Whatsie                  [########################################] 29/29 100.0%
> 
> Done, Thank you for using the Hardcode-Tray fixer!

**Comment by bil-elmoussaoui** [comment]
Perfect! I'm closing this then, can you open a new issue with the stuff that we need to change in order to get the patched version of sni-qt and hardcode-tray on opensuse?

**Comment by KottV** [comment]
But it don't creates dirs in ~/.local/share/sni-qt

until i change to "force_create_folder":  true

**Comment by KottV** [comment]
I will, but tomorrow.
Thank you again!

**Comment by bil-elmoussaoui** [comment]
Alright! and i have already fixed skype issue ;) thanks!
