### ISSUE TITLE
Wrong converting

### ISSUE THREAD

**Issue by iwex** [bil-elmoussaoui/Hardcode-Tray#252]
Hello! Script converts svg to black. 
![image](https://cloud.githubusercontent.com/assets/4510068/21411164/e93b58b6-c7ee-11e6-9de6-36c5cff23a13.png)

**Comment by bil-elmoussaoui** [comment]
Are using KDE? if so you will need to take a look at this #245

**Comment by iwex** [comment]
Fixed by reinstalling inkscape :)

**Comment by bil-elmoussaoui** [comment]
Happy that it's working perfectly for you!

**Comment by iwex** [comment]
Thanks for great tool :)
