### ISSUE TITLE
Temps support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#253]
### Specifications
- Application name :  `Temps` based on electron
- Application version : ``
https://github.com/jackd248/temps/

### Steps to reproduce the problem
1. 
2. 
3.

**Comment by bil-elmoussaoui** [comment]
I've just took a look and it seems that the application uses the same icons for tray and on the main ui.. I'm going to open a new issue upstream.

**Comment by varlesh** [comment]
i'm not see tray icons for Temps:
![image](https://cloud.githubusercontent.com/assets/8083855/21923656/bbb611e0-d98e-11e6-8f3a-2a37b90db92d.png)
Ubuntu 16.04 Unity
Temps 0.7.0

**Comment by bil-elmoussaoui** [comment]
![capture d ecran de 2017-01-13 10-21-11](https://cloud.githubusercontent.com/assets/7660997/21924620/3c0be028-d97a-11e6-8d78-a04b4b50241b.png)

**Comment by bil-elmoussaoui** [comment]
The app dev seems quite dead at the moment. So closing this
