### ISSUE TITLE
electron apps black icons

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#255]
hardcode-tray git version
icon theme: ePapirus
inkscape: 0.91
on elementaryOS loki applied black icons for electron apps.
LOG:
```
hardcode-tray -s 24 -fs
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 24
Your current icon theme is : ePapirus
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Clementine               [#.......................................] 1/34 2.9%
Google Chrome            [##......................................] 2/34 5.9%
Skype                    [######################################..] 32/34 94.1%
Wire                     [########################################] 34/34 100.0%
```
Tested with skype4linux and wire:
![2016-12-24 10 29 58](https://cloud.githubusercontent.com/assets/8083855/21466072/f7798e58-c9c3-11e6-8978-fcf8e2d1a0eb.png)

**Comment by varlesh** [comment]
icon changed with inkscape by manual fine. For example:
```
inkscape -z -f wire-tray.svg -e wire-tray.png
```
@bil-elmoussaoui What happened again?

**Comment by varlesh** [comment]
also script change premissions to ROOT on inkscape config home user folder ~/.config/inkscape
![2016-12-24 10 39 05](https://cloud.githubusercontent.com/assets/8083855/21466100/55f52afe-c9c5-11e6-8ab9-8de69cde0670.png)

**Comment by varlesh** [comment]
it's happened with only electron apps. Telegram, Clementine worked fine:
![2016-12-24 10 54 36](https://cloud.githubusercontent.com/assets/8083855/21466143/6452b2d6-c9c7-11e6-8e5d-06265e1de9c5.png)

**Comment by varlesh** [comment]
> Even when you try --force-inskcape ?
Yes, i'm attach log and doing this repeatedly - electron apps not use inkscape, because icon black.
also option revert not worked - status show OK, but really icons not reverted.

**Comment by varlesh** [comment]
@bil-elmoussaoui maybe better use inkscape for all (by default) and remove cairo? Because cairo bugged :(

**Comment by bil-elmoussaoui** [comment]
It's impossible that electron apps won't use inkscape instead of cairo. I will try to investigate more about this tomorrow morning. Are you using elementary OS? and where i can find the theme you're using?

**Comment by varlesh** [comment]
Ok, thank you!
it's Papirus mod for elementary...
```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install-papirus-root.sh | sh
```

**Comment by varlesh** [comment]
@bil-elmoussaoui any news?

**Comment by bil-elmoussaoui** [comment]
@varlesh I just installed elementary OS again, tried installing skypeforlinux but the tray icons are not working on elementary at all... do you have any idea?

**Comment by varlesh** [comment]
need install libs:
`sudo apt install libappindicator1 python-appindicator libappindicator3-1 libindicator3-7 libindicator7 wingpanel-indicator-ayatana`

**Comment by bil-elmoussaoui** [comment]
Ok i got the indicators now, and i got the dark icons too. It seems that inkscape does not convert icons right. As when i use --force-inkscape, it uses inkscape as expected (did some tests). I will try to extract the asar file and see if the icons are black or white..

**Comment by varlesh** [comment]
No, inkscape worked right, because i'm convert icon manual:
`inkscape -z -f input.svg -e output.png`
And for other apps (not electron) all worked fine.
extract not needed - icons available on /tmp - chromium folders

**Comment by varlesh** [comment]
it's happened with electron apps only and i don't know why...

**Comment by varlesh** [comment]
i think script not use inkscape for electron or maybe electron.py have error

**Comment by bil-elmoussaoui** [comment]
You're right! the issue is from electron.py i guess.. as i forgot to add the --force-inkscape to the electron script. I will add a hacky solution to fix this, a better fix will land with #248

**Comment by bil-elmoussaoui** [comment]
Fixed! i've also fixed the same issue with chrome and spotify script. This issue shouldn't happen at all never again with the new version of the code!

**Comment by varlesh** [comment]
revert worked too?

**Comment by bil-elmoussaoui** [comment]
Yes it works perfectly on my computer. You must have corrupted the bak file that's why it doesn't revert to the right file. I'm thinking of a better backup revert feature. Like having the backup saved by date and time so you can have multiple versions saved. All of those saved on `.config/hardcode-tray`. For now, all i can tell you is reinstall the application to get the default asar file back and apply the script again. It should work fine.

**Comment by varlesh** [comment]
@bil-elmoussaoui Big thx!!! All fine:
![image](https://cloud.githubusercontent.com/assets/8083855/21506252/0e1650c6-cc88-11e6-962a-ef23c4235e02.png)

**Comment by bil-elmoussaoui** [comment]
Happy to hear that it works! stay tuned, the new release will add some nice pretty features!
