### ISSUE TITLE
[Electron] Harmony music player

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#259]
App: Harmony
Type: Electron (but not packed)
Site: https://github.com/vincelwt/harmony
install path: `/opt/Harmony`
binary path: `/opt/Harmony/harmony`

3 icons for tray:
- [ ]  icon.png
- [ ]  icon-black.png
- [ ]  icon-white.png

path: `/opt/Harmony/resources/app/icons`

preview:
![image](https://cloud.githubusercontent.com/assets/8083855/21506900/485ea7ba-cc8d-11e6-96c9-a45cacb646e3.png)
All icons not packed to ASAR and have  only hardcoded path! electron.py not needed.

**Comment by varlesh** [comment]
i think need replce only icon.png

**Comment by bil-elmoussaoui** [comment]
I will add those with the same PR as #256 #257 #248 #253 #232 , it might take some time! but it should be here within the first days of the new year!

**Comment by varlesh** [comment]
Yes, i check this. icons used from /opt/Harmony/resources/app/icons/, electron.py not needed.
Also on tray menu used hardcoded icons... maybe this fixed too?
![image](https://cloud.githubusercontent.com/assets/8083855/21506785/4bd934c4-cc8c-11e6-9e94-1dceb52b405a.png)

**Comment by varlesh** [comment]
on tray menu used icons from `/opt/Harmony/resources/app/icons/tray/`:
```
heart.png
hide.png
next.png
pause.png
previous.png
quit.png
show.png
```
but only 16px

**Comment by bil-elmoussaoui** [comment]
I'm not going to add those icons, as the script is supposed to fix only the tray icons. You still can fork my code and add those icons. We have started a project like this, a year ago ( @wa4557 and I) but we stopped working on it. it's quite the same thing as tray icons, but for all kind of apps like (calibre, filezilla, dropbox, megasync..) but again, it's not the purpose of Hardcode-Tray!

**Comment by varlesh** [comment]
Ok, no problem!

**Comment by varlesh** [comment]
on papirus already added icon name `harmony-tray`

**Comment by bil-elmoussaoui** [comment]
Thanks again for the commit!

**Comment by redpop1** [comment]
Doesn't work for harmony 0.4.4.

**Comment by bil-elmoussaoui** [comment]
Where the icons are stored for harmony? And which distro are you using? it might be the installation path that is different in your case

**Comment by redpop1** [comment]
Ubuntu 16.04.1
installation path: /opt/Harmony
Tray icon pathh: /opt/Harmony/resources/app/icons/tray

**Comment by bil-elmoussaoui** [comment]
Can you poste a screenshot of the content of this folder ? because @varlesh used `/opt/Harmony/resources/app/icons`

**Comment by redpop1** [comment]
Im really sorry , my mistake: it's /opt/Harmony/resources/app/icons
![harmonytray](https://cloud.githubusercontent.com/assets/647670/21524624/cb9d0542-cd17-11e6-8cab-bdd70ff7fd12.png)

**Comment by bil-elmoussaoui** [comment]
Not a problem :) have you closed the application and tried again? and which icon is used in your case? as @varlesh has only added the icon.png and not icon-black or icon-white

**Comment by redpop1** [comment]
I use icon.png.

![harmony-terminal](https://cloud.githubusercontent.com/assets/647670/21525083/1788e81a-cd1b-11e6-9ccc-6030054207c9.png)

**Comment by bil-elmoussaoui** [comment]
Have you updated to the latest git version? use `hardcode-tray --update-git` and try again.

**Comment by varlesh** [comment]
Not confirm this:
![image](https://cloud.githubusercontent.com/assets/8083855/21526763/0bddc970-cd40-11e6-9f61-a81ca3e984ce.png)

**Comment by varlesh** [comment]
@redpop1 Update papirus and update hardcode-tray from git. All worked!

**Comment by redpop1** [comment]
I'm really sorry, something went wrong with the updating, I assume combining ubuntu ppa and update git or I don't know what.

I got it finaly to update.

Thanks guys
