### ISSUE TITLE
my-weather-indicator

### ISSUE THREAD

**Issue by redpop1** [bil-elmoussaoui/Hardcode-Tray#264]
### Specifications
- Hardcode-Tray version : `latest git`
- Distribution : `ubuntu 16.04`
- Gtk version : ``
- Inkscape version : 0.91`` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `my-weather-indicator`
- Application version : `0.8.1`

### Steps to reproduce the problem
1. 
2. 
3.
Doesn't work, I get an icon missing in the panel.

Also in the opt directory, these are dark icons and have the wrong name

**Comment by bil-elmoussaoui** [comment]
Can you post a screenshot too? I have never used this application before, this might help me :) also the dark icons, are going to be fixed by this issue #257 (correct me if i misunderstood)

**Comment by redpop1** [comment]
![my-weather-indicator](https://cloud.githubusercontent.com/assets/647670/21524471/8e495bba-cd16-11e6-88c9-218cfef702d1.png)

Missing picture and icons created are dark instead of white

**Comment by bil-elmoussaoui** [comment]
Which icon theme are you using?

**Comment by redpop1** [comment]
papirus-dark, latest...

**Comment by bil-elmoussaoui** [comment]
Have you tried using  `--force-inkscape` ?

**Comment by redpop1** [comment]
yes with --force-inkscape , and I also tried to completely remove my-weather-indicator and reinstalling.

**Comment by bil-elmoussaoui** [comment]
It's an issue with cairosvg, which i can do anything about it... Just report it upstream :( that's why i added the force-inkscape argument, and it's mentionned on Papirus theme README page.

**Comment by bil-elmoussaoui** [comment]
For more information take a look here #245

**Comment by redpop1** [comment]
It's not working with --force-inkscape, just the same problem

**Comment by bil-elmoussaoui** [comment]
Can you post a screenshot of the tray icons folder? `        "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/icons/"`

**Comment by varlesh** [comment]
@redpop1 It's Papirus icon! It's Fog!
