### ISSUE TITLE
[Enhancement] Colorize icons

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#265]
Maybe add option for colorize icons for tray? We support SVG icon theme and SVG contained color. It's very easy replace colors with sed.
For example:
`hardcode-tray --change-color #d3dae3 #dfdbd2`
This command change color hardcoded icons on Papirus to color ubuntu-mono-dark - user can use main icon theme ubuntu-mono, but for tray fro Papirus with modify colors.

**Comment by bil-elmoussaoui** [comment]
I will keep this open for later versions.

**Comment by bil-elmoussaoui** [comment]
This shouldn't work with CairoSVG? if for example the user uses SVG icons that does not use CSS SVG ?

**Comment by varlesh** [comment]
no, need copy file to temporary folder, apply sed, then convert to png and etc...
CSS SVG also contained color. For example:
```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" height="22" width="22" version="1.1" viewBox="0 0 22 22" id="svg2">
 <defs id="defs10">
  <style type="text/css" id="current-color-scheme">
   .ColorScheme-Text { color:#5c616c; } .ColorScheme-Highlight { color:#5294e2; } .ColorScheme-ButtonBackground { color:#d3dae3; }
  </style>
 </defs>
 <g transform="translate(-201 -671.36)" id="g4">
  <path style="fill:currentColor" d="m212 675.37c-3.866 0-7 3.134-7 7s3.134 7 7 7 7-3.134 7-7-3.134-7-7-7zm0 3v3h3l-3 5v-3h-3l3-5z" id="path6" class="ColorScheme-ButtonBackground"/>
 </g>
</svg>
```

**Comment by bil-elmoussaoui** [comment]
I will take a look this evening

Le 29 déc. 2016 4:15 PM, "Alexey Varfolomeev" <notifications@github.com> a
écrit :

**Comment by bil-elmoussaoui** [comment]
This is now on master. Just use `hardcode-tray --change-color "#FIRSTCOLOR #REPLACE_FIRST_COLOR" "#SECONDCOLOR #REPLACE_SECOND_COLOR"...`. Of course, it supports more than one icon to replace.

**Comment by varlesh** [comment]
Fine. Thank you :+1:
