### ISSUE TITLE
[critical] electron apps not running

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#269]
after hardcode-tray electron apps not running.
It's happened wit fresh git-version
Tested with skype and wire.
![image](https://cloud.githubusercontent.com/assets/8083855/21558784/074358f2-ce59-11e6-9892-c0f145218013.png)
hardcode-tray not show error logs.
electron apps not show error on terminal, but not running (wire show message error on screenshot)

**Comment by bil-elmoussaoui** [comment]
I will take a look

**Comment by bil-elmoussaoui** [comment]
Fixed!

**Comment by varlesh** [comment]
Thx Bilal, all fine now!
