### ISSUE TITLE
Doesn't get real username/userhome when run with sudo

### ISSUE THREAD

**Issue by alex94puchades** [bil-elmoussaoui/Hardcode-Tray#27]
Maybe [this](https://stackoverflow.com/questions/10272784/how-do-i-get-the-users-real-uid-if-the-program-is-run-with-sudo) would work, it should check for SUDO_USER/SUDO_UID to check if run with sudo or getpwname otherwise.

**Comment by bil-elmoussaoui** [comment]
Thank you for reporting this, this should be fixed in the latest commit

**Comment by alex94puchades** [comment]
Only now it doesn't work for the root user xd Instead of checking for the uid, you could check for the SUDO_USER variable being present, and if not, fallback to getpwname

**Comment by bil-elmoussaoui** [comment]
Ops :P I forgot to remove ```username``` as i'm not using it anymore, can you try for the ```userhome``` using root user?

**Comment by alex94puchades** [comment]
Seems that sudo does not change $HOME var, so maybe this is a more elegant solution bash```sudo sh -c "echo $HOME"```

**Comment by alex94puchades** [comment]
I didn't make a commit because for simple fixes I find it a little overkill (all that git stuff xd) but if you want I could give it a try

**Comment by bil-elmoussaoui** [comment]
This is fixed now :+1: , feel free to report any other issues/bugs, thank you!
