### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by Freshman4754** [bil-elmoussaoui/Hardcode-Tray#270]
Traceback (most recent call last):
  File "script.py", line 25, in <module>
    from modules.data import DataManager
ImportError: No module named 'modules'

**Comment by bil-elmoussaoui** [comment]
How did you installed the script ?

**Comment by wa4557** [comment]
I get the same thing. Installed via ppa

**Comment by bil-elmoussaoui** [comment]
Well the ppa seem to not install the modules folder then...

**Comment by wa4557** [comment]
Ah ok, sure. I'll fix that

**Comment by wa4557** [comment]
Should be fixed next time the ppa is updated!

**Comment by Freshman4754** [comment]
AUR

**Comment by bil-elmoussaoui** [comment]
The aur package is outdated. I will update it later , you can try the manual installation script provided (see README)

**Comment by bil-elmoussaoui** [comment]
@Freshman4754 https://github.com/bil-elmoussaoui/Hardcode-Tray#manual-install I will update the AUR package tomorrow

**Comment by bil-elmoussaoui** [comment]
I've updated the AUR package, just run `yaourt -S hardcode-tray` (you might need to use `--force`) or just remove the older version and install it again. 
This should be fixed now!
