### ISSUE TITLE
Hangouts extension is working again :p

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#271]
The hangouts extension can be fixed again, i think the issue we had before wwas due to the permissions and as this is fixed now, everything is fixed :P  
I will push a fix soon !

**Comment by bil-elmoussaoui** [comment]
on master

**Comment by Feichtmeier** [comment]
Hm... strangely it is not fixed for me. The script works for everything except telegram and the chrome hangouts extension which stoped working after I ran the script. I can "repair" it in chrome though.
Telegram works but the icon isn't replaced

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier Which version are of Hardcode-Tray are you using? For Telegram, it seems that you're using Unity? if so, you must have a package missing... Because telegram falls back to Qt to draw tray icons if libappindicator is missing in your system. And we can't fix it for that case unless we do something like #297

**Comment by Feichtmeier** [comment]
I am using the version v3.6.5 from your ubuntu ppa.(ubuntu 16.04 unity)
I will try to install telegram via snap and see if that works

**Comment by bil-elmoussaoui** [comment]
Btw, for Hangouts, we had the same issue as you're reporting and after few fixes in our code it seems to work and i added Hangouts support back(at least for me). Can you try updating your Chrome/Chromium(based browser) to the latest version if it's possible?

**Comment by Feichtmeier** [comment]
I am using the most up to date chrome version I think. 
It is version Version 56.0.2924.87 (64-bit)

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier That's really sad :( i will try to investigate this! in the mean time you can revert only the latest changes done to hangouts using `hardcode-tray --revert --only hangouts`
I will add some type of config file that you can put on your .config folder with a blacklist of apps that you don't want to be fixed. This way, you don't have to revert hangouts everytime you fix your hardcoded icons.

**Comment by bil-elmoussaoui** [comment]
When you open telegram from terminal what's the output that you have ?

**Comment by Feichtmeier** [comment]
~/Telegram$ ./Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number

(Telegram:10080): Gtk-WARNING **: Failed to parse /home/frederik/.config/gtk-3.0/settings.ini: Die Schlüsselwertedatei enthält nicht die Gruppe »Settings«
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier Telegram seems to have some issues to detect libappindicator and fallback to Qt, which we can't sadly fix. You need to install the required running dependencies for Telegram in order to get it to work as expected on your system. 
For hangouts, i will see what i can do as soon as possible.
