### ISSUE TITLE
Error while applying icons for Google Play Music Desktop Player

### ISSUE THREAD

**Issue by orange-buffalo** [bil-elmoussaoui/Hardcode-Tray#277]
### Specifications
- Hardcode-Tray version : `3.6.3`
- Distribution : `Ubuntu 16.10, Plasma shell 5.8.5`
- Gtk version : `3.22.5-1ubuntu1~ubuntu16.10.1`
- Inkscape version : `0.91 r13725`
- Sni-qt version: `0.2.7+20161212~8~ubuntu16.10.1`
- Application name :  `Google Play Music Desktop Player`
- Application version : `4.0.5`

### Expected behavior and actual behavior
Expected - icons are applied successfully.
Actual - errors:
```
fixing failed with error:
        ** (inkscape:6738): WARNING **: File path "/usr/share/google-play-music-desktop-player/resources/build/assets/img/paused/main_tray_white_s.png" includes directory that doesn't exist.
fixing failed with error:
        ** (inkscape:6746): WARNING **: File path "/usr/share/google-play-music-desktop-player/resources/build/assets/img/playing/main_tray_white_s.png" includes directory that doesn't exist.
fixing failed with error:
        ** (inkscape:6754): WARNING **: File path "/usr/share/google-play-music-desktop-player/resources/build/assets/img/main_tray_white_s.png" includes directory that doesn't exist.
```

### Steps to reproduce the problem
1. Install [Google Play Music Desktop Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.0.5/google-play-music-desktop-player_4.0.5_amd64.deb)
2. Install [Papirus Icon Theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)
3. `hardcode-tray --theme Papirus-Dark --size 22 --apply`

**Comment by bil-elmoussaoui** [comment]
Fixed on master, you can use `hardcode-tray --update-git` and after that, just run the script again ;)

**Comment by orange-buffalo** [comment]
Works like a charm, thanks a lot for the prompt fix!

**Comment by bil-elmoussaoui** [comment]
You're welcome! Feel free to report any other issues/improvements :)
