### ISSUE TITLE
Lyricfier support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#278]
an other electron application :p

**Comment by varlesh** [comment]
It's this https://github.com/emilioastarita/lyricfier ?
Use tray?

**Comment by bil-elmoussaoui** [comment]
The icons are not hardcoded. They are under `/opt/lyricfier/resources/app/render/img/` 
and the icon is `tray-icon-mac.png`

**Comment by bil-elmoussaoui** [comment]
@varlesh btw, can you get hangouts tray icons support on Papirus?

**Comment by varlesh** [comment]
> @varlesh btw, can you get hangouts tray icons support on Papirus?

for chrome extension?

**Comment by bil-elmoussaoui** [comment]
Yes, it works like a charm :p

**Comment by varlesh** [comment]
oh, i see:
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/hangouts.json
but need add google-chrome path and ... if extension will be updated, we need again fix path for that?

**Comment by varlesh** [comment]
Maybe available electron app for hangouts?

**Comment by bil-elmoussaoui** [comment]
@varlesh for now, yeah :) but i will figure out how to get this works easily :)

**Comment by varlesh** [comment]
ok, i'm add hangouts

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/254
