### ISSUE TITLE
Yakyak support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#280]
Yakyak is an other electron application
(Hangouts)
Icons are under `/usr/share/yakyak/app/icons/`
Icons are 
- icon-read.png
- icon-unread.png

**Comment by varlesh** [comment]
i think better use icon names from hangouts for this app:
```
hangouts-available
hangouts-offline
hangouts-working
hangouts-notification
```

**Comment by bil-elmoussaoui** [comment]
It's what i'm going to do, don't worry ;)

**Comment by varlesh** [comment]
@bil-elmoussaoui You can show original icon hangouts-working? What it this? It's connecting status or ...?

**Comment by bil-elmoussaoui** [comment]
![icon_loading_44](https://cloud.githubusercontent.com/assets/7660997/21705949/880e1944-d3c3-11e6-8cb2-d29445b7b727.png)

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
hangouts added:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/08e1642d7a6d9ce26d0f88d4549e0a86c41e0861
@bil-elmoussaoui please add google-chrome path also

**Comment by bil-elmoussaoui** [comment]
Will do soon :) as i will have to add the stable,unstable and the beta version of chrome :p

**Comment by varlesh** [comment]
i don't know but maybe need add support for 3-d party apps (chromium based) for example opera or etc...

**Comment by bil-elmoussaoui** [comment]
I will take a look later ;) for now i will add only chrome and chromium
