### ISSUE TITLE
WeChat support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#281]
https://github.com/geeeeeeeeek/electronic-wechat

**Comment by varlesh** [comment]
on papirus already exist icons:
```
wechat-tray-white
wechat-tray-unread-white
```
also program have dark version icons for tray (but this not supported for papirus):
```
wechat-tray-black
wechat-tray-unread-black
```
original icons here:
https://github.com/geeeeeeeeek/electronic-wechat/tree/master/assets

**Comment by bil-elmoussaoui** [comment]
Fixed! Please don't user -black or -white on tray icon names :p just the tray icon

**Comment by varlesh** [comment]
@bil-elmoussaoui But other icons we add this option. Maybe we support single standard for this?
I think light/dark, black/white really not needed? because no body use dark icon for app if other tray icons light.
For example:
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/gpmdp.json

**Comment by bil-elmoussaoui** [comment]
I will take care of that! instead of having dark and light in the icon name i will add an other key with "is_dark": true/false

**Comment by varlesh** [comment]
But icon names and icons already exist on papirus... will be good if we use single standard for all

**Comment by varlesh** [comment]
i really not understand why this needed for us! For example you use numix > run hardcode-tray > icons fixed.. ok, you chnage icon theme to numix-dark > run again hardcode-tray - that's all. All worked, all fine!
Why needed this option really? It's сomplicates the implementation of us!

**Comment by varlesh** [comment]
I'm confused :)

**Comment by varlesh** [comment]
Why google-play-music-desktop- player have light/dark but wechat not?

**Comment by bil-elmoussaoui** [comment]
because i'm not the one who added google-play-music ;)

**Comment by varlesh** [comment]
yes we add gpmdp, but now all icons have different names, it's confused me, other designers, users and etc... we need use single standard for all icons

**Comment by bil-elmoussaoui** [comment]
Just don't add -dark -light icons at all. I will fix all of that pretty soon :) sorry for that!

**Comment by varlesh** [comment]
i'm support only light icons, because by default mostly apps use light icons for tray (mostly DE's by default hav dark panel or Ubuntu as standard)

**Comment by varlesh** [comment]
> Just don't add -dark -light icons at all. I will fix all of that pretty soon :) sorry for that!

Fine, we need open new issue and rename all icons on icon theme and database

**Comment by varlesh** [comment]
fixed on papirus
