### ISSUE TITLE
Whatsapp Desktop support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#282]
https://github.com/bcalik/Whatsapp-Desktop

**Comment by varlesh** [comment]
On Papirus already exist:
```
whatsie-tray
whatsie-tray-attention
```

**Comment by bil-elmoussaoui** [comment]
It's an other whatsapp electron app! i will use whatsapp-tray and whatsapp-tray-attention, you can create symlinks for them on Papirus once it's done

**Comment by varlesh** [comment]
on papirus already exist tray icon `whatsapp-tray`:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/01a31af632a41df20ffda2c500d9b157bcf49232

**Comment by KottV** [comment]
Hi.
The original app doesn't exist anymore, here the successor: https://github.com/Enrico204/Whatsapp-Desktop
And it uses icons from /opt/whatsapp-desktop/resources/app/assets/icon
