### ISSUE TITLE
Spotify Electron

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#283]
https://github.com/Quacky2200/Spotify-Web-Player-for-Linux

**Comment by varlesh** [comment]
omg, please stop ;) i'm not have more RAM

**Comment by bil-elmoussaoui** [comment]
I just took a look at the most starred projects on Github ;) you don't need to add all those icons on Papirus, just the ones asked by the users ;)

**Comment by bil-elmoussaoui** [comment]
Fixed
