### ISSUE TITLE
No icons being replaced

### ISSUE THREAD

**Issue by eldelacajita** [bil-elmoussaoui/Hardcode-Tray#288]
### Specifications
- Hardcode-Tray version : `v3.6.4`
- Distribution : `Ubuntu Gnome - 16.04.1 LTS 64-bit`
- Gtk version : `3.18.9-1ubuntu3.1`
- Inkscape version : `Inkscape 0.91 r13725`
- Cairo version : `` not installed, AFAIK
- Sni-qt version: `0.2.7+20161212~8~ubuntu16.04.1`
- Application name :  `any`
- Application version : `any`
- I am also using:
-- 'Topicons Plus' shell extension
-- 'Dash to panel' shell extension
-- Paper GTK+ theme
-- Papirus icon theme
-- Paper cursor theme

### Expected behavior and actual behavior
Running 'hardcode-tray' should detect and apply the script to any relevant apps, but it doesn't seem to change anything in my system.

### Steps to reproduce the problem
1. Run 'hardcode-tray'. This is the text it displays: 

```
Your indicator icon size is : 22
Your current icon theme is : Papirus-Light
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : All
```
2. After entering '1', it shows this:

```
Applying now..

Chromium            [####################....................] 1/2 50.0%
Google Chrome       [########################################] 2/2 100.0%

Done, Thank you for using the Hardcode-Tray fixer!
```
I have no Chrome/Chromium tray icon for some reason, so I can't test if it is working. 

Other apps don't seem to be detected. For example, I have Telegram, Mega, Insync and Dropbox running and the icons remain the same.

3. Running 'hardcode-tray --only dropbox' or the same for other programs gives this:

```
Applying now..

No apps to fix! Please report on GitHub if this is not the case
```

**Comment by bil-elmoussaoui** [comment]
In order to get, google chrome or chromium tray icons to work you will need to install Hangouts extensions (which will enable the extension of the browser too). I don't know if it's possible to enable it without installing hangouts :p 

Insync, should not have a problem with tray icons. For the rest, we might need the icons path or the installation path of those applications. 
For Dropbox : Open Nautilus in your home folder, click on CTRL +H, and look for a folder named .dropbox-dist. Under this folder you will find the icons of it. If it's not the case, you might have to check in /opt or /usr/share. Otherwise, if you can give me the link of the deb package i can take care of that.
For Telegram, you might need to install libappindicator in order to make it using a Gtk instead of Qt to draw the tray icons. By default Qt icons are stored in /tmp folder, can you check if they do exists once you open Telegram in your case?
And for MegaSync, it's either that the application is built using Qt5 which in this case canno't be fixed :( as we couldn't figure out yet how to do that. If it's built using Qt4, it must be the patched version of sni-qt that have not been installed correctly. Can you check if you will find any folder in  /tmp/ with the tray icons of megasync? if it's the case, can you send me a screenshot.

**Comment by bil-elmoussaoui** [comment]
@eldelacajita ping?

**Comment by eldelacajita** [comment]
I'm back! Here is what I got: 

- Telegram: it's now working, after a reboot. 
- Dropbox: the files are where you said, under `/home/user/.dropbox-dist/dropbox-lnx.x86_64-16.4.30/images/hicolor/16x16/status`. I am not sure if the icon I'm seeing now is the replaced one. Is it?

![captura de pantalla de 2017-01-10 21-04-22](https://cloud.githubusercontent.com/assets/2880679/21822869/3667fccc-d779-11e6-999e-d3bc36b4fb4c.png)

- Insync: the icon is not showing up, but it wasn't before either, so it seems an unrelated issue.
- MegaSync: I have found an empty folder here `/tmp/sni-qt_megasync_3083-k4Lhi8/icons`. Is that of any help?

**Comment by bil-elmoussaoui** [comment]
@eldelacajita I've pushed a new version that should fix your issue with MegaSync, just use `hardcode-tray --update-git` and run the script again. Restart MegaSync and see if it works! 
For Dropbox, can you paste a screenshot of the content of this folder? It seems that Hardcode-tray does not detect the dropbox icons path

**Comment by eldelacajita** [comment]
BTW, this bug is no longer true, as some icons were indeed replaced. If you prefer we can close this one and open a new one just for Megasync. Just to keep things tidy.

**Comment by bil-elmoussaoui** [comment]
@eldelacajita is the dropbox issue fixed too?

**Comment by eldelacajita** [comment]
Not yet, just saw your reply after my last comment, sorry. 

This is the content of the `/home/user/.dropbox-dist/dropbox-lnx.x86_64-16.4.30/images/hicolor/16x16/status` folder. 

![captura de pantalla de 2017-01-10 21-25-32](https://cloud.githubusercontent.com/assets/2880679/21823499/841818e2-d77b-11e6-870f-9532ded091a4.png)

I tried your command for updating, but I get a 'command not found' error: `hardcode-tray: no se encontró la orden`. Actually, writing `hardcore-tray` in the terminal is not working at all now. It is still installed, though. This version: `3.5.2.1~682~ubuntu16.04.1`

**Comment by bil-elmoussaoui** [comment]
Ok, i'm going to add some logging information in order to get this right ;)
Can you go to `cd /opt/Hardcode-Tray` and then run `sudo -E python3 script.py --only megasync`

**Comment by bil-elmoussaoui** [comment]
Under this folder /home/user/.dropbox-dist/ you have a VERSION file. What's the content of it?

**Comment by bil-elmoussaoui** [comment]
I've added some debug options. Run the script again using `sudo -E python3 script.py --only dropbox --debug`

**Comment by eldelacajita** [comment]
> Under this folder /home/user/.dropbox-dist/ you have a VERSION file. What's the content of it?
17.4.33

> Can you go to cd /opt/Hardcode-Tray and then run sudo -E python3 script.py --only megasync

This is what I got:

```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : megasync
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Megasync            [########################################] 4/4 100.0%

Done, Thank you for using the Hardcode-Tray fixer!
```
Megasync icon remains the same, though. 

> I've added some debug options. Run the script again using sudo -E python3 script.py --only dropbox --debug

It shows a man page and says `Hardcode-Tray: error: unrecognized arguments: --debug`. Before doing this, I updated, and the sni-qt and sni-qt:i386 packages were upgraded, but not the hardcore-tray one. Is that right?

Thanks for your patience ;)

**Comment by bil-elmoussaoui** [comment]
sni-qt updates automatically whenever we push something new to github. Which is not the case with hardcode-tray as some commits might break your system (not really, but might break some apps instead of fixing them)
The debug version was just added. You should update to the github version using `hardcode-tray --update-git` first, which will download the latest version of hardcode-tray that includes the debug flags

**Comment by bil-elmoussaoui** [comment]
Well, i've got what causes this issue on your dropbox installation. The version file does not containt the right value; Either you change it manually to `16.4.30` or use `hardcode-tray --only dropbox --path home/user/.dropbox-dist/dropbox-lnx.x86_64-16.4.30/images/hicolor/16x16/status/`
which will fix your icons ;)
anyway i will push a better fix for dropbox right now!

**Comment by eldelacajita** [comment]
Right! As I was getting an 'unknown command' error everytime I run `hardcode-tray`, I just uninstalled and reinstalled it, run the --update-git option (which went fine) just to be sure, and then tried the `sudo -E python3 script.py --only dropbox --debug` script again. 

Now I got this: 

```
[DEBUG] - 2017-01-10 23:52:47 - new application Dropbox path : /home/jt/.dropbox-dist/ 
[DEBUG] - 2017-01-10 23:52:47 - new application Dropbox path : /home/jt/.dropbox-dist//images/hicolor/16x16/status/
No apps to fix! Please report on GitHub if this is not the case
```

I tried both changing the version file or using `hardcode-tray --only dropbox --path home/user/.dropbox-dist/dropbox-lnx.x86_64-16.4.30/images/hicolor/16x16/status/` and still got the 'no apps to fix!' message. 

BTW, just noticed that the debug output is omitting part of the actual path, maybe that has something to do with it.

**Comment by bil-elmoussaoui** [comment]
is `user` you real username? if not, you should use `hardcode-tray --only dropbox --path home/YOURREALUSERNAME/.dropbox-dist/dropbox-lnx.x86_64-16.4.30/images/hicolor/16x16/status/` instead ;)

**Comment by eldelacajita** [comment]
Yes! I was replacing 'user' with my actual username all this time, I promise xD

**Comment by bil-elmoussaoui** [comment]
Is it working now? For megasync, can you run `megasync --debug` and paste the output here so i can see if it's using qt4 or qt5?

**Comment by rpbaptist** [comment]
I have the same issue with dropbox-lnx.x86_64-17.4.33.

Choosing the path didn't work. I think this happened after a dropbox update as it was working before. I just copied the files manually now.

**Comment by bil-elmoussaoui** [comment]
I will see what can i do about this tomorrow ;)

**Comment by bil-elmoussaoui** [comment]
You can now fix it using `--path` i will fix the autodetecting of the path as soon as i can

**Comment by bil-elmoussaoui** [comment]
The dropbox issue is now fixed on master. You can either  wait for a new version or update to the git version using `hardcode-tray --update-git`
@eldelacajita if you still have an issue with MegaSync please open a new issue with more detailed information; like the application version and also try running `megasync --debug` in order to help us check whether the application in your case is using Qt4 or Qt5. Qt5 apps are not supported see #293

**Comment by JanSimek** [comment]
I am using Arch with hardcode-tray 3.6.5 and my dropbox icon looks like this: ![dropbox icon](http://i.imgur.com/75cnICQ.png)

```
$ hardcode-tray --debug --only dropbox

Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Adwaita
Svg to png functions are : Enabled
Conversion tool : RSVGConvert
Applications will be fixed : dropbox
1 - Apply
2 - Revert
Please choose: 1
Applying now..

[DEBUG] - 2017-01-21 18:33:09 - new application Dropbox path : /home/jsimek/.dropbox-dist/
[DEBUG] - 2017-01-21 18:33:09 - new application Dropbox path : /home/jsimek/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
No apps to fix! Please report on GitHub if this is not the case
```

Was it fixed for you @eldelacajita ?

**Comment by bil-elmoussaoui** [comment]
@JanSimek You should use git version. Try using this `hardcode-tray --update-git` and after that `hardcode-tray --only dropbox --apply --debug`

**Comment by JanSimek** [comment]
I was already using hardcode-tray-git from AUR, but I did as you said and even tried manually installing from git, but I got the same result unfortunately. 

```
[jsimek@localhost Hardcode-Tray]$ ./install.sh --g
Downloading Hardcode-Tray ...
Cloning the repository...
Cloning into 'Hardcode-Tray'...
remote: Counting objects: 4087, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 4087 (delta 7), reused 0 (delta 0), pack-reused 4065
Receiving objects: 100% (4087/4087), 723.94 KiB | 353.00 KiB/s, done.
Resolving deltas: 100% (2747/2747), done.
Creating symbolic link..
Hardcode-Tray was updated to git version successfully.
You can run the script using 'hardcode-tray'
[jsimek@localhost Hardcode-Tray]$ hardcode-tray --only dropbox --apply --debug

Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Adwaita
Svg to png functions are : Enabled
Conversion tool : RSVGConvert
Applications will be fixed : dropbox
Applying now..

[DEBUG] - 2017-01-22 10:55:58 - new application Dropbox path : /home/jsimek/.dropbox-dist/
[DEBUG] - 2017-01-22 10:55:58 - new application Dropbox path : /home/jsimek/.dropbox-dist/dropbox-lnx.x86_64-17.4.33/images/hicolor/16x16/status/
No apps to fix! Please report on GitHub if this is not the case
```

**Comment by bil-elmoussaoui** [comment]
@JanSimek It's not an issue anymore, in your first comment the dropbox path was not detected and now it is! Your current theme is not detected correctly. As you can see in the information provided by the script. `Your current icon theme is : Adwaita` I assume you're using Papirus? If it's the case just use `hardcode-tray --theme Papirus --only dropbox --apply` which will override the automatically detected theme. 
I can't do anything about it :( i mean fixing the dete

**Comment by bil-elmoussaoui** [comment]
@JanSimek  https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/FAQ#default-theme-is-not-correctly-detected
