### ISSUE TITLE
Vivaldi icon support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#291]
Vivaldi is based on chromium too! and so it uses a tray icon. i tried to use the same icon name as chromium or google-chrome but it does not work.
@wa4557 do you still have that old code that we used to extract pak files? so i can take a look at the exact file name! Thanks

**Comment by varlesh** [comment]
icon name?

**Comment by bil-elmoussaoui** [comment]
Fixed! The icon name is `vivaldi-tray`

**Comment by bil-elmoussaoui** [comment]
@varlesh Have you tried the new backup/revert system? I'm not sure if it's that good! if you have any ideas to improve it..

**Comment by varlesh** [comment]
oh, no i'm not tried... maybe later, I'm now draw icons ;)
