### ISSUE TITLE
simplescreenrecorder

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#292]
It uses qt icons on my system, seem to be compiled using qt4 (as the folder is on /tmp)

**Comment by varlesh** [comment]
ssr use icons for tray from icon theme, not hardcoded

**Comment by bil-elmoussaoui** [comment]
Ah never mind :p

**Comment by bil-elmoussaoui** [comment]
@varlesh it's a qt application and uses sni-qt;) just tested that on elementary. If you already provide those icons, can you please give me the icon names?

**Comment by bil-elmoussaoui** [comment]
The application do create a tmp file as all the sni-qt applications but it uses icons from theme. It's something we can change from sni-qt which will fix some broken icons for Numix theme (it uses the same indicator name as the icon name)

**Comment by varlesh** [comment]
numix have icons for ssr:
![image](https://cloud.githubusercontent.com/assets/8083855/21922475/32323152-d988-11e6-9bfb-189027f31a2d.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh I know, but the application never use them. It uses the circle icon instead
![capture du 2017-01-13 09-21-26](https://cloud.githubusercontent.com/assets/7660997/21922970/ba912ef2-d971-11e6-9d5c-db13822b1865.png)

**Comment by varlesh** [comment]
need icon `simplescreenrecorder-panel`

**Comment by varlesh** [comment]
suffix **-panel** worked for Qt-apps, for example this worked with vlc, qbittorrent and etc...

**Comment by varlesh** [comment]
with papirus:
![image](https://cloud.githubusercontent.com/assets/8083855/21923104/89f2720a-d98b-11e6-98df-58e39017fce5.png)

**Comment by bil-elmoussaoui** [comment]
I know it works with Papirus, but it won't work correctly with Numix as Numix separate the base theme from the application theme

**Comment by varlesh** [comment]
open request for new icon for Numix - `simplescreenrecorder-panel`

**Comment by varlesh** [comment]
Why need draw code if easier draw icon?!

**Comment by bil-elmoussaoui** [comment]
I think you misunderstood everything. Those icons already exists on Numix; We have renamed them to `renamed-xxx` as that does not work correctly. Check it by yourself and you will understand https://github.com/numixproject/numix-icon-theme/issues/190

**Comment by varlesh** [comment]
This icon not exist:
https://github.com/numixproject/numix-icon-theme/tree/master/Numix/22/panel

**Comment by varlesh** [comment]
On Papirus:
```
simplescreenrecorder-panel
simplescreenrecorder-paused
simplescreenrecorder-recording
```

On Numix:
```
simplescreenrecorder-paused
simplescreenrecorder-recording
```

**Comment by bil-elmoussaoui** [comment]
@varlesh https://github.com/numixproject/numix-icon-theme/blob/master/Numix/24/status/renamed-simplescreenrecorder.svg

**Comment by varlesh** [comment]
omg... i mean **QSystemTrayIcon** if available icon with suffix **-panel** > this icon used for PANEL only.
Create symlink **simplescreenrecorder-panel** on Numix and check this.
renamed-simplescreenrecorder.svg it's will be  simplescreenrecorder.svg, but i mean simplescreenrecorder-panel... Suffix -panel worked for QSystemTrayIcon only... but maybe for not all apps

**Comment by varlesh** [comment]
It's worked for Papirus why not for Numix? I have too 22px and 24px simplescreenrecorder icon
![image](https://cloud.githubusercontent.com/assets/8083855/21924802/0e67fbf6-d994-11e6-9739-e459f76d60f5.png)

**Comment by bil-elmoussaoui** [comment]
Try it by yourself using Numix theme and you will what i'm talking about ;) Anyway this won't change anything for Papirus as you have those icons and it works just fine

**Comment by varlesh** [comment]
it's problem Numix, but not harcode-tray... they must add new icon
It's worked for Numix too:
![image](https://cloud.githubusercontent.com/assets/8083855/21925006/ebed0fe8-d994-11e6-9e29-bfb3526847dd.png)

**Comment by bil-elmoussaoui** [comment]
As i said before, check the issue link i gave you ;)
![capture d ecran de 2017-01-13 10-36-31](https://cloud.githubusercontent.com/assets/7660997/21925108/3b17057e-d97c-11e6-9c14-528fb6b07e3d.png)
As you can see it's not working even if i have added those icons from an old version of Numix and updated the icon cache

**Comment by varlesh** [comment]
Maybe it's Gnome bug? Because on Unity this working

**Comment by bil-elmoussaoui** [comment]
It's not a gnome bug, Gnome does not draw tray icons. And It's a Qt bug, because it does not get the right icon name(not follow the Inherits in the index.theme file). So if you copy the panel icons and move them to an other theme for example hicolor and you use Papirus that inherits from that theme those icons won't work as expected. The guys from Numix did tests with almost every DE out there and we had to rename those icons because they just don't work. Also on some desktops if you resize the dock to a a very small size the tray icons will be used instead of the application icon (which is another bug ;)) Anyway, if you need information about this, read my link! otherwise, this will stay open until i figure out either it's fixable using sni-qt or not

**Comment by bil-elmoussaoui** [comment]
Shouldn't happen anymore once my PR is merged upstream, the new icon name will be `simplescreenrecorder-indicator`
