### ISSUE TITLE
Megasync

### ISSUE THREAD

**Issue by eldelacajita** [bil-elmoussaoui/Hardcode-Tray#296]
### Specifications
- Hardcode-Tray version : `v3.6.4`
- Distribution : `Ubuntu Gnome - 16.04.1 LTS 64-bit`
- Gtk version : `3.18.9-1ubuntu3.1`
- Inkscape version : `Inkscape 0.91 r13725`
- Cairo version : `` not installed, AFAIK
- Sni-qt version: `0.2.7+20161212~8~ubuntu16.04.1`
- Application name :  `any`
- Application version : `any`
- I am also using:
-- 'Topicons Plus' shell extension
-- 'Dash to panel' shell extension
-- Paper GTK+ theme
-- Papirus icon theme
-- Paper cursor theme

### Expected behavior and actual behavior
Megasync tray icon should change after running `hardcode-tray`. It doesn't.

### Steps to reproduce the problem
1. Run `hardcode-tray`. It seems to apply the changes to megasync, but the icons remain the same: 

`Chromium            [#######.................................] 1/6 16.7%`
`Google Chrome       [#############...........................] 2/6 33.3%`
`Megasync            [########################################] 6/6 100.0%`

2. Running `megasync --debug` I get the attached output.

[megasync-log.txt](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/705851/megasync-log.txt)

**Comment by bil-elmoussaoui** [comment]
@wa4557  Do you have any idea why this message is shown on his log? 
```bash
09:01:34 (warn):  QT Warning: "sni-qt/4211" WARN  10:01:34.452 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
```

**Comment by wa4557** [comment]
no not really. Not sure this is related to the icon not shown :/

**Comment by bil-elmoussaoui** [comment]
@eldelacajita What's the version of megasync you're using? and from you've got it /download it

**Comment by bil-elmoussaoui** [comment]
@wa4557 https://bugs.dogfood.paddev.net/ubuntu/+source/sni-qt/+bug/1168554 this is related to sni-qt :( and in my case it forces the icons to use non themed icons. Using Archlinux, Insync is not able to start at all (got that from the logs)

**Comment by bil-elmoussaoui** [comment]
Ok, this happens only when you're using Gnome!

**Comment by eldelacajita** [comment]
@bil-elmoussaoui I have the latest version downloaded from the [website](https://mega.nz/#sync).

Version is `MEGAsync v2.9.10 (2c928)`

**Comment by wa4557** [comment]
Ok, I guess it means that some function call fails and never reaches the method that looks for the custom icons.

**Comment by bil-elmoussaoui** [comment]
@wa4557 it seems that the dbus service used to draw icons is not available somehow on Gnome. I've asked on iirc and still waiting for an answer on how we can fix this; anyway it's a sni-qt issue!

**Comment by bil-elmoussaoui** [comment]
@wa4557 got some good news about this! it seems that the dbus service `"org.kde.StatusNotifierWatcher"` was replaced all over the distros in order to follow org.freedesktop. The new dbus service is  `org.freedesktop.StatusNotiferItem` Compiling when i replace the dbus service name works just fine, no issues but the icons does not work :p

**Comment by infuerano** [comment]
so i am using Mega sync 3.0.1 
 i have tried "hardcode-- tray" and tried " hardcode tray only" command but it doesn't fix the problem for skype and MEGAsync. i am getting " hardcode-tray --only Mega
[sudo] password for zeus: 
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : GnomeYosemiteIcons-master
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : mega
1 - Apply
2 - Revert
Please choose: 1
Applying now..

No apps to fix! Please report on GitHub if this is not the case"

i am using linux mint 18.1  MATE

**Comment by bil-elmoussaoui** [comment]
@infuerano You need to use `hardcode-tray --only megasync` and not `hardcode-tray --only Mega`. It's not the same issue at all...

**Comment by infuerano** [comment]
@bil-elmoussaoui   sorry for so late reply. i have performed the  atep and what i am geting is 

hardcode-tray --only megasync
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
The detected desktop environement : Mate
Your current icon theme is : GnomeYosemiteIcons-master
Conversion tool : Inkscape
Applications will be fixed : Megasync
1 - Apply
2 - Revert
Please choose: 1
Applying now..

No apps to fix! Please report on GitHub if this is not the case

**Comment by bil-elmoussaoui** [comment]
@infuerano The icon theme that are you using doesn't support Hardcode-Tray. Either you report that upstream or you can use an icon theme to fix your Megasync icons by adding `--theme Numix` or `--theme Papirus`

**Comment by akyag** [comment]
Is there a chance of getting this fixed? I didnt want to create another similar topic, but I am getting the following result after I applied the latest script. 
 
![screenshot from 2017-05-26 01-42-55](https://cloud.githubusercontent.com/assets/7376589/26478959/98681d42-41ed-11e7-8e8e-8d4b09ecca95.png)

Hardcode-Tray version : v3.8.1
Distribution : Fedora 25 x64
Gtk version : 3.22.3

**Comment by bil-elmoussaoui** [comment]
@akyag i only work on Hardcode-tray on my free time...

**Comment by akyag** [comment]
I completely understand. Just that the script said these were fixed too and I can see the icons for these apps in the screenshot in this repo. So I am just wondering if all of this is because of the issue mentioned in this thread or is it just on my end.

**Comment by bil-elmoussaoui** [comment]
It's the same issue, sni-qt doesn't work correctly on gnome. And my C/C++ skills are not that good to fix it easily(the same issue for hplip)
Hexchat should be fixed, if not it's must be that Papirus doesn't have that icon.
And what's that ugly lock icon?

**Comment by akyag** [comment]
That's keepass.

**Comment by bil-elmoussaoui** [comment]
Agh, i don't know if it's possible to fix it but you can open a new issue for that and i will see what can i do =)

**Comment by bil-elmoussaoui** [comment]
I spent some time trying to figure out how to fix this, i've tried to patch sni-qt in order to get it to work with freedesktop interface but it seems to be broken on ubuntu :(((( 
Anyway, i will keep this little snippet here that was pretty helpful to test if it works or not without having to open an application and close it all over again 
```python
from PySide.QtGui import QApplication, QIcon, QSystemTrayIcon
import sys, signal

app = QApplication(sys.argv)
QIcon.setThemeName('Numix')
icon = QIcon.fromTheme('teamviewer-indicator')
tray = QSystemTrayIcon(icon)
tray.show()
signal.signal(signal.SIGINT, signal.SIG_DFL)

for path in QIcon.themeSearchPaths():
        print("%s/%s" % (path, QIcon.themeName()))

sys.exit(app.exec_())
```
@wa4557 The code might be of a help for you in order to get the icons from the theme directly for sni-qt :+1:

**Comment by varlesh** [comment]
It's not Papirus problem, because all this icons available on theme:
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/keepassx.json
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/hp-indicator.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/hexchat-fileoffer.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/hexchat-highlight.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/hexchat-indicator.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/hexchat-message.svg

**Comment by bil-elmoussaoui** [comment]
@varlesh It's an issue with Gnome & sni-qt

**Comment by varlesh** [comment]
@bil-elmoussaoui  Ok :) @akyag Maybe need install  and configure Qt5ct on your system? Also for right work need SVG's libraries for Qt-apps - libqt4-svg and libqt5svg5

**Comment by varlesh** [comment]
i'm extract binary file and open on ghex .rodata. 
On source code i see this:
```
QCheckBox::indicator {
     width: 24px;
     height: 24px;
	 subcontrol-position:  center;
 }


  QCheckBox::indicator:checked
  {
    image: url(://images/tray_play_ico.png);
  }
QCheckBox::indicator:checked:hover
  {
    image: url(://images/tray_play_over_ico.png);
  }
  QCheckBox::indicator:unchecked
  {
    image: url(://images/tray_pause_ico.png);
  }
QCheckBox::indicator:unchecked:hover
  {
    image: url(://images/tray_pause_over_ico.png
```
Maybe it's help create patch or another method for change tray icons on Qt5-apps

**Comment by bil-elmoussaoui** [comment]
One of the issues about supporting qt5 apps is that there's no way for us to know if it's a qt5 or a qt4 app...

**Comment by varlesh** [comment]
Mega maybe fix this on upstream.
![2017-07-18 18-02-52](https://user-images.githubusercontent.com/8083855/28321119-6cf7d5ce-6be3-11e7-8196-fc74cd68ea03.png)

**Comment by bil-elmoussaoui** [comment]
Until then we should find a solution for other qt apps :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed in the latest release of MegaSync; the icons are not hardcoded anymore

**Comment by hxss** [comment]
@bil-elmoussaoui 

on xfce megasync dont use new icons. Hardcode-tray said that mega-icon changed, but megasync still use default icon.
```
# sudo hardcode-tray --apply
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..

Megasync            [############........................] 1/3 33.3% 0.00s
Telegram            [########################............] 2/3 66.7% 1.87s
Vivaldi             [####################################] 3/3 100.0% 2.24s
Took 4.10s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```
![image](https://user-images.githubusercontent.com/17298149/33517977-5269a3da-d7af-11e7-8134-ecb40c0fda76.png)
I was try mega [from aur](https://aur.archlinux.org/packages/megasync/) and now install megasyng [from official site](https://mega.nz/sync).

4.13.12-1-ARCH
megasync 3.5-1
Papirus-icons
[sni-qt-patched-git r.-1](https://aur.archlinux.org/packages/sni-qt-patched-git/)

**Comment by bil-elmoussaoui** [comment]
Have you used hardcode tray?

**Comment by ikurek** [comment]
@bil-elmoussaoui Yes, i ran 'sudo hardcode-tray', but I'd didn't detect megasync, so I tried 'sudo hardcode-tray --only megasync', still without success.

**Comment by bil-elmoussaoui** [comment]
Please send me the log files. They are on /tmp/Hardcode-Tray

**Comment by varlesh** [comment]
@ikurek Megasync not hardcoded anymore! What you doing? XFCE have bugs with some tray-apps icons -  it's happened because some OS compiled xfce4-session package without flag `--disable-legacy-sm` . See this for more info: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/549
And this: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/943

**Comment by varlesh** [comment]
Also install needed libs `libqt5svg5` and `libqt4-svg` (it's deb-packages names, but i think you found this on manjaro repos)

**Comment by ikurek** [comment]
@bil-elmoussaoui I'm attaching the logs
[11-01-2018_10-58-22.log](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1622054/11-01-2018_10-58-22.log)
[11-01-2018_10-59-37.log](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1622055/11-01-2018_10-59-37.log)

@varlesh I'll check If Manjaro uses this flag and report soon

**Comment by hxss** [comment]
@ikurek Hi. If you use qt5ct, you need to disable it when running megasync. And you steel need to hardcode icons into hicolor theme. See [here](https://github.com/meganz/MEGAsync/issues/149#issuecomment-354794215) my solution.

**Comment by ikurek** [comment]
@hxss Yeah, that worked, so it was an XFCE bug after all. Thank you all for help.
