### ISSUE TITLE
google-chrome is not detected

### ISSUE THREAD

**Issue by ebeem** [bil-elmoussaoui/Hardcode-Tray#298]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Ubuntu 16.04`
- Gtk version : `2.0, 3.0`
- Inkscape version : `0.91 r13725`
- Sni-qt version: `0.2.8-0~81`
- Application name :  `google-chrome`
- Application version : `55.0.2883.87`

### Expected behavior and actual behavior
google chrome is not detected as an installed app, /opt/google/chrome
note: I do have 'resources.pak' for sure

after debugging, I found out that it detects it as installed and add it to the installed apps list, but at some point, it's kind of discarded, output:

Megasync                     [####....................................] 4/43 9.3%
My Weather Indicator   [#####################...................] 23/43 53.5%
Skype                           [##################################......] 37/43 86.0%
Teamviewer                  [########################################] 43/43 100.0%

I modified the code so chrome is added to the list, the output:

Google Chrome             [........................................] 0/43 0.0%
Megasync                      [####....................................] 4/43 9.3%
My Weather Indicator    [#####################...................] 23/43 53.5%
Skype                            [##################################......] 37/43 86.0%
Teamviewer                   [########################################] 43/43 100.0%

but the icon didn't change, I think there is a problem with the detection

### Steps to reproduce the problem
1. install chrome using the .deb package or repository
2. execute 'hardcode-tray --apply'

**Comment by bil-elmoussaoui** [comment]
Which theme are you using? the application is detected by the theme you're using does not have a proper tray icon for Google chrome

**Comment by ebeem** [comment]
I use Numix-Circle, I think it does provide an icon right?

**Comment by bil-elmoussaoui** [comment]
Yeah it does, but are you using the latest version of both Numix Circle and Numix icon theme(the base theme) ? Just go to `/usr/share/icons/Numix` and look for `google-chrome-tray`

**Comment by ebeem** [comment]
ops, now I feel stupid, sorry bro, my bad.
It's as you said, the Numix icons were not updated, I performed an update and everything works fine now

Thank you so much!!

**Comment by bil-elmoussaoui** [comment]
Not a problem! Feel free to open new issues if you have any problem in the future ;)
