### ISSUE TITLE
Spotify icon not fixed

### ISSUE THREAD

**Issue by dslul** [bil-elmoussaoui/Hardcode-Tray#30]
Everything on the terminal seems to go fine, however the Spotify tray icon is still the original one.

**Comment by bil-elmoussaoui** [comment]
Which icon theme are you using? And can you give more informations about the version of spotify?

**Comment by bil-elmoussaoui** [comment]
Try installing ```inkscape``` as we use it to convert ```.svg``` icons to ```.ico``` in spotify!

**Comment by dslul** [comment]
Perfect, now it works fine!

**Comment by bil-elmoussaoui** [comment]
Thank you for reporting this
