### ISSUE TITLE
[ERROR]  b"chmod:

### ISSUE THREAD

**Issue by KottV** [bil-elmoussaoui/Hardcode-Tray#304]
### Specifications
- Hardcode-Tray version : `git`
- Distribution : `openSUSE TW`
- Gtk version : `2.24.31 and 3.22.6`
- Inkscape version : `0.91`
- Cairo version : `1.15.4`
- Sni-qt version: `git`
- Application name :  `all sni-qt based`
- Application version : `latest`

### Expected behavior and actual behavior
added theme icons in ~/.local/share/sni-qt/icons/<app>/<size>

```
kv@Kot:~/src/Hardcode-Tray> ./hardcode-tray --theme Papirus-Light -o tomahawk 
[sudo] ?????? ??? root: 
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: ?? ??????? ???????????? ?: Connection refused

(script.py:4717): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Light
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : tomahawk
1 - Apply
2 - Revert
Please choose: 1
Applying now..

[ERROR] - 2017-01-23 14:53:56 - b"chmod: \xd0\xbd\xd0\xb5\xd0\xb2\xd0\xbe\xd0\xb7\xd0\xbc\xd0\xbe\xd0\xb6\xd0\xbd\xd0\xbe \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c \xd0\xbf\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x81\xd1\x88\xd1\x83\xd1\x8e \xd1\x81\xd0\xb8\xd0\xbc\xd0\xb2\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x83\xd1\x8e \xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd1\x83 'home/kv/.local/share/sni-qt/icons/tomahawk/22/ab2668bcbd200f43239986abd17cb459.svg'\n"
Tomahawk            [########################################] 1/1 100.0%

Done, Thank you for using the Hardcode-Tray fixer!
```
### Steps to reproduce the problem
1.  Run hardcode-tray for some sni-qt application (skype, tomahawk)

**Comment by bil-elmoussaoui** [comment]
Does it happen with skype too or just Tomahawk?

**Comment by KottV** [comment]
with skype too
i've selected tomahawk, cause it has just one icon
skype error output for every icon is huge

**Comment by bil-elmoussaoui** [comment]
Sorry but i can't really reproduce your issue :( I will add more debugging informations in few seconds! I will let you know once it's done so you can give me more information..

**Comment by bil-elmoussaoui** [comment]
@KottV Done! Please update to git version and try again, this should help me debugging your issue!

**Comment by KottV** [comment]
```
kv@Kot:/> LANG=C
kv@Kot:/> hardcode-tray --theme Papirus-Light -o tomahawk 
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(script.py:16593): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Light
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : tomahawk
1 - Apply
2 - Revert
Please choose: 1
Applying now..

[ERROR] - 2017-01-23 15:43:36 - chmod: cannot operate on dangling symlink 'home/kv/.local/share/sni-qt/icons/tomahawk/22/ab2668bcbd200f43239986abd17cb459.svg'
: execute in /opt/Hardcode-Tray/modules/utils.py:113
Tomahawk            [########################################] 1/1 100.0%

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by bil-elmoussaoui** [comment]
Something is not working correctly in your case :o your home path does not start with "/"?? 
Do you have any icon here `/home/kv/.local/share/sni-qt/icons/tomahawk/22/`? The output of this would be good `cd /home/kv/.local/share/sni-qt/icons/tomahawk/22/ && ls -la `

**Comment by bil-elmoussaoui** [comment]
I forced having `/` at the beginning of the home path. This should do fix your issue ;)

**Comment by KottV** [comment]
i firstly renamed /home/kv/.local/share/sni-qt/ to sni-qt_
so there is now such dir

 echo $HOME
/home/kv

**Comment by bil-elmoussaoui** [comment]
Can you try the git version?

**Comment by KottV** [comment]
i will
little busy now

**Comment by KottV** [comment]
you missed / in USERHOME = path.join("", USERHOME)
https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/89e93417e2a7a691ad2694f4a4634b6e39b9fad7

i added it, now seems to works :)

**Comment by bil-elmoussaoui** [comment]
Thanks! Fixed that on master!
