### ISSUE TITLE
The latest Chromium can't be patched

### ISSUE THREAD

**Issue by ootaharuki99** [bil-elmoussaoui/Hardcode-Tray#307]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Arch Linux (latest in 2017/01/28)`
- Gtk version : `3.22.7`
- Inkscape version : `0.92.0` 
- Sni-qt version: `unknown`
- Application name :  `Chromium`
- Application version : `56.0.2924.76`

### Expected behavior and actual behavior
Expected: `hardcode-tray` would replace chromium's tray icon.
Actual: `hardcode-tray` doesn't replaces chromium's tray icon.

### Steps to reproduce the problem
1. update chromium to the latest version
2. run `hardcode-tray --theme Papirus-Dark --only chromium --apply`

**Comment by bil-elmoussaoui** [comment]
I will update that this evening !

**Comment by bil-elmoussaoui** [comment]
Fixed on master, just use `hardcode-tray --update-git` to update to the latest version and run the script again! 👍

**Comment by ootaharuki99** [comment]
Thank you for your quick fix!
It's working now. 🙌

**Comment by bil-elmoussaoui** [comment]
You're welcome! Thanks for reporting!:D
