### ISSUE TITLE
QuodLibet icon 

### ISSUE THREAD

**Issue by kmf** [bil-elmoussaoui/Hardcode-Tray#308]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Ubuntu 16.04.1`
- Gtk version : `3.18.9-1ubuntu3.1`
- Inkscape version : `0.91-7ubuntu2` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `quodlibet`
- Application version : `3.8.1`

### Expected behavior and actual behavior
should be fixed

**Comment by bil-elmoussaoui** [comment]
The tray icon on Quodlibet isn't hardcoded but they're using the same icon name as the application icon name :( see this line of code https://github.com/quodlibet/quodlibet/blob/02b2f8946da5c400ebcab78ae958ebca05eb03ae/quodlibet/quodlibet/ext/events/trayicon/appindicator.py#L44
Please report it upstream, as i cannot fix it from my side :( if they want , i can create a PR to fix that upstream 👍

**Comment by kmf** [comment]
A PR would be great.

**Comment by bil-elmoussaoui** [comment]
Alright! I will keep this issue open and i will add it to my to-do list ;)

**Comment by bil-elmoussaoui** [comment]
Opened a new issue upstream. I will close this one https://github.com/quodlibet/quodlibet/issues/2217
