### ISSUE TITLE
Albert icon

### ISSUE THREAD

**Issue by kmf** [bil-elmoussaoui/Hardcode-Tray#309]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Ubuntu 16.04.1`
- Gtk version : `3.18.9-1ubuntu3.1`
- Inkscape version : `0.91-7ubuntu2` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `albert`
- Application version : `0.9.1-1~webupd8~xenial0`

### Expected behavior and actual behavior
should be fixed

**Comment by bil-elmoussaoui** [comment]
Albert hardcoded their tray icon on the binary file, i've reported that upstream and this is fixed now; they're still using the same icon name for the application and the tray menu. Anyway, here's the original upstream issue https://github.com/albertlauncher/albert/issues/324
Closing, as i hope that the guys from Albert will get this done without having to replace anything on the binary file...
