### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by Ghokun** [bil-elmoussaoui/Hardcode-Tray#31]
Telegram, spotify, dropbox are installed

Welcome to the tray icons hardcoder fixer! 

Copying now..

Traceback (most recent call last):
  File "script.py", line 169, in <module>
    copy_files()
  File "script.py", line 151, in copy_files
    cairosvg.svg2png(bytestring=bytes(svg,'UTF-8'),write_to=fout)
  File "/usr/lib/python3/dist-packages/cairosvg/__init__.py", line 43, in <lambda>
    surface_type.convert(*args, **kwargs))(_surface_type)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 84, in convert
    cls(tree, output, dpi).finish()
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 138, in __init__
    self.draw_root(tree)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 191, in draw_root
    self.draw(node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 300, in draw
    TAGS[node.tag](self, node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/path.py", line 324, in path
    draw_marker(surface, node, "end")
  File "/usr/lib/python3/dist-packages/cairosvg/surface/defs.py", line 279, in draw_marker
    angle1 = node.tangents.pop(0)
IndexError: pop from empty list

**Comment by bil-elmoussaoui** [comment]
I have no idea where this from, i will take a look in two days!

**Comment by bil-elmoussaoui** [comment]
@Ghokun Can you give me those informations; you've installed python cairosvg? Which version of Ubuntu or the distro you're using?

**Comment by Foggalong** [comment]
If python-cairosvg is a non-default package then the importing should definitely be `try` with `except` to handle errors.

**Comment by bil-elmoussaoui** [comment]
@Ghokun Can you try the latest version?

**Comment by Ghokun** [comment]
I am away from the computer that I got this error. Will try inform you tomorrow.

**Comment by Ghokun** [comment]
Ubuntu 14.04.2

Welcome to the tray icons hardcoder fixer! 

Copying now..

dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-busy.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-busy2.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-idle.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-logo.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-x.svg
Traceback (most recent call last):
  File "script.py", line 168, in <module>
    copy_files()
  File "script.py", line 149, in copy_files
    svg2png(bytestring=bytes(svg, 'UTF-8'), write_to=fout)
  File "/usr/lib/python3/dist-packages/cairosvg/__init__.py", line 43, in <lambda>
    surface_type.convert(*args, **kwargs))(_surface_type)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 84, in convert
    cls(tree, output, dpi).finish()
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 138, in __init__
    self.draw_root(tree)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 191, in draw_root
    self.draw(node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 344, in draw
    self.draw(child)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/__init__.py", line 300, in draw
    TAGS[node.tag](self, node)
  File "/usr/lib/python3/dist-packages/cairosvg/surface/path.py", line 324, in path
    draw_marker(surface, node, "end")
  File "/usr/lib/python3/dist-packages/cairosvg/surface/defs.py", line 279, in draw_marker
    angle1 = node.tangents.pop(0)
IndexError: pop from empty list

**Comment by bil-elmoussaoui** [comment]
I have no idea why this is happening..

**Comment by bil-elmoussaoui** [comment]
@Ghokun I add a code to print the current application so i can debug this. Can you try this again?

**Comment by wa4557** [comment]
Seems to be a cairosvg issue not a Hardcode tray issue. @Ghokun can you try `sudo pip3 install cairosvg -U' and run again?

**Comment by wa4557** [comment]
Ah or the svg is invalid, which means that it cannot be converted to png. Might be a programming error after all

**Comment by bil-elmoussaoui** [comment]
@wa4557 I didn't think about this, i modified the script to handle this case

**Comment by wa4557** [comment]
Still it would be interesting for which icon this happens. @Ghokun please run the script once more and tell us for which icon the terminal says, that it is an invalid svg icon

**Comment by wa4557** [comment]
@bil-elmoussaoui This might be fixed now as well, after we found out that the extensions were wrong. However we will never not unitl @Ghokun runs the script once more :)

**Comment by Ghokun** [comment]
Sorry for the late reply. It seems ok now.

Welcome to the tray icons hardcoder fixer! 

Copying now..

The svg file `/usr/share/icons/Numix-Circle/scalable/apps/keepassx.svg` is invalid.
keepassx -- fixed using /usr/share/icons/Numix-Circle/scalable/apps/keepassx.svg
keepassx_locked -- theme icon not found. You should report that to the theme maintainer!
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
spotify -- fixed using /usr/share/icons/Numix/22x22/status/spotify-indicator.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg
dropboxstatus-blank -- theme icon not found. You should report that to the theme maintainer!
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-busy.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-busy2.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-idle.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-logo.svg
dropbox -- fixed using /usr/share/icons/Numix-Circle/22x22/status/dropboxstatus-x.svg

Done , Thank you for using the Hardcode-Tray fixer!

**Comment by Ghokun** [comment]
I will close this if you say it is all good

**Comment by bil-elmoussaoui** [comment]
Everything looks fine, expect the icon of keepass, you can open a new issue for this
