### ISSUE TITLE
Telegram Desktop icon

### ISSUE THREAD

**Issue by kmf** [bil-elmoussaoui/Hardcode-Tray#310]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Ubuntu 16.04.1`
- Gtk version : `3.18.9-1ubuntu3.1`
- Inkscape version : `0.91-7ubuntu2` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `Telegram Desktop`
- Application version : `1.0.2`

### Expected behavior and actual behavior
should be fixed

**Comment by bil-elmoussaoui** [comment]
Telegram desktop is already supported.

**Comment by kmf** [comment]
![image](https://cloud.githubusercontent.com/assets/78700/22423402/2db03d7a-e6fa-11e6-833a-85eb1ddb70db.png)

**Comment by bil-elmoussaoui** [comment]
Is the icon stored on /tmp? or in `/home/yourusername/.local/share/TelegramDesktop/tdata`?

**Comment by kmf** [comment]
deleted my tdata .... what am I looking for in /tmp

**Comment by bil-elmoussaoui** [comment]
Just the tray icon? it should be somewhere there in that case, it's a png file

**Comment by kmf** [comment]
found it deleted it ... still the same ... will investigate.

**Comment by bil-elmoussaoui** [comment]
Well in that case you're missing libappindicator;, that's why Telegram falls back to using a Qt tray icon that we canno't fix. Please install it , close the application and start again ;)

**Comment by kmf** [comment]
already installed, 
libappindicator1, libappindicator3-1

**Comment by bil-elmoussaoui** [comment]
Take a look at those issues
https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/135 https://github.com/telegramdesktop/tdesktop/issues/1023

**Comment by kmf** [comment]
ok ... .using ... Rambox .... to ease the pain3

**Comment by bil-elmoussaoui** [comment]
As you wish! Anyway, this is not an issue for Hardcode-Tray, you will just need to install all the dependencies needed by Telegram to work correctly on Unity.
