### ISSUE TITLE
Wire not working

### ISSUE THREAD

**Issue by Freshman4754** [bil-elmoussaoui/Hardcode-Tray#312]
### Specifications
- Hardcode-Tray version : `3.6.5`
- Distribution : `Arch Linux`
- Gtk version : `3.22.7`
- Cairo version : `2.0.1`
- Sni-qt version: `latest patched from AUR`
- Application name :  `Wire`
- Application version : `2.11.2703`

It doesn't even appear in apps list.

**Comment by bil-elmoussaoui** [comment]
It must be due to the installation path of the package you're using. Can you point me to the package you've installed ? was it using AUR?

**Comment by bil-elmoussaoui** [comment]
Fixed on master. Run `hardcode-tray --update-git` to get the latest modifications, and run `hardcode-tray --apply --only wire` to fix Wire 👍
