### ISSUE TITLE
Chrome stable icon doesn't change

### ISSUE THREAD

**Issue by romannazarenko** [bil-elmoussaoui/Hardcode-Tray#313]
### Specifications
- Hardcode-Tray version : 3.6.5
- Distribution : Ubuntu 16.04 LTS x64
- Gtk version : 	3.18.9
- Inkscape version : 0.91
- Cairo version : Not installed
- Sni-qt version: 0.2.7
- Application name :  google-chrome-stable
- Application version : 56.0.2924.87-1

### Expected behavior and actual behavior
Expected: Change default tray icon
Actual: Tray icon doesn't change
### Steps to reproduce the problem
1. Install google-chrome-stable
2. Run hardcode-tray to fix the icon
3. Launch google-chrome-stable

**Comment by bil-elmoussaoui** [comment]
Already fixed on master ;)
