### ISSUE TITLE
Clementine "currently playing" icon

### ISSUE THREAD

**Issue by Stanzer** [bil-elmoussaoui/Hardcode-Tray#315]
### Specifications
- Hardcode-Tray version : `3.6.5`
- Distribution : `Ubuntu 16.04 amd64`
- Gtk version : `3.18.9-1ubun amd64`
- Inkscape version : `0.91 r13725`
- Sni-qt version: last one I guess, installed today from ppa 
- Application name :  `Clementine`
- Application version : `1.3.1-286-g1aed619`

### Expected behavior and actual behavior
Change Clementine hard-coded icons to current Ubuntu theme (Uniform+ in my case, even though I know it is not specifically supported by your script). Works perfectly but for the small "play" icon dispatched at the beginning of current track (see step 0) , which appears huge when Hardcode-tray applied (see step 3).

### Steps to reproduce the problem
0. 
![screenshot18](https://cloud.githubusercontent.com/assets/7616441/23300806/8f7f676a-fa87-11e6-9e00-1e68655125b4.png)

1. ~$ hardcode-tray --size 22 --only clementine
2. Restart Clementine
3. 
![screenshot15](https://cloud.githubusercontent.com/assets/7616441/23300811/9523271a-fa87-11e6-8584-f3034391ddd6.png)
Thanks

**Comment by bil-elmoussaoui** [comment]
Can you give me your modified version of clementine.json?

**Comment by Stanzer** [comment]
There it is.


`{
    "name": "Clementine",
    "app_path": [
        "/usr/bin/clementine"
    ],
    "icons_path": [
        "{userhome}/.local/share/sni-qt/icons/clementine/{size}/"
    ],
    "is_qt": true,
    "is_script": false,
    "force_create_folder": true,
    "exec_path_script": false,
    "backup_ignore": true,
    "icons": {
        "indicator": {
            "original": "e1c70cd6785ac768670030ea5df41c35",
            "theme": "clementine-panel"
        },
        "100": {
            "original": "10a04e23b84e9983c45c711ba0ed64cc",
            "theme": "clementine-100-playing",
            "symlinks": [
                "2d4aaad14ea972aab69fb008299762a7"
            ]
        },
        "90": {
            "original": "2c73462acd0f550bd40b4eb69c92c9ff",
            "theme": "clementine-90-playing"
        },
        "80": {
            "original": "94fd15a06fb5343f3aed1c0790df117f",
            "theme": "clementine-80-playing",
            "symlinks": [
                "bc2bf417e092cfd9485f9e263aebc609"
            ]
        },
        "70": {
            "original": "209c8d6f9b60d2e2ebc5a0fe387ca48f",
            "theme": "clementine-70-playing",
            "symlinks": [
                "4f79d0cf1ce058a79572708bba62db34"
            ]
        },
        "60": {
            "original": "9e25e457f43d36b9717b028be10cd64e",
            "theme": "clementine-60-playing"
        },
        "50": {
            "original": "fd857104813caf9b67ee95dbb8385ec0",
            "theme": "clementine-50-playing",
            "symlinks": [
                "a6c84d822084f3b540ca1915aaf76fc6"
            ]
        },
        "40": {
            "original": "77f87b3f44ff898e46833b2d8e08a32e",
            "theme": "clementine-40-playing",
            "symlinks": [
                "56d57e1c8dae66b0a9e02dfde8364c0a"
            ]
        },
        "30": {
            "original": "702d17b9e830ed7f3a9a3d44ed6f062c",
            "theme": "clementine-30-playing"
        },
        "25": {
            "original": "59cc4572186ec4d80d6117ddb6ca05fe",
            "theme": "clementine-25-playing"
        },
        "20": {
            "original": "42cef68137f7db86c78f511db7a39d65",
            "theme": "clementine-20-playing"
        },
        "15": {
            "original": "cc3bc778663612e29d742386c227e89d",
            "theme": "clementine-15-playing"
        },
        "10": {
            "original": "d918cc6f4ba4bbec172cb6932dca6083",
            "theme": "clementine-10-playing"
        },
        "05": {
            "original": "60be45c633978239990190b7148de8fc",
            "theme": "clementine-05-playing"
        }
    }
}`

**Comment by bil-elmoussaoui** [comment]
I think you've sent the incorrect version?

**Comment by Stanzer** [comment]
It is the one I found in _/opt/Hardcode-Tray/database/clementine.json_

Where else should I look for it ? Been searching my whole home dir, but I couldn't find anything in it…

**Comment by bil-elmoussaoui** [comment]
Ah okey, and how you were able to change those icons? As they're not supported by Hardcode-Tray  by default...

**Comment by Stanzer** [comment]
At the beginning I just wanted to give it a try, so I followed these steps :
`cd /tmp && wget -O - https://raw.githubusercontent.com/bil-elmoussaoui/Hardcode-Tray/master/uninstall.sh | bashcd /tmp && wget -O - https://raw.githubusercontent.com/bil-elmoussaoui/Hardcode-Tray/master/uninstall.sh | bash`

then
`sudo apt install sni-qt sni-qt:i386 hardcode-tray` 
and finally, 
`hardcode-tray --size 22 --only clementine`

I did not add any further step

**Comment by bil-elmoussaoui** [comment]
Well, that's an upstream issue as we don't support any of other icons then Tray ones ;) please report it either to clementine or to your theme designer :)

**Comment by Stanzer** [comment]
Anyway, I am not willing to force you into something that you don't officially support. Don't bother with my problem ; I guess you have more important things to do ;) … I only asked, just in case you had an easy solution for it

Thanks for taking the time to answer me. :+1:

**Comment by bil-elmoussaoui** [comment]
It's must be a problem with the way the svg icon was designed at first place, i don't use Clementine, neither your theme so it's just impossible for me to help :)
If you have any solution, please post it here, maybe someone else will have the same issue in the future! 
Thanks
