### ISSUE TITLE
hamster-indicator tray icon

### ISSUE THREAD

**Issue by mgor** [bil-elmoussaoui/Hardcode-Tray#316]
### Specifications
- Hardcode-Tray version : `3.5.2.1~723~ubuntu16.10.1`
- Distribution : `Ubuntu 16.10`
- Gtk version : `3.20.9-1ubuntu2`
- Inkscape version : `0.91-11ubuntu16.10.1`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.10.1`
- Application name :  `hamster-indicator`
- Application version : `0.1+037dd2e-0ubuntu2`

### Expected behavior and actual behavior
Would be nice to have support for the hamster-indicator tray icon, since it's the only one in my tray, at the moment, that "sticks out".

**Comment by bil-elmoussaoui** [comment]
The icons are not hardcoded, the icons are 
`hamster-applet-active` and `hamster-applet-inactive`
All you have to do is to request those icons upstream (the theme icon repository)
