### ISSUE TITLE
can't run hardcoded-tray from terminal

### ISSUE THREAD

**Issue by Feichtmeier** [bil-elmoussaoui/Hardcode-Tray#322]
### Specifications
- Hardcode-Tray version : `i cant check because of this issue but my ppa updated like 10 mins ago`
- Distribution : `ubuntu 16.04`
- Gtk version : `3.18`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

### Steps to reproduce the problem
1. open a terminal
2. try to run hardcoded-tray
3. doesn't work :(

**Comment by bil-elmoussaoui** [comment]
Is there any output ?

**Comment by Feichtmeier** [comment]
It's german :( But it is like "didn't find that commad" (in the path?)

![bildschirmfoto vom 2017-03-02 21-59-42](https://cloud.githubusercontent.com/assets/15329494/23526889/0b6cd8e2-ff94-11e6-9f53-22d82b9330ec.png)

**Comment by bil-elmoussaoui** [comment]
It's not hardecode-tray but `hardcode-tray` :P

**Comment by Feichtmeier** [comment]
![image](https://cloud.githubusercontent.com/assets/15329494/23551218/861b7d4c-0015-11e7-9506-463fd4f250d0.png)

Yeah typo there but it really can't be found. Normally it was found with TAB autocomplete.

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier Can you check if you have anything under /opt/Hardcode-Tray? Something like `ls -la /opt/Hardcode-Tray/` would be great :) also `which hardcode-tray`
Thanks

**Comment by Feichtmeier** [comment]
frederik@akira:/opt/Hardcode-Tray$ ls -la
insgesamt 60
drwxr-xr-x 6 root root  4096 Mär  3 13:42 .
drwxr-xr-x 8 root root  4096 Mär  2 16:17 ..
drwxr-xr-x 2 root root 12288 Mär  3 13:42 database
-rwxr-xr-x 1 root root  1148 Mär  3 13:01 hardcode-tray
-rwxr-xr-x 1 root root  1646 Mär  3 13:01 install.sh
drwxr-xr-x 2 root root  4096 Mär  3 13:42 license
drwxr-xr-x 6 root root  4096 Mär  3 13:42 modules
-rw-r--r-- 1 root root  7476 Mär  3 13:01 README.md
drwxr-xr-x 2 root root  4096 Mär  3 13:42 screenshots
-rwxr-xr-x 1 root root  6942 Mär  3 13:01 script.py
-rw-r--r-- 1 root root   168 Mär  3 13:01 uninstall.sh

![image](https://cloud.githubusercontent.com/assets/15329494/23551569/9bf5d796-0017-11e7-8135-082ee7e54169.png)

**Comment by bil-elmoussaoui** [comment]
It seems that the PPA is broken. Can you please follow the manual installation in the README ? It's just one line to copy paste in your terminal. Please make sure to remove the current version. Once it's done can you report back if everything's working fine ?

**Comment by Feichtmeier** [comment]
Okay remove the ppa and purged the ppa version and installed it manually.
Now skype and play music got their sharp icons back but chrome is still blurry. :(

**Comment by bil-elmoussaoui** [comment]
Which version of Chrome are you using ? Have you killed chrome and tried again? a restart would do the same thing

**Comment by Feichtmeier** [comment]
Yup, killed it, rebooted, still the same. Used the revert command and still The blurry icon. 
Version is the most up to date version from the google ppa:
56.0.292487

**Comment by bil-elmoussaoui** [comment]
Ah okey, try using an other icon size for chrome `hardcode-tray --only google-chrome --size 22` or even 16 if 22 isn't enough for you :)

**Comment by Feichtmeier** [comment]
Hm... tried all sizes and still the blurry icon :( Sorry for stealing your time

**Comment by bil-elmoussaoui** [comment]
Hmmm, i have really no idea about that! :( Do you have something else other than Unity to try it on? We have tried it on Unity and everything was working perfectly! The same on Gnome, mate, xfce and KDE! 

Also, it seems that the conversion tool used by Hardcode-Tray is ImageMagick. do you have Inkscape installed? if so try forcing it using `hardcode-tray -ct Inkscape` which will use it to convert the icons from SVG to PNG instead of ImageMagick (which sucks a little :p, was added only for the sake of not forcing users to use only Inkscape or another conversion tool)

**Comment by Feichtmeier** [comment]
Atm only Unity here. It worked for me perfectly too for many versions.
Can I manually remove the chrome icons? Would it help to reinstall chrome?

**Comment by bil-elmoussaoui** [comment]
Give it a try and let me know :) Try something like `hardcode-tray --update-git` to update to the latest git version and see if it fixes the issue for you

**Comment by Feichtmeier** [comment]
I reinstalled chrome and deleted all folders in .cache .config of hardcode tray and chrome and now I got the old google icon back :dagger: 
And your script doesn't change anything at all now :(

**Comment by bil-elmoussaoui** [comment]
I will take a look today ;) when you run the script, can you paste the output ?

**Comment by Feichtmeier** [comment]
frederik@akira:~$ hardcode-tray
[sudo] Passwort für frederik: 
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Google Chrome       [#.......................................] 1/37 2.7%
Google Play Music Desktop Player            [########................................] 7/37 18.9%
Skype               [########################################] 37/37 100.0%

Done, Thank you for using the Hardcode-Tray fixer!
frederik@akira:~$

**Comment by bil-elmoussaoui** [comment]
What's the version of Google chrome ? Can you get me the log under tmp file ?

**Comment by Feichtmeier** [comment]
Chrome Version is  56.0.2924.87

The logs in /tmp are empty

**Comment by bil-elmoussaoui** [comment]
Can you ping me on Telegram? This way i can get you sort this out easily :)

**Comment by Feichtmeier** [comment]
Sure, is there any other option than to share phone numbers on github? :D

**Comment by bil-elmoussaoui** [comment]
https://t.me/bilelmoussaoui

**Comment by bil-elmoussaoui** [comment]
Fixed

**Comment by MarekAG** [comment]
@bil-elmoussaoui Hi, I want to inform you that using PPA still stops hardcode-tray from being run from terminal. I can run app from /opt/Hardcode-Tray/ and also running --update-git fixes it (at least to the next update trough PPA).

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you check the PPA once you've some free time? it must be a symlink issue; or at worst you can add @varlesh as a collaborator on launchpad and let's see if he have some free time to get this fixed :)

**Comment by wa4557** [comment]
I'll do that:) I should have a bit more freetime from now on
