### ISSUE TITLE
Hplilp/ HP pirnter tray icon support? 

### ISSUE THREAD

**Issue by phyrz91** [bil-elmoussaoui/Hardcode-Tray#325]
### Specifications
- Hardcode-Tray version : `3.5.2.1~729~ubuntu17.04.1`
- Distribution : `Debian Testing`
- Gtk version : `3.22`
- Inkscape version : `0.92`
- Cairo version : ``
- Sni-qt version: `0.2.7+20161212~10~ubuntu17.04.1`
- Application name :  `hplip`
- Application version : `3.16.11+repack0-2`

### Expected behavior and actual behavior
The hplip tray icon doesn't change.
HP Print is detect when i use hardcode-tray --theme Papirus-Dark --size 22 command.

### Steps to reproduce the problem
1. hardcode-tray --theme Papirus-Dark --size 22
2. 
3.

I use Plasma 5.8.4 and Papirus Dark icons.
http://i66.tinypic.com/20z5jzq.png

**Comment by bil-elmoussaoui** [comment]
Do you have the patched version of sni-qt installed ?

**Comment by phyrz91** [comment]
I install sni-qt from ppa repository. How can I install patched version of sni-qt?

**Comment by bil-elmoussaoui** [comment]
You have used our PPA(see README)?

**Comment by phyrz91** [comment]
Yes, I used this repo:
ppa:andreas-angerer89/sni-qt-patched

Everythings work great except hplip icon.

**Comment by bil-elmoussaoui** [comment]
I will investigate this

**Comment by bil-elmoussaoui** [comment]
@phyrz91 I will need your help in order to get this done correctly. First of all, can you remove the patched version of sni-qt and restart your system. Once it's done, open HPlilp and go to /tmp, under that folder you will find a folder named `sni-qt_...` or somethong related to hplilp, just take a look under every folder and once you've found that folder (it contains the tray icon on it). Send me the complete path to the icon. And i will fix it :)

**Comment by phyrz91** [comment]
My /tmp folder does not contain folder named sni-qt.. :(

[https://postimg.org/image/az4nspyrz/](url)

**Comment by bil-elmoussaoui** [comment]
Hmm! I will set up a Debian distro and see how to handle this :)

**Comment by bil-elmoussaoui** [comment]
Sorry for the long delay, but it's now fixed on master! Your theme must have the `hp-indicator` icon in order for it to work :)

**Comment by bil-elmoussaoui** [comment]
Good news! I've just figured out how to fix it without having to use sni-qt, so the new fix (now on master) will work across all the distros :+1:
