### ISSUE TITLE
Support for new applications.

### ISSUE THREAD

**Issue by phyrz91** [bil-elmoussaoui/Hardcode-Tray#326]
Can you add new tray icons for two applications?

https://github.com/QNapi/qnapi
http://sayonara-player.com/index.php

Thank you in advance.

**Comment by bil-elmoussaoui** [comment]
I will take a look in few hours

**Comment by bil-elmoussaoui** [comment]
For Sayonara the icons are hardcoded on the binary. For now we don't want to overwrite those icons see #297 
![screenshot from 2017-03-09 15-45-59](https://cloud.githubusercontent.com/assets/7660997/23755079/8250d3c8-04df-11e7-95f8-9cc22a2ba712.png)

**Comment by bil-elmoussaoui** [comment]
The same thing for qnapi 

![screenshot from 2017-03-09 16-07-58](https://cloud.githubusercontent.com/assets/7660997/23756005/975696d8-04e2-11e7-96ee-6e2ce86df416.png)

**Comment by bil-elmoussaoui** [comment]
I will mark this issue as not fixed (and not won't fix) until we decide either we implement a way to change icons on binary files or not(if it's possible without breaking the app). Closing, will reopen if we got this #297 got fixed :+1:
