### ISSUE TITLE
Stopped working for prime indicator plus

### ISSUE THREAD

**Issue by MarekAG** [bil-elmoussaoui/Hardcode-Tray#328]
### Specifications
- Hardcode-Tray version : `3.6.6, but package is 3.5.2.1~735~ubuntu16.04.1 (isn't smth wrong with this?)`
- Distribution : `Ubuntu 16.04.2 LTS`
- Gtk version : `3.18.9-1ubuntu3.2`
- Inkscape version : `0.91 r13725` 
- Cairo version : `1.0.19`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `Prime indicator plus`
- Application version : `1.0.3-1~webupd8~2`

### Expected behavior and actual behavior
I'm using Papirus theme on Unity. Yesterday after updating packages prime indicator went back to the old blue icon. Earlier it was working fine (icon was monochromatic).
I was trying to run hardcode-tray without any arguments and also with some of them, but nothing helped. See screenshot:
![](http://i.imgur.com/Y2UIoWi.png)
### Steps to reproduce the problem
1. Install prime indicator:
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install prime-indicator-plus
2. Run hardcode-tray.

**Comment by bil-elmoussaoui** [comment]
I will fix it this evening. Thanks for reporting
