### ISSUE TITLE
Cant' working 

### ISSUE THREAD

**Issue by TheDoop** [bil-elmoussaoui/Hardcode-Tray#333]
### Specifications
- Hardcode-Tray version : `latest`
- Distribution : `xubuntu 16.04 lts`
- Gtk version : `ı dont know`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `telegram,chrome`
- Application version : `latest`

### Steps to reproduce the problem
1. doop@Doop-PC:~$ hardcode-tray --apply
ls: 'xprop -root _DT_SAVE_MODE''e Inaccessible: no such file or directory
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
The detected desktop environement : Other
Your current icon theme is : elementary-xfce-darker
Conversion tool : CairoSVG
Applications will be fixed : All
Applying now..
(but my icon theme papirus)

**Comment by bil-elmoussaoui** [comment]
Please see https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/FAQ#default-theme-is-not-correctly-detected

**Comment by TheDoop** [comment]
I'm write "org.gnome.desktop.interface icon-theme "papirus-dark" " but 
org.gnome.desktop.interface icon-theme "papirus-dark" command not found

**Comment by bil-elmoussaoui** [comment]
Just use the argument --theme or type hardcode-tray --help to get the list of the themes
