### ISSUE TITLE
Icon uses the dark variant in a dark theme

### ISSUE THREAD

**Issue by mustaqimM** [bil-elmoussaoui/Hardcode-Tray#334]
### Specifications
- Hardcode-Tray version : `3.6.6`
- Distribution : `arch linux`
- Gtk version : `3.22.10-1`
- Cairo version : `1.14.8-1`
- Sni-qt version: `r.-1`
- Application name :  `Dropbox`
- Application version : `22.4.24-1`

### Expected behavior and actual behavior
Expected: Use a  light icon after running `hardcode-tray --dark-theme Papirus-dark --light-theme Papirus`, running the similar commmand `hardcode-tray --dark-theme Numix-light --light-theme Numix` works correctly, the white variant shows
### Steps to reproduce the problem
1. `hardcode-tray --dark-theme Papirus-dark --light-theme Papirus`

**Comment by bil-elmoussaoui** [comment]
You should use -ct Inkscape with Papirus as they use CSS SVG which does not work with cairosvg or any other conversion tool as far as i know except Inkscape

**Comment by mustaqimM** [comment]
@bil-elmoussaoui Thanks, it works now perfectly. On an unrelated note, is it possible to theme `mono` apps like `KeePass`

**Comment by bil-elmoussaoui** [comment]
KeePass icon isn't hardcoded see #173 #239 #143

**Comment by mustaqimM** [comment]
@bil-elmoussaoui I found with `keebuntu` installed, the icon at `/usr/share/icons/hicolor/256x256/apps/keepass2-locked.png` can be changed with the icon `/usr/share/icons/Papirus-Dark/24x24/panel/keepassx-locked.svg`. For anyone that wants to use it: 
![screenshot_20170328_125224](https://cloud.githubusercontent.com/assets/24436622/24401662/8355eec2-13b5-11e7-9d80-406f7b010dab.png)

**Comment by bil-elmoussaoui** [comment]
Alright I will see how to handle that. At worse take a look at the keepassx.json file under /opt/Hardcode-tray and modify it to fix it for you and open a PR please.
