### ISSUE TITLE
Doesn't find Telegram

### ISSUE THREAD

**Issue by vayan** [bil-elmoussaoui/Hardcode-Tray#335]
### Specifications
- Hardcode-Tray version : `3.6.6`
- Distribution : `Ubuntu 16.10`
- Application name :  `Telegram`
- Application version : `1.0.14`

I'm not sure what I'm doing wrong but hardcode-tray doesn't seems to find my Telegram install.

I have : 
`~App/Telegram` with `Telegram` and `Updater` and `~/.local/share/TelegramDesktop` with `tdata` and everything.

I tried using `--only telegram --path foobar` but nothing worked, always "No apps to fix!"

**Comment by bil-elmoussaoui** [comment]
What do you use for the --path ? At worst add your installation path under /opt/Hardcode-Tray/telegram.json

**Comment by bil-elmoussaoui** [comment]
Ah maybe the binary of telegram was not found on the same location as mine :) please create a PR to fix it by adding a new line with the location of your binary file :+1: 
Thanks!

**Comment by jfkpdq** [comment]
Same issue after installing as flatpack. Set the location right `/home/USER/.var/app/org.telegram.desktop/data/TelegramDesktop/` but I got "app not found".

**Comment by bil-elmoussaoui** [comment]
Can you modify the /usr/share/hardcode-tray/database/telegram.json and add that path to icons_path and try again? + Which icon theme are you using? If you can paste the output you got in terminal that would be great

**Comment by jfkpdq** [comment]
OK I tried some modifications on the .json but nothing works. Strangely the `ticons` folder in the flatpack version (from` flathub`) only have 3 icons, which looks weird. 

Theme is Mint-X-Grey.

`$ sudo hardcode-tray --only telegram --path /home/fabien/.var/app/org.telegram.desktop/data/TelegramDesktop
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Mint-X-Grey
Conversion Tool: RSVGConvert
To Do: Telegram
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


No apps to fix!

Done, Thank you for using the Hardcode-Tray fixer!`

**Comment by bil-elmoussaoui** [comment]
Well, that theme just doesn't support hardcode-tray...please read the readme carefully next time ;) we don't ship any icon at all! we use the icons shipped by the theme used by default ;)
try using --theme Numix or Papirus to fix those icons or add the icons by yourself to your current theme

**Comment by jfkpdq** [comment]
OK sorry. I'll find a manual way to copy new icons that suits HiDPi display in the tray.

**Comment by bil-elmoussaoui** [comment]
What do you mean by that? you can use a theme icon to just replace the tray icons, without even using it ;)
