### ISSUE TITLE
ls: cannot access 'xprop -root _DT_SAVE_MODE': No such file or directory

### ISSUE THREAD

**Issue by edouard-lopez** [bil-elmoussaoui/Hardcode-Tray#340]
**follow:** #339

### Specifications
- Hardcode-Tray version : `v3.7` (apt show `3.5.2.1~742~ubuntu16.04.1` but I run  `hardcode-tray --update-git`)
- Distribution : 

    ```
    lsb_release -a
    No LSB modules are available.
    Distributor ID: LinuxMint
    Description:    Linux Mint 18 Sarah
    Release:        18
    Codename:       sarah
    ```
- Gtk version : `2.7.4`
- Inkscape version : `0.91 r13725` if installed
- Cairo version : `` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1` if installed
- Desktop: **Cinnamon 3.2.7**

### Expected 

- No error message
- Should detect `Papirus-light` as icon theme instead of `Mint-X`
![selection_026](https://cloud.githubusercontent.com/assets/1212392/24727717/5d3e2404-1a57-11e7-8d0a-b87426202db0.png)

### Actual

```
$ hardcode-tray --conversion-tool Inkscape
ls: cannot access 'xprop -root _DT_SAVE_MODE': No such file or directory
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
The detected desktop environement : Other
Your current icon theme is : Mint-X
Conversion tool : Inkscape
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose:
```

### Steps to reproduce the problem

1. [install via PPA](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#ubuntu-and-derivatives) as describe on PapirusDevelopmentTeam/papirus-icon-theme readme

       sudo add-apt-repository ppa:papirus/papirus
       sudo apt-get update
       sudo apt-get install papirus-icon-theme
2. run

       hardcode-tray --conversion-tool Inkscape

**Comment by bil-elmoussaoui** [comment]
This is not an issue on Hardcode-Tray at all... You need to install xprop on your DE. It's used to detect your current DE in order to use the correct icon size :) If xprop is not installed it shows this error :) I might need to polish it a little bit

**Comment by redpop1** [comment]
xprop in ubuntu16.04 is within x11-utils and is installed.

Since the latest release there are a lot problems with hardcode-tray.

It seems that xprop with the arguments is crashing with ubuntu16.04.2

If the problem is not hardcode-tray, has there been an update x11-utils for ubuntu 16.04?

**Comment by redpop1** [comment]
hardcode-tray crashes at startup of ubuntu.
![hardcode-tray](https://cloud.githubusercontent.com/assets/647670/24767397/1acead52-1aff-11e7-801d-0265ee150221.png)

**Comment by bil-elmoussaoui** [comment]
@redpop1 apport is a trash. Hardcode-tray does not run automatically at startup..

**Comment by bil-elmoussaoui** [comment]
I have removed xprop dependency. The current desktop might not be detected correctly. In that case just `--size`argument to force using the right icon size you want :)
