### ISSUE TITLE
Discord Official Release Icon

### ISSUE THREAD

**Issue by TheGohan1905** [bil-elmoussaoui/Hardcode-Tray#342]
### Specifications
- Hardcode-Tray version : `3.5.2.1`
- Distribution : `Mint 18.1 Cinnamon`
- Gtk version : `Default`
- Inkscape version : `Most Recent` if installed
- Cairo version : `Not Installed` if installed
- Sni-qt version: `Most Recent` if installed
- Application name :  `Discord`
- Application version : `Official Release'

### Expected behavior and actual behavior
The Hardcode-Tray can only work with Discord for the Canary release, a beta release of Discord.
It wont work with the Official Release of it, even the earliest Version.
It should work naturally.
The result won't change even with other icon themes.

### Steps to reproduce the problem
1. Just trying to fix all the icons of installed apps gives the same result, only for discord, using hardcode-tray --theme Papirus-Dark --conversion-tool Inkscape

**Comment by bil-elmoussaoui** [comment]
Already on master :+1: Just use `hardcode-tray --update-git` to update your Hardcode-Tray to git version or wait until a new stable release :) 
Thanks for reporting

**Comment by TheGohan1905** [comment]
Thanks, did it!

**Comment by bil-elmoussaoui** [comment]
Feel free to report any new issues in the future !
