### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by tiamattia** [bil-elmoussaoui/Hardcode-Tray#344]
### Specifications
- Hardcode-Tray version : `3.7`
- Distribution : `Ubuntu Gnome 16.10`
- Gtk version : ``
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
When I run the command `hardcode-tray --only telegram`, the program throws an error:
![screenshot from 2017-04-10 15-51-37](https://cloud.githubusercontent.com/assets/5357945/24864854/c590483c-1e05-11e7-9017-8644c053a534.png)

### Steps to reproduce the problem
1. Install hardcode-tray thrugh apt-get
2. Run hardcode-tray --update-git to fix ArgsParser error
3. Run hardcode-tray --only telegram

**Comment by bil-elmoussaoui** [comment]
Will fix pretty soon! Thanks for reporting

**Comment by bil-elmoussaoui** [comment]
Fixed, please run `hardcode-tray --update-git` or wait for the hotfix release (should be released pretty soon)
