### ISSUE TITLE
Option for not creating backup

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#346]
I personally don't want to create backups all the time since I don't care about the original icons and don't want to clutter my harddisk with unnecessary files too much. 

How about an option that disables the possibility to create backups? (And one the cleans already exisiting ones, maybe)

**Comment by bil-elmoussaoui** [comment]
I will add the option for not creating a backup to the new config.json file that i've added recently :)
And i will add an argument to clean the old backups

**Comment by bil-elmoussaoui** [comment]
This should land next weekend! i'm improving the base code of Hardcode-Tray and make it more easier to create new plugins for it :)

**Comment by bil-elmoussaoui** [comment]
Done on 3.8 https://github.com/bil-elmoussaoui/Hardcode-Tray#config-file
