### ISSUE TITLE
Trying to contribute, but I am overlooking something

### ISSUE THREAD

**Issue by rpbaptist** [bil-elmoussaoui/Hardcode-Tray#348]
### Specifications
- Hardcode-Tray version : `master` branch
- Distribution : `Ubuntu 16.04.2`
- Gtk version : ``
- Inkscape version : `0.91 r13725`
- Cairo version : `1.0.19`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `copyq`
- Application version : `v2.9.0 `

I added the following JSON locally:

```javascript
// database/copyq.json
{
    "name": "CopyQ",
    "app_path": [
        "/usr/bin/copyq",
        "/usr/lib/copyq/"
        "/usr/share/copyq/"
    ],
    "icons_path": [
        "/usr/share/hicolor/{size}/apps/"
    ],
    "is_qt": false,
    "is_script": false,
    "force_create_folder": false,
    "exec_path_script": false,
    "backup_ignore": false,
    "icons": [
        "copyq-normal.svg",
        "copyq-busy.svg"
    ]
}
```

I tried with `icons_path` `/usr/share/hicolor/scalable/apps/` as well. I tried with and without extensions.

This is the output after running the script:

```
> ./hardcode-tray --conversion-tool Inkscape --dark-theme Papirus --size 24 --only copyq
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 24
The detected desktop environement : Other
Your current icon theme is : Papirus-Dark
Conversion tool : Inkscape
Applications will be fixed : Copyq
1 - Apply
2 - Revert
Please choose: 1
Applying now..

No apps to fix! Please report on GitHub if this is not the case
```

I would be happy to contribute, but I am missing something which I cannot find in the wiki. I tried the same for the `insync` application and see the same result.

**Comment by bil-elmoussaoui** [comment]
If the original icons are on `/usr/share/icons/hicolor`Hardcode-Tray is not needed at all... as those icons are not hardcoded, it must be your theme that doesn't provide those icons.

**Comment by rpbaptist** [comment]
Strange, because it does have the icons. I suppose it's an issue for Papirus then.

**Comment by bil-elmoussaoui** [comment]
Feel free to reopen this if you have any other questions or any help =)
