### ISSUE TITLE
Mullvad (AUR) not getting themed suddenly?

### ISSUE THREAD

**Issue by ryderdavid** [bil-elmoussaoui/Hardcode-Tray#350]
### Specifications
- Hardcode-Tray version : ``3.6.6-1
- Distribution : ``Manjaro
- Gtk version : ``2.24.31-1 (GTK2) 3.22.10-1 (GTK3)
- Inkscape version : `` 3.6.6-1
- Cairo version : `` 1.14.8-1
- Sni-qt version: `` not installed
- Application name :  ``mullvad
- Application version : ``62-1

### Expected behavior and actual behavior
Icon should be themed by hardcode tray
Icon is not themed, and is the stock icon. 
When trying to run 
`hardcode-tray --theme Papirus --only mullvad
`
Returns:
```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
The detected desktop environement : Other
Your current icon theme is : Papirus
Conversion tool : Inkscape
Applications will be fixed : Mullvad
1 - Apply
2 - Revert
Please choose: 1
Applying now..

No apps to fix! Please report on GitHub if this is not the case
```

### Steps to reproduce the problem
1. Can't get it rethemed. Persists across reboots and restarting session.
2. 
3.

**Comment by bil-elmoussaoui** [comment]
@ryderdavid mullvad is not supported (yet), i have to take a look and see if it's possible

**Comment by bil-elmoussaoui** [comment]
@ryderdavid its now supported https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/mullvad.json
You will have to ask Papirus guys to add some new icons; Just link this issue :+1:
