### ISSUE TITLE
Wire app changed its destination (to wire-desktop).  hardcode-tray still assumes it is in wire directory

### ISSUE THREAD

**Issue by dwellerattic** [bil-elmoussaoui/Hardcode-Tray#351]
### Specifications
- Hardcode-Tray version : ``
- Distribution : `Antegro (Arch Linux) KDE`
- Gtk version : ``
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Wire`
- Application version : `2.13.2741-1`

### Expected behavior and actual behavior
Expected Wire to be found in /usr/lib/wire-desktop
Actual behaviour is an app is sought in /usr/lib/wire

As a side note, asar is now called electron.asar. wire_elec.json in hardcode-tray refers to app.asar

### Steps to reproduce the problem
1. install latest wire-desktop with pacaur -S wire-desktop
2. apply hardcode-tray to a theme (I did this hardcode-tray -lt Papirus-Light -dt Papirus-Dark -o wire)
3. hardcode-tray complains with `No apps to fix! Please report on GitHub if this is not the case`

**Comment by bil-elmoussaoui** [comment]
I will take a look this evening :)

**Comment by dwellerattic** [comment]
Very much appreciated. I got it working after modifying wire.json and wire_elec.json (I realise I could override it with a local config):

in this way

```json
{
    "name": "Wire",
    "app_path": [
        "/opt/Wire/",
        "/usr/lib/wire-desktop/"
    ],
    "icons_path": [
        "/opt/Wire/resources/app/img/",
        "/usr/lib/wire-desktop/resources/app/img/"
    ],
    "is_qt": false,
    "force_create_folder": false,
    "exec_path_script": false,
    "is_script": false,
    "backup_ignore": false,
    "icons": {
        "tray": {
            "original": "tray.png",
            "theme": "wire-tray"
        },
        "notification": {
            "original": "tray.badge.png",
            "theme": "wire-tray-attention"
        }
    }
}
```
And I  got an icon
![image](https://cloud.githubusercontent.com/assets/28548427/26007745/32bbe914-3785-11e7-9bea-d1be343ef8f1.png)

**Comment by bil-elmoussaoui** [comment]
@dwellerattic A PR will be much appreciated :)

**Comment by bil-elmoussaoui** [comment]
A Pull request would be really appreciated
