### ISSUE TITLE
JDownloader support?

### ISSUE THREAD

**Issue by GUiHKX** [bil-elmoussaoui/Hardcode-Tray#354]
### Specifications
- Hardcode-Tray version : `v3.6.6`
- Distribution : `Arch Linux`
- Gtk version : `gtk2 2.24.31 / gtk3 3.22.15`
- Inkscape version : Not installed
- Cairo version : `1.14.8`
- Sni-qt version: Not installed
- Application name :  `JDownloader`
- Application version : `v2`

**Comment by bil-elmoussaoui** [comment]
As far as i can tell, JDownloader uses`jdownloader-panel` as a tray icon. So Hardcode-Tray is not needed at all...

**Comment by GUiHKX** [comment]
Actually, by browsing trough [JDownloader's code](https://github.com/mirror/jdownloader/blob/master/src/org/jdownloader/gui/jdtrayicon/TrayExtension.java#L224-L228), I've found out that they generate the tray icon "on the fly"... So yes, Hardcore-Tray isn't needed. In case somebody get here through Google, a rather easy workaround for the ugly tray icon would be:

1. Back-up the original icon first (assuming your JDownloader path is located at `/home/YOU/.jd/`):

```
cd $HOME/.jd/themes/standard/org/jdownloader/images/logo/
mv jd_logo_128_128.png jd_logo_128_128.png.bak
```
2. Create a symlink to your new icon. (in this example, I'll be using the icon from the amazing [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)):

```
ln -s /usr/share/icons/Papirus-Dark/64x64/apps/jdownloader.svg $HOME/.jd/themes/standard/org/jdownloader/images/logo/jd_logo_128_128.svg
```
Don't worry, it will work just fine with SVG.

3. Restart JDownloader. It should look like this:

![screenshot_2017-05-21_08-47-34](https://cloud.githubusercontent.com/assets/626206/26283611/30e6c644-3e02-11e7-96f6-7a8368d024fc.png)

Unfortunately, since I use the Dark version of Papirus, there's no monochrome/grey icon for JDownloader yet, so it doesn't look as good as some other programs, but at least it does look much better than the original icon. There's also an optional in JDownloader to make it a grey icon. [Follow these steps to activate it](https://i.imgur.com/gxm9QZX.png) and then restart JDownloader. It should be in greyscale now:

![screenshot_2017-05-21_08-47-13](https://cloud.githubusercontent.com/assets/626206/26283791/9c17684a-3e04-11e7-9044-c87f581688ba.png)

Also, for some reason, the tray icon has no transparency... :thinking. But that was happening using the old icon as well, so... I don't know & I don't care.

**Comment by bil-elmoussaoui** [comment]
@GUiHKX I've added JDownloader support (which does the steps you explained below). It should work well if your theme has a `jdownloader-indicator` icon

**Comment by GUiHKX** [comment]
Great! Thank you!
