### ISSUE TITLE
Panel icon colors

### ISSUE THREAD

**Issue by redpop1** [bil-elmoussaoui/Hardcode-Tray#356]
### Specifications
- Hardcode-Tray version : `latest git`
- Distribution : `ubuntu gnome 16.04`
- Gtk version : ``
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
Icon color from my-weather-indicator and radiotray does not match color from other icons
See screenshot
Papirus-Dark icon theme
![panel](https://cloud.githubusercontent.com/assets/647670/26326010/aec2fe6a-3f39-11e7-948e-aa618a0bb8bf.png)

Is it a bug or am I doing something wrong?

**Comment by bil-elmoussaoui** [comment]
Take a look at https://github.com/bil-elmoussaoui/Hardcode-Tray#options `--change-color` option or use something else other  than CairoSVG as a conversion tool. Can you paste the output you had on your terminal to be sure of that?

**Comment by redpop1** [comment]
I'm really sorry.
It's the gnome extension TopIcons plus which was changing the color.

Can be closed

**Comment by bil-elmoussaoui** [comment]
Perfect 👍
