### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#357]
### Specifications
- Hardcode-Tray version : All

Can you add in the README an example config file? Json is probably not obvious to everyone. 

Great work btw. lately on code quality :)

**Comment by wa4557** [comment]
Nevermind, just saw that there is already an example

**Comment by bil-elmoussaoui** [comment]
@wa4557 Thanks :) it's now much more easier to contribute than ever, but i'm still trying to improve the code more :+1:
