### ISSUE TITLE
can't install patched sni-qt

### ISSUE THREAD

**Issue by MichSt** [bil-elmoussaoui/Hardcode-Tray#360]
[mikhail@home build]$ make
[  6%] Generating iconcache.moc
moc: Cannot open options file specified with @
Usage: moc [options] <header-file>
  -o<file>           write output to file rather than stdout
  -I<dir>            add dir to the include path for header files
  -E                 preprocess only; do not generate meta object code
  -D<macro>[=<def>]  define macro, with optional definition
  -U<macro>          undefine macro
  -i                 do not generate an #include statement
  -p<path>           path prefix for included file
  -f[<file>]         force #include, optional file name
  -nn                do not display notes
  -nw                do not display warnings
  @<file>            read additional options from file
  -v                 display version of moc
src/CMakeFiles/sni-qt.dir/build.make:62: ошибка выполнения рецепта для цели «src/iconcache.moc»
make[2]: *** [src/iconcache.moc] Ошибка 1
CMakeFiles/Makefile2:149: ошибка выполнения рецепта для цели «src/CMakeFiles/sni-qt.dir/all»
make[1]: *** [src/CMakeFiles/sni-qt.dir/all] Ошибка 2
Makefile:129: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
[mikhail@home build]$ 

Fedora 25 x64 Gnome 3.22.2

**Comment by MichSt** [comment]
That's my fault. On the way there should be no symbols other than Latin. In my case, I compiled in the "Загрузки" folder

**Comment by bil-elmoussaoui** [comment]
Not a problem =)
