### ISSUE TITLE
config-file ignored

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#361]
### Specifications
- Hardcode-Tray version : latest

### Steps to reproduce the problem
1. Run the script use hardcode-tray.json config file

One more thing: right now the config file is ignored (the conversion tool as well as the option to not make a backup).

+ There is somewhere a debugging print somewhere

```
Dropbox             [###.....................................] 5/79 6.3% 0.07s
Franz               [#####...................................] 9/79 11.4% 0.05s
Google Chrome       [########................................] 16/79 20.3% 9.56s
Google Music Manager[#########...............................] 17/79 21.5% 0.0s
Keepassx            [##########..............................] 19/79 24.1% 0.02s
Megasync            [############............................] 23/79 29.1% 0.0s
OwnCloud            [###############.........................] 29/79 36.7% 0.0s
Skype               [##############################..........] 59/79 74.7% 9.99s
Spotify             [##################################......] 68/79 86.1% 0.13s
hey
Teamviewer          [#####################################...] 74/79 93.7% 0.01s
Telegram            [#######################################.] 77/79 97.5% 0.34s
Whatsie             [########################################] 79/79 100.0% 0.5s
```
After spotify it says `hey`

**Comment by bil-elmoussaoui** [comment]
@wa4557 I've already removed the hey message. And cleaned few issues on master (just few seconds ago.) Can you try that and also paste the content of the latest log file `/tmp/Hardcode-Tray/`?

**Comment by wa4557** [comment]
The hey message is gone, but the config file is still ignored (i.e. backup is made and CairoSVG is used instead of inkscape)

**Comment by bil-elmoussaoui** [comment]
I can't confirm that at all :/ Can you paste the log content ?

**Comment by wa4557** [comment]
Nevermind I'm stupid :/ I named it hardcode-config.json not hardcode-tray.json

**Comment by bil-elmoussaoui** [comment]
Not a problem :+1: 
Happy to hear that
