### ISSUE TITLE
Google Music Manager Icon When Paused

### ISSUE THREAD

**Issue by dylanparry** [bil-elmoussaoui/Hardcode-Tray#362]
### Specifications
- Hardcode-Tray version : `3.8`
- Distribution : `ubuntu (zesty)`
- Gtk version : `3.22.11`
- Inkscape version : `0.92.1 r15371`
- Cairo version : `1.0.20`
- Sni-qt version: `0.2.7` (also installed patched version)
- Application name :  `Google Music Manager`
- Application version : `1.0.243.1116`

### Expected behavior and actual behavior

When starting up, the icon appears to be correct.

![image](https://cloud.githubusercontent.com/assets/3692873/26443433/5217bac2-4130-11e7-8882-9a8b0b4b30e0.png)

When uploading is paused, the icon returns to its original coloured version. Un-pausing, and continuing the upload does not return the icon to the correct version.

![image](https://cloud.githubusercontent.com/assets/3692873/26443481/7e5a8812-4130-11e7-8978-3d1cf6c492ae.png)

The only way to get the icon back to the correct version appears to be to restart Google Music Manager.

### Steps to reproduce the problem
1. Start Google Music Manager
2. Pause uploads (Icon changes to colour)
3. Resume uploads (Icon remains in colour)

**Comment by bil-elmoussaoui** [comment]
Must be an unsupported icon then, the icon names can be found either on tmp folder or using 
```bash
dbus-send --type=method_call --print-reply --dest=com.canonical.indicator.application /com/canonical/indicator/application/service com.canonical.indicator.application.service.GetApplications
```
Once you've got the icon names, you can paste the names here and i will fix it :)

See the Qt applications part 
https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/How-to-contribute

**Comment by dylanparry** [comment]
Thanks for the quick reply.

Here are the relevant sections from the command above:

### On application start

```
struct {
         string "MusicManager_8422_740a272c66baa9a105e48101377bd5a0"
         int32 4
         string "org.kde.StatusNotifierItem-8422-1"
         object path "/StatusNotifierItem/menu"
         string "/tmp/sni-qt_MusicManager_8422-HPTp7G/icons"
         string ""
         string ""
         string ""
         string "MusicManager"
         string "google-musicmanager"
      }
```

### After pausing

```
struct {
         string "MusicManager_8422_1e81c636c8e65b767474caf9dab52c37"
         int32 4
         string "org.kde.StatusNotifierItem-8422-1"
         object path "/StatusNotifierItem/menu"
         string "/tmp/sni-qt_MusicManager_8422-HPTp7G/icons"
         string ""
         string ""
         string ""
         string "MusicManager"
         string "google-musicmanager"
      }
```

The output after resuming is the same as the paused output.

Thanks :)

**Comment by dylanparry** [comment]
Also, the greyscale icon is in the `22x22` directory, whereas the colour version appears in the `32x32` directory within the `tmp` folder.

**Comment by bil-elmoussaoui** [comment]
The icon doesn't change with the original theme? Just wondering if the pause state should use a different icon

**Comment by dylanparry** [comment]
No, in the original theme it's the same coloured icon used for both paused and unpaused states. If it's different, then it's not noticeable to me---there doesn't appear to be any status indicator on the icon, and the colours used are the same.

**Comment by bil-elmoussaoui** [comment]
Fixed on master, you can use `hardcode-tray --update-git` to get the latest release right now or wait until Launchpad creates a new update if you've used the PPA to install it

**Comment by dylanparry** [comment]
Works wonderfully, thanks :+1:

**Comment by bil-elmoussaoui** [comment]
Don't hesitate to report any missing features or issues!
