### ISSUE TITLE
I Can't install the Hardcode-Tray stable from AUR, error of sha256sums

### ISSUE THREAD

**Issue by acutbal** [bil-elmoussaoui/Hardcode-Tray#367]
Hi!!
I can't install from AUR, I get an error of sha256sums. I attach a screenshot:
![captura de pantalla_2017-05-26_15-27-09](https://cloud.githubusercontent.com/assets/2278584/26496538/3bf26438-4228-11e7-92e7-900dd898f1ba.png)
Thank you very much!!

**Comment by bil-elmoussaoui** [comment]
I will fix that with a new release this evening. Yoi can use hardcode-tray-git from AUR

**Comment by acutbal** [comment]
Yes, that's what I've done. :+1: 

But now, I've a new issue, the config file hardcode-tray.json is missing... Do I open a new issue?

Thank you very much!!

**Comment by bil-elmoussaoui** [comment]
Nop it's up to you to create it. See the readme. It's just makes it easier for you to use the script without having to type all those arguments each time you use it.

**Comment by acutbal** [comment]
OK, I only need to fix Insync icon, so I should proceed as follows: To add this file I've create a new document with Mousepad (Xfce ;D), name it as hardcode-tray.json and leave it blank

Is this right?

**Comment by bil-elmoussaoui** [comment]
You don't have to create it at all... It's not required

**Comment by acutbal** [comment]
I apologize, English it's not my language... :smile: I attach a screenshot:
![captura de pantalla_2017-05-26_16-04-50](https://cloud.githubusercontent.com/assets/2278584/26497812/10b7d8c0-422d-11e7-96b2-50da27e2586f.png)
Hardcode-Tray crashes because it doesn't find such file. That's I was wondering if I should open or not a new issue.

Thank you very much for your help!!

**Comment by bil-elmoussaoui** [comment]
I just took a look at the code i will fix it as soon as I'm home in front of a computer. You can create an empty file if you don't want to wait :p

**Comment by acutbal** [comment]
Great, I'll wait your fixes. One million thanks for your interest :smile:  :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by acutbal** [comment]
Yes, it has worked:
![captura de pantalla_2017-05-26_16-53-34](https://cloud.githubusercontent.com/assets/2278584/26499744/f6e5ab6e-4233-11e7-9090-853c5c601c36.png)

But now I have a new problem, I have ran the command `hardcode-tray --apply --only insync --conversion-tool Inkscape` to fix my Insync icon. But I haven't realized that Insync was already running. So now I have a blank space where should be the Insync icon. Should I reinstall Insync and run again the command?

**Comment by bil-elmoussaoui** [comment]
Nop, just restart Insync :)

**Comment by acutbal** [comment]
This is the first thing that I've done... But, no luck:
![captura de pantalla_2017-05-26_16-53-42](https://cloud.githubusercontent.com/assets/2278584/26500095/0b580d84-4235-11e7-91b6-212a17c69cff.png)
Insync is running after quit and restart.

**Comment by bil-elmoussaoui** [comment]
Can you take a screenshot of the content of `/usr/share/icons/hicolor/48x48/status/`?  Also, try switching the state of Insync to pause and see if things are the same?

**Comment by acutbal** [comment]
> Also, try switching the state of Insync to pause and see if things are the same?
Nope, still the same.
Here the screenshot:
![captura de pantalla_2017-05-26_17-06-41](https://cloud.githubusercontent.com/assets/2278584/26500359/e3ae3690-4235-11e7-8657-47cda44a7109.png)

**Comment by bil-elmoussaoui** [comment]
Ah i see what causes your issue :P The theme is not detected correctly on xfce :( 
but you can force it using the argument `--theme Papirus` or by adding the theme to your config.json file

**Comment by acutbal** [comment]
`hardcode-tray --apply --only insync --conversion-tool Inkscape --theme Papirus
` doesn't work. Now I'm going to try with the json file. :smile:

**Comment by bil-elmoussaoui** [comment]
What do you mean by doesn't work? What's the output on the terminal? 
Can you try by removing those generated files first?
`cd /usr/share/icons/hicolor/48x48/status/ && sudo rm ./insync-*.png`

**Comment by acutbal** [comment]
Finally, deleting those files has fixed!! Just one thing, I see the icon weird, if like it was "bitten":
![captura de pantalla_2017-05-26_17-19-11](https://cloud.githubusercontent.com/assets/2278584/26500833/bc123eae-4237-11e7-8013-67a739fe8c01.png)

**Comment by bil-elmoussaoui** [comment]
You can try a smaller size like `--size 22

**Comment by acutbal** [comment]
With 24 is perfect now:
![captura de pantalla_2017-05-26_17-25-13](https://cloud.githubusercontent.com/assets/2278584/26500958/4da853f8-4238-11e7-9639-1c69486f15d6.png)

Really, thank you very much, I really appreciate your help!! I owe you a beer... :smile: :smile: :smile:

**Comment by bil-elmoussaoui** [comment]
Happy to hear that everything works perfectly for you :+1:
