### ISSUE TITLE
Mint 18.1 - small tray icons, no change to mintupdate and bluetooth icons

### ISSUE THREAD

**Issue by DanyGee** [bil-elmoussaoui/Hardcode-Tray#370]
### Specifications
- Hardcode-Tray version : `v3.8.2`
- Distribution : `Linux Mint 18.1 Serena`
- Gtk version : `Gtk 3.18.9-1ubuntu3.3`
- Inkscape version : ` 0.91 r13725`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `Telegram, Hexchat,Discord` - icons too small
Mint update & Bluetooth - icons not scaled
- Application version : `1.1.2, 2.10.2, 0.0.1`

### Expected behavior and actual behavior
Expected:Icons should have equal size and resolution.
Actual:Icons are different in size and resolution.
### Steps to reproduce the problem
1. Login
2. Watch tray icons
3. Apply hardcode-tray command
```bash
hardcode-tray --size 24 --theme Papirus-Dark --apply
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus-Dark
Conversion Tool: Inkscape
To Do: All
Applying now..

Clementine          [#####...............................] 1/7 14.3% 0.00s
Discord             [##########..........................] 2/7 28.6% 0.38s
Hexchat             [###############.....................] 3/7 42.9% 0.19s
Keepassx            [#####################...............] 4/7 57.1% 0.21s
Skype               [##########################..........] 5/7 71.4% 5.76s
Steam               [###############################.....] 6/7 85.7% 0.16s
Telegram            [####################################] 7/7 100.0% 0.45s
Took 7.15s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```
4.Restart apps and system
5. Check tray icons

Additional info:
Environment:

Distro: Linux Mint 18.1 Serena
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3)
WM Theme: Arc-Dark (Arc-Dark) 
Theme: Arc-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3]
Display Server: X.Org 1.18.4
Driver: nvidia
Resolution: 3840x2160@59.94hz
Interface scaling: x2
GLX Renderer: GeForce GTX 1080/PCIe/SSE2
GLX Version: 4.5.0 NVIDIA 381.22
Direct Rendering: Yes
Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)

Problem:

Bluetooth, Mint Update and Redshift icons don't scale to HiDPI and look blurry.
Telegram, Discord and Hexchat icons too little.

Command:
```bash
hardcode-tray --size 24 --theme Papirus-Dark --apply
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus-Dark
Conversion Tool: Inkscape
To Do: All
Applying now..

Clementine          [#####...............................] 1/7 14.3% 0.00s
Discord             [##########..........................] 2/7 28.6% 0.38s
Hexchat             [###############.....................] 3/7 42.9% 0.19s
Keepassx            [#####################...............] 4/7 57.1% 0.21s
Skype               [##########################..........] 5/7 71.4% 5.76s
Steam               [###############################.....] 6/7 85.7% 0.16s
Telegram            [####################################] 7/7 100.0% 0.45s
Took 7.15s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!

```
How it looks like:
https://1drv.ms/i/s!AoqBMCk_0jNCgbF-fUusQBYU2jcy9Q

**Comment by bil-elmoussaoui** [comment]
A screenshot will be good..

**Comment by DanyGee** [comment]
https://1drv.ms/i/s!AoqBMCk_0jNCgbF-fUusQBYU2jcy9Q

**Comment by bil-elmoussaoui** [comment]
For the Bluetooth icon, i can't do anything about it(it's an issue on Papirus icon theme, which should be reported upstream)
The same thing for mintupdate, as the icons, are not hardcoded anymore (i kept their support for older versions)

For Telegram and Hexchat, the issue is due to the really small icon size (24px compared to a  3840x2160 screen resolution is nothing...)
For now, tray icons are limited to 24px at max, but you can change that pretty easily by modifying this file https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/src/const.py#L42  (it should be on /opt/Hardcode-Tray/src/const.py)
And adding whatever icon sizes you wish to use; Try something like 48 or 64, after you've modified the file. Run Hardcode-Tray again and use `--size 48` instead of 24 which will fix your issue.

I limited the icon size to 24 because I'm afraid that some DE might not have a limited icon size and won't scale the icons down which might cause some issues for users if they use something like `--size 512`

**Comment by bil-elmoussaoui** [comment]
Happy to hear that! the best solution would be to use a scaling factor on mint but i don't even know if it's possible. Because for now, i only support scaling factor on GNOME & KDE. If you have any idea if it's possible to set or how to do so, just let me know and i will implement a proper solution.
Thanks for using Hardcode-Tray!

**Comment by DanyGee** [comment]
In Mint u can set interface scaling in system settings, which scales the whole interface, inlcuding icons.
Settings>General>Interface scaling 
We have 3 options:
1. Automatic
2. Standard
3. Double (HiDPI)

**Comment by bil-elmoussaoui** [comment]
i assume you're using cinnamon ? do you know where's the value is stored? GSettings? or a config file? I have never used mint before....

**Comment by bil-elmoussaoui** [comment]
@DanyGee Already implement on master. If you wish to give a try just run `hardcode-tray --update-git`

**Comment by DanyGee** [comment]
Unfortunately I dont know how it scales the hud.
Hardcode-Tray update seems to have finished successfully:
hardcode-tray --update-git
[sudo] hasło użytkownika dany:         
Downloading Hardcode-Tray ...
Cloning the repository...
Cloning into 'Hardcode-Tray'...
remote: Counting objects: 5118, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 5118 (delta 23), reused 24 (delta 9), pack-reused 5069
Receiving objects: 100% (5118/5118), 7.44 MiB | 3.39 MiB/s, done.
Resolving deltas: 100% (3571/3571), done.
Checking connectivity... done.
Creating symbolic link..
Hardcode-Tray was updated to git version successfully.
You can run the script using 'hardcode-tray'

Apllying this:
hardcode-tray --theme Papirus-Dark --apply
Welcome to Hardcode-Tray!
Desktop Environment: Cinnamon
Scaling Factor: 3
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: Inkscape
To Do: All
Applying now..

Clementine          [#####...............................] 1/7 14.3% 0.00s
Discord             [##########..........................] 2/7 28.6% 0.38s
Hexchat             [###############.....................] 3/7 42.9% 0.25s
Keepassx            [#####################...............] 4/7 57.1% 0.16s
Skype               [##########################..........] 5/7 71.4% 5.82s
Steam               [###############################.....] 6/7 85.7% 0.18s
Telegram            [####################################] 7/7 100.0% 0.50s
Took 7.30s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!

...did not scale the icons. They are small again. For now I'll use the workaround. I'll also try to find out how the scaling is handled in Mint. I'll post it here.

**Comment by bil-elmoussaoui** [comment]
Can you send me the log file that you can find under /tmp/Hardcode-Tray? this will help me debug why it's not working in your case

**Comment by DanyGee** [comment]
Sure
[29-05-2017_21-41-59.log.tar.gz](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1036543/29-05-2017_21-41-59.log.tar.gz)

**Comment by bil-elmoussaoui** [comment]
Okey should be fixed now :+1:

**Comment by DanyGee** [comment]
Updated.
Now getting this:
hardcode-tray --theme Papirus-Dark --apply
Welcome to Hardcode-Tray!
Desktop Environment: Cinnamon
Traceback (most recent call last):
  File "hardcode-tray.py", line 85, in <module>
    print("Scaling Factor: {}".format(App.scaling_factor()))
  File "/opt/Hardcode-Tray/src/app.py", line 161, in scaling_factor
    Logger.debug("Icon Size: {}".format(App._size))
AttributeError: type object 'App' has no attribute '_size'

**Comment by bil-elmoussaoui** [comment]
It was a typo, just fixed it! Sorry for that

**Comment by DanyGee** [comment]
Yep, now its working perfectly! THX!
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by bil-elmoussaoui** [comment]
You're welcome :) don't hesitate to share the script with other to make linux a beautiful place :D
