### ISSUE TITLE
Script fails on scaling factor

### ISSUE THREAD

**Issue by kennethso168** [bil-elmoussaoui/Hardcode-Tray#371]
### Specifications
- Hardcode-Tray version : `v3.8.2`
- Distribution : `Manjaro`
- Gtk version : `3.22.15`
- Inkscape version : `0.92.1` if installed
- Cairo version : `1.14.8` if installed
- Sni-qt version: `patched version provided by sni-qt` if installed

### Expected behavior and actual behavior
Expected: the script runs successfully
Actual: The script terminates with return value 1 with the following output
```
% hardcode-tray
Welcome to Hardcode-Tray!
Desktop Environment: Kde
Traceback (most recent call last):
  File "hardcode-tray.py", line 85, in <module>
    print("Scaling Factor: {}".format(App.scaling_factor()))
  File "/opt/Hardcode-Tray/src/app.py", line 158, in scaling_factor
    if scaling_factor > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### Steps to reproduce the problem
1. Run hardcode-tray

**Comment by bil-elmoussaoui** [comment]
Thanks for reporting! fixed

**Comment by yochaigal** [comment]
I have this exact issue on Arch Linux KDE Plasma 5.10.1

Welcome to Hardcode-Tray!
Desktop Environment: Kde
Traceback (most recent call last):
  File "hardcode-tray.py", line 85, in <module>
    print("Scaling Factor: {}".format(App.scaling_factor()))
  File "/opt/Hardcode-Tray/src/app.py", line 159, in scaling_factor
    if scaling_factor > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by bil-elmoussaoui** [comment]
This was fixed few days ago, please update to the latest version!

**Comment by yochaigal** [comment]
Ah, I switched to the git version on AUR and it works.
Thansk!

**Comment by bil-elmoussaoui** [comment]
Enjoy!
