### ISSUE TITLE
Don't work on Deepin

### ISSUE THREAD

**Issue by PrzemekSkw** [bil-elmoussaoui/Hardcode-Tray#372]
### Specifications
- Hardcode-Tray version : `3.8.2-1`
- Distribution : `Manjaro Deepin`
- Gtk version : ``
- Inkscape version : `0.92.1r` if installed
- Cairo version : `` if installed
- Sni-qt version: `r,-1` if installed
- Application name :  ``
- Application version : ``

Hi, I try hardcode-tray on Manjaro Deepin and it don't work.
I try to fix qbittorrent and telegram icons but it only see steam and broke it:
![image](https://cloud.githubusercontent.com/assets/25219988/26714095/244cf4a4-4770-11e7-991a-455e762727c4.png)
I try two times and now I can't fix my steam icon by revertin it because it shows only two versions.

**Comment by bil-elmoussaoui** [comment]
When you run the script on terminal what's the output you got ? Also, there's some log files on /tmp and that would be helpful if you can get me one of them.
By looking at your screenshot, you seem to be using an icon theme that doesn't support Hardcode-Tray.

**Comment by PrzemekSkw** [comment]
Hi, thanks for fast response. I use Papirus icon theme but this is Manjaro Deepin so maybe that's the problem. Output from terminal is:
`hardcode-tray
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Adwaita
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..

Steam               [####################################] 1/1 100.0% 0.00s
Took 0.00s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!`

and from log file is:

`[DEBUG] 2017-06-02 09:21:10 DE not detected.
[DEBUG] 2017-06-02 09:21:10 Arguments/Icon Size: None
[DEBUG] 2017-06-02 09:21:10 Config file: Not found.
[DEBUG] 2017-06-02 09:21:10 System/Icon Size: 22
[DEBUG] 2017-06-02 09:21:10 System/Theme: Adwaita
[DEBUG] 2017-06-02 09:21:10 Arguments/Conversion Tool: None
[DEBUG] 2017-06-02 09:21:10 Config/Conversion Tool: None
[DEBUG] 2017-06-02 09:21:10 SVG Factory: Import Inkscape
[DEBUG] 2017-06-02 09:21:12 Path with condition: dropbox_callback /home/przemek/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Path with condition: hangouts_callback /home/przemek/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 09:21:12 Config/Backup Ignore: False
[DEBUG] 2017-06-02 09:21:12 Create new backup folder for Steam
[DEBUG] 2017-06-02 09:21:12 Creating directory: /home/przemek/.config/Hardcode-Tray/Steam/02-06-2017_09-21-12/`

**Comment by bil-elmoussaoui** [comment]
Yeah, the icon theme is not detected correctly as Deepin doesn't use `org.gnome.interface.desktop icon-theme` to store the icon name; Do you have any idea what's the equivalent on Deepin? 
Also, what's the output of `echo $XDG_CURRENT_DESKTOP`

**Comment by bil-elmoussaoui** [comment]
(this just to help me add Deepin support for the rest of the users) otherwise, you can force the icon theme using --theme argument, see the readme for more information

**Comment by PrzemekSkw** [comment]
`echo $XDG_CURRENT_DESKTOP
Deepin`

only this
Can I reverse my steam icon by uninstalling hardcode-tray ?

**Comment by bil-elmoussaoui** [comment]
You can reverse the steam icon using hardcode-tray --revert --only steam and select the first backup (ordered by date)

**Comment by bil-elmoussaoui** [comment]
Anyway, as i said you can use `hardcode-tray --apply --theme Papirus`

**Comment by PrzemekSkw** [comment]
I have dconf editor on Deepin but it don't work properly I think. I find that:
![image](https://cloud.githubusercontent.com/assets/25219988/26716859/7428a0e4-477b-11e7-9507-76cd9f3015f9.png)

**Comment by bil-elmoussaoui** [comment]
Can you look for something like org.deepin.desktop.interface?

**Comment by PrzemekSkw** [comment]
`hardcode-tray --apply --theme Papirus`
and
`hardcode-tray --revert --only steam`
does nothing. Reverting don't work because it don't save my first icon and now when I reverting it's always broken.
I don't `have org.deepin.desktop.interface` only that I show above.

**Comment by bil-elmoussaoui** [comment]
Does nothing isn't helpful, what's the output on the terminal? + The log file ;)

**Comment by PrzemekSkw** [comment]
It's something strange with that Deepin DE because few things I want to change (like hide desktop icons) in dconf editor and it don't work. So maybe You can tell me how to manually change that steam icon and I will remove hardcode-tray and wait untill it will support Deepin?

**Comment by PrzemekSkw** [comment]
` hardcode-tray --apply --theme Papirus
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: All
Applying now..

Google Chrome       [#######.............................] 1/5 20.0% 3.72s
HP Printer          [##############......................] 2/5 40.0% 0.29s
Nylas N1(Mail)      [#############################.......] 4/5 80.0% 3.85s
Steam               [####################################] 5/5 100.0% 0.28s
Took 8.14s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!`

and

`hardcode-tray --revert --only steam
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Adwaita
Conversion Tool: Inkscape
To Do: Steam
Reverting now..

1) Steam/02-06-2017_09-07-06 
2) Steam/02-06-2017_09-21-12 
3) Steam/02-06-2017_10-09-22 
(Q)uit to cancel
Select a restore date : 1
Steam               [####################################] 1/1 100.0% 25.17s
Took 25.17s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!`

Log files:

`[DEBUG] 2017-06-02 10:09:14 DE not detected.
[DEBUG] 2017-06-02 10:09:14 Arguments/Icon Size: None
[DEBUG] 2017-06-02 10:09:14 Config file: Not found.
[DEBUG] 2017-06-02 10:09:14 System/Icon Size: 22
[DEBUG] 2017-06-02 10:09:14 Arguments/Theme: Papirus
[DEBUG] 2017-06-02 10:09:14 Arguments/Conversion Tool: None
[DEBUG] 2017-06-02 10:09:14 Config/Conversion Tool: None
[DEBUG] 2017-06-02 10:09:14 SVG Factory: Import Inkscape
[DEBUG] 2017-06-02 10:09:14 Path with condition: dropbox_callback /home/przemek/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Path with condition: hangouts_callback /home/przemek/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-06-02 10:09:14 Creating directory: /home/przemek/.local/share/sni-qt/icons/python2.7/22/
[DEBUG] 2017-06-02 10:09:14 Creating directory: /home/przemek/.local/share/sni-qt/icons/python3.5/22/
[DEBUG] 2017-06-02 10:09:14 Config/Backup Ignore: False
[DEBUG] 2017-06-02 10:09:14 Create new backup folder for Google Chrome
[DEBUG] 2017-06-02 10:09:14 Creating directory: /home/przemek/.config/Hardcode-Tray/Google Chrome/02-06-2017_10-09-14/
[DEBUG] 2017-06-02 10:09:14 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/google-chrome-tray.svg -e /tmp/tmpzbvreeu5 -w 22 -h 22
[ERROR] 2017-06-02 10:09:18 Couldn't find a PNG file.
[DEBUG] 2017-06-02 10:09:18 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/google-chrome-tray.svg -e /tmp/tmp5gekrg7x -w 22 -h 22
[DEBUG] 2017-06-02 10:09:18 Backup file: /tmp/10153 to: /home/przemek/.config/Hardcode-Tray/Google Chrome/02-06-2017_10-09-14/10153
[DEBUG] 2017-06-02 10:09:18 Executing command: chmod 0777 /home/przemek/.config/Hardcode-Tray/Google Chrome/02-06-2017_10-09-14/10153
[DEBUG] 2017-06-02 10:09:18 Create new backup folder for HP Printer
[DEBUG] 2017-06-02 10:09:18 Creating directory: /home/przemek/.config/Hardcode-Tray/HP Printer/02-06-2017_10-09-18/
[DEBUG] 2017-06-02 10:09:18 Backup file: /usr/share/hplip/data/images/32x32/hp_logo.png to: /home/przemek/.config/Hardcode-Tray/HP Printer/02-06-2017_10-09-18/hp_logo.png
[DEBUG] 2017-06-02 10:09:18 Executing command: chmod 0777 /home/przemek/.config/Hardcode-Tray/HP Printer/02-06-2017_10-09-18/hp_logo.png
[DEBUG] 2017-06-02 10:09:18 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/hp-indicator.svg -e /usr/share/hplip/data/images/32x32/hp_logo.png -w 22 -h 22
[DEBUG] 2017-06-02 10:09:18 Create new backup folder for Nylas N1(Mail)
[DEBUG] 2017-06-02 10:09:18 Creating directory: /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/
[DEBUG] 2017-06-02 10:09:18 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/nylas-tray-empty.svg -e /tmp/tmp2jcpg0xq -w 22 -h 22
[DEBUG] 2017-06-02 10:09:19 Backup file: /tmp/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Zero@2x.png to: /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Zero@2x.png
[DEBUG] 2017-06-02 10:09:19 Executing command: chmod 0777 /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Zero@2x.png
[DEBUG] 2017-06-02 10:09:20 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/nylas-tray-full.svg -e /tmp/tmpfza3rila -w 22 -h 22
[DEBUG] 2017-06-02 10:09:20 Backup file: /tmp/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full@2x.png to: /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full@2x.png
[DEBUG] 2017-06-02 10:09:20 Executing command: chmod 0777 /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full@2x.png
[DEBUG] 2017-06-02 10:09:21 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/nylas-tray-full-newitems.svg -e /tmp/tmpwegz0b6p -w 22 -h 22
[DEBUG] 2017-06-02 10:09:22 Backup file: /tmp/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full-NewItems@2x.png to: /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full-NewItems@2x.png
[DEBUG] 2017-06-02 10:09:22 Executing command: chmod 0777 /home/przemek/.config/Hardcode-Tray/Nylas N1(Mail)/02-06-2017_10-09-18/files|internal_packages|files|system-tray|files|assets|files|linux|files|MenuItem-Inbox-Full-NewItems@2x.png
[DEBUG] 2017-06-02 10:09:22 Create new backup folder for Steam
[DEBUG] 2017-06-02 10:09:22 Creating directory: /home/przemek/.config/Hardcode-Tray/Steam/02-06-2017_10-09-22/
[DEBUG] 2017-06-02 10:09:22 Executing command: inkscape -z -f /usr/share/icons/Papirus/22x22/panel/steam_tray_mono.svg -e /usr/share/pixmaps/steam_tray_mono.png -w 22 -h 22`

and

`[DEBUG] 2017-06-02 10:10:06 DE not detected.
[DEBUG] 2017-06-02 10:10:06 Arguments/Icon Size: None
[DEBUG] 2017-06-02 10:10:06 Config file: Not found.
[DEBUG] 2017-06-02 10:10:06 System/Icon Size: 22
[DEBUG] 2017-06-02 10:10:06 System/Theme: Adwaita
[DEBUG] 2017-06-02 10:10:06 Arguments/Conversion Tool: None
[DEBUG] 2017-06-02 10:10:06 Config/Conversion Tool: None
[DEBUG] 2017-06-02 10:10:06 SVG Factory: Import Inkscape
[DEBUG] 2017-06-02 10:10:06 Arguments/Only: steam
[DEBUG] 2017-06-02 10:10:06 Config/Backup Ignore: False
[DEBUG] 2017-06-02 10:10:31 No backup folder found for the application Steam`

**Comment by bil-elmoussaoui** [comment]
Hardcode-Tray was made to work on every linux distro and it works without any problem. The only issue here is that the icon theme is not detected correctly on deepin, i don't use deepin so i can't figure out from where i can get that value. That's why i asked for that information.

**Comment by bil-elmoussaoui** [comment]
The icon should be here /usr/share/pixmaps/steam_tray_mono.png , if not or the icon is broken you can remove it using `sudo rm /usr/share/pixmaps/steam_tray_mono.png` and recreate a new one using `sudo inkscape -z -f /usr/share/icons/Papirus/22x22/panel/steam_tray_mono.svg -e /usr/share/pixmaps/steam_tray_mono.png -w 22 -h 22`.

**Comment by PrzemekSkw** [comment]
I try IOS icons and steam icon changes:
![image](https://cloud.githubusercontent.com/assets/25219988/26717466/c97bf27e-477d-11e7-8bb3-084a326bda5e.png)
but not look like steam :)

**Comment by bil-elmoussaoui** [comment]
Have you tried to close the application and reopen it again ?

**Comment by PrzemekSkw** [comment]
Yes I close and open steam every time. I find that icon and something is wrong with it:
![image](https://cloud.githubusercontent.com/assets/25219988/26717604/4b82246e-477e-11e7-9026-31629db9e517.png)

**Comment by bil-elmoussaoui** [comment]
Can you follow the tips i've proposed below ? As the icon theme wasn't detected correctly the icon that was found was itself. I will push a fix for that as soon as i can but you can fix it as i said. Remove that icon and run the script again using --theme Papirus argument.

**Comment by PrzemekSkw** [comment]
Now it works :) thank You  very much for Your time and help.

**Comment by bil-elmoussaoui** [comment]
& I've fixed the issue that caused the broken symlink on master ;)
