### ISSUE TITLE
Big chrome icon

### ISSUE THREAD

**Issue by Feichtmeier** [bil-elmoussaoui/Hardcode-Tray#375]
### Specifications
- Hardcode-Tray version : `3.8.2`
- Distribution : `Ubuntu 16.04`
- Gtk version : `3.20`
- Inkscape version : `0.9.1` if installed
- Cairo version : `` if installed
- Sni-qt version: `no idea how to check this but I installed it from your repo
- Application name :  `google-chrome`
- Application version : `59.0.3071.86`

### Expected behavior and actual behavior
I would expect the icon to have the same size as other icons that have been successfully converted by hardcode-tray like telegram and dropbox but instead the icon size is much bigger - about 30% bigger (sea the screenshot)

### Steps to reproduce the problem
1. install GNOME 3.20, chrome, hardcode-tray
2. hardcode-tray -ct Inkscape
3. see big chrome icon
![screenshot from 2017-06-09 14-23-37](https://user-images.githubusercontent.com/15329494/26975417-f31bb04a-4d1f-11e7-83c4-7d6ffbf29ebf.png)

**Comment by bil-elmoussaoui** [comment]
Can you paste the content of the log file that can be found in /tmp/Hardcode-Tray/. The log files are ordered by date/time

**Comment by Feichtmeier** [comment]
There is no Hardcode-Tray folder in tmp :O
![screenshot from 2017-06-09 16-00-31](https://user-images.githubusercontent.com/15329494/26978721-d55b076a-4d2c-11e7-97e0-827e4c0b68e8.png)

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier Can you try running the script again and see what happen? you might have restarted your laptop since the last time you've used Hardcode-Tray. The files on /tmp folder are removed automatically whenever you restart your system.
Also, the output on the terminal would be great too.
Try running something like `hardcode-tray --apply -ct Inkscape --only google-chrome`

**Comment by Feichtmeier** [comment]
hardcode-tray --apply -ct Inkscape --only google-chrome
[sudo] password for mememe: 
Welcome to Hardcode-Tray!
Desktop Environment: Gnome
Scaling Factor: 2
Icon Size: 44
Icon Theme: Pop
Conversion Tool: Inkscape
To Do: Google-Chrome
Applying now..

Google Chrome       [####################################] 1/1 100.0% 2.76s
Took 2.76s to finish the tasks

Logfile which is now there (sorry):

[DEBUG] 2017-06-09 16:07:05 DE: Gnome
[DEBUG] 2017-06-09 16:07:05 Scaling Factor/GNOME: 2
[DEBUG] 2017-06-09 16:07:05 Arguments/Icon Size: None
[DEBUG] 2017-06-09 16:07:05 Config file: Not found.
[DEBUG] 2017-06-09 16:07:05 System/Icon Size: 22
[DEBUG] 2017-06-09 16:07:05 Icon Size: 44
[DEBUG] 2017-06-09 16:07:05 System/Theme/GSettings: Pop
[DEBUG] 2017-06-09 16:07:05 Arguments/Conversion Tool: Inkscape
[DEBUG] 2017-06-09 16:07:05 Arguments/Only: google-chrome
[DEBUG] 2017-06-09 16:07:05 Config/Backup Ignore: False
[DEBUG] 2017-06-09 16:07:05 Create new backup folder for Google Chrome
[DEBUG] 2017-06-09 16:07:05 Creating directory: /home/frederik/.config/Hardcode-Tray/Google Chrome/09-06$
[DEBUG] 2017-06-09 16:07:05 Executing command: inkscape -z -f /usr/share/icons/Pop/22x22@2x/panel/google$
[ERROR] 2017-06-09 16:07:07 Couldn't find a PNG file.
[DEBUG] 2017-06-09 16:07:07 Executing command: inkscape -z -f /usr/share/icons/Pop/22x22@2x/panel/google$
[DEBUG] 2017-06-09 16:07:08 Backup file: /tmp/10153 to: /home/frederik/.config/Hardcode-Tray/Google Chro$
[DEBUG] 2017-06-09 16:07:08 Executing command: chmod 0777 /home/frederik/.config/Hardcode-Tray/Google Ch$


Done, Thank you for using the Hardcode-Tray fixer!

**Comment by Feichtmeier** [comment]
It became indeed smaller! But when I apply it to all without the "--only " parameter will all icons become smaller? since telegram and insync and dropbox look fine. Now only the GPMDP looks big
![screenshot from 2017-06-09 16-15-37](https://user-images.githubusercontent.com/15329494/26979415-f9847b4c-4d2e-11e7-953e-a627db2c3e2f.png)

**Comment by varlesh** [comment]
I think it's bug HiDPI libappindicator, he don't have scale for SVG's. Papirus have only vector icons and 44px should bee rendered fine...
Similar bug https://github.com/Bajoja/indicator-kdeconnect/issues/53

**Comment by bil-elmoussaoui** [comment]
@varlesh Thanks for the feedback! Anyway, i wasn't going to modify anything as Scaling factor is detected correctly from Hardcode-Tray side...

**Comment by bil-elmoussaoui** [comment]
At worst, you can change the value of scaling factor to 1 again. And set whatever icon size you want. For now, the icon size must be one of the following values `16, 22, 24`. But you can change it pretty easily by modifying this file https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/src/const.py#L42 and adding another icon size for example 32 or 48... And use `hardcode-tray --size MYNEWSIZE`

I can't do more about this, as it's out of the purpose of Hardcode-Tray. If you think that the way the scaling factor works should be reworked please reopen the issue :)
