### ISSUE TITLE
Request: Icon for vmware player

### ISSUE THREAD

**Issue by dylanparry** [bil-elmoussaoui/Hardcode-Tray#377]
### Specifications
- Hardcode-Tray version : `3.9`
- Distribution : `Ubuntu Zesty (with Gnome Shell)`
- Gtk version : `3.22.11`
- Inkscape version : `0.92.1 r15371`
- Cairo version : `1.0.20`
- Sni-qt version: `0.2.7`
- Application name :  `vmware player/workstation`
- Application version : `12.5.6`

Hi,

Could you add icons for vmware player? Here's what it looks like at the moment:

![vmware](https://user-images.githubusercontent.com/3692873/27032579-66c154e2-4f6d-11e7-8623-c52ec030e434.png)

From what I can see, there's only the one icon in use. Pausing virtual machines doesn't change the green play icon to a pause or anything like that.

I have tried running:

```
dbus-send --type=method_call --print-reply --dest=com.canonical.indicator.application /com/canonical/indicator/application/service com.canonical.indicator.application.service.GetApplications
```

to get the config info for you, but got an error:

```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.indicator.application was not provided by any .service files
```

Which is presumably because I'm now using Gnome Shell instead of Unity. Is there an equivalent command I can run in Gnome?

Thanks.

**Comment by bil-elmoussaoui** [comment]
@dylanparry Hey, Thanks for reporting the issue! i will see what i can do about it. Yeah, it's because you're using Gnome instead of Unity. And i'm not aware if any equivalent exists, I will let you know if i ever find something else

**Comment by dylanparry** [comment]
Thanks. Looking at the processes running on my machine, it appears that the icon is provided by `vmware-tray`. That's assuming that the application name is sensible, and it's not doing something totally unrelated to the tray icon!

**Comment by bil-elmoussaoui** [comment]
At first look, it seems that VMware superposes two icons on top of each other. You can find the icons in `/usr/lib/vmware/share/icons` the "play" icon you see, is `vmware-powered-on` But I still didn't find out the "background" icon

**Comment by dylanparry** [comment]
It looks similar to the `vm-upload.png` icon, but that already has a badge. I wonder if it is that one with the play icon laid over it to cover the other badge?

**Comment by bil-elmoussaoui** [comment]
Maybe :P My computer is not that good to run vmware, you can backup those icons and just play with them using Gimp by changing the background color and see if the icon is changed! That will really helpful

**Comment by dylanparry** [comment]
I'll have a look to see if I can find the right icon and get back to you.

**Comment by dylanparry** [comment]
I've found a better fix... There's a setting to hide the icon and not show it in the tray at all, which is fine by me as I didn't really want it in the first place! Thanks for your help.

**Comment by bil-elmoussaoui** [comment]
As you wish :) at worst, you can still report that upstream and we hope they will get that fixed for the rest of VMware users :+1:
