### ISSUE TITLE
ghetto-skype not recognized in Arch Linux

### ISSUE THREAD

**Issue by marhkb** [bil-elmoussaoui/Hardcode-Tray#378]
### Specifications
- Hardcode-Tray version : `3.9.r0.g07dfcc6`
- Distribution : `Arch`
- Gtk version : `3.22.15`
- Inkscape version : `0.92.1`
- Cairo version : `1.14.8`
- Sni-qt version: `latest git`
- Application name :  `ghetto-skype`
- Application version : `1.5.0`

### Expected behavior and actual behavior
ghetto-skype should be recognized, but is not on Arch Linux. The cause may be that the paths are different.

[ghetto-skype_files.txt](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1068962/ghetto-skype_files.txt)

### Steps to reproduce the problem
1. run hardcode-tray --theme Papirus
2. Although ghetto-skype is installed, nothing is applied here

**Comment by bil-elmoussaoui** [comment]
Fixed on master
