### ISSUE TITLE
--size is multiplied with 3 (scaling factor)

### ISSUE THREAD

**Issue by marhkb** [bil-elmoussaoui/Hardcode-Tray#379]
### Specifications
- Hardcode-Tray version : `3.9.r1.gb4bb5ea`
- Distribution : `Arch`
- Gtk version : `3.22.15`
- Inkscape version : `0.92.1`
- Cairo version : `1.14.8`
- Sni-qt version: `latest git`
- Application name :  `ghetto-skype`
- Application version : `1.5.0`

### Expected behavior and actual behavior
by executing "hardcode-tray --size 22 --theme Papirus" I get the following output

```
Welcome to Hardcode-Tray!
Desktop Environment: Kde
Scaling Factor: 3
Icon Size: 66
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: All

1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..

Ghetto Skype        [#########...........................] 1/4 25.0% 0.33s
Steam               [##################..................] 2/4 50.0% 0.29s
Teamviewer          [###########################.........] 3/4 75.0% 0.00s
Telegram            [####################################] 4/4 100.0% 0.91s
Took 1.53s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```
the size i pass as argument is multiplied with 3, thus I got a cropped skype icon in Plasma. The help dialog shows no way to set scaling factor to 1.

**Comment by bil-elmoussaoui** [comment]
Well, because you've set 3 as a scaling factor on your system that you've got this result... can you share the log file? it can be found on /tmp/Hardcode-Tray/

**Comment by marhkb** [comment]
Ok, do you know where to set it back to 1? I cannot remember that I have ever changed such a value. Here is the log file

[12-06-2017_21-28-43.log.txt](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1069315/12-06-2017_21-28-43.log.txt)

**Comment by bil-elmoussaoui** [comment]
i will take a look this evening once I'm in front of a screen and a keyboard

**Comment by marhkb** [comment]
I solved it by myself after taking a look at source code. In file ".config/plasma-org.kde.plasma.desktop-appletsrc" there was an entry "iconSize=3". I don't know how it get there. Changing it back to "1" was the solution and has no other effect except that ghetto-skype symbol isn't cropped anymore.

**Comment by bil-elmoussaoui** [comment]
Sorry for the long delay. I was a little bit, and yeah the scaling factor on KDE is detected from that file as you've mentioned. 
If there's any other issues just let me know :+1:

**Comment by bil-elmoussaoui** [comment]
You can now set the scaling factor on the config.json file as explained on the README; This value will always overwrite your system settings
