### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by viggy96** [bil-elmoussaoui/Hardcode-Tray#380]
### Specifications
- Hardcode-Tray version : `3.5.2.1~830~ubuntu16.04.1`
- Distribution : `Ubuntu 16.04.2 LTS`
- Inkscape version : `0.91-7ubuntu2` 
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1` 
- Application name :  `Discord`
- Application version : `0.0.1`

### Expected behavior and actual behavior
Please add support for Discord system tray icon

**Comment by bil-elmoussaoui** [comment]
Discord is already supported. please upgrade to a newer version

**Comment by bil-elmoussaoui** [comment]
you can use hardcode-tray --update-git

**Comment by viggy96** [comment]
Upon using `hardcode-tray --update-git`:

`Traceback (most recent call last):
  File "hardcode-tray.py", line 104, in <module>
    App.execute()
  File "/opt/Hardcode-Tray/src/app.py", line 119, in execute
    delta = app.do_action(action)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 151, in do_action
    self.install()
  File "/opt/Hardcode-Tray/src/decorators.py", line 59, in wrapper
    func(app)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 97, in install
    self.execute(Action.APPLY)
  File "/opt/Hardcode-Tray/src/modules/applications/helpers/binary.py", line 51, in execute
    self.install_icon(icon, icon_path)
  File "/opt/Hardcode-Tray/src/modules/applications/pak.py", line 65, in install_icon
    png_bytes = get_pngbytes(icon)
  File "/opt/Hardcode-Tray/src/utils.py", line 242, in get_pngbytes
    App.icon_size())
  File "/opt/Hardcode-Tray/src/modules/svg/svg.py", line 87, in to_bin
    with open(outfile, 'rb') as temppng:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpip9cl4pv'
`

**Comment by bil-elmoussaoui** [comment]
Which conversion tool do you use? CairoSVG?

**Comment by viggy96** [comment]
ImageMagick was the conversion tool.

**Comment by bil-elmoussaoui** [comment]
Can you try using something else? just to know if it's the imagemagick backend that's broken or something else

**Comment by viggy96** [comment]
Do you know how I can install a different one?

**Comment by bil-elmoussaoui** [comment]
Just check the readme you can use Inkscape for example or python-cairosvg with librsvg

**Comment by viggy96** [comment]
Sorry, it works now, but it still doesn't fix the Discord icon.

**Comment by bil-elmoussaoui** [comment]
Hmm, i will take a look but i would like how did you installed Discord?
i will fix Imagemagick backend soon too

**Comment by viggy96** [comment]
I installed it with the deb package on the Discord website.

**Comment by bil-elmoussaoui** [comment]
Alright, i will fix it as soon as I'm home

**Comment by varlesh** [comment]
icon names and place not changed (fresh package from website discord-0.0.1.deb):
![image](https://user-images.githubusercontent.com/8083855/27077671-eaee5bbe-5041-11e7-8332-c2a5c72889b3.png)

**Comment by bil-elmoussaoui** [comment]
Can you paste the log file that can be found on /tmp/Hardcode-Tray?

**Comment by varlesh** [comment]
Not confirm this bug, all worked fine:
![image](https://user-images.githubusercontent.com/8083855/27077938-d4326ed2-5042-11e7-9c21-2dfeafa9f6fb.png)
hardcode-tray --theme Papirus-Dark -s 22 -ct Inkscape

**Comment by varlesh** [comment]
log https://pastebin.com/D5bhGsZd

**Comment by bil-elmoussaoui** [comment]
@varlesh i was asking the issue reporter :p

**Comment by varlesh** [comment]
@bil-elmoussaoui Bilal please add short option for `--theme` > `-t`

**Comment by bil-elmoussaoui** [comment]
@varlesh you can use the config.json file and you won't have to type any more arguments anymore, see the readme

**Comment by bil-elmoussaoui** [comment]
@viggy96 The ImageMagick backend is now fixed on master. The fact that Discord is not detected must be due to the non-detection of your current icon theme. You can force your current theme using either `--theme` argument or just use the config.json file which will make your life much much easier :)

**Comment by bil-elmoussaoui** [comment]
Closing as this issue is already fixed, please make sure that the theme is correctly set to Papirus or Numix or whatever theme that does support Hardcode-Tray
