### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by thob** [bil-elmoussaoui/Hardcode-Tray#381]
### Specifications
- Hardcode-Tray version : `3.9`
- Distribution : `Ubuntu 16.04`

I get this error message

![image](https://user-images.githubusercontent.com/755337/27092226-f09cc7fa-5062-11e7-8216-bbdc16e1cecf.png)

`hardcode-tray --theme Papirus` does work it seems

**Comment by bil-elmoussaoui** [comment]
Fixed on master.
The issue was due to me assmuing that Cinnamon stores the Icon Theme Name in `.config/gtk-3.0/settings.ini` and i've corrected that :)
