### ISSUE TITLE
manual KDE bugs fix possible?

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#387]
Hi all. It's not hardcode-tray bug, but maybe we can fix it?
By default on KDE draw only 22px icons for system tray apps. It's fine worked for KDE and Qt-apps. But for GTK and electron ugly (libindicator). Icons not draw with 22px size (i think likely draw 32px icons - it's blurred and big for tray).
For compare:
Bug already registered and confirmed https://bugs.kde.org/show_bug.cgi?id=366062
![image](https://user-images.githubusercontent.com/8083855/27378836-2a312786-568a-11e7-8744-effcba1e0b1a.png)
With hardcode-tray and Papirus-Dark:
![image](https://user-images.githubusercontent.com/8083855/27379518-923bbeac-568c-11e7-98a5-bda0393ee0a0.png)
See telegram icon looks fine, but wire blurred :(
On xembed-sni-proxy i found this [line](https://github.com/KDE/plasma-workspace/blob/master/xembed-sni-proxy/sniproxy.cpp#L51):
`static uint16_t s_embedSize = 32;` Maybe this problem?
Anyone know Qt5, C++ or maybe found another solution for fix this?

**Comment by varlesh** [comment]
i'm try red backgrond color for wire. Source file have size 22x22px, but on tray really used 20,5px or 21px:
![image](https://user-images.githubusercontent.com/8083855/27407840-16a7a6ca-56eb-11e7-8729-0c987973462d.png)
See, red square have 1px outline with transparent...
Anybody use KDE?

**Comment by varlesh** [comment]
@davidedmundson David you main developer, sorry for this report, but really [bug](https://bugs.kde.org/show_bug.cgi?id=366062) opened 2016-07-24 with Plasma 5.7 and not fixed on Plasma 5.10.2.

**Comment by davidedmundson** [comment]
*If* you're using libindicator you're not using xembedsniproxy.
Easiest way to tell, kill xembedsniproxy and see if the icon disappears.

**Comment by varlesh** [comment]
@davidedmundson thx for support, yes you right i kill xembedsniproxy and icon not disappears.

**Comment by bil-elmoussaoui** [comment]
Sadly i can't do anything about it; You can try by using a smaller size for Wire and the rest of electron apps and see if that helps. 
My C/C++ skills are not good enough to fix this issue upstream so...
