### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Jacobtey** [bil-elmoussaoui/Hardcode-Tray#390]
What about translating the script?

**Comment by bil-elmoussaoui** [comment]
Is this really needed? there's just few words that should be translated, the rest are just logs which i must keep in English so i can fix bugs easier ;)

**Comment by Jacobtey** [comment]
I think about 'hardcode-tray -h' after all .

**Comment by bil-elmoussaoui** [comment]
Makes sense, i will take care of that

**Comment by bil-elmoussaoui** [comment]
Fixed on master. You can now translate the file `po/hardcode-tray.pot` using Poedit 


:stop_sign: 
Don't update to master version yet, as i'm trying to fix this #385. A new version should land this evening

**Comment by bil-elmoussaoui** [comment]
I've pushed a new release, if you want to translate the script go ahead :+1:

**Comment by Jacobtey** [comment]
Oops! I can't find `po/hardcode-tray.pot` or I'm looking for smth wrong

**Comment by bil-elmoussaoui** [comment]
Here you go https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/po/hardcode-tray.pot

**Comment by Jacobtey** [comment]
ок

**Comment by bil-elmoussaoui** [comment]
The original strings might be really awful, as my English skills are not that good. If you want to update anything just go ahead ;)
