### ISSUE TITLE
Update PPA

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#391]
I've just pushed a new release which introduces translations and few bugs fixes 
In order to get translations to work, i had to use a build system (Meson here). And I've also removed the update & update-git options as it's now easier to update the script using meson.

The PPA should be updated to use meson build system. I've added the build commands to the README.

@wa4557 Do you think that you will have some free time to take a look at this? My Debian packaging skills are close to 0

**Comment by wa4557** [comment]
Yes. But not overly soon. I'm occupied until Thursday...

**Comment by wa4557** [comment]
Your commands in the README don't work.

`meson builddir --prefix=/usr`

```
Error during basic setup:

[Errno 2] No such file or directory: '/home/andreas/Diverses/Hardcode-Tray/builddir'
```

**Comment by wa4557** [comment]
If I create an empty folder called `builddir` I get a different error :

```
The Meson build system
Version: 0.29.0
Source dir: /home/andreas/Diverses/Hardcode-Tray
Build dir: /home/andreas/Diverses/Hardcode-Tray/builddir
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

Please make sure that the commands are correct otherwise I cannot update the ppa.

**Comment by bil-elmoussaoui** [comment]
The commands do work. I just forgot to mention that you need meson > 0.40. You can upgrade to this version using pip. `sudo pip3 install --upgrade meson`

**Comment by wa4557** [comment]
Ok, got it now. There might be an issue though, ppa with meson are apparently not supported... Will further investigate

**Comment by bil-elmoussaoui** [comment]
Thank you very much!!! I will take a look too as soon as I can

**Comment by wa4557** [comment]
@bil-elmoussaoui 

I think  figured out how to do it, however on launchpad they use an older meson version. Can you change the meson.build files such that the also work with lower versions?

**Comment by bil-elmoussaoui** [comment]
@wa4557 older versions doesn't work as expected with gettext for translations... I will take a look anyway. Launchpad is really the worst tool ever invented in the history of Linux. 
I think one of the best way to fix this, is to create a deb package using Travis CI and upload it directly into the releases archives

**Comment by wa4557** [comment]
My packaging skills are also only ...semi good...
And I have to learn everything the hard way. But I think it should be possible

**Comment by wa4557** [comment]
As expected the packaging does not work with the provided `meson.build` file. 

https://launchpadlibrarian.net/328244612/buildlog_ubuntu-yakkety-amd64.hardcode-tray_3.5.2.1~849~ubuntu16.10.1_BUILDING.txt.gz

If we would be able to change the meson version, I guess it would work

**Comment by bil-elmoussaoui** [comment]
@wa4557 I will try to get this to work or at least provide a patch for the PPA

**Comment by wa4557** [comment]
I asked on AskUbuntu

https://askubuntu.com/questions/936337/build-launchpad-ppa-packages-with-backport-version

Building on trusty won't be possible though, because in trusty there is no meson package

**Comment by varlesh** [comment]
i think better solution for all distros - it's appimage package - portable and worked on all distros... but only we need patched sni-qt library on deb's

**Comment by varlesh** [comment]
More info here:
https://github.com/AppImage/AppImageKit/blob/appimagetool/master/README.md

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by bil-elmoussaoui** [comment]
@probonopd  I don't know how AppImage works internally. But the case here is the app(cli here) runs only from terminal and must have access to the user's file system. Can be this done using AppImage?

**Comment by probonopd** [comment]
Yes.

**Comment by bil-elmoussaoui** [comment]
Alright, i will see what i can during this week/weekend.  I might need some help. Do you mind if a ping you or is there an official iirc where i can get some help?

**Comment by probonopd** [comment]
Sure, either ask me here or drop by #AppImage on irc.freenode.net

**Comment by wa4557** [comment]
Even thoug an AppImage would be great I still think that a working PPA would make sense. 
I got meson to work but now I have a different problem I don't know how to solve

@bil-elmoussaoui I think the issue is that there is no "build" command in meson.build. Because the install thing is not what is needed for building the deb file. Can you look into that?

Here the logfile of the (failed) build

**Comment by bil-elmoussaoui** [comment]
@wa4557 Sorry for the delay. I think you forgot to copy/paste the logfile content here :P

**Comment by bil-elmoussaoui** [comment]
By taking a look at the current PPA build status, i think i might have figured out how to fix that issue. I'm forcing to install the content of the database files into /opt/HardcodeTray but that won't work for fake root. I have fixed that on my alpha branch, but there are few things to be fixed there before i can merge into the master branch. i will try to do that before the weekend and hopefully, we will get the latest release on the PPA! :+1:

**Comment by wa4557** [comment]
@bil-elmoussaoui Cool. But you must not update meson to 0.41 otherwise a PPA won't work! The latest version of meson in Trusty/Xenial is 0.40.1. So if your script also works with 0.40 we have to keep it

**Comment by bil-elmoussaoui** [comment]
I will not, we don't use any new features from 0.41 (the latest thing we use the python module on Meson which was released with the 0.40 version http://mesonbuild.com/Python-3-module.html)

**Comment by wa4557** [comment]
Was just looking at your commit messages. It says 0.41 :)

**Comment by bil-elmoussaoui** [comment]
It must be a typo (see https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/alpha/meson.build#L3)

**Comment by wa4557** [comment]
is the alpha branch already usable? Wanna try if packaging works

**Comment by bil-elmoussaoui** [comment]
Yep should work as expected :+1:

**Comment by wa4557** [comment]
I get :` Native dependency 'gobject-introspection-1.0' not found`

**Comment by bil-elmoussaoui** [comment]
We need also `libgirepository1.0-dev` in order to make it detectable using pkgconfig

**Comment by wa4557** [comment]
And for gtk+-3.0?

**Comment by bil-elmoussaoui** [comment]
it must be `libgtk3-dev`

**Comment by wa4557** [comment]
Got it it's `libgtk-3-dev`
Still get a permission error though :( `PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages'`

**Comment by bil-elmoussaoui** [comment]
@wa4557 I think that you might need to use the --prefix argument somewhere? as I don't force installing on /usr/lib at all see 
 https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/alpha/meson.build#L28 which all does is installing on `PREFIX/python libraries location`

**Comment by wa4557** [comment]
So which `--prefix` should I use? Isn't the standard python location in `usr/lib/python3.5`?

**Comment by wa4557** [comment]
Never mind, I get a new permission error now 

```
Traceback (most recent call last):
  File "/usr/share/meson/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/share/meson/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 306, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 124, in do_install
    install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 139, in install_subdirs
    os.makedirs(dst_dir)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/hardcode-tray'
```

**Comment by bil-elmoussaoui** [comment]
It depends on the Python version shipped with the Ubuntu version :/ The python path is detected automatically thanks to Meson.
 
For the /usr/local/share i don't see what it's saying that there's a permission error :/. That shouldn't be a problem?

**Comment by wa4557** [comment]
As a normal user I can't install to `/usr` right?

**Comment by bil-elmoussaoui** [comment]
Nop, normal users can't install any deb file at all...

**Comment by bil-elmoussaoui** [comment]
But for packaging, you should be able to create /usr/share/Hardcode-Tray/ without any issue as launchpad build system uses a fake root

**Comment by wa4557** [comment]
But still I should be able to build the deb file. Oh boy I know so little about packaging, just trying random stuff :)

**Comment by wa4557** [comment]
Can you have a look at this? They seem to have a working `meson.build` on launchpad

https://bazaar.launchpad.net/~ztefn/haguichi/meson-build/view/head:/meson.build

**Comment by bil-elmoussaoui** [comment]
Hey the problem isn't on meson :P As i have switched recently Lollypop from Autotools to Meson and the build works just fine. It seems that they use something like this for the nina -C install 
`DESTDIR=/<<PKGBUILDDIR>>/debian/lollypop ninja -C build -v install`
In our case it must be
`DESTDIR=/<<PKGBUILDDIR>>/debian/hardcode-tray ninja -C builddir -v install`
I don't know where this should be placed :P maybe in the rules file?
Here's the log file of the build 
https://launchpadlibrarian.net/328570949/buildlog_ubuntu-artful-amd64.lollypop_0.9.244-1ppa1ubuntu1.2_BUILDING.txt.gz

**Comment by wa4557** [comment]
Yes I guess you're right. Now I need to find the `debian` folder for lollypop somewhere to reverse engineer it...

**Comment by bil-elmoussaoui** [comment]
@wa4557 
Here's the rules file of Lollypop
```bash
#!/usr/bin/make -f

override_dh_auto_clean:
	rm -fr build

override_dh_auto_configure:
	mkdir -p build
	cd build && meson .. --prefix=/usr

override_dh_auto_build:
	cd build && ninja -v

override_dh_auto_test:
	cd build && ninja test

override_dh_auto_install:
	DESTDIR=$(CURDIR)/debian/lollypop ninja -C build -v install

%:
	dh $@
```

**Comment by wa4557** [comment]
Got it working :) Can I change the file in the master branch?

**Comment by wa4557** [comment]
Nevermind you already merged, awesome

**Comment by bil-elmoussaoui** [comment]
What's the next step? Should i create a new release to trigger the PPA update?

**Comment by wa4557** [comment]
@bil-elmoussaoui Already building. That's ok its adaily build anyways

**Comment by bil-elmoussaoui** [comment]
Trusty doesn't have the needed version of Ninja either + it's not supported anymore. People should upgrade to 16.04 or build from source code by installing meson using `pip3 install meson` and building ninja from source code...
This can now be closed? 
I will create a new issue for the AppImage as it's a completely different story....

**Comment by wa4557** [comment]
Wait a moment, I get a few warnings during build. Might be worth looking into:
```
E: hardcode-tray source: source-contains-unsafe-symlink HardcodeTray
E: hardcode-tray source: source-contains-unsafe-symlink README.md
E: hardcode-tray source: source-contains-unsafe-symlink const.py.in
E: hardcode-tray source: source-contains-unsafe-symlink data
E: hardcode-tray source: source-contains-unsafe-symlink debian
E: hardcode-tray source: source-contains-unsafe-symlink hardcode-tray.py.in
E: hardcode-tray source: source-contains-unsafe-symlink license
E: hardcode-tray source: source-contains-unsafe-symlink meson.build
E: hardcode-tray source: source-contains-unsafe-symlink po
E: hardcode-tray source: source-contains-unsafe-symlink screenshots
E: hardcode-tray source: source-contains-unsafe-symlink src
E: hardcode-tray source: build-depends-on-build-essential build-depends
W: hardcode-tray source: ancient-standards-version 3.9.3 (current is 3.9.7)
W: hardcode-tray: copyright-without-copyright-notice
E: hardcode-tray: extended-description-is-empty
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/ usr/lib/python3/dist-packages/HardcodeTray/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/app.py usr/lib/python3/dist-packages/HardcodeTray/app.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/const.py usr/lib/python3/dist-packages/HardcodeTray/const.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/decorators.py usr/lib/python3/dist-packages/HardcodeTray/decorators.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/enum.py usr/lib/python3/dist-packages/HardcodeTray/enum.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/ usr/lib/python3/dist-packages/HardcodeTray/modules/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/ usr/lib/python3/dist-packages/HardcodeTray/modules/applications/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/application.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/application.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/electron.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/electron.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/ usr/lib/python3/dist-packages/HardcodeTray/modules/applications/helpers/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/asar.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/helpers/asar.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/binary.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/helpers/binary.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/helpers/data_pack.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/extract.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/helpers/extract.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/nwjs.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/nwjs.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/pak.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/pak.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/qt.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/qt.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/zip.py usr/lib/python3/dist-packages/HardcodeTray/modules/applications/zip.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/backup.py usr/lib/python3/dist-packages/HardcodeTray/modules/backup.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/config/ usr/lib/python3/dist-packages/HardcodeTray/modules/config/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/config/arguments.py usr/lib/python3/dist-packages/HardcodeTray/modules/config/arguments.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/config/json.py usr/lib/python3/dist-packages/HardcodeTray/modules/config/json.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/config/system.py usr/lib/python3/dist-packages/HardcodeTray/modules/config/system.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/icon.py usr/lib/python3/dist-packages/HardcodeTray/modules/icon.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/log.py usr/lib/python3/dist-packages/HardcodeTray/modules/log.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/parser.py usr/lib/python3/dist-packages/HardcodeTray/modules/parser.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/path.py usr/lib/python3/dist-packages/HardcodeTray/modules/path.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/ usr/lib/python3/dist-packages/HardcodeTray/modules/svg/
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/cairosvg.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/cairosvg.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/imagemagick.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/imagemagick.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/inkscape.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/inkscape.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/rsvgconvert.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/rsvgconvert.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/svg.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/svg.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/svg/svgexport.py usr/lib/python3/dist-packages/HardcodeTray/modules/svg/svgexport.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/modules/theme.py usr/lib/python3/dist-packages/HardcodeTray/modules/theme.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/path.py usr/lib/python3/dist-packages/HardcodeTray/path.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/tools.py usr/lib/python3/dist-packages/HardcodeTray/tools.py
W: hardcode-tray: python-module-in-wrong-location usr/lib/python3.5/site-packages/HardcodeTray/utils.py usr/lib/python3/dist-packages/HardcodeTray/utils.py
W: hardcode-tray: extra-license-file usr/share/hardcode-tray/license/BSD
W: hardcode-tray: extra-license-file usr/share/hardcode-tray/license/GPL
W: hardcode-tray: binary-without-manpage usr/bin/hardcode-tray
W: hardcode-tray: executable-not-elf-or-script usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py
```

**Comment by bil-elmoussaoui** [comment]
`W: hardcode-tray: executable-not-elf-or-script usr/lib/python3.5/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py` Fixed that on master
I think somehow it complains about installing some files in usr instead of /usr

**Comment by wa4557** [comment]
What about the location of the python module?

**Comment by bil-elmoussaoui** [comment]
I've just downloaded the latest deb, extracted it and everything seems to be okey. I don't have an Ubuntu machine at the moment to try it

**Comment by wa4557** [comment]
It's not ok. Ubuntu does not recognize the installed python module...

**Comment by bil-elmoussaoui** [comment]
i've tried the latest package in elementary OS and everything is installed correctly except the executable file...

**Comment by bil-elmoussaoui** [comment]
@wa4557 Should be fixed now https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/5250d099232f7064f77d63f4fbab18c21dc33459

**Comment by wa4557** [comment]
Cool, I'll check it out. I don't know why the executable is not installed, though...

**Comment by bil-elmoussaoui** [comment]
Thanks for your work on this @wa4557. We have finally got a working PPA again :P
