### ISSUE TITLE
Support more apps

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#4]
Wel, still needs to support more apps : 
- [x] Viber -wontfix- 
- [x] Spotify
- [ ] Google chrome
- [x] Telegram 
- [ ] Google Music Manager 

Sni-qt apps? I'm not sure that i will implement anything like this in my code..But who knows
- [ ] Megasync 
- [ ] Skype 
- [x] OwnCloud -not hardcoded-

**Comment by bil-elmoussaoui** [comment]
For Viber ,the icon used as an indicator is 16x16.png which is not very specific as an icon name. I really don't have any ideas about this?

**Comment by wa4557** [comment]
This could be circumvented by using an additional column in your csv. One column for the name of the icon in the icon theme, one for the icon name that is hardcoded and the symlink (or converted png) is pointing to

**Comment by bil-elmoussaoui** [comment]
I thought about this too, but if i do so the designers must choose the same name of the viber indicator? 
For the Spotify and google chrome icons. We have to open a zip file, change the icon file and compress it again, So maybe i will create a bash script for this.

**Comment by wa4557** [comment]
No. I don't think so. You just symlink `viber-indicator.svg` or whatever the designer want to call it. Afterwards you can symlink it to `24x24.png` (or convert it to this filename). 
Yeah google is not really doable I think, spotify probably is

**Comment by bil-elmoussaoui** [comment]
I will try this. I think about writing a code that will look if there's any icon that uses viber in it's name and use it? That will make the designers free to use whatever they want as an icon name? And i will implement this asap

**Comment by bil-elmoussaoui** [comment]
Just to have your point of view. For spotify the app uses some icons in a zip file. The fastest way is to write a bash script code to do this and call it in the python script?

**Comment by wa4557** [comment]
Much late replay:/ yes Most definitely the fastest Way python is really bad in handling zip files

**Comment by bil-elmoussaoui** [comment]
It's not a problem! i will support the rest of applications after my finals

**Comment by wa4557** [comment]
Owncloud is Not hardcoded

**Comment by bil-elmoussaoui** [comment]
Owncloud is qt application to change the icons you've to install a patched version of sni-qt and copy the icons to ```/tmp ```
the same case is for megasync and skype

**Comment by wa4557** [comment]
I'm using owncloud right now, and the icons from numix are used

**Comment by bil-elmoussaoui** [comment]
Well, if you say so :D the last time i used owncloud, i had such ugly icons

**Comment by bil-elmoussaoui** [comment]
Do you have any idea how to open a ```.pak``` archive file? if it's possible of course

**Comment by wa4557** [comment]
There seems to be a python script that can work with `.pak` files. You could add that to the script folder...
https://code.google.com/p/grit-i18n/source/browse/trunk/grit/format/data_pack.py

**Comment by bil-elmoussaoui** [comment]
@wa4557 can you take a look at this ? [ElementaryPlus Owncloud Icon issue](https://github.com/mank319/elementaryPlus/issues/137) and confirm that's working for you?

**Comment by wa4557** [comment]
I'm using version owncloud 1.7 the icons change correct. For me these icons are NOT hardcoded

**Comment by bil-elmoussaoui** [comment]
Well, i tried the 1.8.1 version in Ubuntu 14.04.2 and this is how its looks like 
![screenshot from 2015-05-31 12 12 56](https://cloud.githubusercontent.com/assets/7660997/7901555/90d32acc-078e-11e5-8c62-822d1cb8ee34.png)

**Comment by wa4557** [comment]
Ubuntu 15.04 with owncloud 1.7
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7901768/8dc3b472-0799-11e5-9be3-0522346e9ffa.png)

**Comment by Foggalong** [comment]
ownCloud is hardcoded for me, Xubuntu 15.04 client 1.7 :/

**Comment by wa4557** [comment]
oO 
I have my package from there: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by Foggalong** [comment]
Yup, mine from the same location :(

**Comment by bil-elmoussaoui** [comment]
To fix ownCloud (and the rest of icons in this list too) we will need to install a patched version of sni-qt

**Comment by bil-elmoussaoui** [comment]
@wa4557 @Foggalong Can you give me the path of ownCloud? i'm going to add sni-qt apps soon

**Comment by Foggalong** [comment]
Here are all the ownCloud data locations I could find:

* /usr/share/owncloud/
* /usr/bin/owncloud
* ~/.local/share/data/ownCloud/

**Comment by wa4557** [comment]
same here

**Comment by bil-elmoussaoui** [comment]
@Foggalong @wa4557 I added a support to sni-qt applications, i still need a bash script to convert svg icons to png icons like the one used for spotify. The icons must be copied into ```~/.local/share/sni-qt/icons/```

**Comment by wa4557** [comment]
I can do this on the weekend if you wish?

Bilal Elmoussaoui <notifications@github.com> schrieb am Do., 2. Juli 2015
um 17:44 Uhr:

**Comment by Foggalong** [comment]
I don't have that folder on my machine :/

**Comment by bil-elmoussaoui** [comment]
You have to installed the patched version of sni-qt and restart your machine first

**Comment by wa4557** [comment]
And where do I get this patched version?

**Comment by bil-elmoussaoui** [comment]
I added a ppa in the readme, im not sure that's the latest version. If its not the case i will create a new ppa for that

**Comment by wa4557** [comment]
and what if I'm not on a debian based distro (fedora?)

**Comment by bil-elmoussaoui** [comment]
You can download it from here i guess : [Package Sni-qt](https://apps.fedoraproject.org/packages/sni-qt)

**Comment by Foggalong** [comment]
I still don't have that folder after installing the package

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you try installing this version [elementaryPlus sni-qt](https://answers.launchpad.net/~cybre/+archive/ubuntu/elementaryplus). The one in the ppa is outdated

**Comment by bil-elmoussaoui** [comment]
@wa4557 yeah, you can do that if you want to :+1:

**Comment by wa4557** [comment]
@bil-elmoussaoui What has the script to do exactly?

**Comment by bil-elmoussaoui** [comment]
The script will convert the svg icons sent as a parameter to the script, and save them in ```.local/share/sni-qt/icons/``` as a png icons with a new name that is sent as a parameter too

**Comment by wa4557** [comment]
Give me a sec.

**Comment by wa4557** [comment]
@bil-elmoussaoui If the source icon is a png (like in the `moka` icon theme) is then symlinking enough or should the file be copied?

**Comment by bil-elmoussaoui** [comment]
@wa4557 a symlink will be fine

**Comment by bil-elmoussaoui** [comment]
I will close and open a seperate issue for each application
