### ISSUE TITLE
Plasma 5 what wrong?

### ISSUE THREAD

**Issue by romanlex** [bil-elmoussaoui/Hardcode-Tray#400]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Arch Linux`
- Gtk version : `3.22`
- Inkscape version : `0.92.1 r` if installed
- Cairo version : `` if installed
- Sni-qt version: `from AUR sni-qt-patched-git` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
Expect icons from Papirus Icon Theme or 
![image](https://user-images.githubusercontent.com/3369304/27872287-f15e92f4-61b0-11e7-8568-c80b27b3e897.png)

### Steps to reproduce the problem
1. ```hardcode-tray --theme Papirus```
2. Look panel icons
![image](https://user-images.githubusercontent.com/3369304/27872218-ba2c29fe-61b0-11e7-8349-f4061ca7789c.png)

What i'm doing wrong?
Why my icons not converted

Plasma 5

**Comment by bil-elmoussaoui** [comment]
What's the output on terminal? And can you also send the logs that can be found on /tmp/Hardcode-Tray

**Comment by romanlex** [comment]
@bil-elmoussaoui 
console output:

> [roman@n550jv ~]$ LANG=en sudo hardcode-tray --theme Papirus --dark-theme Papirus-Light
> Welcome to Hardcode-Tray!
> Desktop Environment: Other
> Scaling Factor: 1
> Icon Size: 22
> Icon Theme: Papirus
> Conversion Tool: Inkscape
> To Do: All
> 1 - Apply
> 2 - Revert
> 3 - Clear Backup Cache
> Please choose: 1
> Applying now..
> 
> 
> Chromium            [###.................................] 1/12 8.3% 3.38s
> Clementine          [######..............................] 2/12 16.7% 0.00s
> Google Chrome       [#########...........................] 3/12 25.0% 3.54s
> Megasync            [############........................] 4/12 33.3% 0.00s
> Skype               [###############.....................] 5/12 41.7% 0.01s
> Steam               [#####################...............] 7/12 58.3% 0.22s
> Teamviewer          [########################............] 8/12 66.7% 0.00s
> Telegram            [###########################.........] 9/12 75.0% 1.06s
> Trimage             [##############################......] 10/12 83.3% 0.22s
> Vivaldi             [#################################...] 11/12 91.7% 3.58s
> Whatsie             [####################################] 12/12 100.0% 0.64s
> Took 21.45s to finish the tasks
> 
> Done, Thank you for using the Hardcode-Tray fixer!

log:
[05-07-2017_20-38-56.txt](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1125534/05-07-2017_20-38-56.txt)

**Comment by bil-elmoussaoui** [comment]
Which Skype version is this? electron or Qt?

**Comment by romanlex** [comment]
@bil-elmoussaoui 
Qt version.
Megasync and Octopi from AUR

**Comment by bil-elmoussaoui** [comment]
Well, it must be an issue with our patched version of sni-qt :( I'm using arch as well and I wasn't able to get it to work.

Octopi is not supported as the icons are hardcoded on the binary file

**Comment by varlesh** [comment]
@romanlex 
- Skype 4.3 discontinued from 1 july 2017, use new electron version. (hardcode-tray supported)
- MegaSync - not supported anymore, because tray icon now on binary file, see [this](https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/296)
- Octopi fresh version from git now have option for choose icon tray, see [this](https://github.com/aarnt/octopi/issues/156)

**Comment by bil-elmoussaoui** [comment]
Closing as i can't do anything about this yet. There's an open issue for each issue you've mentionned.
