### ISSUE TITLE
Syncthing-GTK support

### ISSUE THREAD

**Issue by mnmlguy** [bil-elmoussaoui/Hardcode-Tray#402]
Hi! Thanks for the awesome script!

Would love to see support for Syncthing-GTK if possible.
https://github.com/syncthing/syncthing-gtk
Papirus icon theme already has the icons for it.

Cheers!

**Comment by mnmlguy** [comment]
Sorry for bothering you. I've figured out why Papirus icons didn't work.
Syncthing-GTK needs .png icons instead of .svg that are provided with the icon theme.
Simple conversion to png did the thing.

**Comment by varlesh** [comment]
@mnmlguy Update last version from git, i'm fix icon names:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/9a818a91500d0e2b690619ff6e25169c223337c4
