### ISSUE TITLE
installed but icon tray in random theme

### ISSUE THREAD

**Issue by artkis** [bil-elmoussaoui/Hardcode-Tray#404]
### Specifications
- Hardcode-Tray version : `3.5.2.1~837~ubuntu17.04.1`
- Distribution : `Ubuntu GNOME 17.04 64-bit`
- Gtk version : `libgtk-3-bin	3.22.11-0ubuntu3`
- Inkscape version : `0.92.1-1`
- Cairo version : `1.15.4-0intel1`
- Sni-qt version: `0.2.7+20161212~10~ubuntu17.04.1`
- Application name :  `vlc, qbittorrent, dropbox`
- Application version : `vlc 2.2.4-14ubuntu2.1, qbitorrent3.3.13-1ppa1~zesty, dropbox 2015.10.28`
### Expected behavior and actual behavior
![screenshot from 2017-07-13 21-47-52](https://user-images.githubusercontent.com/30148306/28180251-a1ebeb5c-6815-11e7-8f08-058294fde4ad.png)
![screenshot from 2017-07-13 21-45-50](https://user-images.githubusercontent.com/30148306/28180253-a208828a-6815-11e7-9350-4a1cd115dc28.png)
### Steps to reproduce the problem
1. GNOME EXTENSION at top bar: dynamic panel transparency, gnome shutdown button, topicon plus, user themes, caffeine

**Comment by bil-elmoussaoui** [comment]
the qbitorrent is not hardcoded. It uses the Papirus icon theme. Neither is the VLC. 
For the dropbox icon, what's the output in the terminal? + The logs from /tmp/Hardcode-Tray/

**Comment by artkis** [comment]
i done this to terminal:
Swipe your finger across the fingerprint reader
Welcome to Hardcode-Tray!
Desktop Environment: Gnome
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus.foldercolor
Conversion Tool: ImageMagick
To Do: All
Applying now..

Chromium            [#########...........................] 1/4 25.0% 23.00s
Clementine          [##################..................] 2/4 50.0% 0.00s
Skype               [###########################.........] 3/4 75.0% 32.40s
WebTorrent Desktop  [####################################] 4/4 100.0% 1.16s
Took 56.56s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
I check that vlc, qbittorrent and the one i forgot yesterday is clipgrab is the same- no change.
tmp/Hardcode-Tray/- (not found)

**Comment by bil-elmoussaoui** [comment]
its /tmp and not tmp/

**Comment by artkis** [comment]
[DEBUG] 2017-07-14 14:17:35 DE: Gnome
[DEBUG] 2017-07-14 14:17:35 Config file: Not found.
[DEBUG] 2017-07-14 14:17:35 Arguments/Icon Size: None
[DEBUG] 2017-07-14 14:17:35 System/Icon Size: 22
[DEBUG] 2017-07-14 14:17:36 System/Theme: Papirus.foldercolor
[DEBUG] 2017-07-14 14:17:36 Arguments/Conversion Tool: None
[DEBUG] 2017-07-14 14:17:36 Config/Conversion Tool: None
[DEBUG] 2017-07-14 14:17:36 SVG Factory: Import ImageMagick
[DEBUG] 2017-07-14 14:17:37 Path with condition: dropbox_callback {userhome}/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Path with condition: hangouts_callback /home/ubuntu101/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-07-14 14:17:37 Config/Backup Ignore: False
[DEBUG] 2017-07-14 14:17:37 Create new backup folder for Chromium
[DEBUG] 2017-07-14 14:17:37 Creating directory: /home/ubuntu101/.config/Hardcode-Tray/Chromium/14-07-2017_14-17-37/
[DEBUG] 2017-07-14 14:17:37 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/google-chrome-tray.svg /tmp/tmpozzn6otd
[DEBUG] 2017-07-14 14:17:51 Backup file: /tmp/10153 to: /home/ubuntu101/.config/Hardcode-Tray/Chromium/14-07-2017_14-17-37/10153
[DEBUG] 2017-07-14 14:17:51 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Chromium/14-07-2017_14-17-37/10153
[DEBUG] 2017-07-14 14:17:52 Create new backup folder for Skype
[DEBUG] 2017-07-14 14:17:52 Creating directory: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/
[DEBUG] 2017-07-14 14:17:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden-notification.svg /tmp/tmpr4w1ofjf
[DEBUG] 2017-07-14 14:17:53 Backup file: /tmp/files|tray|files|win|files|tray-hiddenUnreadTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:53 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:53 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away-notification.svg /tmp/tmpy69me8g1
[DEBUG] 2017-07-14 14:17:55 Backup file: /tmp/files|tray|files|win|files|tray-awayUnreadTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awayUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:55 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awayUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:55 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected.svg /tmp/tmpnq3xktg4
[DEBUG] 2017-07-14 14:17:55 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb.svg /tmp/tmpdqmauc86
[DEBUG] 2017-07-14 14:17:56 Backup file: /tmp/files|tray|files|win|files|tray-donotdisturbSmallTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:17:56 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:17:56 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away.svg /tmp/tmp3wcs_rqf
[DEBUG] 2017-07-14 14:17:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb-notification.svg /tmp/tmpcx8wmro2
[DEBUG] 2017-07-14 14:17:58 Backup file: /tmp/files|tray|files|win|files|tray-donotdisturbUnreadTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:59 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:17:59 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away.svg /tmp/tmpj51if6s7
[DEBUG] 2017-07-14 14:17:59 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden.svg /tmp/tmpvosgtz5q
[DEBUG] 2017-07-14 14:18:01 Backup file: /tmp/files|tray|files|win|files|tray-hiddenSmallTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:01 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:01 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden.svg /tmp/tmpwibinrrs
[DEBUG] 2017-07-14 14:18:02 Backup file: /tmp/files|tray|files|win|files|tray-hiddenTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenTemplate@2x.png
[DEBUG] 2017-07-14 14:18:02 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-hiddenTemplate@2x.png
[DEBUG] 2017-07-14 14:18:02 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected-notification.svg /tmp/tmpa2qjapci
[DEBUG] 2017-07-14 14:18:03 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-indicator.svg /tmp/tmplovd_jyo
[DEBUG] 2017-07-14 14:18:03 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb.svg /tmp/tmpjkghaus0
[DEBUG] 2017-07-14 14:18:04 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-indicator.svg /tmp/tmp_v39zsc_
[DEBUG] 2017-07-14 14:18:05 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden.svg /tmp/tmpe9p94nzf
[DEBUG] 2017-07-14 14:18:06 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden.svg /tmp/tmphnn4juj6
[DEBUG] 2017-07-14 14:18:06 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away-notification.svg /tmp/tmpmopwsaw6
[DEBUG] 2017-07-14 14:18:07 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-offline.svg /tmp/tmpcwfsn8k3
[DEBUG] 2017-07-14 14:18:08 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-offline.svg /tmp/tmpk7s5z977
[DEBUG] 2017-07-14 14:18:09 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected.svg /tmp/tmpj3ccokz8
[DEBUG] 2017-07-14 14:18:10 Backup file: /tmp/files|tray|files|win|files|tray-onlineTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineTemplate@2x.png
[DEBUG] 2017-07-14 14:18:10 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineTemplate@2x.png
[DEBUG] 2017-07-14 14:18:11 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb-notification.svg /tmp/tmppxmncrv8
[DEBUG] 2017-07-14 14:18:11 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected.svg /tmp/tmprbbbe7_m
[DEBUG] 2017-07-14 14:18:12 Backup file: /tmp/files|tray|files|win|files|tray-onlineSmallTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:12 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:12 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb.svg /tmp/tmpivt3mwls
[DEBUG] 2017-07-14 14:18:14 Backup file: /tmp/files|tray|files|win|files|tray-donotdisturbTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbTemplate@2x.png
[DEBUG] 2017-07-14 14:18:14 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-donotdisturbTemplate@2x.png
[DEBUG] 2017-07-14 14:18:14 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected.svg /tmp/tmp1v1up9y_
[DEBUG] 2017-07-14 14:18:14 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-connected-notification.svg /tmp/tmpspuo7hzf
[DEBUG] 2017-07-14 14:18:15 Backup file: /tmp/files|tray|files|win|files|tray-onlineUnreadTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:18:15 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-onlineUnreadTemplate@2x.png
[DEBUG] 2017-07-14 14:18:16 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away.svg /tmp/tmp3fkk8ag2
[DEBUG] 2017-07-14 14:18:17 Backup file: /tmp/files|tray|files|win|files|tray-awayTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awayTemplate@2x.png
[DEBUG] 2017-07-14 14:18:17 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awayTemplate@2x.png
[DEBUG] 2017-07-14 14:18:17 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-disturb.svg /tmp/tmphvgo051_
[DEBUG] 2017-07-14 14:18:18 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-offline.svg /tmp/tmpdooe8vyp
[DEBUG] 2017-07-14 14:18:19 Backup file: /tmp/files|tray|files|win|files|tray-offlineTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-offlineTemplate@2x.png
[DEBUG] 2017-07-14 14:18:19 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-offlineTemplate@2x.png
[DEBUG] 2017-07-14 14:18:19 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-away.svg /tmp/tmps_7cmivh
[DEBUG] 2017-07-14 14:18:20 Backup file: /tmp/files|tray|files|win|files|tray-awaySmallTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awaySmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:20 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-awaySmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:20 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-offline.svg /tmp/tmp_n1m75b4
[DEBUG] 2017-07-14 14:18:22 Backup file: /tmp/files|tray|files|win|files|tray-offlineSmallTemplate@2x.png to: /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-offlineSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:22 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/Skype/14-07-2017_14-17-52/files|tray|files|win|files|tray-offlineSmallTemplate@2x.png
[DEBUG] 2017-07-14 14:18:22 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/skype-status-hidden-notification.svg /tmp/tmp8h5ijv23
[DEBUG] 2017-07-14 14:18:23 Create new backup folder for WebTorrent Desktop
[DEBUG] 2017-07-14 14:18:23 Creating directory: /home/ubuntu101/.config/Hardcode-Tray/WebTorrent Desktop/14-07-2017_14-18-23/
[DEBUG] 2017-07-14 14:18:23 Backup file: /opt/webtorrent-desktop/resources/app.asar.unpacked/static/WebTorrent.png to: /home/ubuntu101/.config/Hardcode-Tray/WebTorrent Desktop/14-07-2017_14-18-23/WebTorrent.png
[DEBUG] 2017-07-14 14:18:23 Executing command: chmod 0777 /home/ubuntu101/.config/Hardcode-Tray/WebTorrent Desktop/14-07-2017_14-18-23/WebTorrent.png
[DEBUG] 2017-07-14 14:18:23 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus/22x22/panel/webtorrent-desktop-panel.svg /opt/webtorrent-desktop/resources/app.asar.unpacked/static/WebTorrent.png

**Comment by bil-elmoussaoui** [comment]
Can you try doing this;
```bash
hardcode-tray --apply --only dropbox --theme Papirus
```
And see if that changes anything?

**Comment by artkis** [comment]
Welcome to Hardcode-Tray!
Desktop Environment: Gnome
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: Dropbox
Applying now..

No apps to fix! Please report on GitHub if this is not the case

Done, Thank you for using the Hardcode-Tray fixer!
![screenshot from 2017-07-15 18-15-13](https://user-images.githubusercontent.com/30148306/28239990-aa38e63c-6989-11e7-9cda-8ea0a9f5fae4.png)

it changes

**Comment by bil-elmoussaoui** [comment]
It seems that Hardcode-Tray couldn't detect the Dropbox installation path. You can check that here 
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/dropbox.json
And look for the correct installation path and add it to the config file. A PR would be really welcome, as i don't really have the time at the moment to test it on your OS/DE

**Comment by artkis** [comment]
Thank you  very much for sharing your time and talent Mr. bil-elmoussaoui!

**Comment by bil-elmoussaoui** [comment]
Any news? Is this fixed for you?

**Comment by artkis** [comment]
Yes, I am already satisfied. Skype has an update, it returns also to its original icon but after command line (hardcode-tray --apply), it was fixed also.
![screenshot from 2017-07-18 20-45-49](https://user-images.githubusercontent.com/30148306/28329365-a115633c-6bfa-11e7-99fb-ee72d392803a.png).
Thanks. Hope for your continue improving of Linux look.

**Comment by bil-elmoussaoui** [comment]
Yeah, because skype stores the icons on a binary file. Each update will overwrite the binary file with a new one. That's why you should run hardcode-tray each time you update skype or any other electron based app.
Btw, there's an option to change the color of the tray icons so they can be white as the rest of yours ;) Just check the README file

**Comment by artkis** [comment]
ok i will try

**Comment by varlesh** [comment]
@artkis why you not change color on gnome shell tray icons? it's looks ugly.
With ePapirus and your gnome-shel theme i recommend fix color:
`sed -i 's/#f6f6f6/#6e6e6e/g' ~/.themes/THEME_NAME/gnome-shell/gnome-shell.css`
Looks better with single color palette on tray:
![2017-07-27 13-26-47](https://user-images.githubusercontent.com/8083855/28663766-575332b6-72cf-11e7-9bc5-3093355452b2.png)
More info here: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#manual-fixes
