### ISSUE TITLE
With Papirus icons, Hardcode Tray does not change Steam's tray icon.

### ISSUE THREAD

**Issue by chuutatsu** [bil-elmoussaoui/Hardcode-Tray#409]
### Specifications
- Hardcode-Tray and sni-qt versions:
![screenshot_2017-07-23_18-06-45](https://user-images.githubusercontent.com/24815847/28498847-dda1976e-6fd1-11e7-8d14-dd5cb799ccee.png)
- Distribution : Manjaro 17.0.2 XFCE
- Gtk version : 3.22
- Inkscape version : 0.9.2-1.3
- Icon name :  Papirus

###  Actual Behavior
1. After running hardcode tray with Papirus icons, all tray icons changed successfully to Papirus. 
But Steam was left with a broken icon.
![screenshot_2017-07-23_18-10-12](https://user-images.githubusercontent.com/24815847/28498879-aba0c824-6fd2-11e7-941a-0d1007647902.png)
(the right broken icon is supposed to be Steam icon)

### Requests
1. Please have look at hardcode tray codes and fix this problem.
2. If this was indeed a problem that comes from Papirus icons, please close the thread. I'll move to their Github page.

Thank you.

**Comment by bil-elmoussaoui** [comment]
That was fixed few releases before...The latest version of Hardcode-Tray is 4.1 and not 3.8 :(

**Comment by bil-elmoussaoui** [comment]
The best way to fix the broken icon is first to reinstall Steam so the original icon can be reinstalled (this won't remove your games library). After that, upgrade Hardcode-Tray using the manual installation to get the latest version (see README). And then run `hardcode-tray --apply --only steam` paste the output here & also the log file from `/tmp/Hardcode-Tray` (just the latest one)

**Comment by chuutatsu** [comment]
So that was meant.... the packages in AUR wasn't updated.

Alright.

**Comment by bil-elmoussaoui** [comment]
I maintain the AUR packages myself and they are up to date as far as i know. Do yoy you use the stable or the git version?

**Comment by chuutatsu** [comment]
I'm using the **hardcode-tray** one, not **hardcode-tray-git**.

**Comment by bil-elmoussaoui** [comment]
@chuutatsu You can now run `yaourt -S hardcode-tray` which will grab the latest release; I thought that i have upgraded the script, but i didn't git push :rofl:

**Comment by chuutatsu** [comment]
Alright, I'll redownload them now and post the result here then.

**Comment by bil-elmoussaoui** [comment]
You're welcome
