### ISSUE TITLE
Create a man page

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#412]
Debian build system complains about that. Shouldn't be too hard to do

**Comment by SolarLiner** [comment]
I was already on my way to do that. I'll update with a pull request soon enough (I hope!).

**Comment by bil-elmoussaoui** [comment]
@SolarLiner that would be really awesome

**Comment by SolarLiner** [comment]
So the man file itself can be anything and put anywhere, but the file must be placed at `/usr/local/man/man1/hardcode-tray.1` and then gzipped. I see no scripts folder, only a travis configuration. 

I've put the source man file in `./doc/man/hardcode-tray.1` if that's okay.
![image](https://user-images.githubusercontent.com/4302963/29110724-e27c0024-7d11-11e7-8e88-2db68e174151.png)

**Comment by bil-elmoussaoui** [comment]
Fixed on master thanks to @SolarLiner
