### ISSUE TITLE
[Icon Request]  Rhythmbox Music Player

### ISSUE THREAD

**Issue by Armanmd** [bil-elmoussaoui/Hardcode-Tray#416]
App name:Rhythmbox

- url(github):https://github.com/mendhak/rhythmbox-tray-icon

**_Tray icons:_**
![](http://i.imgur.com/joOtcFb.png)
![](http://i.imgur.com/sx0TYYI.png)
**_location:_**
![](http://i.imgur.com/oyjcPXF.png)

**Comment by bil-elmoussaoui** [comment]
Fixed on master. Your icon theme must provide 
- `rhythmbox-indicator`
- `rhythmbox-playing`
