### ISSUE TITLE
Running Hardcode-Tray crashes

### ISSUE THREAD

**Issue by SolarLiner** [bil-elmoussaoui/Hardcode-Tray#421]
### Specifications
- Hardcode-Tray version : `` (impossible to retrieve, crashes)
- Distribution : `Ubuntu GNOME 17.04`
- Gtk version : `2.24.31-1ubuntu1 | 3.22.11-0ubuntu3`
- Inkscape version : `0.92.1` if installed
- Cairo version : `1.0.20` if installed
- Sni-qt version: `0.2.7+20161212~1` if installed
- Application name :  ``
- Application version : ``

Running hardcode-tray in any mode (even just to check version) yeilds a crash.
![image](https://user-images.githubusercontent.com/4302963/29256584-a81067e6-80d5-11e7-822d-9d7ca8f08b8c.png)

```bash
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 40, in <module>
    from HardcodeTray.app import App
  File "/usr/lib/python3.5/site-packages/HardcodeTray/app.py", line 25, in <module>
    from HardcodeTray.const import DB_FOLDER
  File "/usr/lib/python3.5/site-packages/HardcodeTray/const.py", line 36, in <module>
    USER_ID = int(getenv("SUDO_UID")) or geteuid()
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by kmf** [comment]
Have the same issue.

**Comment by bil-elmoussaoui** [comment]
Hmm i should have tested this more. I will fix this one tonight

**Comment by SolarLiner** [comment]
Something something not enough automated testing... 🙃🙃

**Comment by bil-elmoussaoui** [comment]
Tests are not ready yet :( and I'm so busy these days...

**Comment by ianfebriyanto** [comment]
same here

**Comment by bil-elmoussaoui** [comment]
Fixed on master. Now Hardcode-Tray doesn't change the permissions of any file which caused a lot of issues. This will be improved a lot with #397 & #406
