### ISSUE TITLE
KeePass2 Plugin Application Indicator

### ISSUE THREAD

**Issue by diogo-gomes** [bil-elmoussaoui/Hardcode-Tray#422]
### Specifications
- Hardcode-Tray version : `3.5.2.1~863~ubuntu16.04.1`
- Distribution : `Xubuntu 16.04`
- Gtk version : `3.2.0-2`
- Inkscape version : `0.91-7ubuntu2`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1`
- Application name :  `keepass2-plugin-application-indicator`
- Application version : `0.4.7+0.5.7`
- PPA: `[launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins]`(https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins)
- Repository: `[github.com/dlech/Keebuntu](https://github.com/dlech/Keebuntu)` 

### Expected behavior and actual behavior
keepass2-plugin-application-indicator stays the same icon (coloured icon).

**Comment by BrusAndr** [comment]
+1, I also noticed this problem.
KeePassX site: http://www.keepassx.org/
GitHub repo: https://github.com/keepassx/keepassx

**Comment by diogo-gomes** [comment]
@bil-elmoussaoui,

I updated the issue with:

- PPA: `[launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins]`(https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins)
- Repository: `[github.com/dlech/Keebuntu](https://github.com/dlech/Keebuntu)`

**Comment by bil-elmoussaoui** [comment]
@BrusAndr It's not the same issue. Keepassx is the other issue that has been reported few times but i can't do anything about it (the last time i checked). I will do some verifications again (and open an issue upstream about that)

@diogo-gomes Thanks for the links. I will see if it can be done tonight :)

**Comment by bil-elmoussaoui** [comment]
@diogo-gomes The deb file you linked doesn't use a hardcoded icon. But `keepass2-locked`
![keepass2-locked](https://user-images.githubusercontent.com/7660997/29485710-d58b0d66-84d6-11e7-9698-be49556e1ecc.png)
![keepass2-locked](https://user-images.githubusercontent.com/7660997/29485717-db9f52a2-84d6-11e7-808a-b7a4efd7b181.png)
![keepass2-locked 1](https://user-images.githubusercontent.com/7660997/29485718-dbb5de96-84d6-11e7-93ef-3a3cbfcfbccb.png)
![keepass2-locked 2](https://user-images.githubusercontent.com/7660997/29485719-dbbf992c-84d6-11e7-923c-59481a85acf6.png)

You should report that upstream to the icon theme you're using
