### ISSUE TITLE
Missing dependency gobject-introspection?

### ISSUE THREAD

**Issue by chuutatsu** [bil-elmoussaoui/Hardcode-Tray#423]
I tried to reinstall hardcode-tray-git again. The build process failed and I got this error.

"missing dependency gobject-introspection"

Apparently I am not the only one who experienced this. The commenter at this AUR page also gave the same error message. https://aur.archlinux.org/packages/hardcode-tray-git

I am using the stable version (hardcode-tray) for now.

**Comment by bil-elmoussaoui** [comment]
I will fix the AUR repository right now

**Comment by bil-elmoussaoui** [comment]
Fixed

**Comment by chuutatsu** [comment]
Thank you!
