### ISSUE TITLE
Meson problem

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#424]
Just reporting an issue. Running on Ubuntu 17.04 (Linux moon 4.10.0-32-generic)

```
~/Downloads/Hardcode-Tray-4.1 » meson builddir --prefix=/usr               

The Meson build system
Version: 0.39.1
Source dir: /home/lheck/Downloads/Hardcode-Tray-4.1
Build dir: /home/lheck/Downloads/Hardcode-Tray-4.1/builddir
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

**Comment by bil-elmoussaoui** [comment]
@leoheck Can you try upgrade meson to a newer version using `pip3 install --upgrade meson`? That should fix the issue. As we request meson >= 0.40

**Comment by bil-elmoussaoui** [comment]
See the readme https://github.com/bil-elmoussaoui/Hardcode-Tray#building-dependencies

**Comment by leoheck** [comment]
Good, it worked, thanks. I had to use sudo instead.
`sudo -H pip3 install --upgrade meson`
