### ISSUE TITLE
Missing tray icon for google-chrome

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#425]
Google Chrome version
Version 61.0.3163.49 (Official Build) beta (64-bit)
Edit: I am using paper icon theme

**Comment by bil-elmoussaoui** [comment]
Paper doesn't support Hardcode-tray. You can either open an issue about that upstream or just use an other theme like Numix or Papirus to set the icons with the --theme argument. You can also recolour the icons to make them look like Paper tray icons. Just look at the README or use man hardcode-tray to see the list of possible options.
