### ISSUE TITLE
New icons request

### ISSUE THREAD

**Issue by jcubic** [bil-elmoussaoui/Hardcode-Tray#426]
Do you accept new icons requests? It would be nice to have icons for liferea. The icons that need to be replaced are located in [pixemap directory](https://github.com/lwindolf/liferea/tree/master/pixmaps) the other icons are taken from theme but not the one from tray.

**Comment by bil-elmoussaoui** [comment]
@jcubic Which ones are used by Lifrea as tray icons?

**Comment by jcubic** [comment]
the ones outside of folders, and after install they are located in /usr/share/liferea/pixmaps/

**Comment by bil-elmoussaoui** [comment]
By looking at the source code the only used icons are https://github.com/lwindolf/liferea/blob/00ac9b126f9908468b32a17da699f3a85012ae47/plugins/trayicon.py#L92-L93

**Comment by jcubic** [comment]
Yes I just look ate the source code in the same time just wanted to comment that only two of them are used available.png and unread.png

**Comment by bil-elmoussaoui** [comment]
Fixed on master. You can use `sudo hardcode-tray --only liferea` to fix only Liferea once the icons are included by the theme you're using right now.
The icons are: 
- [ ] ![unread](https://user-images.githubusercontent.com/7660997/29524776-09519410-8691-11e7-8ea7-11f5df7f8ae9.png) `liferea-unread`

- [ ] ![available](https://user-images.githubusercontent.com/7660997/29524779-0c5bb33e-8691-11e7-9e02-8073fb40226e.png) `liferea-available`

**Comment by jcubic** [comment]
Wow, that was fast, thanks.

**Comment by bil-elmoussaoui** [comment]
It's pretty easy to include new applications support thanks to our base code;)
