### ISSUE TITLE
How to create icons in theme?

### ISSUE THREAD

**Issue by jcubic** [bil-elmoussaoui/Hardcode-Tray#427]
I want to start adding hardcode-tray icons to my theme [Clarity](https://github.com/jcubic/Clarity), should I just add icon like `/scalable/status/bitcoin-indicator.svg`  and the icon will work or something else need to be done. This info can be added to README as well.

**Comment by bil-elmoussaoui** [comment]
@jcubic I have already thought about everything :p just take a look at our Wiki https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/FAQ#how-to-support-an-application-in-your-theme

**Comment by bil-elmoussaoui** [comment]
All needs to be done is just adding the icons. And the users can run hardcode-tray if they want and the icons will be picked from their current theme (if they exist). This way we avoid adding any icon into our repository and each theme can support one or more app ;)

**Comment by bil-elmoussaoui** [comment]
The wiki might need some re-wording indeed. Any help is always welcome:+1:
