### ISSUE TITLE
Not Patching Steam's icon with Papirus Theme

### ISSUE THREAD

**Issue by GohanSaiyajin** [bil-elmoussaoui/Hardcode-Tray#428]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Linux Mint 18.2 Cinnamon`
- Gtk version : `3.18`
- Inkscape version : `Most Recent` if installed
- Cairo version : `Not Installed` if installed
- Sni-qt version: `Most Recent` if installed
- Application name :  `Steam`
- Application version : `Most Recent`

### Expected behavior and actual behavior
Steam's icon is simply not updating when trying to patch it for Papirus theme, did not try with any other themes. Also does not work if trying with alternative color codes.
Just adding, this issue may be on Steam because the last update broke some compatibilities like creating shortcuts. Reporting here because i don't know if it's Steam or Hardcode-tray that's causing the conflict.
EDIT: After changing the panel height, noticed that it still works if the icons are large. If Medium or Small icons are selected, it reverts to the base icon. This icon size is defined by Cinnamon.
EDIT2: It seems that even if using large icons on Cinnamon panel, trying to make Steam's icon smaller by appending to --size (16,22) is making no change.

### Steps to reproduce the problem
1. Try to patch Steam icon to Papirus Theme

**Comment by TheGohan1905** [comment]
EDIT: After changing the panel height, noticed that it still works if the icons are large. If Medium or Small icons are selected, it reverts to the base icon.

**Comment by bil-elmoussaoui** [comment]
Which version of hardcode-tray are you using? The git one? Can you also copy/paste the logs from Hardcode-tray, they can be found on /tmp/Hardcode-tray. Ordered by date

**Comment by TheGohan1905** [comment]
Using version 4.1, added from the rep. I tried using --update-git like I did last time I had an issue, but it seems the command is not here anymore. Posting the logs.

> [DEBUG] 2017-08-22 09:28:50 DE not detected.
> [DEBUG] 2017-08-22 09:28:50 Config file: Not found.
> [DEBUG] 2017-08-22 09:28:50 Arguments/Icon Size: 24
> [DEBUG] 2017-08-22 09:28:50 Arguments/Theme: Papirus
> [DEBUG] 2017-08-22 09:28:50 Arguments/Conversion Tool: Inkscape
> [DEBUG] 2017-08-22 09:28:52 Path with condition: dropbox_callback /home/gohan/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:52 Path with condition: hangouts_callback /home/gohan/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
> [DEBUG] 2017-08-22 09:28:53 Config/Backup Ignore: False
> [DEBUG] 2017-08-22 09:28:53 Create new backup folder for Discord
> [DEBUG] 2017-08-22 09:28:53 Creating directory: /home/gohan/.config/Hardcode-Tray/Discord/22-08-2017_09-28-53/
> [DEBUG] 2017-08-22 09:28:53 Executing command: inkscape -z -f /tmp/discord-tray-notification.svg -e /tmp/tmp4vtnnknb -w 24 -h 24
> [DEBUG] 2017-08-22 09:28:54 Backup file: /tmp/files|images|files|linux-tray-unread.png to: /home/gohan/.config/Hardcode-Tray/Discord/22-08-2017_09-28-53/files|images|files|linux-tray-unread.png
> [DEBUG] 2017-08-22 09:28:54 Executing command: inkscape -z -f /tmp/discord-tray.svg -e /tmp/tmpcslq06pw -w 24 -h 24
> [DEBUG] 2017-08-22 09:28:55 Backup file: /tmp/files|images|files|linux-tray.png to: /home/gohan/.config/Hardcode-Tray/Discord/22-08-2017_09-28-53/files|images|files|linux-tray.png
> [DEBUG] 2017-08-22 09:28:55 Create new backup folder for Google Chrome
> [DEBUG] 2017-08-22 09:28:55 Creating directory: /home/gohan/.config/Hardcode-Tray/Google Chrome/22-08-2017_09-28-55/
> [DEBUG] 2017-08-22 09:28:55 Executing command: inkscape -z -f /tmp/google-chrome-tray.svg -e /tmp/tmpsbeelnxz -w 24 -h 24
> [ERROR] 2017-08-22 09:28:59 Couldn't find a PNG file.
> [DEBUG] 2017-08-22 09:28:59 Executing command: inkscape -z -f /tmp/google-chrome-tray.svg -e /tmp/tmp_am3yi4b -w 24 -h 24
> [DEBUG] 2017-08-22 09:29:00 Backup file: /tmp/10153 to: /home/gohan/.config/Hardcode-Tray/Google Chrome/22-08-2017_09-28-55/10153
> [DEBUG] 2017-08-22 09:29:00 Executing command: inkscape -z -f /tmp/google-chrome-tray.svg -e /tmp/tmpastiqusg -w 24 -h 24
> [ERROR] 2017-08-22 09:29:00 Couldn't find a PNG file.
> [DEBUG] 2017-08-22 09:29:00 Create new backup folder for Steam
> [DEBUG] 2017-08-22 09:29:00 Creating directory: /home/gohan/.config/Hardcode-Tray/Steam/22-08-2017_09-29-00/
> [DEBUG] 2017-08-22 09:29:00 Backup file: /usr/share/pixmaps/steam_tray_mono.png to: /home/gohan/.config/Hardcode-Tray/Steam/22-08-2017_09-29-00/steam_tray_mono.png
> [DEBUG] 2017-08-22 09:29:00 Executing command: inkscape -z -f /tmp/steam_tray_mono.svg -e /usr/share/pixmaps/steam_tray_mono.png -w 24 -h 24

Actually, this is the only log I could find, did a fresh install before reporting.

**Comment by bil-elmoussaoui** [comment]
By looking at the last line it seems that it works without any issue. Can you take a look at /usr/share/pixmaps/steam_tray_mono.png?

**Comment by TheGohan1905** [comment]
![steam_tray_mono](https://user-images.githubusercontent.com/26198732/29574024-bb9cc2d4-8736-11e7-92e3-400173393902.png)

It looks exactly how it should be.
Like i said, if i use a custom panel size with the "Allow Cinnamon to scale text and icons according to the panel height" option enabled and leaving it at 40, 45% of the indicator, the Steam icon goes like the image above, but if lower than that, the default icon is used. No changes occur if appending to --size 22 or 16.

**Comment by bil-elmoussaoui** [comment]
It must be an issue with cinnamon then. I don't know how things works there but if it works for a size and doesn't for an other it has to be an upstream size where the cinnamon panel tries to get a larger size of the icon but it doesn't get the right one :/

**Comment by GohanSaiyajin** [comment]
Okay, gonna try some workaround here. Thanks for helping!

**Comment by bil-elmoussaoui** [comment]
You can always open an issue upstream
