### ISSUE TITLE
Is that possible to change Papirus tray icons' color using this command?

### ISSUE THREAD

**Issue by chuutatsu** [bil-elmoussaoui/Hardcode-Tray#429]
I need a little help. I found this in the Papirus page.

>  hardcode-tray --change-color "#FIRSTCOLOR #REPLACE_FIRST_COLOR" "#SECONDCOLOR #REPLACE_SECOND_COLOR"...

Can I use the command above to change the color of Papirus tray icons?
And how is the exact example?

**Comment by bil-elmoussaoui** [comment]
yeah, ofc you can use that. The default color used by Papirus tray icons is `#5c616c` you can find that pretty easily by opening any tray icon using Inkscape.

Or if you want you can open the text editor and open any svg icon from Papirus

```xml
<style type="text/css" id="current-color-scheme">
.ColorScheme-Text { color:#5c616c; } 
.ColorScheme-Highlight { color:#5294e2; } 
.ColorScheme-ButtonBackground { color:#d3dae3; }
</style>
```

Then all you have to do is using `hardcode-tray --change-color "#5c616c #00000" That will replace `#5c616c` with `#000000` before copying the icons to their correct path/binary.

This won't work for apps that use SVG icons as tray icons (at the moment, need some rework on Hardcode-Tray. But I don't have enough time at the moment...). But hey, almost every app that uses hard coded tray icons uses PNG ones.

**Comment by chuutatsu** [comment]
Alright, thanks for explanation.
