### ISSUE TITLE
Google-chrome

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#43]
See here: http://askubuntu.com/questions/470691/how-can-i-replace-google-chromes-low-resolution-notification-icon?lq=1 it seems to be pretty complicated to do that

**Comment by bil-elmoussaoui** [comment]
The Google music manager icon can be fixed by installing the patched version of sni-qt, i don't know if it's the same for Google Chrome. Are you using Ubuntu 15.04? as i didn't manage to show the indicator icon of Chrome

**Comment by wa4557** [comment]
I think google chrome cannot be changed by using a different sni-qt version (since it isn't a qt version) it seems to be the same as with spotify, that the icon is embedded in this `chrome-100percent.bak` (way more complicated of course than spotify)

**Comment by bil-elmoussaoui** [comment]
Well, i think that we should fix Megasync , Skype & Google music manager first

**Comment by wa4557** [comment]
skype and google music manager should be extremely easy now, am I right?

**Comment by bil-elmoussaoui** [comment]
Yeah, i just don't know which icons name i'm going to use for those applications. I think that something like for skype will be fine 
``` 
skype-status-connected
skype-status-busy
....
```
For Google Music Manager there's only one icon ```google-music-manager-panel```
and for Megasync 
```
megasync-status-error
megasync-status-connected
megasync-status-sync1
...
````
What do you think?

**Comment by wa4557** [comment]
:+1: If the whole status icon thing is sorted out, we can create issues at Numix and add them!

**Comment by bil-elmoussaoui** [comment]
I'm going to add them right now :dancer: and keep this open maybe it will change in the near future

**Comment by wa4557** [comment]
Cool, I'll try to come up with a script for chrome, but no promises :)

**Comment by Foggalong** [comment]
Google Chrome uses it's own toolkit iirc which might be part of why it's so complicated. I think that's why their GTK theme support is also a bit pants

**Comment by bil-elmoussaoui** [comment]
I added google chrome support :smiley:

**Comment by wa4557** [comment]
Doesn't work yet, but I think it's not far from working :)

**Comment by bil-elmoussaoui** [comment]
I think it's not possible to fix it using a script. As the icons name are : 
``` 
7360.png
7361.png
7358.png
7359.png
```
And if you look at the link you shared, the icons are has different icon names..maybe it's depends on the chrome version or something like this

**Comment by wa4557** [comment]
Maybe it is possible to query the icon names using a script?

**Comment by bil-elmoussaoui** [comment]
I have no idea about this :P can you try to check in your case if you have the same icons name or not?

**Comment by wa4557** [comment]
Sure

**Comment by wa4557** [comment]
@bil-elmoussaoui You have to change the line `node ./node-chrome-pak.js unpack chrome_100_percent_old.pak` to `nodejs ...` (at least on my computer)

**Comment by bil-elmoussaoui** [comment]
try installing ```nodejs-legacy```

**Comment by wa4557** [comment]
That works, but is that better than using `node`?

**Comment by wa4557** [comment]
Hmm, maybe you should also include the original author of this `javascript` script somewhere? I'm not an expert in licensing things but I suppose it's necessary to include him somewhere

**Comment by bil-elmoussaoui** [comment]
Yeah i was going to do that, but i had no idea where i should include him. @Foggalong do you have any idea?

**Comment by bil-elmoussaoui** [comment]
@wa4557 it's same thing i guess

**Comment by wa4557** [comment]
I guess for the MIT license (that's the licence he used) its OK to just use it (you have to keep the copyright header in the file however). Btw. you should add a copright header as well in your script :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 I will do add that once everything is fixed in the script

**Comment by wa4557** [comment]
Since google chrome works now I'll close this here :+1:
