### ISSUE TITLE
Please consider adding Qnapi app.

### ISSUE THREAD

**Issue by jareksprysz** [bil-elmoussaoui/Hardcode-Tray#430]
Qnapi is movie subtitles searching tool.

**Comment by bil-elmoussaoui** [comment]
I can't fix this as the icon is hardcoded on the binary. The application uses a qresource file see https://github.com/QNapi/qnapi/blob/master/gui/res/resources.qrc#L3
And the icon is set from that file 
https://github.com/QNapi/qnapi/blob/cdc431b2214ae45e420286ff460bb0131d7a1360/gui/src/qnapiapp.cpp#L166

Instead, they should use `QIcon::fromTheme("qnapi-tray")` and fall back to the current icon from the qresource if the icon doesn't exist in the current theme. This will allow theme creators to support it. Currently, i can't support replacing the icons on binaries. It's complicated, and might work for a specific version and break an other one :(
Can you please an issue about that upstream?

**Comment by bil-elmoussaoui** [comment]
See https://github.com/QNapi/qnapi/issues/125
