### ISSUE TITLE
Skype Preview not working

### ISSUE THREAD

**Issue by drakkar1969** [bil-elmoussaoui/Hardcode-Tray#431]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Arch Linux`
- Gtk version : `3.22`
- Inkscape version : `0.92.2 5c3e80d, 2017-08-06` if installed
- Sni-qt version: `sni-qt-patched-git r.-1` if installed
- Application name :  `Skype Preview`
- Application version : `8.5.76.55323`

### Expected behavior and actual behavior
Tray icons no longer changed since upgrade from Skype for Linux Beta to Skype Preview

Love hardcode-tray btw!

**Comment by bil-elmoussaoui** [comment]
What's skype preview? 🤔

**Comment by drakkar1969** [comment]
Latest version of Skype for Linux Beta has picked up the Skype re-design already rolled out on Android/Windows - and re-named Skype Preview ....

**Comment by bil-elmoussaoui** [comment]
I will see what i can do

**Comment by drakkar1969** [comment]
Thanks!

**Comment by varlesh** [comment]
extract asar skypeforlinux (8.5.76.55323) :
```
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-offlineTemplate.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-offlineTemplate@2x.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-offlineUnreadTemplate.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-offlineUnreadTemplate@2x.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-onlineTemplate.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-onlineTemplate@2x.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-onlineUnreadTemplate.png
skypeforlinux/resources/skypeforlinux/images/tray/linux/tray-onlineUnreadTemplate@2x.png
```

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/29979902-5ec17c60-8f58-11e7-8d9c-a36602a506bc.png)

**Comment by varlesh** [comment]
PPA https://repo.skype.com/deb/pool/main/s/skypeforlinux/

**Comment by varlesh** [comment]
Skype Preview (skypeforlinux_8.5.76.55323) it's unstable app... maybe need create another file for database, because skypeforlinux_5.3.0 it's stable release?

**Comment by varlesh** [comment]
On official download link https://go.skype.com/linux.deb downloaded stable version skypeforlinux_5.3.0. Users will be confused

**Comment by varlesh** [comment]
on skypeforlinux_5.3.0 used another paths an icons:
```
skypeforlinux/resources/skypeforlinux/tray/win/tray-awaySmallTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-awayTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-awayUnreadTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-donotdisturbSmallTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-donotdisturbTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-donotdisturbUnreadTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-hiddenSmallTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-hiddenTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-hiddenUnreadTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-offlineSmallTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-offlineTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-onlineSmallTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-onlineTemplate@2x.png
skypeforlinux/resources/skypeforlinux/tray/win/tray-onlineUnreadTemplate@2x.png
```
![image](https://user-images.githubusercontent.com/8083855/29980434-f078d944-8f5a-11e7-86ed-4d75a6fcb1bf.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh Currently, we don't have a way to check the application version. I don't know if there's any way to do that (that works on almost every linux distro). 
But indeed, we should at least separate the icons from each version, otherwise, it will be impossible to debug in the future.

**Comment by drakkar1969** [comment]
Managed to patch with this database file:

skypepreview.json
```
{
    "name": "SkypePreview",
    "app_path": [
        "/usr/share/skypeforlinux/"
    ],
    "icons_path": [
        "/usr/share/skypeforlinux/resources/"
    ],
    "script": "electron",
    "binary": "app.asar",
    "icons": {
        "offline": {
            "original": "images/tray/linux/tray-offlineTemplate.png",
            "theme": "skype-status-offline"
        },
        "offline2": {
            "original": "images/tray/linux/tray-offlineTemplate@2x.png",
            "theme": "skype-status-offline"
        },
        "offline-notification": {
            "original": "images/tray/linux/tray-offlineUnreadTemplate.png",
            "theme": "skype-status-offline-notification"
        },
        "offline-notification2": {
            "original": "images/tray/linux/tray-offlineUnreadTemplate@2x.png",
            "theme": "skype-status-offline-notification"
        },
        "online": {
            "original": "images/tray/linux/tray-onlineTemplate.png",
            "theme": "skype-status-connected"
        },
        "online2": {
            "original": "images/tray/linux/tray-onlineTemplate@2x.png",
            "theme": "skype-status-connected"
        },
        "online-notification": {
            "original": "images/tray/linux/tray-onlineUnreadTemplate.png",
            "theme": "skype-status-connected-notification"
        },
        "online-notification2": {
            "original": "images/tray/linux/tray-onlineUnreadTemplate@2x.png",
            "theme": "skype-status-connected-notification"
        }
    }
}
```

**Comment by varlesh** [comment]
Variants:
- options `--help` or `--version`. Skypeforlinux not have yet :(
- use package manager (for example, `dpkg -s skypeforlinux | grep Version`) - but this not good solution (More systems and more package managers - it's not universal)
- check hash sum binary file - not good too, because we must control always new changes/releases and generate new sum.
- wait stable release :) It's most practical solution. 

i don't know anymore...

**Comment by bil-elmoussaoui** [comment]
@varlesh This will make things more complicated :( there's no standard way to verify if the application is installed. As the user can install the application from the official deb, or just compile it by himself (apps other than Skype); and i must support dpkg, pacman, dnf (fedora)...which is a lot worse than you can imagine :P

**Comment by bil-elmoussaoui** [comment]
Fixed on master. I'm not going to separate the application into different json files. At least not anytime soon.
So, i have merged @drakkar1969 is json file with the old json file that we had 👍 
The electron module, does detect if the file exists before replacing it so it shouldn't cause any issue at all here

**Comment by drakkar1969** [comment]
awesome, thanks
