### ISSUE TITLE
Telegram icons are partially applied

### ISSUE THREAD

**Issue by orange-buffalo** [bil-elmoussaoui/Hardcode-Tray#441]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Kubuntu 17.04`
- Gtk version : `3.22`
- Inkscape version : `0.92.1 r15371`
- Sni-qt version: `0.2.7+20161212~11~ubuntu17.04.1`
- Application name :  `Telegram`
- Application version : `1.1.23`

### Expected behavior and actual behavior
ER: Icon theme is applied
AR: Icon theme is partially applied (proper icon is rendered in tray when there is an unread message, but default telegram icon is rendered when no unread messages pending)
![normal](https://user-images.githubusercontent.com/4532247/30238810-fb2f7e84-954e-11e7-94bb-9e2d60756d99.png)
![unread](https://user-images.githubusercontent.com/4532247/30238811-fb2fe1f8-954e-11e7-9a08-e62da2a104fc.png)

**Comment by bil-elmoussaoui** [comment]
Can you see which icons are unthemed on `$HOME/.local/share/TelegramDesktop/tdata/ticons/`?

**Comment by orange-buffalo** [comment]
For me the location was `$HOME/.TelegramDesktop/tdata/ticons/`, but anyway, the only unthemed file there is `ico_22_0.png`

**Comment by bil-elmoussaoui** [comment]
Fixed on the master branch. Please either upgrade to master or wait until the v4.2 is released 
Thanks

**Comment by orange-buffalo** [comment]
Thanks a lot for such a quick resolution!
