### ISSUE TITLE
Run hardcode-tray as user from root?

### ISSUE THREAD

**Issue by drakkar1969** [bil-elmoussaoui/Hardcode-Tray#442]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Arch Linux`
- Gtk version : `3.22`
- Inkscape version : `0.92.2 5c3e80d, 2017-08-06`
- Sni-qt version: `r.-1`

Is there a way to run the script as a specific user from root? The reason for this is that, when apps are updated/re-installed, tray icons revert to original and have to be re-patched with hardcode-tray. I would like to add pacman hooks to run hardcode-tray automatically when apps are updated - and pacman hooks run commands as root.

I have tried various combinations with `sudo` and `-E` `-u` `-H` `-i` switches with no luck, getting the following error:
```
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 40, in <module>
    from HardcodeTray.app import App
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 25, in <module>
    from HardcodeTray.const import DB_FOLDER
  File "/usr/lib/python3.6/site-packages/HardcodeTray/const.py", line 36, in <module>
    THEMES_LIST = get_themes(USERHOME)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/tools.py", line 50, in get_themes
    sub_dirs = listdir(icon_path)
PermissionError: [Errno 13] Permission denied: '/root/.local/share/icons/'
```

**Comment by bil-elmoussaoui** [comment]
It seems a great idea :) But first let me finish #440 once it's done, we can see how to make this possible

**Comment by drakkar1969** [comment]
Sounds good, thanks

**Comment by bil-elmoussaoui** [comment]
So the best way to handle this i guess, is to add some option to specify the user that he runs the script?
I think this could be easily fixed by patching your own const.py
As you can see here https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/const.py.in#L27
Just replace the USERNAME and USERHOME variable with the username you want to use and the USERHOME with the path to your home directory and run the script. 

Otherwise, i don't see any other way to fix this except adding an argument for the username which will make things more complicated for this specific task...

**Comment by drakkar1969** [comment]
ok thanks, let me try that out

**Comment by drakkar1969** [comment]
Ok, so I'm dumb: I was running hardcode-tray with various combinations of `sudo` in the pacman hook. But pacman hooks already run commands with elevated privileges, so `sudo` is not required.

If I just run `hardcode-tray` (without `sudo`) from the pacman hook, it works, and USERNAME/USERHOME are correctly assigned as my user name/my home dir respectively.

The only thing that does not work is detection of the desktop environment, DESKTOP_ENV shows up as 'other'.

Same thing happens, btw, if I run `sudo -Ei`, `sudo -i` (or `sudo -i -u username`) from command line and then run `hardcode-tray`: in all cases USERNAME/USERHOME are correctly detected, but the DE isn't.
However, if I run `su` and then `hardcode-tray`, everything works, including DE detection.

**Comment by bil-elmoussaoui** [comment]
Nice! The DE is used only to decide which icon size to use and other stuff. That can be configured either from the command line or using the json config file. There's no easy way to detect any distro sadly :( all i do is read the env variables, that might be not exported correctly with pacman...

**Comment by drakkar1969** [comment]
I'm setting icon size from the command line, so that works

Re env variables, in effect DESKTOP_SESSION and XDG_CURRENT_DESKTOP are not exported with pacman, so no options there ...

**Comment by bil-elmoussaoui** [comment]
It's all i can do for now ! If you have any idea on mind just let me know 👍 otherwise this can be closed I guess

**Comment by drakkar1969** [comment]
ok, thanks
