### ISSUE TITLE
Can't install hardcode-tray when using inkscape-trunk

### ISSUE THREAD

**Issue by dflock** [bil-elmoussaoui/Hardcode-Tray#446]
### Specifications
- Hardcode-Tray version : `hardcode-tray_3.5.2.1~880~ubuntu16.04.1_all.deb`
- Distribution : `XUbuntu`
- Inkscape version : `Inkscape 0.92+devel (unknown)`

### Expected behavior and actual behavior

```console
$ sudo apt install sni-qt sni-qt:i386
...
$ sudo apt install hardcode-tray
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 hardcode-tray : Depends: inkscape but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Note the `hardcode-tray : Depends: inkscape but it is not going to be installed` - this is because I have `inkscape-trunk` installed and the `hardcode-tray` package has a hard dependency on `inkscape`.

This dependency should either be optional or it should depend on `inkscape` or `inkscape-trunk`.

**Comment by dflock** [comment]
Ended up editing the control file to get this to install, like this: https://serverfault.com/a/859394/72740

**Comment by bil-elmoussaoui** [comment]
We should definitely remove the hard dependency of Inkscape. As the user can use whatever conversion tool they want

**Comment by wa4557** [comment]
@bil-elmoussaoui Should I remove it as dependency?

**Comment by bil-elmoussaoui** [comment]
Yeah especially sni-qt and Inkscape. We should ensure to have a working installation, so maybe we should keep the python cairosvg backend?

**Comment by wa4557** [comment]
Ok I'll keep `python3-cairosvg` I guess it's not too big anyways

**Comment by wa4557** [comment]
Done

**Comment by bil-elmoussaoui** [comment]
Perfect 👍

**Comment by varlesh** [comment]
Inkscape need for Papirus icons, because cairosvg not support CSS-styles.
https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/245

**Comment by bil-elmoussaoui** [comment]
People can still install Inkscape and use it, it's just no more a hard dependency

**Comment by wa4557** [comment]
what about rsvg? Maybe we just should keep that then?

**Comment by varlesh** [comment]
@wa4557 I don't know need test it. Also you can move inkscape packgae from `Recommends` to `Suggests`

**Comment by varlesh** [comment]
worked on Ubuntu 16.04:
![image](https://user-images.githubusercontent.com/8083855/30687789-65df5466-9ecd-11e7-827f-4ea6cad4e5f0.png)

**Comment by wa4557** [comment]
Ok let's make a dependency on rsvg then. I will move the others to suggests

**Comment by varlesh** [comment]
@bil-elmoussaoui Why needed this more conversion tools? Maybe we will be used only RSVGConvert?

**Comment by bil-elmoussaoui** [comment]
@varlesh you don't need them; you can keep using only RSVG. Others are there if someone wants to use something else they can do it without any issue ;)

**Comment by varlesh** [comment]
@bil-elmoussaoui But this superfluous work for you - support more coversion tools. I think RSVG enough

**Comment by wa4557** [comment]
@bil-elmoussaoui Any reason for the `git` dependence? Seems to be weird for this kind of program...

**Comment by varlesh** [comment]
It's last option `--update-git` now discontinued.

**Comment by wa4557** [comment]
Ok I remove that dependency as well then

**Comment by varlesh** [comment]
@wa4557 please add `librsvg2-bin` package to `Depends` on **debian/control**
RSVGConvert contained on librsvg2-bin package

**Comment by wa4557** [comment]
@varlesh Done
