### ISSUE TITLE
Chrome does not start anymore after using hardcode-tray

### ISSUE THREAD

**Issue by Feichtmeier** [bil-elmoussaoui/Hardcode-Tray#455]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Ubuntu 17.10 GNOME desktop`
- Gtk version : `3.22`
- Inkscape version : `0.92.2` if installed
- Cairo version : `1.0.20`
- Sni-qt version: `no idea how to check this`
- Application name :  `google-chrome-stable`
- Application version : `62.0.3202.62`

### Expected behavior and actual behavior
After using hardcode tray chrome does not start anymore

### Steps to reproduce the problem
1. start google-chrome --> working
2. run "sudo hardcode-tray -ct Inkscape -o google-chrome
3.run google chrome again --> not working anymore

![bildschirmfoto von 2017-10-26 18-29-41](https://user-images.githubusercontent.com/15329494/32065166-3b4fa5d2-ba7c-11e7-88a7-1815c4e1c382.png)
![bildschirmfoto von 2017-10-26 18-30-01](https://user-images.githubusercontent.com/15329494/32065175-40454146-ba7c-11e7-9ed9-39340d3f91cb.png)

error message after starting google-chrome in terminal:

google-chrome
[1:1:1026/182956.215784:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[1:1:1026/182956.215825:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome/resources.pak
Some features may not be available.
[10998:10998:1026/182956.332439:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[10998:10998:1026/182956.332644:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome/resources.pak
Some features may not be available.
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by bil-elmoussaoui** [comment]
Hmm, it's an issue with my latest attempt to fix the newest version of Chrome. I will try to do that this weekend

**Comment by bil-elmoussaoui** [comment]
I will close this one as #411 is already opened with the same issue
