### ISSUE TITLE
Flareget: Browser Integration won't work after applying hardcode-tray

### ISSUE THREAD

**Issue by NusryNizam** [bil-elmoussaoui/Hardcode-Tray#456]
### Specifications
- Hardcode-Tray version : `v3.9`
- Distribution : `Xubuntu 14.04.5, Ubuntu 16.04.3`
- Gtk version : `libgtk-3-0:amd64  3.10.8-0ubunt amd64 , libgtk2.0-0:amd64 2.24.23-0ubun amd64`
- Inkscape version : `0.92` 
- Cairo version : `` (no idea)
- Sni-qt version: `` (no idea
- Application name :  `flareget`
- Application version : `v4.5-102`

### Expected behavior and actual behavior
Browser integration won't work after applying hardcode-tray. This happens in Ubuntu 16.04.3 LTS with XFCE, and also with Xubuntu 14.04.5 LTS 

### Steps to reproduce the problem
1. Install Flareget
2. Then install browser extension for Browser integration
3. Apply hardcode-tray

**Comment by bil-elmoussaoui** [comment]
Hardcode-tray doesn't modify anything in the source code of flareget. It just add some icons in $HOME/.local/share/sni-qt/icons. Nothing more. So I can't understand how does this could change anything related to the browser extension
