### ISSUE TITLE
Support for f.lux.

### ISSUE THREAD

**Issue by phyrz91** [bil-elmoussaoui/Hardcode-Tray#457]
Can you add new tray icon for f.lux?

https://justgetflux.com/

Thank you in advance.

Great job!

**Comment by bil-elmoussaoui** [comment]
which icon theme are you using? f.lux doesn't use a hardcoded tray icon :) so it's up to the theme you're using to ship it 
The icon name is `fluxgui-panel`

**Comment by phyrz91** [comment]
Hi Bil, I use Papirus icon theme.

**Comment by bil-elmoussaoui** [comment]
Papirus icon theme already has this icon. Which distro you're using?

**Comment by phyrz91** [comment]
Debian testing.

**Comment by bil-elmoussaoui** [comment]
I have really no idea why it doesn't work in your case :/ Is there a way to download the deb file that you used to install f.lux on your system?

**Comment by varlesh** [comment]
https://github.com/xflux-gui/xflux-gui/issues/79
