### ISSUE TITLE
Deluge Icon

### ISSUE THREAD

**Issue by hxss** [bil-elmoussaoui/Hardcode-Tray#460]
### Specifications
- Hardcode-Tray version : `4.1-1`
- Distribution : `4.13.11-1-ARCH`
- Gtk version : `gtk2 2.24.31-1, gtk3 3.22.26-1`
- Application name :  `Deluge`
- Application version : `deluge 1.3.15+2+g38d7b7cdf-1`

### Expected behavior and actual behavior
Please add deluge tray icon replacement.
![image](https://user-images.githubusercontent.com/17298149/32769637-8e7b9d6c-c93e-11e7-9188-312ea9c013c0.png)

**Comment by varlesh** [comment]
It's upstream issue:
https://github.com/deluge-torrent/deluge/blob/develop/deluge/ui/gtkui/systemtray.py#L104

Used application icon name `deluge` on tray

**Comment by hxss** [comment]
I dont understand. Deluge now use "deluge" icon name and this is problem?

**Comment by varlesh** [comment]
Yes, other apps used different icons. 
For example, [QMPlay2](https://github.com/zaps166/QMPlay2):

- desktop-launcher icon name `QMPlay2`
- tray icon name `QMPlay2-panel`

**Comment by hxss** [comment]
got it. Thank you

**Comment by cas--** [comment]
As far as I was aware if the theme has a `<app>-panel.png` status icon then it will be used e.g. `/usr/share/icons/Faenza-Dark/status/24/deluge-panel.png`

**Comment by varlesh** [comment]
@cas-- That worked on Unity and Gnome only
