### ISSUE TITLE
Megasync icon not overridable 

### ISSUE THREAD

**Issue by Lupusaurus** [bil-elmoussaoui/Hardcode-Tray#464]
Megasync get updated (to 3.5 ver.) and the icon returned to the original, I tried to override it again but didn't work.

Hardcode-Tray version: 4.1, elementary Loki, Gtk 3.18

**Comment by varlesh** [comment]
Megasync not hardcoded anymore. Used tray icons from system icon theme now:
![2017-11-18 08-54-09](https://user-images.githubusercontent.com/8083855/32977026-20d792cc-cc3e-11e7-8482-328557915ffb.png)
@bil-elmoussaoui Bilal delete Mega from database
#296

**Comment by varlesh** [comment]
original hicolor status icons:
![image](https://user-images.githubusercontent.com/8083855/32977040-91d4bd74-cc3e-11e7-8eb5-74ccc6e5ce68.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh i don't think that we should remove the file from the database as people who still uses the old version can keep using it! 
i will remove it once it's updated everywhere 👍 
Thanks for the info!

**Comment by varlesh** [comment]
old version not worked.
