### ISSUE TITLE
Won't work on Franz v5

### ISSUE THREAD

**Issue by GGimenez96** [bil-elmoussaoui/Hardcode-Tray#466]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Ubuntu 16.04.3`
- Gtk version : `3.18`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Franz`
- Application version : `5.0.0-beta.14`

### Expected behavior and actual behavior
Franz tray icon is shown black, big and ugly. Messages counter won't appear. Hardcode-tray executed several times using different options and arguments but nothing seems to work.
### Steps to reproduce the problem
1. Install new version of Franz (5.0.0-beta.14)
2. Open Franz
3. Try executing hardcode-tray

**Comment by bil-elmoussaoui** [comment]
I can't compile the 5.0 beta. Can you please send me the resources folder? It can be found in the source folder of the application. Or just send me the deb file you've used to install the application

**Comment by GGimenez96** [comment]
I used the deb file provided by the official website: https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.14/franz_5.0.0-beta.14_amd64.deb

**Comment by bil-elmoussaoui** [comment]
I will take a look tomorrow

**Comment by GGimenez96** [comment]
Ok. Thanks!

**Comment by bil-elmoussaoui** [comment]
Fixed on master
