### ISSUE TITLE
Support for Caprine.

### ISSUE THREAD

**Issue by phyrz91** [bil-elmoussaoui/Hardcode-Tray#467]
Can you add new tray icon for Caprine?

https://github.com/sindresorhus/caprine

Thank you in advance.

**Comment by bil-elmoussaoui** [comment]
I'm using Caprine daily and i don't have any issue with that. Which theme are you using?

**Comment by phyrz91** [comment]
I use Papirus Dark icons  & Debian Testing and Hardcode-Tray: 4.1

**Comment by bil-elmoussaoui** [comment]
Can you run hardcode-tray and send me the logs? can be found on /tmp/Hardcode-Tray/ 
the files are ordered by date/time

**Comment by phyrz91** [comment]
[caprine.tar.gz](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1517883/caprine.tar.gz)

**Comment by bil-elmoussaoui** [comment]
It seems that it can find the caprine installation path. How did you install it? Can i have the link of the deb or the ppa or whatever you used please

**Comment by phyrz91** [comment]
I downloaded this version: caprine_2.7.1_amd64.deb
[https://github.com/sindresorhus/caprine/releases/tag/v2.7.1](url)

I used console(dpkg) for installed.

**Comment by bil-elmoussaoui** [comment]
Fixed on master.
