### ISSUE TITLE
Request for Zoom desktop client tray icon

### ISSUE THREAD

**Issue by fabiomargarido** [bil-elmoussaoui/Hardcode-Tray#468]
Request for Zoom desktop client (https://zoom.us) tray icon

### Specifications
- Hardcode-Tray version : `3.5.2.1~885~ubuntu16.04.1`
- Distribution : `Ubuntu 16.04.3 LTS`
- Gtk version : `3.18.9-1ubuntu3.3`
- Inkscape version : `0.91-7ubuntu2`
- Cairo version : `1.14.6-1`
- Sni-qt version: `0.2.7+20161212~11~ubuntu16.04.1`
- Application name :  `Zoom`
- Application version : `2.0.106600.0904`

### Expected behavior and actual behavior
Expect a themed tray icon, not the ugly default one 😃
This is a Qt application.

**Comment by bil-elmoussaoui** [comment]
Sorry but i can't fix this one :( 
The icon seems to be hardcoded on the binary. And as the application is closed source, i can't provide a patch to fix it or even find out a way to fix it.

The only thing i can propose you, is sending an email to the devs asking them to make the tray icon themeable

**Comment by fabiomargarido** [comment]
Thank you for the prompt reply.

I'll try to do that.

Keep up the great work!
