### ISSUE TITLE
Tusk app support

### ISSUE THREAD

**Issue by lbngoc** [bil-elmoussaoui/Hardcode-Tray#472]
Hi, can you add support for Tusk app (an alternate Evernote in Linux) ?
https://github.com/klauscfhq/tusk
https://electronjs.org/apps/tusk

**Comment by bil-elmoussaoui** [comment]
The app support was added in master
Here's the default tray icon
![icontray](https://user-images.githubusercontent.com/7660997/34045813-ec701f72-e1aa-11e7-92a1-defc9ca5fb3f.png)

The icon name is `tusk-indicator`
