### ISSUE TITLE
Discord Fault

### ISSUE THREAD

**Issue by remlap** [bil-elmoussaoui/Hardcode-Tray#473]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Ubuntu Mate 17.10`
- Gtk version : `3.22`
- Sni-qt version: `0.2.7+17.04.20170112-0ubuntu1`
- Application name :  `Discord`
- Application version : `12.11.2017 `

### Expected behavior and actual behavior
Discord has updated and now Hardcode-Tray will not convert.

**Comment by bil-elmoussaoui** [comment]
Here's the list of the new tray icons
- [ ] `discord-tray` ![tray](https://user-images.githubusercontent.com/7660997/34046009-b72cd5f2-e1ab-11e7-8dae-94642212a662.png)
- [ ] `discord-tray-connected` ![tray-connected](https://user-images.githubusercontent.com/7660997/34046010-b74a5c9e-e1ab-11e7-8994-13d3f9a1bdeb.png)
- [ ] `discord-tray-deafened` ![tray-deafened](https://user-images.githubusercontent.com/7660997/34046011-b760c70e-e1ab-11e7-8547-1acbef1ee9b9.png)
- [ ] `discord-tray-muted` ![tray-muted](https://user-images.githubusercontent.com/7660997/34046012-b77c717a-e1ab-11e7-9559-0d6c8a264bca.png)
- [ ] `discord-tray-speaking` ![tray-speaking](https://user-images.githubusercontent.com/7660997/34046013-b7972952-e1ab-11e7-8b6e-b97ba3a11d08.png)
- [ ] `discord-tray-unread` ![tray-unread](https://user-images.githubusercontent.com/7660997/34046014-b81cc8be-e1ab-11e7-9254-2e6a8982b33f.png)

Please report that to the theme you're using currently so they can add those new icons

**Comment by bil-elmoussaoui** [comment]
@varlesh Discord added new tray icons on their latest version

**Comment by varlesh** [comment]
@bil-elmoussaoui ok. deafened and muted - it's similar status?

**Comment by bil-elmoussaoui** [comment]
@varlesh The muted status is for the microphone/audio input; and the daefened status is for the audio output

**Comment by HenriqueY** [comment]
Discord tray still not working for me, using papirus

**Comment by varlesh** [comment]
On Discord 0.0.4 now tray icons packed to double archives - **ASAR** > **ZIP**:
`/usr/share/discord/resources/bootstrap/discord_desktop_core.zip/core.asar`

**core.asar**
images path: `app/images/systemtray/linux`
icons:
- tray.png
- tray-connected.png
- tray-deafened.png
- tray-muted.png
- tray-speaking.png
- tray-unread.png
preview:
![image](https://user-images.githubusercontent.com/8083855/35998865-5498ae36-0d37-11e8-85d9-feaa069bb303.png)

**Comment by varlesh** [comment]
extracted core.asar:
[core.asar.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1708842/core.asar.zip)

**Comment by HenriqueY** [comment]
I managed to replace the images on the file u pointed, also changed it on '/home/user/.config/discord', but got this error:
![screenshot from 2018-02-08 20-00-50](https://user-images.githubusercontent.com/25267506/36000765-23114dcc-0d0b-11e8-80ea-fac6f1e62ac9.png)

**Comment by varlesh** [comment]
@bil-elmoussaoui

**Comment by bil-elmoussaoui** [comment]
See https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/497
I will take a look tonight. Don't really know why the put the asar file on an archive............
