### ISSUE TITLE
Add Whatapp Desktop v0.4.0 support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#478]
Not sure since when exactly, but Whatsapp-Desktop now uses asar for the assets. We should add a different database file for it.

**Comment by varlesh** [comment]
Icons not packed and located on directory `/opt/whatsapp-desktop/resources/app/assets/icon`:

- icon.png
- icon@1.5x.png
- icon@1.25x.png
- icon@2x.png
- iconWarning.png
- iconWarningWithMsg.png
- iconWithMsg.png

![image](https://user-images.githubusercontent.com/8083855/34534407-734c0804-f0d7-11e7-81df-766fd4f657ed.png)
Version 0.4.2 resources from deb-package
