### ISSUE TITLE
Wrong Logfile Date Format

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#481]
One thing I noticed when testing for #480 (so same versions) is that the logfiles aren't using the right date format. [Within the log](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/HardcodeTray/modules/log.py#L32) it's fine, using `%Y-%m-%d %H:%M:%S` as expected. For the [log file name](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/const.py.in#L33-L34) however (and backup files? not sure what they are) it uses `d-%m-%Y_%H-%M-%S` which is super weird.

Only noticed this because when I was looking for the log files for that issue I realised after some confusion that the files weren't being listed in chronological order.

**Comment by bil-elmoussaoui** [comment]
I'm willing to clean the whole code for the next major release and add a lot of tests for every signle small case. To make sure the product distributed is working correctly in every platform with few simplifications ;) I will make sure the backup and logs have the correct format

**Comment by bil-elmoussaoui** [comment]
Fixed on master. Should be there on v4.3
