### ISSUE TITLE
Unable to change Whatsapp panel icon

### ISSUE THREAD

**Issue by jeremyj** [bil-elmoussaoui/Hardcode-Tray#485]
### Specifications
- Hardcode-Tray version : `3.5.2.1~885~ubuntu16.04.1`
- Distribution : `Ubuntu 16.04.3 LTS`
- Gtk version : `2`
- Cairo version : `1.14.6` (not sure)
- Sni-qt version: `0.2.7+20161212~11~ubuntu16.04.1`
- Application name :  `Whataspp`
- Application version : `0.4.2`

### Expected behavior and actual behavior
icon is expected to be Papiurs (grey monochrome) but is instead the Whatsapp default (colored)

### Steps to reproduce the problem
1. install Papirus theme from official PPA
2. install hardcode-tray from official PPA
3. apply Papirus icon theme
4. `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus`
5. the above command changes all icons except Whatsapp
6. Also tried 
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus --only whatsapp` to confirm that Whatsapp icon is not detected (`No apps to fix!`)

**Comment by varlesh** [comment]
@jeremyj You use old version package 3.5.2.1~885~ubuntu16.04.1 builded 2017-10-24

@wa4557 i think PPA not updated anymore

**Comment by jeremyj** [comment]
@wa4557 is it possible to update the PPA?

**Comment by bil-elmoussaoui** [comment]
The PPA should be updated right now. Don't know why it was failing to update recently :(

**Comment by varlesh** [comment]
PPA have wrong version: `hardcode-tray - 3.5.2.1~908~ubuntu17.10.1`

**Comment by varlesh** [comment]
now 4.2

**Comment by bil-elmoussaoui** [comment]
I will fix that right now

**Comment by jeremyj** [comment]
I still see version `3.5.2.1~908~ubuntu16.04.1` in the PPA

**Comment by jeremyj** [comment]
I'm sorry guys I don't understand what's going on with the PPA.
@varlesh says it's now 4.2 but I still see version `3.5.2.1~908~ubuntu16.04.1` and my WhatsApp icon is still green

**Comment by bil-elmoussaoui** [comment]
@jeremyj The PPA should be up to date, I couldn't update the version number. I don't know why :( 
Can you try to install it manually? shouldn't be too complicated...If you need any help to do so, don't hesitate to check our Gitter channel, I will provide as much help as I can!

**Comment by jeremyj** [comment]
@bil-elmoussaoui OK I will try compilng the package
