### ISSUE TITLE
Messenger for Desktop

### ISSUE THREAD

**Issue by natanvarga** [bil-elmoussaoui/Hardcode-Tray#486]
### Specifications
- Hardcode-Tray version : `4.2-1`
- Distribution : `Manjaro Linux`
- Desktop environment : `cinnamon`
- Gtk version : `3.22.26-4`
- Inkscape version : `0.92.2-8`
- Cairo version : `1.15.10-1`
- Sni-qt version: `r.-1`
- Application name :  `messengerfordesktop`
- Application version : `2.0.9+42+g4e4d6f1-3`

### Expected behavior and actual behavior
Does not change to theme's panel icon. Says no apps to update.
### Steps to reproduce the problem
1. Run `hardcode-tray`
2. Run it with argument `--size 16`
3. Run it with argument `--conversion-tool RSVGConvert`

**Comment by bil-elmoussaoui** [comment]
I will take a look right now.  Please, next time include the package on the issue. I will add that to the issue template

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by natanvarga** [comment]
Thanks. Fixed now.
