### ISSUE TITLE
Chromium 64 hard-coded tray icon not getting fixed

### ISSUE THREAD

**Issue by terencode** [bil-elmoussaoui/Hardcode-Tray#488]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `ArchLinux`
- Gtk version : `3.22`
- Inkscape version : `0.92.2 5c3e80d` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Chromium`
- Application version : `64.0.3282.119`

### Expected behavior and actual behavior
Icon should get replaced by the one of the corresponding theme but it's not the case.
### Steps to reproduce the problem
1.  sudo -E hardcode-tray 
2. Apply for chromium
3. Start chromium

**Comment by bil-elmoussaoui** [comment]
Can you please paste the output of Hardcode-Tray when you run it?

**Comment by GUiHKX** [comment]
I'm facing the same issue 

```
$ sudo -E hardcode-tray
Welcome to Hardcode-Tray!
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Chromium            [######..............................] 1/6 16.7% 0.04s
Discord Canary      [############........................] 2/6 33.3% 0.02s
JDownloader         [##################..................] 3/6 50.0% 0.01s
Steam               [########################............] 4/6 66.7% 0.01s
Teamviewer          [##############################......] 5/6 83.3% 0.00s
Telegram            [####################################] 6/6 100.0% 0.20s
Took 0.29s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by GUiHKX** [comment]
Log file for `sudo -E hardcode-tray --only chromium`:

```
[DEBUG] 2018-01-26 00:56:03 DE: Kde
[DEBUG] 2018-01-26 00:56:03 Config file: Not found.
[DEBUG] 2018-01-26 00:56:03 Arguments/Icon Size: None
[DEBUG] 2018-01-26 00:56:03 System/Icon Size: 22
[DEBUG] 2018-01-26 00:56:03 System/Theme: Papirus-Dark
[DEBUG] 2018-01-26 00:56:03 Arguments/Conversion Tool: None
[DEBUG] 2018-01-26 00:56:03 Config/Conversion Tool: None
[DEBUG] 2018-01-26 00:56:03 SVG Factory: Failed Inkscape
[DEBUG] 2018-01-26 00:56:03 SVG Factory: Failed CairoSVG
[DEBUG] 2018-01-26 00:56:03 SVG Factory: Import RSVGConvert
[DEBUG] 2018-01-26 00:56:03 Arguments/Only: chromium
[DEBUG] 2018-01-26 00:56:04 Config/Backup Ignore: False
[DEBUG] 2018-01-26 00:56:04 Create new backup folder for Chromium
[DEBUG] 2018-01-26 00:56:04 Creating directory: /home/gui/.config/Hardcode-Tray/Chromium/26-01-2018_00-56-04/
[DEBUG] 2018-01-26 00:56:04 Executing command: rsvg-convert -f png -o /tmp/tmpfmq8r3_r -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg
[ERROR] 2018-01-26 00:56:04 Couldn't find a PNG file.
```

**Comment by terencode** [comment]
@bil-elmoussaoui forgot about that sorry, here are the relevant lines: 
``[DEBUG] 2018-01-25 20:14:15 Executing command: inkscape -z -f /usr/share/icons/Papirus/24x24/panel/google-chrome-tray.svg -e /tmp/tmpzsutk_82 -w 24 -h 24
[ERROR] 2018-01-25 20:14:15 Couldn't find a PNG file.
``

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by GUiHKX** [comment]
Thanks for the fix, but the icon looks too blurry for me on KDE...

![image](https://user-images.githubusercontent.com/626206/35472755-3d3f5b0c-035c-11e8-9bdc-69223b9d9d74.png)

**Comment by bil-elmoussaoui** [comment]
@GUiHKX You can force a different size for chromium only using 
`sudo -E hardcode-tray --only chromium --size 24` and see if it makes things better ;) You can try also 16/22

**Comment by GUiHKX** [comment]
Unfortunately it didn't. I mean, using `16` made the icon look larger, but it was still blurry. Do you think that's not fixable or is it a KDE issue?

**Comment by bil-elmoussaoui** [comment]
I don't think It's an issue of Hardcode-Tray. Can you try with a different conversion tool like Inkscape?

**Comment by GUiHKX** [comment]
I see no difference unfortunately:

![image](https://user-images.githubusercontent.com/626206/35473431-bd64e3b4-0367-11e8-8ff8-2bac429dadfc.png)


Log:
```
[DEBUG] 2018-01-27 13:33:20 DE: Kde
[DEBUG] 2018-01-27 13:33:20 Config file: Not found.
[DEBUG] 2018-01-27 13:33:20 Arguments/Icon Size: None
[DEBUG] 2018-01-27 13:33:20 System/Icon Size: 22
[DEBUG] 2018-01-27 13:33:20 System/Theme: Papirus-Dark
[DEBUG] 2018-01-27 13:33:20 Arguments/Conversion Tool: None
[DEBUG] 2018-01-27 13:33:20 Config/Conversion Tool: None
[DEBUG] 2018-01-27 13:33:20 SVG Factory: Import Inkscape
[DEBUG] 2018-01-27 13:33:20 Arguments/Only: chromium
[DEBUG] 2018-01-27 13:35:07 Config/Backup Ignore: False
[DEBUG] 2018-01-27 13:35:07 Create new backup folder for Chromium
[DEBUG] 2018-01-27 13:35:07 Creating directory: /home/gui/.config/Hardcode-Tray/Chromium/2018-01-27 13:35:07/
[DEBUG] 2018-01-27 13:35:07 Executing command: inkscape -z -f /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg -e /tmp/tmpaelr7qnw -w 22 -h 22
[DEBUG] 2018-01-27 13:35:07 Backup file: /tmp/10156 to: /home/gui/.config/Hardcode-Tray/Chromium/2018-01-27 13:35:07/10156
```

But to be honest, I don't think the original icon looks that great either, lol

![image](https://user-images.githubusercontent.com/626206/35473445-fd63df1a-0367-11e8-91a1-a6b47824c053.png)

So never mind I guess...

**Comment by bil-elmoussaoui** [comment]
Must be something related to KDE then

**Comment by varlesh** [comment]
@GUiHKX 
`XDG_CURRENT_DESKTOP=Unity chromium`
by default on KDE used 22px icons on tray

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/35474190-58e95c98-03a4-11e8-80ab-f59fd29fb3fb.png)

**Comment by GUiHKX** [comment]
@varlesh I've tried to run that command but I saw no changes as well (am I supposed to?)

On a side note, is that a RSS reader in your tray? Which program is it? Thanks :)

**Comment by varlesh** [comment]
@GUiHKX 
> I've tried to run that command but I saw no changes as well (am I supposed to?)

Need kill chromium:
`killall -9 chromium`
or maybe (it's different on some Linux OS's):
`killall -9 chromium-browser`
And start again with Unity env option from terminal:
`XDG_CURRENT_DESKTOP=Unity chromium`
or:
`XDG_CURRENT_DESKTOP=Unity chromium-browser`
tray icon will be rendered right and hardcoded version too...

**Comment by GUiHKX** [comment]
Yup, tried that, still didn't work. Blurry tray icon still

**Comment by varlesh** [comment]
> On a side note, is that a RSS reader in your tray? Which program is it? Thanks :)

install widget:
plasma-widget https://github.com/cute-jumper/plasma-rss-indicator
also you can change icon tray.
Download attach file and extract to **~/.local/share/plasma/plasmoids/rss_indicator/contents/ui/**
[akregator.tar.gz](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1670329/akregator.tar.gz)
And changed on code ~/.local/share/plasma/plasmoids/rss_indicator/contents/ui/main.qml:
`property string appletIcon: "akregator.svg"`

**Comment by varlesh** [comment]
> Yup, tried that, still didn't work. Blurry tray icon still

Hm, it's strange... Maybe you need libappindicator libs or other Unity-specific libs on Arch?

**Comment by GUiHKX** [comment]
Bingo! I had `libindicator-gtk2` installed, but not `libindicator-gtk3`. Installing it fixed it! Thank you very much!

**Comment by varlesh** [comment]
without `XDG_CURRENT_DESKTOP=Unity`:
![image](https://user-images.githubusercontent.com/8083855/35474607-201cbe22-03aa-11e8-858e-19ee8658ac64.png)
with `XDG_CURRENT_DESKTOP=Unity`:
![image](https://user-images.githubusercontent.com/8083855/35474612-2facdc96-03aa-11e8-8b60-d9ce1e8d59ce.png)

**Comment by GUiHKX** [comment]
Using `XDG_CURRENT_DESKTOP=Unity` is better for the tray icon size, but Chromium's window controls are hidden when the window is maximized.... But not that big of a deal.

**Comment by abouvier** [comment]
How did you make this Chromium tray icon appear? I'm on KDE and I never saw one.

**Comment by GUiHKX** [comment]
In order to make the icon appear, first you have to enable this option in `chrome://settings`:

![image](https://user-images.githubusercontent.com/626206/35694997-4d72e978-076a-11e8-8fba-48fc7149d7ea.png)

Even then, the tray icon will only show up you have an extension that requires the [`background` permission](https://developer.chrome.com/apps/declare_permissions#background).

**Comment by terencode** [comment]
@bilelmoussaoui since Chromium 65, It's not working anymore.
From the debug log: 
``
[DEBUG] 2018-03-17 12:14:16 Executing command: inkscape -z -f /usr/share/icons/Flat-Remix/panel/google-chrome-tray.svg -e /tmp/tmpifw9ekyl -w 22 -h 22
[ERROR] 2018-03-17 12:14:16 Couldn't find a PNG file.
``

**Comment by Grief** [comment]
@bilelmoussaoui I can confirm that the fix is not working anymore. Could you please re-open this issue?
