### ISSUE TITLE
Mailspring seems does not work

### ISSUE THREAD

**Issue by oceanicdev** [bil-elmoussaoui/Hardcode-Tray#495]
Seems it does not work after latest updated of Mailspring (1.1.3-27dcee2f). Icon is not fixed.

![screenshot from 2018-02-07 18-03-37](https://user-images.githubusercontent.com/29436639/35923423-3eb34574-0c31-11e8-977c-3fa4eb157c48.png)

**Comment by drakkar1969** [comment]
Icon names have changed, need to update the `mailspring.json` file

- `MenuItem-Inbox-Zero@2x.png` changed to `MenuItem-Inbox-Zero.png`
- `MenuItem-Inbox-Full@2x.png` changed to `MenuItem-Inbox-Full.png`
- `MenuItem-Inbox-Full-NewItems@2x.png` changed to `MenuItem-Inbox-Full-NewItems.png`

Thanks!

**Comment by oceanicdev** [comment]
@drakkar1969 thanks!

**Comment by bil-elmoussaoui** [comment]
Fixed on master
