### ISSUE TITLE
Signal Desktop support

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#498]
- site: https://signal.org
- method: **electron**
- install path: **/opt/Signal**
- icons path: **/opt/Signal/resources/**
- icon names:
**read messages:**
```
images/icon_16.png
images/icon_32.png
images/icon_48.png
images/icon_128.png
images/icon_250.png
images/icon_256.png
images/icon_1024.png
```
**unread messages:**
```
images/alert/16/1.png
images/alert/16/2.png
images/alert/16/3.png
images/alert/16/4.png
images/alert/16/5.png
images/alert/16/6.png
images/alert/16/7.png
images/alert/16/8.png
images/alert/16/9.png
images/alert/16/10.png
images/alert/256/1.png
images/alert/256/2.png
images/alert/256/3.png
images/alert/256/4.png
images/alert/256/5.png
images/alert/256/6.png
images/alert/256/7.png
images/alert/256/8.png
images/alert/256/9.png
images/alert/256/10.png

```
preview:
![image](https://user-images.githubusercontent.com/8083855/36059299-f503c258-0e4e-11e8-85ee-a6ba4e186b3a.png)

![image](https://user-images.githubusercontent.com/8083855/36059215-f3cd2958-0e4c-11e8-925e-48a53f7ef640.png)

**Comment by bil-elmoussaoui** [comment]
Fixed
