### ISSUE TITLE
Revert on Fedora Wayland

### ISSUE THREAD

**Issue by orschiro** [bil-elmoussaoui/Hardcode-Tray#499]
Built hardcode tray from source on Fedora 27 Wayland to revert the Telegram icon. 

But running into issues when running with sudo and from root. 

Is there any solution to this?

Thank you for your help!

As root:

```
[root@localhost Hardcode-Tray]# hardcode-tray --revert
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Traceback (most recent call last):
  File "/bin/hardcode-tray", line 103, in <module>
    if not isinstance(App.theme(), dict):
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 177, in theme
    theme = App.get("theme")
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 77, in get
    value = method()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/config/system.py", line 67, in theme
    theme_name = Gtk.Settings.get_default().get_property("gtk-icon-theme-name")
AttributeError: 'NoneType' object has no attribute 'get_property'
```

with sudo:

```
[orschiro@localhost Hardcode-Tray]$ sudo -E hardcode-tray --revert
No protocol specified

** (hardcode-tray:19812): WARNING **: Could not open X display
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Gnome
Scaling Factor: 1
Icon Size: 22
Icon Theme: Adwaita
Failed to load any SVG module.
[orschiro@localhost Hardcode-Tray]$ sudo -E hardcode-tray --revert
No protocol specified

** (hardcode-tray:19833): WARNING **: Could not open X display
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Gnome
Scaling Factor: 1
Icon Size: 22
Icon Theme: Adwaita
Failed to load any SVG module.
[orschiro@localhost Hardcode-Tray]$ sudo -E hardcode-tray --revert
No protocol specified

** (hardcode-tray:20088): WARNING **: Could not open X display
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Gnome
Scaling Factor: 1
Icon Size: 22
Icon Theme: Adwaita
Failed to load any SVG module.
```

**Comment by bil-elmoussaoui** [comment]
You shouldn't use Hardcode-Tray as root. 
And for the revert part, as mentionned here, you need an svg module, you can install librsvg for example, or python3-cairosvg

**Comment by bil-elmoussaoui** [comment]
You should use an icon theme that has the telegram icons.  you can just use --theme argument for that

**Comment by orschiro** [comment]
Wait you mean that Adwaita doesn't have a Telegram icon and that's why I don't see the default icon (but I do see it when using the Flatpak version because the icon is packaged?)?

![image](https://user-images.githubusercontent.com/170947/36197961-a2d1bd30-1175-11e8-892c-166187735837.png)

**Comment by bil-elmoussaoui** [comment]
When I meant is that the infrastructure of hardcode-tray is not coded correctly. It requires an icon theme that does have a modified version of telegram tray icons (numix or papirus for example) in order to execute the revert action. Otherwise, none of the supported apps will be detected. I'm currently thinking of a way to rewrite some parts of the script logic to make it work as it should.

**Comment by orschiro** [comment]
Got you! :-)

Installed Numix and then was able to revert. Thank you so much!

![image](https://user-images.githubusercontent.com/170947/36198553-2e1b8dd4-1177-11e8-87b4-a6c5a9f4e588.png)

**Comment by orschiro** [comment]
Sorry need to reopen the issue. Not only having this issue with Telegram but also Skype. 

Reverted the backup but the icon is still not restored. Is there another way I can restore the Skype icon manually?

![image](https://user-images.githubusercontent.com/170947/36302082-6f997cd0-1307-11e8-922d-c8eba48bd067.png)

```
(Q)uit to cancel
(Q)uit to cancel
Select a restore date : q
1) Skype/08-01-2018_16-24-26 
2) Skype/2018-02-14 19:16:35 
3) Skype/23-01-2018_10-16-02 
4) Skype/30-12-2017_09-11-50 
(Q)uit to cancel
Select a restore date : 4
Skype               [#########...........................] 1/4 25.0% 3.63s
1) Slack/2018-02-14 19:16:38 
```

**Comment by bil-elmoussaoui** [comment]
You can always reinstall skype and the icon will be reverted automatically... Can you share the content of `.cache/hardcode-Tray/skype****/` and see if the icons are the default ones or not?

**Comment by orschiro** [comment]
> You can always reinstall skype and the icon will be reverted automatically..

Good catch! Actually I tried that then with Telegram and it did not work for some reasons. 

In the case of Skype it worked (for now). Let me do some more testing and rebooting...

BTW I don't have the cache folder:

```
[orschiro@localhost ~]$ cd .cache/hardcode-Tray/
bash: cd: .cache/hardcode-Tray/: No such file or directory
```

**Comment by bil-elmoussaoui** [comment]
Sorry it's `.config/Hardcode-Tray/`. That didn't work on Telegram because the icons are created once the application is open. If the files are there, they don't get replaced. While Skype has the tray icons replaced on a binary file called  `app.asar`

**Comment by orschiro** [comment]
Skype folder looks ok to me. But Telegram not.

Check this: https://youtu.be/62DFOzuqHdw

**Comment by bil-elmoussaoui** [comment]
Telegram should have a backup ignore option enabled. As the icons shouldn't even be stored anyway. Once they're removed, Telegram will recreate them automatically

**Comment by orschiro** [comment]
>  Once they're removed, Telegram will recreate them automatically

So I just need to remove the backup folder? Going to try that again. Had to actually install the Flatpak version of Telegram because only that kept the default icon. The one from the repo always reverted back to using the modified icon.

**Comment by bil-elmoussaoui** [comment]
I didn't said that you should remove the backup files :p You should remove the icons in `.local/share/TelegramDesktop/tdata/ticons`

**Comment by orschiro** [comment]
Haha got you. The contents of that folder look correct right? But still the icon is wrong after reopening it. 

![image](https://user-images.githubusercontent.com/170947/36305093-79c50bce-1312-11e8-8ccf-6dabbf265b4d.png)

**Comment by bil-elmoussaoui** [comment]
Can you check this path too https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/telegram.json#L11 ?

**Comment by orschiro** [comment]
This folder doesn't exist:

```
[orschiro@localhost ~]$ cd .TelegramDesktop/tdata/ticons/
bash: cd: .TelegramDesktop/tdata/ticons/: No such file or directory
```

**Comment by bil-elmoussaoui** [comment]
Well, in that case I have no idea why the icons are not restored. Can you remove the whole ticons folder, check if there's anything in /tmp folder and remove it too (related to telegram ofc) and restart the application

**Comment by orschiro** [comment]
Will do. Look at this weird behaviour: https://youtu.be/ID-kPko4oMY

**Comment by orschiro** [comment]
Hmm tmp doesn't have any Telegram related files:

```
[orschiro@localhost tmp]$ ls
 1c76594fbf1bc2479fe309881a3e36bc-{87A94AB0-E370-4cde-98D3-ACC110C5967D}
 adb.1000.log
 gnome-software-432EEZ
 gnome-software-V7OOEZ
 Hardcode-Tray
 mpsyt-input0211_zc2
 mpsyt-mpvq03gfuyn.sock
 skypeforlinux-64.rpm
'skypeforlinux Crashes'
 skype.gpgsig.uaQ1gP
 systemd-private-879a7c9e327c44d3a72cccd81dcc1942-chronyd.service-fLw5PR
 systemd-private-879a7c9e327c44d3a72cccd81dcc1942-colord.service-2e14D1
 systemd-private-879a7c9e327c44d3a72cccd81dcc1942-fwupd.service-gLeHIH
 systemd-private-879a7c9e327c44d3a72cccd81dcc1942-rtkit-daemon.service-H0QS7i
 tmux-1000
 tracker-extract-files.1000
```

**Comment by orschiro** [comment]
Yes, it wouldn't show Telegram at all.... :-(

**Comment by orschiro** [comment]
But let me do some more testing. I removed telegram desktop (repo version) and reinstalled. Now it shows up correctly. Weird! Will report back later.

**Comment by orschiro** [comment]
OK, Telegram and Skype now seems to work well. :-) 

But Franz is broken too. Running it from the franz-5.0.0-beta.15-x86_64.AppImage.

Is there also a trick for this to remove any kind of old cache files or icons?

Thanks @bil-elmoussaoui! Really appreciate your help

![screenshot from 2018-02-16 16-39-32](https://user-images.githubusercontent.com/170947/36316314-4c0ff928-133a-11e8-8f00-1f75f8fcb435.png)

**Comment by bil-elmoussaoui** [comment]
We can't patch AppImages applications yet. So there was no patch applied from Hardcode-Tray. If the tray icon doesn't look as expected, well it's an issue with either the extension you're using or the AppImage itself....

**Comment by orschiro** [comment]
OK that's good to know. Let me dig further now...

PS: it cannot be that the AppImage somehow uses the icons from the previously installed deb file right?

**Comment by bil-elmoussaoui** [comment]
Don't really know how AppImages works. It's supposed to be sandboxed. But got no idea how they manage to get their stuff to work... Plus Franz, uses ASAR files (binary ones) to store the tray icons. There's no possible way for a package to use another package's icons in this case...

**Comment by orschiro** [comment]
OK, so the Franz problem seems to be somewhere else: https://github.com/meetfranz/franz/issues/701#issuecomment-366302624

Finally, thanks for all your help restoring my configurations. I am good and settled. :-)
