### ISSUE TITLE
Chrome icon issue

### ISSUE THREAD

**Issue by iwex** [bil-elmoussaoui/Hardcode-Tray#500]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Ubuntu 16.04`
- Gtk version : `3.20`
- Inkscape version : `0.91 r13725`
- Cairo version : `1.0.19`
- Sni-qt version: `0.2.7`
- Application name :  `Chrome`
- Application version : `Version 64.0.3282.140 (Official Build) (64-bit)`

`sudo -E hardcode-tray` and Chrome icon still colourful :)
Logs: https://pastebin.com/MC5bvif9

**Comment by bil-elmoussaoui** [comment]
Somehow, launchpad doesn't trigger new builds anymore :/ We have already added support of the latest chrome/chromium version on master. Can you try to build from there? It's pretty easy to do. If you have any issue with that, don't hesitate to join our Gitter channel. I will try to provide as much help as I can..

**Comment by iwex** [comment]
@bil-elmoussaoui 
```
The Meson build system
Version: 0.29.0
Source dir: /home/iwex/Hardcode-Tray
Build dir: /home/iwex
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

**Comment by bil-elmoussaoui** [comment]
You need to upgrade meson `sudo pip3 install meson --upgrade`

**Comment by iwex** [comment]
@bil-elmoussaoui thanks, i've installed)
But still no success with chrome..

**Comment by bil-elmoussaoui** [comment]
What do you mean by no success? what's the output on the terminal and the log files in /tmp/Hardcode-Tray?
