### ISSUE TITLE
Counldn't Start Hardcode-Tray

### ISSUE THREAD

**Issue by foreverBirds** [bil-elmoussaoui/Hardcode-Tray#501]
# Specifications
- Hardcode-Tray version : **`It is unknown due to start error`**
- Distribution : `Arch Linux(64 bits)`
- Gtk2 version : `2.24.32-1`
- Gtk3 version : `3.22.28-1`
- Cairo version : `1.15.10-1`
- Sni-qt version: `0.2.6`

# Unexpected Behaviour
When I type the command **`sudo -E Hardcode-Tray`** to start the Hardcode-Tray
```
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 30, in <module>
    from gi import require_version
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
```

**I have installed `the patched version for sni-qt`,`Hardcode-Tray` manually, installed `python3-gi` by the command `sudo python3 -m pip intsall gi`, installed other dependencies by `pacman`**

**I am sure that there were no error during installation**

**And I can't install `Hardcode-Tray` via `yaourt` in Arch Linux.**

**Comment by bil-elmoussaoui** [comment]
Why can't you install hardcode-tray using yaourt? And you can't install python3-gi from pip. You should install gobject-introspection and the python package for it using pacman.

**Comment by foreverBirds** [comment]
@bil-elmoussaoui because there are some orphaned package could be dealt with  **`yaourt`**, and there is no package called **`python3-gi`**    in **`Arch Linux Official Repositories`**.
I am sure that I have installed **`gobject-introspection`** 

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 A59 发送_

**Comment by bil-elmoussaoui** [comment]
@foreverBirds  All you need is `gobject-introspection` and `python-gobject` from pacman. Nothing more. 
The package you installed using pip must be removed first.

**Comment by foreverBirds** [comment]
@bil-elmoussaoui OK, I will try it later

**Comment by bil-elmoussaoui** [comment]
Any updates?

**Comment by foreverBirds** [comment]
Yeah,I just uncomment the **[multilib]** section in `/etc/pacman.conf` and successfully try installing it both via **yaourt**  and manually.

**Comment by bil-elmoussaoui** [comment]
Dors it work now?

**Comment by foreverBirds** [comment]
Yes
