### ISSUE TITLE
Flameshot support

### ISSUE THREAD

**Issue by orange-buffalo** [bil-elmoussaoui/Hardcode-Tray#506]
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Kubuntu 17.10`
- Gtk version : `3.22`
- Inkscape version : `0.92.1`
- Sni-qt version: `0.2.7`
- Application name :  `Flameshot`
- Application version : `0.5.1`

### Expected behavior and actual behavior

Currently Flameshot (https://github.com/lupoDharkael/flameshot) is not supported and its regular icon is displayed in the tray. 

![image](https://user-images.githubusercontent.com/4532247/36646472-d2f88eee-1acb-11e8-868b-32f731795c77.png)

Would be great to have this application fully supported.

**Comment by bil-elmoussaoui** [comment]
I will take a look right now :+1:

**Comment by bil-elmoussaoui** [comment]
The application uses an icon from the qresource file. Which means it's hardcoded on the binary file 
https://github.com/lupoDharkael/flameshot/blob/b1174a1e0501fff9e1d09bdf14028ca230746fe5/src/core/controller.cpp#L128
We can't do anything about it. You should report that upstream so they can use `QIcon::fromTheme("flameshot-tray)` and fall back to the hardcoded icon if nothing was found.

**Comment by orange-buffalo** [comment]
Thanks a lot for your investigation, @bil-elmoussaoui! I have created an issue in upstream (lupoDharkael/flameshot#143).
