### ISSUE TITLE
HiDPI Compatibility

### ISSUE THREAD

**Issue by crouthamela** [bil-elmoussaoui/Hardcode-Tray#507]
Could you make this HiDPI compatible? When I run this, even with 24px icons selected, the fixed apps (such as MEGA) are all pixelated due to my screen being HiDPI with 2x scaling. If I could specify higher resolutions, that would be helpful.

**Comment by bil-elmoussaoui** [comment]
Already implemented thanks to the scaling factor config entry
https://github.com/bil-elmoussaoui/Hardcode-Tray#config-file

**Comment by crouthamela** [comment]
Thanks for the quick reply. Do you have an example config file? I'm unfamiliar with how to format that correctly.

**Comment by bil-elmoussaoui** [comment]
There's an example here 
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/config.json

**Comment by crouthamela** [comment]
Thanks!
