### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by gonzo-the-great** [bil-elmoussaoui/Hardcode-Tray#509]
### Specifications
- Hardcode-Tray version : `4.2-1`
- Distribution : `Manjaro Linux (64 bits)`
- Gtk2 version : `2.24.32-1`
- Gtk3 version : `3.22.28-1`
- Inkscape version : `0.92.2-8`
- Cairo version : `1.15.10-1`
- Sni-qt version: `r-1`

when starting hardcode-tray i get the following error
```
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 30, in <module>
  from gi import require_version
ModuleNotFoundError: No module named 'gi
```
installed via pamac, and have these dependents installed too

- gobject-introspection
- gtk3
- inkscape
- imagemagick
- lib32-sni-qt-patched-git
- librsvg
- python
- python3-cairosvg
- python-gobject
- sni-qt-patched-git

**Comment by gonzo-the-great** [comment]
ok, ive fixed the issue,
ive been using anaconda and my python path was set to

```
# added by Anaconda3 installer
export PATH="/home/adhunter/anaconda3/bin:$PATH"
```

**Comment by maeckha** [comment]
Hi ghost,
I´ve got the same issue and I checked my .zshrc and my .bashrc to confirm that my PATH is also pointed to anaconda3/bin:$PATH. 
But I don´t know what to do next. Do I change the setting of the python path? Or do I have to execute hardcode-tray differently?

Thank you.

**Comment by rcragun** [comment]
What, exactly, was the solution?
