### ISSUE TITLE
Skype script doesn't work

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#53]
The script doesn't try to fix skype icons. Doesn't the second column in db.csv needs to be a folder? (I don't have a skype folder in `/usr/bin`

**Comment by bil-elmoussaoui** [comment]
Yeah, the second column is there to check if the application is installed. Can you give me any other location of skype in your DE?

**Comment by wa4557** [comment]
I think we shudl go with /usr/share/skype

**Comment by wa4557** [comment]
Hmm. Now the skype icon doesn't show up anymore at all :(

**Comment by bil-elmoussaoui** [comment]
Ah! you should install sni-qt 32 bits version too (just for skype as it's a 32 bits application)

**Comment by wa4557** [comment]
yes :/

**Comment by bil-elmoussaoui** [comment]
The icons are correctly copied? I canno't test this right now, i'm using a beta version of elementary OS and the indicators does not work. can you share a screenshot of ```~/.local/share/sni-qt/icons/skype```

**Comment by wa4557** [comment]
Yes the icons are correct. Reverting back to the default sni-qt package and the usual skype tray icon shows. 
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8581065/9489902c-25be-11e5-8cc7-a1eb694c8589.png)

**Comment by bil-elmoussaoui** [comment]
@wa4557 when you say that the icon is not showing, did the "does not exist" icon is shown ? If so, can you try to change the status to something else

**Comment by wa4557** [comment]
No icon, just nothing

**Comment by bil-elmoussaoui** [comment]
can you reinstall the patched version of sni-qt and paste the result of this ```dpkg -l | grep sni-qt```

**Comment by wa4557** [comment]
ii  sni-qt:amd64                                         0.2.7-0~78~ubuntu15.04.1                                           amd64        indicator support for Qt
ii  sni-qt:i386                                          0.2.7-0~78~ubuntu15.04.1                                           i386         indicator support for Qt

**Comment by wa4557** [comment]
Hey reinstalling did it, it works :+1:

**Comment by bil-elmoussaoui** [comment]
@wa4557 Well , share a screenshot to see how it's looks like using Numix icons :dancer:

**Comment by wa4557** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8581264/e67d9792-25bf-11e5-921b-0c8cea03f1b8.png)

**Comment by bil-elmoussaoui** [comment]
That's awesome! i updated the database file
