### ISSUE TITLE
The tray icon of insync and mailspring has not been replaced.

### ISSUE THREAD

**Issue by x86vk** [bil-elmoussaoui/Hardcode-Tray#535]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Arch Linux`
- Gtk version : `3.22`
- Inkscape version : `0.92.2`
- Cairo version : `Not Installed`
- Application name :  `Insync` and `Mailspring`
- Application version : `1.4.7.37098`

### Expected behavior and actual behavior
The tray icon of insync and mailspring should be replaced, but not.
### Steps to reproduce the problem
1. install all of the applications
2. run the command `sudo -E hardcode-tray --apply --size 22 --theme Papirus-Adapta`

As pasted, the tray icon of insync and mailspring has not been replaced.
![image](https://user-images.githubusercontent.com/12608529/41193273-659b310e-6c3c-11e8-8aba-bacb695227a0.png)

**Comment by x86vk** [comment]
```
$ sudo -E hardcode-tray --size 22 --theme Papirus-Adapta                              
(hardcode-tray:6095): Gtk-WARNING **: 23:31:01.668: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(hardcode-tray:6095): Gtk-WARNING **: 23:31:01.668: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(hardcode-tray:6095): Gtk-WARNING **: 23:31:01.668: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Welcome to Hardcode-Tray!
Desktop Environment: Kde
Scaling Factor: 2
Icon Size: 44
Icon Theme: Papirus-Adapta
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..
Chromium            [#######.............................] 1/5 20.0% 0.25s
Insync              [##############......................] 2/5 40.0% 2.26s
Mailspring          [######################..............] 3/5 60.0% 0.70s
Telegram            [#############################.......] 4/5 80.0% 0.83s
Electronic WeChat   [####################################] 5/5 100.0% 1.18s
Took 5.22s to finish the tasks
Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by bilelmoussaoui** [comment]
The Insync were replaced. For mailspring, they might have changed the icons path again. Will fix that ASAP

**Comment by varlesh** [comment]
Mailspring 1.3.0 used current icons
![image](https://user-images.githubusercontent.com/8083855/43379015-4502be82-93db-11e8-8e04-6fd0c10a67ae.png)
@x86vk Try change conversion tool option to `RSVGConvert`
`sudo -E hardcode-tray -ct RSVGConvert`
Also for good rendering on plasma i'm recommend use Unity environment option:
`XDG_CURRENT_DESKTOP=Unity mailspring`

**Comment by x86vk** [comment]
@varlesh Fixed after updating to v4.3 and using RSVGConvert. Thanks!

**Comment by carmenfdezb** [comment]
> Mailspring 1.3.0 used current icons
> ![image](https://user-images.githubusercontent.com/8083855/43379015-4502be82-93db-11e8-8e04-6fd0c10a67ae.png)
> @x86vk Try change conversion tool option to `RSVGConvert`
> `sudo -E hardcode-tray -ct RSVGConvert`
> Also for good rendering on plasma i'm recommend use Unity environment option:
> `XDG_CURRENT_DESKTOP=Unity mailspring`

I did that but Maispring icon-tray looks blurry:
![screenshot_20190219_232257](https://user-images.githubusercontent.com/6286776/53051865-878a2c00-349d-11e9-8dd4-cc7d7ba9383a.png)
How can I remove this icon? Revert option doesn't do anything
Does it possible to uninstall hardcode-tray?

**Comment by varlesh** [comment]
> How can I remove this icon? Revert option doesn't do anything
Does it possible to uninstall hardcode-tray?

reinstall mailspring

**Comment by carmenfdezb** [comment]
> > How can I remove this icon? Revert option doesn't do anything
> > Does it possible to uninstall hardcode-tray?
> 
> reinstall mailspring

Thanks, that solved my problem!
