### ISSUE TITLE
Skype symlinks

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#54]
Skype has a lot of repeated icons instead of symlinks. This is due to different version of skype that are supported. I think that having a symlink instead of a copy would be great! i still don't have any idea how to deal with that..

**Comment by bil-elmoussaoui** [comment]
This is fixed in my latest commit , can you try this with skype @wa4557 ? Remove everything in ```~/.local/share/sni-qt/icons/skype``` first

**Comment by wa4557** [comment]
This does'nt work. The symlinks point to svg files in `Numix`

**Comment by bil-elmoussaoui** [comment]
Thanks for tesing :+1:
