### ISSUE TITLE
Add a new coloumn in database file 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#55]
We should add a new column in database file for sni-qt application folder; some application uses the same folder as the application names and some don't. For example ,Google play music uses ```MusicManager``` as a folder.
the new db line will look like this : 
```
google-music-manager, /opt/google/musicmanager/google-musicmanager, MusicManager
```
if the new column is empty nothing will happen, if it's a Qt application we willl take the application name

**Comment by bil-elmoussaoui** [comment]
Done in my latest commit, need to be tested!

**Comment by wa4557** [comment]
The whole thing becomes more and more complicated (compared to the initial commit). But I guess that's ok :P

**Comment by bil-elmoussaoui** [comment]
@wa4557 there's nothing more we can add/edit at the moment. In the future the only updates will be supporting more applications

**Comment by wa4557** [comment]
I bet that there will be a special app, that needs special treatment :)

**Comment by bil-elmoussaoui** [comment]
We will be more than happy to fix it too :P
