### ISSUE TITLE
Better variable naming and commenting

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#58]
Well, the script work so fine at the moment. Some of variables need to be renamed; and some of line code/functions need comments 
- [x] Better variable naming
- [x] Comments
- [ ] ```copy_files()``` is a really so big function, we need to optimize it if possible 
- [x] add copyright header
- [ ] add ```node-chrome-pak``` license 
- [x] ```convert2svg``` is added in three files. we should call the python script in ```database/scripts```

**Comment by bil-elmoussaoui** [comment]
@wa4557 do you have any idea how i can call the svg2png python script in ```script.py``` ? i used  ```call``` but i had a permission error

**Comment by wa4557** [comment]
Try `os.system(script.py)`

**Comment by wa4557** [comment]
But I would keep it as a seperate function in the script. Calling an outside script is a little bit of a overkill for such a small function

**Comment by Foggalong** [comment]
`os.system` is a deprecated function now, only supposed to be used in maintaining compatibility with Python 2.6 or lower

**Comment by bil-elmoussaoui** [comment]
@wa4557 i reverted my latest commit!

**Comment by bil-elmoussaoui** [comment]
@Foggalong I might need your help with the Node Chrome Pak license, we use the script to open the pak files in Google chrome to fix the hardcoded icons. This script is released under MIT license, @wa4557 proposed to add MIT license too; what do you think?

**Comment by bil-elmoussaoui** [comment]
I will close this as we re going to remove the node chrome pak script ;) and i can't do anything with the install function :/
