### ISSUE TITLE
Revert to default

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#60]
I guess it would be a good idea, to have a way to revert to the default icons (if the user wants to stop using this icon theme). I guess for that a major rewrite is necessary :(

**Comment by bil-elmoussaoui** [comment]
I think that won't be that hard.. we just need to create a folder, create an other folder inside. And copy back the icons if you want to revert back the icons?

**Comment by wa4557** [comment]
Yeah something like that

**Comment by bil-elmoussaoui** [comment]
I will give it a try today

**Comment by bil-elmoussaoui** [comment]
I finished this one, but it's a little hard to fix spotify & google chrome icons..i think we will need a script for reverting the old icons?

**Comment by wa4557** [comment]
Can't we use the same script with just changing the icons?

**Comment by bil-elmoussaoui** [comment]
Yeah, but we will need a backup script in this case?

**Comment by wa4557** [comment]
Backup script? What do you mean

**Comment by bil-elmoussaoui** [comment]
I thought that we will need a script to backup the original spotify/chrome icons. But i will just copy the zip/pak file and copy it back when you run the reinstall/revert script

**Comment by bil-elmoussaoui** [comment]
@wa4557 can you try my latest commit?

**Comment by wa4557** [comment]
Not quite:
First error message:
```
Traceback (most recent call last):
  File "./script.py", line 293, in <module>
    install() 
  File "./script.py", line 196, in install
    backup(app,apps[app]['link'],app_icons)
  File "./script.py", line 127, in backup
    backup_spotify(icons_folder)
  File "./script.py", line 147, in backup_spotify
    move(src, backup_app_path)
  File "/usr/lib/python3.4/shutil.py", line 521, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/home/andreas/.Hardcode-Tray-Backup/spotify/resources.zip' already exists
```


Second: for variety the whole folder where the pictures are located is backed up. Wouldn't it make more sense to backup only the files the script is overwriting?

**Comment by bil-elmoussaoui** [comment]
@wa4557 can you try again? :p

**Comment by wa4557** [comment]
Everything works (except spotify):

fixing spotify failed with error:
	Traceback (most recent call last):
	  File "svg2png.py", line 11, in <module>
	    fout = open(symlfile, 'wb')
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify_icon.ico'

etc...

**Comment by bil-elmoussaoui** [comment]
Well, maybe you've lost the recources.zip folder ? as this issue is in the install file

**Comment by wa4557** [comment]
nope. still there

**Comment by wa4557** [comment]
Whoa look what's in in my `resources.zip` now :) Wtf happened here?
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8633908/f43230f8-27e2-11e5-8351-899161b0e44f.png)

**Comment by bil-elmoussaoui** [comment]
WTF :O how that even possible?  can you try reinstalling spotify and retry again, this issue was there before i guess

**Comment by wa4557** [comment]
No idea what happened here. The problem doesn't occur again, and everything is now correctly backed up :+1:

**Comment by wa4557** [comment]
Some more things:
-  as far as I can see the script doesn't remove the icons from .local/share/sni-qt when choosing to revert. I guess however that this is the way to revert for the sni-qt icons

- could you please add a space after the double dot? `choice  = int(input("Please choose :"))` (Too small to make a PR)

- is it really necessary to have two distinct functions for spotify & google chrome? From what I can see they do exactly the same...

**Comment by bil-elmoussaoui** [comment]
- for the ```sni-qt``` folder, the icons are removed in my case, which application you're using?
- fixed
- i merged chrome & spotify function

**Comment by wa4557** [comment]
Cool, Yeah sni-qt is fixed my bad, but there's another serious problem:
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8634180/ba69a1ba-27ee-11e5-95c8-edc3189e9520.png)

This happens when opening google-chrome after running the script (although the script shouldn't do anything since the google chrome icons are not there yet)

**Comment by wa4557** [comment]
In other words. The script should only do a backup if the icons are actually overwritten

**Comment by wa4557** [comment]
Ok this whole revert thing doesn't work as you want it to happen: If the script is run more than once e.g. `resources.zip` is copied from `opt/spotify` to `hardcode-tray-backup`. The problem however: The second time a `resources.zip` is copied that is already overwritten with the theme icon. Right now I have no idea how to deal with that :(

**Comment by bil-elmoussaoui** [comment]
For the google chrome issue, i guess that the icon names are not the same as in my computer, could you verify that? 
And for the backup/revert i was thinking about creating a file named "already_backudup" , what do you think about this?

**Comment by wa4557** [comment]
Nope same icon name, copying doesn't work somehow. Or copy and don't overwrite already files ?

**Comment by bil-elmoussaoui** [comment]
@wa4557 this should be fixed now

**Comment by bil-elmoussaoui** [comment]
after merging your latest PR, is this fixed now or there's still something to do ?

**Comment by wa4557** [comment]
Hmm. What if there will be a new `resource.zip` in the future in a new version? Then reverting back will most likely break the program. But I don't think this is something we can't fix. In general this works now :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 i've installed the new beta of spotify and they've changed a lot of things. the spotify indicator does not seem to work now; we will take a look at this when this version will be released!
