### ISSUE TITLE
Check if script worked

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#62]
It would be great to see if the script that was called worked or didn't and give an error message if it doesn't. Right now always a success message is given. 
I'll give that a try if you wish

**Comment by bil-elmoussaoui** [comment]
I tried using ```try``` but that does not work.. that would be very helpful to debug future scripts;

**Comment by wa4557** [comment]
`try` does not work because python knows nothing about the script, but there are ways to handle that I think :)

**Comment by bil-elmoussaoui** [comment]
this is fixed now
