### ISSUE TITLE
Why dark light?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#7]
Just a quick question:

Why do you make the differentiation between light and dark themes? Why don't you just replace both icons (for variety for example `variety-indicator` and `variety-indicator-light`). For me this seems to be an unnecessary option, the user shouldn't and doesn't care about

**Comment by bil-elmoussaoui** [comment]
@wa4557 i did this for grive-tools, as the applications has two folders one for dark and the other one for the light indicators. But i will fix this soon by adding two versions of grive and each one will change different icons

**Comment by wa4557** [comment]
Good idea!

**Comment by bil-elmoussaoui** [comment]
This is fixed now, thank you for reporting this
