### ISSUE TITLE
Add a screenshot to readme

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#71]
I think we should add a screenshot before/after using Hardcode-Tray showing the ugly and non-monochrome icons and how they look like after using the script

**Comment by bil-elmoussaoui** [comment]
@Foggalong @wa4557 anyone of you can provide this? i'm using an unstable version of elementary OS and the things looks very ugly there. if you cannot i will try to install Ubuntu on a VM and do that

**Comment by wa4557** [comment]
I can do that but not today/tomorrow. If it's ok I'll do it on weekend

**Comment by bil-elmoussaoui** [comment]
@wa4557 take your time ;)

**Comment by wa4557** [comment]
I completely forgot this :) I'll do that this weekend I promise

**Comment by bil-elmoussaoui** [comment]
Not a problem ;)

**Comment by bil-elmoussaoui** [comment]
No need to install all the applications indicators (more than 30). Only the famous ones, like Chrome, Music manager, Telegram.. :+1:

**Comment by wa4557** [comment]
Hmm. Those where the only icons that are already supported by numix and I was able to run.. I'm not sure this is enough yet :(
![bildschirmfoto vom 2015-08-23 10 17 49](https://cloud.githubusercontent.com/assets/6475757/9427507/f931bb12-4981-11e5-84d1-91bb5af0524c.png)
![bildschirmfoto vom 2015-08-23 10 29 28](https://cloud.githubusercontent.com/assets/6475757/9427508/fabe8de8-4981-11e5-8266-d373a5f129f4.png)

**Comment by bil-elmoussaoui** [comment]
Theres google music manager, megasync too ;) i think just adding those two is enough. We will update that when Numix or an other theme support more icons

**Comment by bil-elmoussaoui** [comment]
I forgot telegram, if you it of course ;)

**Comment by wa4557** [comment]
Telegram doesn't work for me :) The same problem as described here #89

**Comment by bil-elmoussaoui** [comment]
@wa4557 do you still want to do this? if not i can install an Ubuntu version using vmware and take a screenshot

**Comment by wa4557** [comment]
Unfotunately this is very time consuming and I have tons of work to do right now :( If you're up to the task I'd be more than grateful...

**Comment by bil-elmoussaoui** [comment]
I will do it tomorrow if i can ;)

**Comment by wa4557** [comment]
Much thanks!

**Comment by bil-elmoussaoui** [comment]
Had to install all those apps :P 
![before](https://github-cloud.s3.amazonaws.com/assets/7660997/10566342/ef6d55ca-75e4-11e5-96a1-d2b879fa6758.png)

**Comment by wa4557** [comment]
lol, that's why we have the script :P

**Comment by bil-elmoussaoui** [comment]
I will add your screenshot @wa4557 and close this one! I don't think i will have the time to take a screenshot with all the applications, maybe i will update it one day :)
