### ISSUE TITLE
Better distro detection

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#72]
Well, the detect_de is not detecting the right icon sizes in case you're using elementary OS with an other desktop instead of Panatheon. 
I think we need a better function to handle all the possible cases

**Comment by bil-elmoussaoui** [comment]
Fixed in my latest commit

**Comment by bil-elmoussaoui** [comment]
really don't know why but this is not working again `environ({'TERM': 'xterm', 'LC_NAME': 'fr_BE.UTF-8', 'LANGUAGE': 'fr_FR', 'LC_NUMERIC': 'fr_BE.UTF-8', 'DISPLAY': ':0', 'LC_TIME': 'fr_BE.UTF-8', 'LC_ADDRESS': 'fr_BE.UTF-8', 'SUDO_USER': 'bilal', 'MAIL': '/var/mail/root', 'LC_IDENTIFICATION': 'fr_BE.UTF-8', 'LC_MEASUREMENT': 'fr_BE.UTF-8', 'XAUTHORITY': '/home/bilal/.Xauthority', 'LC_MONETARY': 'fr_BE.UTF-8', 'SUDO_GID': '1000', 'SUDO_UID': '1000', 'SHELL': '/bin/bash', 'SUDO_COMMAND': '/usr/bin/python3 script.py', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LC_PAPER': 'fr_BE.UTF-8', 'HOME': '/home/bilal', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_TELEPHONE': 'fr_BE.UTF-8', 'LANG': 'fr_FR.UTF-8', 'USERNAME': 'root', 'USER': 'root', 'LOGNAME': 'root'})
`

**Comment by bil-elmoussaoui** [comment]
the only possible way i guess, is to use  ̀ sudo -E ̀ instead of  `sudo ̀

**Comment by wa4557** [comment]
Meh, I'm not super happy with that solution :( Is there no other way to do it?

**Comment by bil-elmoussaoui** [comment]
I don't like that too :( but i think its the only way to conserve the environment variables when you run the script using  `sudo`
