### ISSUE TITLE
Script fails

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#73]
Might be because of the new detect environment method

Traceback (most recent call last):
  File "./script.py", line 311, in <module>
    if detect_de() in ("pantheon", "xfce"):
  File "./script.py", line 41, in detect_de
    if "pantheon" in [environ.get("DESKTOP_SESSION"), environ.get("XDG_CURRENT_DESKTOP").lower()]:
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by bil-elmoussaoui** [comment]
This won't work only if you run the script using ``` sudo -E python3 script.py```

**Comment by wa4557** [comment]
Well then there should be a failsafe that prevents the script from running when using standard `sudo`

**Comment by bil-elmoussaoui** [comment]
I was looking on how to handle that, do you have any idea?

**Comment by wa4557** [comment]
Check if a the enironment variable is there, and if not `exit`? I have no idea though if this environment variable is there for every linux distribution

**Comment by bil-elmoussaoui** [comment]
this must be fixed now, i used DESKTOP_SESSION as environment variable

**Comment by wa4557** [comment]
Yes. I guess this is good enough for now :)
