### ISSUE TITLE
Skype indicator not being changed in Elementary OS

### ISSUE THREAD

**Issue by soissons** [bil-elmoussaoui/Hardcode-Tray#74]
Hello, I got this qt-tray error:
```python
Traceback (most recent call last):
  File "script.py", line 324, in <module>
    install() 
  File "script.py", line 294, in install
    p = Popen([script_name, filename, symlink_icon, app_sni_qt_path], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './database/scripts/qt-tray'
```
I've tried fixing it by adding another directory and moving script.py and db.csv into it.

It goes through now, but I get:
```
The application my-weather-indicator does not exist yet, please report this on GitHub
The application skype does not exist yet, please report this on GitHub
No apps to fix! Please report on GitHub if this is not the case
```
I have both these apps installed. I'm using Elementary OS Freya, with the latest numix circle icons.

ls -R /tmp/sni-qt_*:
```
/tmp/sni-qt_skype_28585-GVRoum:
icons

/tmp/sni-qt_skype_28585-GVRoum/icons:
hicolor

/tmp/sni-qt_skype_28585-GVRoum/icons/hicolor:
24x24

/tmp/sni-qt_skype_28585-GVRoum/icons/hicolor/24x24:
apps

/tmp/sni-qt_skype_28585-GVRoum/icons/hicolor/24x24/apps:
skype_28585_2d1ee5482260fd9cd180b32787792683.png  skype_28585_f2fc4a539a7b9553f5b35241d1154e84.png
skype_28585_37e170fc54e7355d9d298917e74f9ea9.png
```
If you maybe also want this:
![skype_tmp_icons](https://cloud.githubusercontent.com/assets/1542063/8865471/e411cacc-31af-11e5-9f11-5bfd15374d5d.png)

**Comment by bil-elmoussaoui** [comment]
I can't reproduce that. Are you using the latest version of the script?

**Comment by soissons** [comment]
Yes. Well I've managed to change the icon with ElementaryPlus. Can I give you any other info to fix the bug for other users?

**Comment by bil-elmoussaoui** [comment]
I'm still thinking about this, can you just change this in the script : 
```python userhome = path.expanduser("~" + getlogin()) ``` with  
```python 
userhome = path.expanduser("~" + getlogin())
print(userhome) ```
run the script again, and paste the result here

**Comment by bil-elmoussaoui** [comment]
And go to the line 297 and add 
```python  print(script_name)```

**Comment by bil-elmoussaoui** [comment]
I pushed a new version that should check if the script file do exists! Can you try that?

**Comment by soissons** [comment]
`autocrlf = true` in git was the problem -.- sry, my bad

**Comment by bil-elmoussaoui** [comment]
not a problem;)
