### ISSUE TITLE
Fixing non tray-icons as well?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#76]
A quick thought that would make this script so much more useful:

What do you think about fixing hardcoded non tray-icons as well? 
Calibre (I really really hope that at some point the calibre-dev will change his mind about using system-icons) or jdownloader use hardcoded but standard icons that could be changed using your script. 

I'm aware that this would require a lot of work setting up the appropriate databases but codewise everything (or most of it) is already here (maybe with a third selection in the script or sth similar)

**Comment by bil-elmoussaoui** [comment]
i was thinking about that too ! i think of creating a new git repo for that and use the same code with some modification to make it easier for the users to choose between fixing indicator or applications icons

**Comment by wa4557** [comment]
Cool :+1: I'll help of course :)

**Comment by bil-elmoussaoui** [comment]
I just need to finish the new google chrome code to merge it and start with the new script, do you have any idea of a name ? :P

**Comment by wa4557** [comment]
hmm. What about "hardcode-icons"? (I'm not very convinced about the name :)

**Comment by bil-elmoussaoui** [comment]
@Foggalong do you have any idea of a name? :p 
@wa4557 We will have to deal with different icon sizes?

**Comment by wa4557** [comment]
Yes, this needs to be an additional column in the database file

**Comment by bil-elmoussaoui** [comment]
I will go with hardcode-icons :P i'm closing this https://github.com/bil-elmoussaoui/Hardcode-Icons
