### ISSUE TITLE
Fedora 40 support

### ISSUE THREAD

**Issue by Enderteck** [bil-elmoussaoui/Hardcode-Tray#775]
There is no option to download for fedora 40, the repo doesn't work and I had to use the Fedora 39 package

![Capture d’écran du 2024-05-15 21-10-23](https://github.com/bilelmoussaoui/Hardcode-Tray/assets/123917079/b0f50500-4756-4aef-abfc-a881b881303c)

**Comment by voedev** [comment]
https://build.opensuse.org/project/show/home:SmartFinn:hardcode-tray

**Comment by SmartFinn** [comment]
Done. The packages for Fedora 40 and 41 were built.

**Comment by voedev** [comment]
> Done. The packages for Fedora 40 and 41 were built.

Thank you so much for all your work!!

**Comment by voedev** [comment]
@Enderteck issue can be closed now :3
