### ISSUE TITLE
VLC media player is not monochrome

### ISSUE THREAD

**Issue by raknerak** [bil-elmoussaoui/Hardcode-Tray#78]
![selection_021](https://cloud.githubusercontent.com/assets/7880734/9159964/28cfb514-3f3b-11e5-8039-b2e190d48541.png)

**Comment by bil-elmoussaoui** [comment]
Well, this cannot be fixed as the VLC indicator icon uses the same icon name as the application name. You might report this to the VLC devs if you want this to be fixed ;)
