### ISSUE TITLE
Open spotify archive file only once

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#84]
Hello ,
We do extract the `resources.zip` too many times and zip it again :/ (10 times)
Any idea how to open the zip file only once, change all the files and then zip it again? :+1:

**Comment by wa4557** [comment]
We have the same problem with the google chrome unpacking :( I was trying to come up with a solution but nothing very good (that is without a lot of rewriting) has come to my mind yet

**Comment by bil-elmoussaoui** [comment]
I think sending all the filenames at once for spotify is a good idea as all the icons will be symlinked to the same icon.
But for chrome i don't think it's the idea way :(

**Comment by wa4557** [comment]
I guess it's the exact for spotify and chrome. 
1) We extract the source file
2) We replace the source icons with our modified ones (more than one icon in both cases)
3) We remove the extracted folder

**Comment by bil-elmoussaoui** [comment]
I'm thinking of a better way, without a lot of modifications in the files.
We just need to send a variable to the script that will contains "start" which means, extract the archive and "end" which means remove the extracted folder
we can do that easily by adding a counter and if the value of the counter is the same as the length of the list..

**Comment by wa4557** [comment]
Yeah I like that idea, that would work for both spotify and chromium, something like a `1` if the last icon is to be replaced, and a `ìf` `else` in the spotify/chrome script

**Comment by bil-elmoussaoui** [comment]
@wa4557 can you do the bash part? if `$4` is `start` extract the files. and if it's `end` remove the extracted folder

**Comment by wa4557** [comment]
Yeah I can. But let's use True or False or 0 and 1 instead of strings :)

**Comment by bil-elmoussaoui** [comment]
Okay as you wish ;) you can update the script file too ?

**Comment by wa4557** [comment]
the chrome script? yes I can do that as well

**Comment by bil-elmoussaoui** [comment]
yes, but i was talking about `script.py` as i already added the counter

**Comment by wa4557** [comment]
Ok I'm, lost what should I change :)?

**Comment by bil-elmoussaoui** [comment]
Line 368 in the github version, i sent "start" , "", "end" to the spotify/chrome script and as you wish to use 0/1 or True/False you ve to change that there too

**Comment by wa4557** [comment]
Ah ok, sure :)

**Comment by wa4557** [comment]
It turns out that there are more problems than expected :) I'll do it tomorrow I'm too tired right now
