### ISSUE TITLE
Some unneeded continue statement

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#85]
Sometimes i feel like there's too much continue statement in the script (10 times) ? Are they really needed or i can remove (some of them) without changing in thing in the way the script works

**Comment by wa4557** [comment]
I'd say that they are needed (only had a quick look though). But I guess that's ok continues are good programming style when using loops (which we heavily are)

**Comment by bil-elmoussaoui** [comment]
For example in the line 192 (in the github version) 3 continue statement :P 
My teacher was saying never use continue or break in a loop (i never understood way)

**Comment by wa4557** [comment]
Yeah me neither :P 
my opninion: if it makes code harder to read when replacing them (which is of course possible using a lot more ifs and elses) it is generally a bad idea

**Comment by Foggalong** [comment]
@bil-elmoussaoui did they ever give a reason? O.o

**Comment by bil-elmoussaoui** [comment]
@Foggalong (It was the only time when i went to the Python class and i was late xD)

**Comment by wa4557** [comment]
I think it's the same reason as for the (somehow unfounded imo) refusal for `goto`. You should have functions with only one return value and no nested loops...

**Comment by bil-elmoussaoui** [comment]
Well, i will close this ;)
