### ISSUE TITLE
Google chrome icons license

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#87]
Should we add a license for having some of default chrome icons in the script [see here](https://github.com/bil-elmoussaoui/Hardcode-Tray/tree/master/database/images/chrome) ?

**Comment by wa4557** [comment]
Yeah probably. Parts of the unpacking script are also from the chrome developers

**Comment by bil-elmoussaoui** [comment]
I don't know anything about licensing :( Which licence we should add? or just add that to the credits section

**Comment by wa4557** [comment]
Me neither. I guess it's ok to add a note to the credits section?

**Comment by bil-elmoussaoui** [comment]
Yeah, i was doing some research it's seems that a big part of Google chrome is released under EULA license

**Comment by wa4557** [comment]
which means?

**Comment by bil-elmoussaoui** [comment]
@Foggalong might help us know what all that means :P

**Comment by bil-elmoussaoui** [comment]
I added that to the credits section

**Comment by Foggalong** [comment]
omg yes. If you're releasing

**Comment by bil-elmoussaoui** [comment]
So the credits section are unneeded for the chrome stuff ?

**Comment by bil-elmoussaoui** [comment]
I will read that this weekend

**Comment by Foggalong** [comment]
The `data_pack.py` definitely needs to be in the credits section, and if you're not re-licensing it then the BSD-like license needs to be included too.

When the icons extracted from Chrome, it's possible that the EULA prevents you from redistributing them separately from Chrome or even at all.

**Comment by wa4557** [comment]
The Icons are in chromium as well,  which is OS

Joshua Fogg <notifications@github.com> schrieb am Mi., 19.08.2015, 0:11:

**Comment by Foggalong** [comment]
That's a good point, though there might be differences in the binaries for copyright reasons.

If not, same thing applies about including the Chromium license :)

**Comment by bil-elmoussaoui** [comment]
The icons are the same in Chrome/chromium. I think we should rename the chrome folder to chromium and only add Chromium license?

**Comment by wa4557** [comment]
Makes sense to me.

**Comment by bil-elmoussaoui** [comment]
Changed the folder name, and the license to BSD-style as mentioned in Wikipedia; We should just upload the BSD license to the github repo?

**Comment by Foggalong** [comment]
Well if the BSD license is just being applied to one part of the repo put it in that part of the repo with a note in the header of the file it applies too. Is there anything else which might also be licensed differently?

**Comment by bil-elmoussaoui** [comment]
it's the only thing in hardcode-tray

**Comment by Foggalong** [comment]
Goodo!

**Comment by bil-elmoussaoui** [comment]
I didn't find a way to apply a license to a part of the repo?

**Comment by Foggalong** [comment]
Just upload the LICENSE as a normal file, it's not though the GitGub interface. You could if you wanted add a clarification in the readme to what license applies where?

**Comment by bil-elmoussaoui** [comment]
I uploaded the bsd license and modified the readme too ;) what do you think?

**Comment by bil-elmoussaoui** [comment]
@Foggalong If you're free this weekend, can you check what've done so i can close this? :)

**Comment by Foggalong** [comment]
I think this can be closed now yeah :)

**Comment by bil-elmoussaoui** [comment]
Thanks <3
