### ISSUE TITLE
Use wiki

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#88]
I think that using Wiki will be a great idea 
- Full list of supported applications 
- How to get the `Qt` icon names (if you want to contribute)
- Why installing `sni-qt`
-  How to get the right icon names if you want to add them to your theme

...

What do you think?

**Comment by wa4557** [comment]
Like that. A lot of work though

**Comment by bil-elmoussaoui** [comment]
Well, we might not add everything today. We will keep updating it;) We just need a list of what we should add and what we should not

**Comment by Foggalong** [comment]
You could add a wiki table similar to the one we use for hc-fix and move [this part of the README](https://github.com/bil-elmoussaoui/Hardcode-Tray#supported-applications) over. You could then keep track of upstream reports to fix it in the same way too :D

**Comment by bil-elmoussaoui** [comment]
I added the first page :P https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/Supported-applications
We still need to do a lot of work

**Comment by bil-elmoussaoui** [comment]
I added two pages today ;) Need some grammar correcting i guess. And i have no idea what to write in the home page?

**Comment by Foggalong** [comment]
What happened to the links from the README?

**Comment by bil-elmoussaoui** [comment]
which links? i will add the wiki pages links to readme

**Comment by Foggalong** [comment]
Weren't there links in the readme originally?

**Comment by bil-elmoussaoui** [comment]
links of supported applications, i moved viber indicator fixer :/ i will move it back

**Comment by bil-elmoussaoui** [comment]
Done, just need to write something in the home page. @wa4557 i added "How to support an application in your theme" to "How does the script works?" Can you take a look at what i wrote? :)

**Comment by wa4557** [comment]
Done. I simplified it a bit because I think it was hard to understand before :)

**Comment by bil-elmoussaoui** [comment]
Thanks! We have added everything :dancer:, this can be closed i guess?

**Comment by wa4557** [comment]
:+1:
