### ISSUE TITLE
Script doesn't work?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#9]
Another thing: Is the script currently not working? Whenever I try do run it it says `The application does not exists, please report this to the dev.` (the problem is `telegram`). 

Wouldn't it be better to replace the `sys.exit` with something that doesn't exit the program `return None` or sth similar and not quit the whole program?

Moreover: an improvement would be to have a different error that tells you which program you have to report to the dev :) Sth like `The application telegram does not exists yet, please report this to the dev.`

If you want I can do this, but I think you understand your program better than I do, so you're rpobably faster

**Comment by bil-elmoussaoui** [comment]
The problem is in ``` get_icons ``` the error shows now the application name and i used print to not stop the script; i really don't know why it's not working with telegram :/

**Comment by wa4557** [comment]
I found the error 
in line 14:

```
db_ext = "txt"
```
you're missing the period before `txt` (it should read `.txt`) 
this leads to errors in line 49 if the period is missing and the `else` is always executed
