### ISSUE TITLE
Update weather indicators symlinks

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#90]

**Comment by bil-elmoussaoui** [comment]
I updated the symlinks, but i couldn't find any icons for those two 
- weather-chance-of-thunderstorms-night
- weather-chance-of-thunderstorms
@wa4557 Can you take a look at the current symlinks and see if i didn't do anything wrong ? :)

**Comment by wa4557** [comment]
I guess we can use `weather-storm` for that. Not much difference imo :)

**Comment by bil-elmoussaoui** [comment]
Done, i'm still not sure about some icons; i don't know if the symlinks are the right ones

**Comment by wa4557** [comment]
I'll have a look

**Comment by wa4557** [comment]
Ok I changed a few, the rest is ok I guess

**Comment by bil-elmoussaoui** [comment]
Thanks :+1:
