### ISSUE TITLE
Workrave

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#91]
Is there any chance we could get [workrave](http://www.workrave.org/) to work on this? The apps tray is complicated to say the least involving timer widgets and such but it still has icons which stand out

**Comment by bil-elmoussaoui** [comment]
I will take a look ;)

**Comment by bil-elmoussaoui** [comment]
I just installed the application, the indicator icon is not working in my case (elementary OS) :( 
The icons are in `/usr/share/workrave/images/` 
Is one of those icons is the right indicator icon?

**Comment by Foggalong** [comment]
Yeah, I think so. One is a sheep and one is a door

**Comment by bil-elmoussaoui** [comment]
Fixed in my latest commit ; you can add those icons to Numix 
- workrave-indicator
- workrave-indicator-quiet
- workrave-indicator-suspended

**Comment by Foggalong** [comment]
Made a request for it :D thanks!

**Comment by bil-elmoussaoui** [comment]
You're welcome
