### ISSUE TITLE
Wrong Theme

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#92]
```bash
josh@brain:~/Code/hardcode/main-tray$ sudo -E !!
sudo -E ./script.py 
[sudo] password for josh: 

(script.py:11405): Gtk-WARNING **: Theme parsing error: gtk.css:2334:31: Missing name of pseudo-class

(script.py:11405): Gtk-WARNING **: Theme parsing error: gtk.css:2337:33: Missing name of pseudo-class

(script.py:11405): Gtk-WARNING **: Theme parsing error: gtk.css:2341:33: Missing name of pseudo-class
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : elementary-xfce-darker
1 - Install
2 - Reinstall
Please choose: 
```

My current theme is Numix :(

**Comment by bil-elmoussaoui** [comment]
Your icon theme? :P as i just get the value using gsettings; what DE you're using?

**Comment by bil-elmoussaoui** [comment]
Can you paste the output of `gsettings get org.gnome.desktop.interface icon-theme` ?

**Comment by Foggalong** [comment]
It's XFCE+i3+Compton but it's worked previously with that setup. I'll get the output of that command asap

**Comment by Foggalong** [comment]
`elementary-xfce-darker` :(

**Comment by bil-elmoussaoui** [comment]
Do you have Dconf installed? if so can you go to `org.gnome.desktop.interface` and share a screenshot as it's the same for all the linux DE i guess

**Comment by Foggalong** [comment]
I don't have dconf installed. Should I get it?

**Comment by bil-elmoussaoui** [comment]
Yes

**Comment by Foggalong** [comment]
![screenshot_2015-08-28_12-55-00](https://cloud.githubusercontent.com/assets/5920259/9545678/02533080-4d84-11e5-9d91-006cbc4535fa.png)

**Comment by bil-elmoussaoui** [comment]
I just don't understand this anymore :P try restarting your system as you've "Numix-Cirlc" as a value for `org.gnome.desktop.interface icon-theme` 
or try this `gsettings set org.gnome.desktop.interface icon-theme "Numix-Circle"`  
this should fix the issue

**Comment by bil-elmoussaoui** [comment]
I see why you want #94 this :dancer:

**Comment by Foggalong** [comment]
I've restarted twice since making this issue with no change, but running `gsettings set org.gnome.desktop.interface icon-theme "Numix-Circle"` seems to have fixed it. The only error that showed in the terminal is this one but I think this just links to #93 

```bash
Running 
fixing Chromium failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 135, in <module>
	    main()
	  File "./data_pack.py", line 128, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 45, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 37, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'chrome_100_percent.pak'
	
fixing Chromium failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 135, in <module>
	    main()
	  File "./data_pack.py", line 128, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 45, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 37, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'chrome_100_percent.pak'
	mv: cannot stat ‘chrome_100_percent.pak’: No such file or directory
```

**Comment by bil-elmoussaoui** [comment]
Yes it's the same issue as in #93; i think this can be closed now ? :D

**Comment by Foggalong** [comment]
Sure thing! :D
