### ISSUE TITLE
xchat and hexchat

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#94]
It would be nice to add support for [xchat](http://xchat.org/) and it's successor [hexchat](https://hexchat.github.io/). Let me know if there's anything else you need :)

**Comment by bil-elmoussaoui** [comment]
I will do today ;)

**Comment by Foggalong** [comment]
Thanks <3

**Comment by bil-elmoussaoui** [comment]
It seems that the icons are not hardcoded [hexchat/data/icons](https://github.com/hexchat/hexchat/tree/master/data/icons) the icons are installed in `/usr/share/icons/hicolor/scalable/apps/`
Can you confirm that?

**Comment by Foggalong** [comment]
I only have `hexchat.svg` in that folder and I believe it's the app icon version, not the tray icon

**Comment by bil-elmoussaoui** [comment]
Are you using any plugin to have the tray icon?

**Comment by Foggalong** [comment]
No, it just comes with the stock program :(

**Comment by bil-elmoussaoui** [comment]
can you paste the ouput of ` cd / && sudo find -name *tray_highlight*`; also a screenshot of `/tmp/` or just the folder content

**Comment by Foggalong** [comment]
Output of `cd / && sudo find -name *tray_highlight*`
* /usr/share/icons/Numix/24x24/status/tray_highlight.svg
* /usr/share/icons/Numix/22x22/status/tray_highlight.svg
* /usr/share/icons/Numix/16x16/status/tray_highlight.svg
./home/josh/Code/numix/hidpi/base/Numix/22/status/tray_highlight.svg
./home/josh/Code/numix/hidpi/base/Numix/16/status/tray_highlight.svg
./home/josh/Code/numix/hidpi/base/Numix/24/status/tray_highlight.svg
./home/josh/Code/numix/base/Numix/24x24/status/tray_highlight.svg
./home/josh/Code/numix/base/Numix/22x22/status/tray_highlight.svg
./home/josh/Code/numix/base/Numix/16x16/status/tray_highlight.svg
./home/josh/Code/elementary/plus/elementaryPlus/status/24/tray_highlight.svg

Screenshot of `/tmp/`
![screenshot_2015-08-28_13-45-56](https://cloud.githubusercontent.com/assets/5920259/9546508/21db45a8-4d8b-11e5-9b58-dbca6ee14a9f.png)

**Comment by bil-elmoussaoui** [comment]
what's inside `sni-qt_python2.7..` ?  if it has nothing to do with hexchat, paste the output of `cd / && sudo find -name "hexchat" `

**Comment by Foggalong** [comment]
Nothing :( 
![screenshot_2015-08-28_14-06-14](https://cloud.githubusercontent.com/assets/5920259/9546851/f6d0eacc-4d8d-11e5-9efd-1bc19046b8f8.png)

Output of `cd / && sudo find -name "hexchat"`
* /usr/bin/hexchat
* /usr/lib/x86_64-linux-gnu/hexchat
* /usr/share/lintian/overrides/hexchat
* /usr/share/menu/hexchat
* /usr/share/doc/hexchat
* /home/josh/.files/config/hexchat
* /home/josh/.config/hexchat

**Comment by bil-elmoussaoui** [comment]
I didn't find any icon :( It's seems that hexchat will merge this brench soon [appindicator](https://github.com/hexchat/hexchat/tree/wip/appindicator/)
I think that icons should be named `hexchat-tray`  but not sure if they will work :/ 
@wa4557 do you have any idea?

**Comment by Foggalong** [comment]
Last work in February doesn't give me much hope for that branch :(

**Comment by bil-elmoussaoui** [comment]
I will look install it in Ubuntu unity and see if i can get the icons name, i don't promise anything :/

**Comment by Foggalong** [comment]
I've tried running `cd / && sudo find . -wholename *tray_highlight*` which is the name of the [attention icon](https://github.com/hexchat/hexchat/blob/master/data/icons/tray_highlight.png) and it's not brought up anything. How have they hardcoded it into the binaries of the application? :(

**Comment by bil-elmoussaoui** [comment]
I downloaded the deb file, extracted it and i think that the icons are hardcoded into the binaries of the application as you said :(

**Comment by Foggalong** [comment]
Well that's shitty of them.

**Comment by bil-elmoussaoui** [comment]
I hope so

**Comment by Foggalong** [comment]
[This is the issue](https://github.com/hexchat/hexchat/issues/1462#issuecomment-135906921) and [this is what I've been linked to](https://hexchat.readthedocs.org/en/latest/appearance.html#icons).

**Comment by Foggalong** [comment]
Just as an update on this, the icons in that directory need to be PNG

**Comment by bil-elmoussaoui** [comment]
Okay, if i understand the icons need to be png but where i should copy the icons? in the doc they only mention that the icons must be in a seperate dir in the config directory but which directory?

**Comment by bil-elmoussaoui** [comment]
If you can have the path to the directory were the icons must be copied i can fix this as soon as i've that ;)

**Comment by bil-elmoussaoui** [comment]
Ops the directory must be named icons. I will do add that tomorrow ;)

**Comment by bil-elmoussaoui** [comment]
Fixed in my latest commit , be sure that `$HOME/.config/hexchat/icons/` do exists ;)

**Comment by Foggalong** [comment]
@bil-elmoussaoui That directory doesn't get created when hexchat is installed so won't be there for the majority of users. Could you make it so that if the folder isn't there it's created? something like this


```python
if not os.path.exists(userhome + "/.config/hexchat/icons/"):
    os.makedirs(userhome + "/.config/hexchat/icons/")
```

**Comment by bil-elmoussaoui** [comment]
Done :+1: 
Can you symlink the icons in Numix into 
```
tray_fileoffer.png, hexchat-fileoffer
tray_highlight.png, hexchat-highlight
tray_message.png, hexchat-message
hexchat.png, hexchat-indicator
```

**Comment by Foggalong** [comment]
Yeah, sure :)

**Comment by Foggalong** [comment]
[Done!](https://github.com/numixproject/numix-icon-theme/commit/b542eb61961a5db43c4bd3a08e2d815f1d3529eb)
