### ISSUE TITLE
Chrome pak file & extracted dirctory issue

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#95]
We have two more issues here 
- [x] extracted & chrome pak file are not removed when everything is finished 
- [x] we should change the extracted folder name and the chrom pak file to something that will avoid issues for users that uses chrome, chromium & chrome unstable version

**Comment by wa4557** [comment]
I'd be happy to do this, unfortunately I'm extremely busy this weekend and next week, but I'll try:)

**Comment by bil-elmoussaoui** [comment]
I will try to fix what i can ;)

**Comment by bil-elmoussaoui** [comment]
I fixed the second issue by moving the looking for icons into the install function to avoid changing a lot in the source code

**Comment by bil-elmoussaoui** [comment]
Should be fixed
