### ISSUE TITLE
sni-qt on non-Ubuntu distros

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#97]
Package names for the patched sni-qt for other distros (Debian, Fedora, Arch, etc) would be useful, or at least a place where it can be compiled from source. Just moved a laptop to Korora and realised I have no idea where the patched version comes from

**Comment by bil-elmoussaoui** [comment]
@cybre As i'm using your PPA for Ubuntu DE. Are you planning to build a version for Fedora/arch..Distros?

**Comment by cybre** [comment]
No, but anyone is free to do so :)

**Comment by bil-elmoussaoui** [comment]
And where i can find the source code? Thanks for the fast answer! :+1:

**Comment by cybre** [comment]
https://code.launchpad.net/~cybre/elementary+/sni-qt-patched

**Comment by bil-elmoussaoui** [comment]
Thanks; @Foggalong If you managed to build it for Fedora or any other distro please feel free to add that to the wiki ;) I will just add the source code link to the readme to keep it clean

**Comment by bil-elmoussaoui** [comment]
I will close this once we add how to build Sni-Qt for other distros

**Comment by Foggalong** [comment]
I'm gonna have a mess around with this and see what I can do :)

**Comment by bil-elmoussaoui** [comment]
I have started this in the Hardcode-Tray Wiki but had no idea where to start haha! https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/How-to-build-Sni-qt

**Comment by bil-elmoussaoui** [comment]
Added [here](https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/How-to-build-sni-qt) I would be very thankful if anyone can correct the english part !

**Comment by wa4557** [comment]
Looks good to me. I've added a bit and was able to build the package :)

**Comment by bil-elmoussaoui** [comment]
Thanks!! We can finally close this one :)
