### ISSUE TITLE
Hangouts extension not working

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#98]
if you do use the script to fix the tray icons in hangouts, and you reopen the browser the tray icon will disappear and you will need to reinstall the extension; if have this issue with Google chrome beta 
any ideas? :/

**Comment by wa4557** [comment]
I can confirm that. Strange... Nah no ideas I'm not even sure why this happens...

**Comment by bil-elmoussaoui** [comment]
I think that user does not have the permission to change any icons/code in the extension.. I will see if there's any work around

**Comment by bil-elmoussaoui** [comment]
I think that i'm going to remove Hangout support :/ i didn't find any solution..

**Comment by wa4557** [comment]
Yes I guess that's the only solution :(

**Comment by bil-elmoussaoui** [comment]
Maybe this will not  happen if the user active devlopper mode ?

**Comment by Foggalong** [comment]
Asking the user to enable developer mode just to fix the bug is a bit iffy

**Comment by bil-elmoussaoui** [comment]
This sadly can't be fixed :/

**Comment by Foggalong** [comment]
Does enabling developer mode actually fix the problem or was that just a suggestion?

**Comment by bil-elmoussaoui** [comment]
Only a suggestion

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
I removed Hangouts support! hope we can fix this issue one day..
