### ISSUE TITLE
Telegram Desktop not being detected

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#99]
Hey!

Trying to replace my Telegram indicator but apparently the script is not detecting it.

Running on Ubuntu 15.04 with Telegram installed from ppa:atareao/telegram

Regards!

**Comment by bil-elmoussaoui** [comment]
Telegram has some issues on Ubuntu #89 to be sure that's the case for you too
1 - Open telegram
2 - Go to /tmp and if you find any telegram icon share the name of the icon

If it's the case you will find enough information here #89

**Comment by edgard** [comment]
Yeah, my bad for not looking thru the already reported issues. The previous report is correct, same is happening to me. Files are being created at /tmp indeed.

Thanks!

**Comment by bil-elmoussaoui** [comment]
@edgard You're welcome, Telegram devs won't fix this issue i guess..maybe in the near future;
